### ISSUE TITLE
表字段发生改变-程序shutdown

### ISSUE THREAD

**Issue by shubifeng** [zendesk/maxwell#1021]
2018-06-15 09:54:54,034 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle setStopped - STOPPED o.e.j.s.ServletContextHandler@4fb343d0{/maxwell,null,UNAVAILABLE}
2018-06-15 09:54:54,034 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle setStopping - stopping qtp1561940237{STARTED,8<=8<=200,i=8,q=0}
2018-06-15 09:54:54,035 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle setStopped - STOPPED qtp1561940237{STOPPED,8<=8<=200,i=0,q=0}
2018-06-15 09:54:54,035 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle setStopped - STOPPED org.eclipse.jetty.server.Server@21430879
2018-06-15 09:54:54,035 DEBUG com.zendesk.maxwell.util.TaskManager stop - Awaiting stop of: com.zendesk.maxwell.schema.PositionStoreThread@2a7cf16a
2018-06-15 09:54:54,135 DEBUG com.zendesk.maxwell.util.TaskManager stop - Awaiting stop of: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@7913a37e
2018-06-15 09:54:55,242 DEBUG com.zendesk.maxwell.util.TaskManager stop - Awaiting stop of: com.zendesk.maxwell.replication.BinlogConnectorReplicator@6ee858dd
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Could not find column order_invoice_status in service_order_refund
        at com.zendesk.maxwell.schema.ddl.ColumnMod.originalIndex(ColumnMod.java:16)
        at com.zendesk.maxwell.schema.ddl.RemoveColumnMod.apply(RemoveColumnMod.java:12)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:52)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:94)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:319)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:294)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
2018-06-15 09:54:55,342 DEBUG com.zendesk.maxwell.util.TaskManager stop - Awaiting stop of: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@2983054a
2018-06-15 09:54:55,342 INFO  com.zendesk.maxwell.util.TaskManager stop - Stopped all tasks
2018-06-15 09:54:55,344 DEBUG com.zendesk.maxwell.MaxwellContext$1 run - Shutdown complete: tru

**Comment by liulikun** [comment]
There should be some logs about this db migration before the error?
