### ISSUE TITLE
 Couldn't find table ha_health_check in database mysql with Alibaba RDS

### ISSUE THREAD

**Issue by kevinclcn** [zendesk/maxwell#1032]
Though the issue https://github.com/zendesk/maxwell/issues/513 was marked as fixed, the maxwell 1.16.1 docker version still complains

```log
java.lang.RuntimeException: Couldn't find table ha_health_check in database mysql
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:28) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:383) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:477) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:146) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:223) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.16.1.jar:1.16.1]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244) ~[maxwell-1.16.1.jar:1.16.1]
15:43:19,388 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@28f1b2ff
15:43:19,388 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
15:43:19,388 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@1f391baa
15:43:19,388 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
15:43:19,389 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
15:43:19,394 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@654447ef
15:43:19,394 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
15:43:19,394 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@7e52bc86
15:43:19,397 INFO  ServerConnector - Stopped ServerConnector@643b56da{HTTP/1.1}{0.0.0.0:13300}
15:43:19,399 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@31026b47{/,null,UNAVAILABLE}
java.lang.RuntimeException: Couldn't find table ha_health_check in database mysql
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:28)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:383)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:477)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:146)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:223)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)
15:43:20,708 INFO  TaskManager - Stopped all tasks
```

**Comment by osheroff** [comment]
damn, this regressed after a filtering rewrite.  PR open to fix.
