### ISSUE TITLE
java.lang.RuntimeException: Couldn't find database

### ISSUE THREAD

**Issue by dmgactive** [zendesk/maxwell#1033]
**java.lang.RuntimeException: Couldn't find database oom**
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:23) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:198) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:294) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:164) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:206) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.16.0.jar:1.16.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:227) ~[maxwell-1.16.0.jar:1.16.0]

**Comment by osheroff** [comment]
are you using blacklists?  how long after maxwell was booted did you encounter this error?  anything special about your maxwell setup?
