### ISSUE TITLE
Issue during startup and capturing initial schema

### ISSUE THREAD

**Issue by theoreh1** [zendesk/maxwell#1052]
I would like to replicate data from a mysql slave to pub/sub and currently have Maxwell running on a separate server.  In testing to stdout Maxwell connects to the database, creates the maxwell schema,  then hangs on "AbstractSchemaStore - Maxwell is capturing initial schema"  , and eventually fails.  What am I missing?

./maxwell --user='<username>' --password='<pwd>' --schema_database='maxwell' --host='<remote host ip>' --producer=stdout --replication_host='<remote host ip>' --replication_user='<username>' --replication_password='<pwd>'

05:56:03,276 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
05:56:03,387 INFO  TaskManager - Stopped all tasks
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.regex.Pattern.sequence(Pattern.java:2100)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.util.regex.Pattern.matches(Pattern.java:1133)
	at java.lang.String.matches(String.java:2121)
	at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:165)
	at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:131)
	at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:102)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:81)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:68)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:58)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:199)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)

**Comment by liulikun** [comment]
Just wondering if there was not much memory available when you got this error. It shouldn't take too much memory during schema capturing stage unless you have way too many tables and databases.

**Comment by theoreh1** [comment]
I was thinking the same.  There are over 1000 databases each with 500+ tables.  I was thinking that may be the issue, so I tried it with a filter as well with one database and one table that contains 1 row and got the same result.  The only schema tables that contain rows at all are the position and heartbeat tables.

--filter='exclude: *.*, include: ted.*'

**Comment by liulikun** [comment]
Oh I see. Maxwell catptures all databases and tables regardless of filter settings currently. So it doesn't help by doing that.

**Comment by theoreh1** [comment]
Okay,  do you know if there is a way to do it in batches, or any java related variables that may help in this case?  It seems like it's an all or nothing as there is nothing in any of the metadata tables outside of position and heartbeat.   It's taking 2+ hours before it fails.

**Comment by theoreh1** [comment]
Thanks for the input @liulikun .  Bumping the memory on the box allowed the abstraction to finally complete.  Hitting some other errors are the moment, but this one looks to be resolved.

Thanks
