### ISSUE TITLE
couldn't extract date/time out of 2

### ISSUE THREAD

**Issue by watacea** [zendesk/maxwell#1063]
17:30:54,380 ERROR TaskManager - cause: 
java.lang.RuntimeException: couldn't extract date/time out of 2
        at com.zendesk.maxwell.schema.columndef.DateFormatter.extractTimestamp(DateFormatter.java:26) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.schema.columndef.DateFormatter.formatDate(DateFormatter.java:94) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.schema.columndef.DateColumnDef.asJSON(DateColumnDef.java:22) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:108) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:158) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:187) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:387) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:490) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:150) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.17.1.jar:1.17.1]

**Comment by Wanyi0708** [comment]
I've had this problem before. Have you solved it now？
