### ISSUE TITLE
Maxwell Pull data out of time

### ISSUE THREAD

**Issue by smallatboy** [zendesk/maxwell#1086]
14:47:57,422 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
com.github.shyiko.mysql.binlog.network.ServerException: [d834667c3c00001][10.29.44.156:3306][yh_waybill]Variable @master_binlog_checksum can't be set to the value of @@global.binlog_checksum
	at com.github.shyiko.mysql.binlog.BinaryLogClient.confirmSupportOfChecksum(BinaryLogClient.java:866)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:514)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
	at java.lang.Thread.run(Thread.java:745)
14:47:59,753 ERROR MaxwellContext - Exception occurred during shutdown:
java.util.concurrent.TimeoutException: Timed out trying waiting for com.zendesk.maxwell.replication.BinlogConnectorReplicator process to stop after 1000ms.
	at com.zendesk.maxwell.util.StoppableTaskState.awaitStop(StoppableTaskState.java:46) ~[maxwell-1.13.2.jar:1.13.2]
	at com.zendesk.maxwell.util.RunLoopProcess.awaitStop(RunLoopProcess.java:18) ~[maxwell-1.13.2.jar:1.13.2]
	at com.zendesk.maxwell.util.TaskManager.stop(TaskManager.java:53) ~[maxwell-1.13.2.jar:1.13.2]
	at com.zendesk.maxwell.MaxwellContext.shutdown(MaxwellContext.java:163) [maxwell-1.13.2.jar:1.13.2]
	at com.zendesk.maxwell.MaxwellContext.access$000(MaxwellContext.java:31) [maxwell-1.13.2.jar:1.13.2]
	at com.zendesk.maxwell.MaxwellContext$1$1.run(MaxwellContext.java:186) [maxwell-1.13.2.jar:1.13.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
14:47:59,754 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process
14:47:59,754 ERROR MaxwellContext - Termination reason:
com.github.shyiko.mysql.binlog.network.ServerException: [d834667c3c00001][10.29.44.156:3306][yh_waybill]Variable @master_binlog_checksum can't be set to the value of @@global.binlog_checksum
	at com.github.shyiko.mysql.binlog.BinaryLogClient.confirmSupportOfChecksum(BinaryLogClient.java:866) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:514) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by osheroff** [comment]
what version of mysql are you running?

**Comment by osheroff** [comment]
Hi, because it's been too long waiting for a response, I'm closing down this issue.  Feel free to re-open it if you have more information.  Thanks!
