### ISSUE TITLE
When delete a large table, an error

### ISSUE THREAD

**Issue by blueoo** [zendesk/maxwell#1088]
09:36:25,496 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.network.ServerException: log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master; the first event 'binlog.001768' at 3412492357, the last event read from '/data/dbdata/mysqllog/binlog/binlog.001768' at 123, the last byte read from '/data/dbdata/mysqllog/binlog/binlog.001768' at 3412492376.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
09:36:25,595 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.001768:3412492357 -- restarting

**Comment by osheroff** [comment]
i think the error message may have the correct solution, to increase `max_allowed_packet` on the master.   what is it set at row?

**Comment by osheroff** [comment]
hmmm... are there any log messages that precede the warning?  and what version of maxwell are you using?

**Comment by kevinclcn** [comment]
Hi @osheroff, I experienced the same issue. maxwell is 1.18.0. When a large transaction happens, maxwell logs `Overflowed in-memory buffer, spilling over into /tmp/maxwell6997463603726579128events` , after 30 minutes later,  it reports `binlog disconnected`, `binlog connected`, then it reports this `communication failure` and stuck at that position.

![image](https://user-images.githubusercontent.com/1789301/46255840-eb06c380-c4d4-11e8-9fb1-99e7f7e8ef1c.png)

**Comment by kevinclcn** [comment]
By the way, `/tmp/maxwell6997463603726579128events` is more about 20G.

**Comment by kevinclcn** [comment]
@osheroff I read the maxwell code and I'm sure the `communication failure` has nothing to do with the `Overflowed in-memory buffer, spilling over into` message. I guess both of them relate to the big transactions, but I still can't pin down the root cause.

BTW, the tmp file `/tmp/maxwell6997463603726579128events` written by maxwell will never be purged, is it a disk leak?

**Comment by kevinclcn** [comment]
Hi @osheroff

I find the root cause.

When I use maxwell 1.10.9, I used include_tables option to filter the unrelated tables, so the  big transaction tables will get ignored by maxwell.

When I use maxwell 1.18.0, I use javascript file to filter the unrelated tables, however, maxwell will buffer the rows anyway and then process the buffered rows with javascript. I think maxwell should use javascript file as the same way as the filters option.

**Comment by osheroff** [comment]
sorry for dropping the ball on this one guys.  I guess I lost it in the shuffle.  I could see an argument that there could be a separate javascript hook that runs before a big transaction could buffer.  That javascript would lose access to the row's thread-id, xid, server-id, and a few other things that get setup at the end, but I think it's probably ok. 

LMK if you're still interested in that feature.

**Comment by njalan** [comment]
can remove /tmp/maxwell6997463603726579128events  ?
