### ISSUE TITLE
undead maxwell processes

### ISSUE THREAD

**Issue by osheroff** [zendesk/maxwell#110]
Saw an open-replicator thread die without maxwell restarting it:

```
06,364 ERROR AbstractBinlogParser - failed to parse binlog
 Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196) ~[?:1.7.0_79]
	at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[?:1.7.0_79]
	at com.google.code.or.io.util.ActiveBufferedInputStream.run(ActiveBufferedInputStream.java:85) ~[open-replicator-1.3.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
```

**Comment by osheroff** [comment]
i think I fixed this one awhile back.
