### ISSUE TITLE
java.sql.SQLException

### ISSUE THREAD

**Issue by shehuaqigai** [zendesk/maxwell#1126]
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLException: Incorrect string value: '\xE5\xBE\xAE\xE4\xBF\xA1...' for column 'enum_values' at row 31
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:78) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:58) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:199) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.18.0.jar:1.18.0]
Caused by: java.sql.SQLException: Incorrect string value: '\xE5\xBE\xAE\xE4\xBF\xA1...' for column 'enum_values' at row 31
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at snaq.db.CachedPreparedStatement.execute(CachedPreparedStatement.java:327) ~[dbpool-7.0-jdk7.jar:?]
	at com.zendesk.maxwell.schema.MysqlSavedSchema.executeColumnInsert(MysqlSavedSchema.java:282) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.schema.MysqlSavedSchema.saveSchema(MysqlSavedSchema.java:259) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.schema.MysqlSavedSchema.save(MysqlSavedSchema.java:118) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:89) ~[maxwell-1.18.0.jar:1.18.0]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:73) ~[maxwell-1.18.0.jar:1.18.0]
	... 4 more
18:39:28,578 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@ba92e78
18:39:28,578 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
18:39:28,578 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@3e669e4d
18:39:28,578 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
18:39:28,580 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
18:39:29,796 INFO  TaskManager - Stopped all tasks

**Comment by osheroff** [comment]
should be fixed in 1.19.0
