### ISSUE TITLE
JS Filters problem "TypeError:is not an Object"

### ISSUE THREAD

**Issue by tomlis** [zendesk/maxwell#1137]
I would like to use custom JS filters to truncate all hashes in "data" and "old_data" to certain length, for example max 2000 characeters. 

Here is code for filters: 
```
function process_row(row) {
  row.query = truncate_param(row.query, 3000, false);
  truncate_object(row.data, 2000, true);
  truncate_object(row.old, 2000, true);
}

function truncate_object(obj, maxLength, replaceNulls) {
  Object.keys(obj).forEach(function (key) {
    obj[key] = truncate_param(obj[key], maxLength, replaceNulls);
  });
}

function truncate_param(param, length, replaceNulls) {
  if (typeof param === 'string' || param instanceof String) {
    return param.substring(0, length);
  }
  if (replaceNulls && param == null){
    return '---empty---';		
  }
  return param;
}
```

I tested with using local env, runnig that script by

>  node filters.js

 and giving as input an example row (output from prod's maxwell) like 
`
var row = {"database":"xxx","table":"yyy","query":"..
process_row (row);`
and it seems to worked fine - it truncated all hashes in data and old_data (also replaced nulls with my string) 

However when run on production server with maxwell I get an errors: 
`<eval>:48 TypeError: {id=586845, status_id=74, order_id=22127, type=terg_wk, created_at=2018-10-17 15:38:14} is not an Object`

Full error: 
```

Using kafka version: 1.0.0
15:38:17,844 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
15:38:19,538 ERROR TaskManager - cause: 
jdk.nashorn.internal.runtime.ECMAException: TypeError: {id=586845, status_id=74, order_id=22127, type=terg_wk, created_at=2018-10-17 15:38:14} is not an Object
    at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:?]
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:?]
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:?]
    at jdk.nashorn.internal.objects.NativeObject.notAnObject(NativeObject.java:136) ~[nashorn.jar:?]
    at jdk.nashorn.internal.objects.NativeObject.keys(NativeObject.java:439) ~[nashorn.jar:?]
    at jdk.nashorn.internal.scripts.Script$Recompilation$3$1377AIZ$\^eval\_.truncate_object(<eval>:48) ~[?:?]
    at jdk.nashorn.internal.scripts.Script$Recompilation$1$1182A$\^eval\_.process_row(<eval>:43) ~[?:?]
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?]
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
    at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?]
    at com.zendesk.maxwell.scripting.Scripting.invoke(Scripting.java:56) ~[maxwell-1.18.0.jar:1.18.0]
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:159) ~[maxwell-1.18.0.jar:1.18.0]
    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.18.0.jar:1.18.0]
    at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.18.0.jar:1.18.0]
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.18.0.jar:1.18.0]
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.18.0.jar:1.18.0]
<eval>:48 TypeError: {id=586845, status_id=74, order_id=22127, type=terg_wk, created_at=2018-10-17 15:38:14} is not an Object
    at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
    at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
    at jdk.nashorn.internal.objects.NativeObject.notAnObject(NativeObject.java:136)
    at jdk.nashorn.internal.objects.NativeObject.keys(NativeObject.java:439)
    at jdk.nashorn.internal.scripts.Script$Recompilation$3$1377AIZ$\^eval\_.truncate_object(<eval>:48)
    at jdk.nashorn.internal.scripts.Script$Recompilation$1$1182A$\^eval\_.process_row(<eval>:43)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
    at com.zendesk.maxwell.scripting.Scripting.invoke(Scripting.java:56)
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:159)
    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
    at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
```

Whats wrong ?

**Comment by osheroff** [comment]
`row.data` and `row.old` aren't actually javascript objects, they're java HashMaps.  You seem to be running into the leaks in this abstraction, nashorn seems to do some work to pretend a hashmap is an object.  let me dig further..

**Comment by osheroff** [comment]
quite the lag there.  Try this instead:

```
function truncate_object(obj, maxLength, replaceNulls) {
  for each (var key in obj.keySet()) {
    obj[key] = truncate_param(obj[key], maxLength, replaceNulls);
  }
}
```

Adding to the example.
