### ISSUE TITLE
OpenJDK 11 support

### ISSUE THREAD

**Issue by hdanes** [zendesk/maxwell#1139]
When I try to run Maxwells daemon on Ubuntu 18.04 with openjdk-11 installed on it it gives the following error during startup:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:879)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:245)
	at com.zendesk.maxwell.producer.MaxwellKinesisProducer.<init>(MaxwellKinesisProducer.java:113)
	at com.zendesk.maxwell.MaxwellContext.getProducer(MaxwellContext.java:345)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:186)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 7 more
```

If I perform a downgrade action to openjdk-8 everything is working fine.

**Comment by epkugelmass** [comment]
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

You need to add JAXB to your classpath or modulepath.

**Comment by therealoneisneo** [comment]
Is it possible that Maxwell can add the dependency of javax.xml.bind in to the release?

**Comment by osheroff** [comment]
this was fixed sometime ago
