### ISSUE TITLE
Cannot give object type or array type value at 'row.data' in js filter

### ISSUE THREAD

**Issue by tkaven** [zendesk/maxwell#1168]
filter.js code:
row.data.put(column, {numArray: numArray});

java.lang.IllegalStateException: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed jdk.nashorn.api.scripting.ScriptObjectMirror)
at com.fasterxml.jackson.core.JsonGenerator._writeSimpleObject(JsonGenerator.java:1984)
at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:381)
at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1662)
at com.zendesk.maxwell.row.RowMap.writeValueToJSON(RowMap.java:260)
at com.zendesk.maxwell.row.RowMap.writeMapToJSON(RowMap.java:237)
at com.zendesk.maxwell.row.RowMap.toJSON(RowMap.java:344)
at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.makeProducerRecord(MaxwellKafkaProducer.java:218)
at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.sendAsync(MaxwellKafkaProducer.java:201)
at com.zendesk.maxwell.producer.AbstractAsyncProducer.push(AbstractAsyncProducer.java:75)
at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.run(MaxwellKafkaProducer.java:174)
at java.lang.Thread.run(Thread.java:748)

why not support, i really need this! 

thank you very much

**Comment by osheroff** [comment]
fixed in 1.19.2
