### ISSUE TITLE
Maxwell bootstrap String cannot be cast to [B

### ISSUE THREAD

**Issue by chenfengli1985** [zendesk/maxwell#1170]
14:34:16,978 INFO  SynchronousBootstrapper - bootstrapping started for hcb_avatar.consignor, binlog position is Position[BinlogPosition[mysql-bin.001177:1044806265], lastHeartbeat=1543818854238]
java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23)
	at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:241)
	at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:66)
	at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper$1.run(AsynchronousBootstrapper.java:74)
	at java.lang.Thread.run(Thread.java:748)

**Comment by osheroff** [comment]
this was fixed in v1.16.1, please upgrade.

**Comment by chenfengli1985** [comment]
I see it version,last shoose  v1.9.2,it is running it ,thank you!
