### ISSUE TITLE
MySQL8.0 Maxwell 1.19.2 connect error

### ISSUE THREAD

**Issue by Shuizhiyu** [zendesk/maxwell#1179]

**Comment by Shuizhiyu** [comment]
[XXXX/maxwell-1.19.2]# bin/maxwell --host='XXXX' --user='maxwell' --password='XXXX' --port=X --producer=file --output_file=XX --ssl=DISABLED --metrics_type=datalog
Using kafka version: 1.0.0
15:19:20,571 INFO  TaskManager - Stopping 0 tasks
15:19:20,574 ERROR TaskManager - cause: 
java.sql.SQLException: Access denied for user 'maxwell'@'%' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at snaq.db.CachedStatement.executeQuery(CachedStatement.java:235) ~[dbpool-7.0-jdk7.jar:?]
	at com.zendesk.maxwell.schema.SchemaStoreSchema.storeDatabaseExists(SchemaStoreSchema.java:37) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.schema.SchemaStoreSchema.ensureMaxwellSchema(SchemaStoreSchema.java:30) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:179) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.19.2.jar:1.19.2]
15:19:20,577 INFO  TaskManager - Stopped all tasks
15:19:20,578 ERROR Maxwell - SQLException: Access denied for user 'maxwell'@'%' (using password: YES)

Do I need more parameters? I add an mysql-connector-java-8.0.11.jar and no use. 
Can I connect to MySQL by mysql-connector-java-5.1.47.jar:5.1.47 or I should change the source code?
Thanks very much.
