### ISSUE TITLE
MaxwellSQLSyntaxError at ALTER with ALGORITHM = INPLACE

### ISSUE THREAD

**Issue by jkrcma** [zendesk/maxwell#1196]
Hi again, you can't get rid of me that easily! :P

This is one of the few errors I encountered after we solved the neverending QueryEvent issue. Looks like the support of online DDL change doesn't work really well. See the obfuscated logs (sorry about it, security reasons) below:

```
11:50:24,167 ERROR MysqlParserListener - (parse / * ALTER TABLE `xxxIP` ALGORITHM = INPLACE , LOCK = NONE , CHANGE `xxxn` `xxxn` VARCHAR ( 255 ) NOT NULL COMMENT 'Comment one.' , CHANGE `xxxu` `xxxu` VARCHAR ( 300 ) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Comment two with \'s.' , CHANGE `xxxc` `xxxc` DECIMAL ( 11 , 2 ) UNSIGNED NOT NULL COMMENT 'Comment three.' , CHANGE `xxxs` `xxxs` TINYINT ( 3 ) UNSIGNED NOT NULL COMMENT '1: Enum. 3: Enum. 4: Enum. 8: Enum. 100: Enum.')
11:50:24,167 ERROR SchemaChange - Error parsing SQL: '#XXXIP
/**/
ALTER TABLE `xxxIP` ALGORITHM=INPLACE, LOCK=NONE,
                            CHANGE `xxxn` `xxxn` VARCHAR(255)    NOT NULL   COMMENT 'Comment one.',
                            CHANGE `xxxu` `xxxu` VARCHAR(300)  CHARACTER SET ascii COLLATE ascii_bin NOT NULL   COMMENT 'Comment two with \'s.',
                            CHANGE `xxxc` `xxxc` DECIMAL(11,2)  UNSIGNED  NOT NULL  COMMENT 'Comment three.',
                            CHANGE `xxxs` `xxxs` TINYINT(3)  UNSIGNED  NOT NULL  COMMENT '1: Enum. 3: Enum. 4: Enum. 8: Enum. 100: Enum.''
11:50:24,168 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[...,00003306-1111-0000-0000-000000000002:1-52945620,...], lastHeartbeat=0]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: /
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:87)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:89)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:101)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:254)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:272)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:532)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:159)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
```

And another one:

```
11:58:36,249 ERROR MysqlParserListener - (parse / * ALTER TABLE `xxxOG` ALGORITHM = INPLACE , LOCK = NONE , CHANGE `xxxs` `xxxs` VARCHAR ( 36 ) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'Comment one.' , CHANGE `xxxn` `xxxn` VARCHAR ( 255 ) NOT NULL COMMENT 'Comment two.')
11:58:36,249 ERROR SchemaChange - Error parsing SQL: '#XXXOG
/**/
ALTER TABLE `xxxOG` ALGORITHM=INPLACE, LOCK=NONE,
                        CHANGE `xxxs` `xxxs` VARCHAR(36)  CHARACTER SET utf8 COLLATE utf8_bin    DEFAULT NULL  COMMENT 'Comment one.',
                        CHANGE `xxxn` `xxxn` VARCHAR(255)    NOT NULL   COMMENT 'Comment two.''
11:58:36,249 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[...,00003306-1111-0000-0000-000000000002:1-52945626,...], lastHeartbeat=0]
```

These are all the logs I have from that time so I hope you have an idea where to look.

Running Maxwell 1.19.5.1 (beta test release based on 1.19.5)

**Comment by osheroff** [comment]
i think so.  looks like our parser is choking on the leading `/**/`
