### ISSUE TITLE
MaxwellSQLSyntaxError: default

### ISSUE THREAD

**Issue by tonytototo** [zendesk/maxwell#1202]
15:52:59,966 INFO  Server - Started @1886ms
15:53:00,147 ERROR MysqlParserListener - (table_creation_option default)
15:53:00,148 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE `sac_mgmt`.`just_test` 
COLLATE = default'
15:53:00,148 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[master-bin.000003:38133905], lastHeartbeat=1548832563476]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: default
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:87)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:89)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:101)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:242)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:260)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:498)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:149)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
15:53:00,149 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
15:53:00,150 INFO  TaskManager - Stopping 4 tasks
15:53:00,150 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: default

How to resolve this issue?

**Comment by osheroff** [comment]
what server/version are you running?

**Comment by tonytototo** [comment]
> what server/version are you running?

v1.19.3

**Comment by osheroff** [comment]
Ni, sorry, what version of mysql?

**Comment by tonytototo** [comment]
> No, sorry, what version of mysql?

MySQL 5.6 and 5.7
