### ISSUE TITLE
Unhandled character set 'ujis'

### ISSUE THREAD

**Issue by jkrcma** [zendesk/maxwell#1209]
Hi again! I am absolutely not aware of us using the Japanese character set, maybe it is some broken Java autodetection based on UTF-16 alike characters?

For now resolved by skipping 4 particular transactions, I noted down the GTIDs so I can look them up.

```14:31:57,374 ERROR TaskManager - cause: 
java.lang.RuntimeException: error: unhandled character set 'ujis'
        at com.zendesk.maxwell.schema.columndef.StringColumnDef.charsetForCharset(StringColumnDef.java:59) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:74) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:111) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:161) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:181) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:453) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:568) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:174) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.19.7.jar:1.19.7]
14:31:57,377 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@23ce9b1b
14:31:57,377 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
14:31:57,378 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@46b271e1
14:31:57,378 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
14:31:57,378 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@2dbfb42c
14:31:57,381 INFO  AbstractConnector - Stopped ServerConnector@53b26051{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
14:31:57,383 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@49a489df{/,null,UNAVAILABLE}```

**Comment by jkrcma** [comment]
I isolated the transaction, a table purge, but there is too many of data and I didn't find any corrupted UTF-8.

**Comment by osheroff** [comment]
check the table's schema, I betcha there's a ujis charset in a column somewhere... maxwell doesn't ever auto-detect, it just relies on whatever mysql says...

**Comment by jkrcma** [comment]
I should have done first lol, sorry! Lesson to learn, never trust developers, it is there on one column indeed :D but Maxwell shouldn't get stuck on this

**Comment by osheroff** [comment]
yeah and I think there is a corresponding character set in java we can use.
