### ISSUE TITLE
Maxwell crashing

### ISSUE THREAD

**Issue by rayjlinden** [zendesk/maxwell#1210]
I'm getting some errors from the Maxwell daemon and then it crashes.  Here is the log.  This is running in a docker compose based dev environment.  Everything generally works fine - we have just seen this crash a couple of times and are not able to reproduce it yet.  Any ideas?

00:39:48,627 INFO  SynchronousBootstrapper - bootstrapping started for personas.personas, binlog position is Position[BinlogPosition[binlog.000003:5684655], lastHeartbeat=0]
00:39:48,675 INFO  Replicator - async bootstrapping: replaying 11 skipped rows...
java.lang.NullPointerException
       at java.lang.String.compareTo(String.java:1155)
       at com.zendesk.maxwell.replication.BinlogPosition.newerThan(BinlogPosition.java:103)
       at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper.replaySkippedRows(AsynchronousBootstrapper.java:135)
       at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper.completeBootstrap(AsynchronousBootstrapper.java:101)
       at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper.work(AsynchronousBootstrapper.java:176)
       at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processRow(BinlogConnectorReplicator.java:260)
       at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:185)
       at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
       at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
       at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
       at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
00:39:48,725 INFO  MaxwellContext - Sending final heartbeat: 1550104788725
00:39:53,738 WARN  MaxwellContext - Timed out waiting for heartbeat 1550104788725
00:39:53,740 INFO  TaskManager - Stopping 2 tasks
00:39:53,740 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@2c195967
00:39:53,740 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
00:39:53,740 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@22dea294
00:39:53,740 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
00:39:54,953 ERROR MaxwellContext - Exception occurred during shutdown:
java.util.concurrent.TimeoutException: Timed out trying waiting for com.zendesk.maxwell.replication.BinlogConnectorReplicator process to stop after 1000ms.
       at com.zendesk.maxwell.util.StoppableTaskState.awaitStop(StoppableTaskState.java:46) ~[maxwell-1.19.7.jar:1.19.7]
       at com.zendesk.maxwell.util.RunLoopProcess.awaitStop(RunLoopProcess.java:18) ~[maxwell-1.19.7.jar:1.19.7]
       at com.zendesk.maxwell.util.TaskManager.stop(TaskManager.java:53) ~[maxwell-1.19.7.jar:1.19.7]
       at com.zendesk.maxwell.MaxwellContext.shutdown(MaxwellContext.java:165) [maxwell-1.19.7.jar:1.19.7]
       at com.zendesk.maxwell.MaxwellContext.access$000(MaxwellContext.java:32) [maxwell-1.19.7.jar:1.19.7]
       at com.zendesk.maxwell.MaxwellContext$1$1.run(MaxwellContext.java:188) [maxwell-1.19.7.jar:1.19.7]
       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
00:39:54,962 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process

**Comment by osheroff** [comment]
hmmm, seems as though `binlog_file` is null for the bootstrap.  what does `SELECT * from maxwell.bootstrap` say?
