### ISSUE TITLE
MaxwellSQLSyntaxError for `CONSTRAINT` and `KEY` expression

### ISSUE THREAD

**Issue by ypereirareis** [zendesk/maxwell#1222]
Hi, thanks for the awesome tool :)

**Maxwell error**: 
```
March 7th 2019, 09:02:37.386    08:02:35,531 ERROR TaskManager - cause: 
    March 7th 2019, 09:02:37.386    com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CONSTRAINT
    March 7th 2019, 09:02:37.386        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:87) ~[maxwell-1.19.3.jar:1.19.3]
    March 7th 2019, 09:02:37.386        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
    March 7th 2019, 09:02:37.386        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:149)
    March 7th 2019, 09:02:37.386        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
    March 7th 2019, 09:02:37.386        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
    March 7th 2019, 09:02:37.386        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
    March 7th 2019, 09:02:37.386        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
    March 7th 2019, 09:02:37.385        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:242)
    March 7th 2019, 09:02:37.385        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
```

**SQL**

```sql
use `DATABASE_NAME`;
CREATE TABLE IF NOT EXISTS TABLE_NAME (
 id_agency bigint(18) unsigned NOT NULL DEFAULT '0',
 id_type bigint(18) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (id_agency,id_type),
 KEY id_agency (id_agency),
 KEY id_type (id_type),
 CONSTRAINT ....abae0fb4a3bdb7a037ad3531712f5614 FOREIGN KEY (id_agency) REFERENCES agencies (id) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT ...._types.id_type FOREIGN KEY (id_type) REFERENCES ...._types (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

The same errors for expressions: 

* `KEY id_agency (id_agency)`
* `KEY id_type (id_type)`

Are those cases supposed to work with Maxwell or not ?

Thanks.

**Comment by osheroff** [comment]
these cases should all work. 

Can you give me less obfuscated SQL to work with?  I really can't fix parser errors unless I know exactly what your SQL says.

**Comment by osheroff** [comment]
Ping, need more data

**Comment by ypereirareis** [comment]
Hi,
sorry for the delay, here is the full SQL instruction:

Maybe the dot in the constraint `agencies_offer_gift_types.id_type` ?

```sql
use `database_name`;
CREATE TABLE IF NOT EXISTS table_name (
 id_agency bigint(18) unsigned NOT NULL DEFAULT '0',
 id_type bigint(18) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (id_agency,id_type),
 KEY id_agency (id_agency),
 KEY id_type (id_type),
 CONSTRAINT 112923b397c621505a97cfc4119f9f98abae0fb4a3bdb7a037ad3531712f5614 FOREIGN KEY (id_agency) REFERENCES agencies (id) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT agencies_offer_gift_types.id_type FOREIGN KEY (id_type) REFERENCES insurance_gift_types (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

thanks !!

**Comment by osheroff** [comment]
'twas indeed the dot

**Comment by ypereirareis** [comment]
Hello !

Ok thanks a lot ! :smiley: 

Not supposed to have errors with the `KEY` instructions ? Maybe the same problems with KEY with dots in the name ?

**Comment by osheroff** [comment]
> Not supposed to have errors with the KEY instructions ? Maybe the same problems with KEY with dots in the name ?

Can you give an example of SQL that you have problems with?

**Comment by osheroff** [comment]
looks like we fixed this.
