### ISSUE TITLE
crash when create a new database,how to solve this problem？

### ISSUE THREAD

**Issue by unixomg** [zendesk/maxwell#1237]
when execute create database sql statement, then maxwell crash
I have blacklist config in my config file, add a blacklist:maxwell.* Is this the cause of this problem?
I hope some can help me to solve this problem,thxs.
logs:
```
22:01:10,355 INFO  BinlogConnectorLifecycleListener - Binlog connected.
22:01:16,728 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[82cc6c77-2442-11e9-8f4d-6c92bf314597:1-1113639], lastHeartbeat=1554793292199] after applying "create database coupon_t" to coupon_t, new schema id is 6
22:01:16,876 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
22:01:16,878 INFO  TaskManager - Stopping 3 tasks
22:01:16,878 ERROR TaskManager - cause:
java.lang.NullPointerException: null
        at java.lang.String.replace(String.java:2240) ~[?:1.8.0_201]
        at com.zendesk.maxwell.producer.RabbitmqProducer.getRoutingKeyFromTemplate(RabbitmqProducer.java:67) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.producer.RabbitmqProducer.push(RabbitmqProducer.java:51) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:304) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:313) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:579) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:174) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.21.1.jar:1.21.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.21.1.jar:1.21.1]
22:01:16,884 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@534e97ea
22:01:16,884 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
22:01:16,884 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@64c7d265
22:01:16,884 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
22:01:16,884 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@3f8b0aaa
22:01:16,891 INFO  AbstractConnector - Stopped ServerConnector@5bfbdd74{HTTP/1.1,[http/1.1]}{0.0.0.0:8111}
22:01:16,893 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@666ae910{/,null,UNAVAILABLE}
java.lang.NullPointerException
        at java.lang.String.replace(String.java:2240)
        at com.zendesk.maxwell.producer.RabbitmqProducer.getRoutingKeyFromTemplate(RabbitmqProducer.java:67)
        at com.zendesk.maxwell.producer.RabbitmqProducer.push(RabbitmqProducer.java:51)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:304)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:313)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:579)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:174)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
22:01:17,096 INFO  TaskManager - Stopped all tasks
```
I found that there are no row records for the create database and create table in the maxwell database.

**Comment by osheroff** [comment]
this looks like a simple bug in the rabbit-mq producer (with DDL statements).  will fix.

**Comment by unixomg** [comment]
I saw a fix merged commit 2173534 into master for this bug before, but I downloaded the latest version. This problem still exists. When will this bug be fixed?

**Comment by unixomg** [comment]
crash logs：
`Using kafka version: 1.0.0
09:48:06,559 INFO  SchemaStoreSchema - Creating maxwell database
09:48:07,014 INFO  Maxwell - Maxwell v1.22.0 is booting (RabbitmqProducer), starting at Position[BinlogPosition[373ed479-2e9b-11e9-92c5-fa163e35115e:1-18443], lastHeartbeat=0]
09:48:07,218 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
09:48:07,466 INFO  BinlogConnectorReplicator - Setting initial gtid to: 373ed479-2e9b-11e9-92c5-fa163e35115e:1-18443
09:48:07,471 INFO  MaxwellHTTPServer - Maxwell http server starting
09:48:07,474 INFO  MaxwellHTTPServer - Maxwell http server started on port 8222
09:48:07,490 INFO  log - Logging initialized @1925ms
09:48:07,609 INFO  BinaryLogClient - Connected to 10.209.241.22:3306 at 373ed479-2e9b-11e9-92c5-fa163e35115e:1-18443 (sid:6379, cid:591)
09:48:07,610 INFO  BinlogConnectorLifecycleListener - Binlog connected.
09:48:07,617 INFO  Server - jetty-9.3.25.v20180904, build timestamp: 2018-09-05T05:11:46+08:00, git hash: 3ce520221d0240229c862b122d2b06c12a625732
09:48:07,657 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@73034e34{/,null,AVAILABLE}
09:48:07,670 INFO  AbstractConnector - Started ServerConnector@2f0d4795{HTTP/1.1,[http/1.1]}{0.0.0.0:8222}
09:48:07,670 INFO  Server - Started @2107ms





10:33:22,895 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[373ed479-2e9b-11e9-92c5-fa163e35115e:1-18990], lastHeartbeat=1557023596051] after applying "create database test2" to test2, new schema id is 2
10:33:22,930 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
10:33:22,932 INFO  TaskManager - Stopping 4 tasks
10:33:22,932 ERROR TaskManager - cause: 
java.lang.NullPointerException: null
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_201]
	at com.zendesk.maxwell.producer.RabbitmqProducer.getRoutingKeyFromTemplate(RabbitmqProducer.java:67) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.producer.RabbitmqProducer.push(RabbitmqProducer.java:51) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:322) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:331) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:603) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:175) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:222) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.22.0.jar:1.22.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:243) ~[maxwell-1.22.0.jar:1.22.0]
10:33:22,937 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@2bc54d03
10:33:22,937 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
10:33:22,937 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@746e1d77
10:33:22,937 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNNING)
10:33:22,937 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@6179b634
10:33:22,937 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
10:33:22,937 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@6092aebc
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at com.zendesk.maxwell.producer.RabbitmqProducer.getRoutingKeyFromTemplate(RabbitmqProducer.java:67)
	at com.zendesk.maxwell.producer.RabbitmqProducer.push(RabbitmqProducer.java:51)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:322)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:331)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:603)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:175)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:222)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:243)
10:33:22,943 INFO  AbstractConnector - Stopped ServerConnector@2f0d4795{HTTP/1.1,[http/1.1]}{0.0.0.0:8222}
10:33:22,945 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@73034e34{/,null,UNAVAILABLE}
10:33:23,248 INFO  TaskManager - Stopped all tasks`

**Comment by osheroff** [comment]
this missed the 1.22.0 release, I've posted 1.22.1 which includes a fix.
