### ISSUE TITLE
anyone meet issue while connect to azure(china) mysql?

### ISSUE THREAD

**Issue by plutoid** [zendesk/maxwell#1239]
hi,

mysql: azure mysql 5.6
maxwell version(tried):
maxwell-1.22.0.tar.gz
maxwell-1.18.0.tar.gz

error log like below:
```

Using kafka version: 1.0.0
06:43:02,383 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
06:43:03,082 WARN  MaxwellMysqlStatus - Warning: binlog_row_image is set to MINIMAL.  This may not be what you want.
06:43:03,082 WARN  MaxwellMysqlStatus - See http://maxwells-daemon.io/compat for more information.
06:43:03,301 INFO  Maxwell - Maxwell v1.22.0 is booting (StdoutProducer), starting at Position[BinlogPosition[mysql-bin.000003:
4790], lastHeartbeat=0]
06:43:03,449 DEBUG MysqlSavedSchema - looking to restore schema at target position Position[BinlogPosition[mysql-bin.000003:479
0], lastHeartbeat=0]
06:43:03,454 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.000003:4790], lastHeartbeat=0])
06:43:03,455 DEBUG MysqlSavedSchema - Restoring full schema
06:43:03,474 DEBUG MysqlSavedSchema - Restoring database maxwell...
06:43:03,567 DEBUG MysqlSavedSchema - Restoring database mysql...
06:43:03,591 DEBUG MysqlSavedSchema - Restoring database shu...
06:43:03,591 DEBUG MysqlSavedSchema - Restored all databases
06:43:03,613 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000003:4790
06:43:03,748 INFO  TaskManager - Stopping 3 tasks
06:43:03,748 ERROR TaskManager - cause:
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_144]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_144]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_144]
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[?:1.8.0_144]
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:886) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:857) ~[?:1.8.0_144]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[?:1.8.0_144]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:138) ~[?:1.8.0_144]
        at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:68) ~[mysql-binlog-connecto
r-java-0.19.1.jar:0.19.1]
        at java.io.OutputStream.write(OutputStream.java:116) ~[?:1.8.0_144]
        at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.write(PacketChannel.java:68) ~[mysql-binlog-connector-
java-0.19.1.jar:0.19.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:717) ~[mysql-binlog-connector-java-
0.19.1.jar:0.19.1]
-0.19.1.jar:0.19.1]                                                                                                   [0/1995]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:514) ~[mysql-binlog-connector-java-0.19
.1.jar:0.19.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:825) ~[mysql-binlog-connector-java-0.19.1
.jar:0.19.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
06:43:03,756 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@295d84f9
06:43:03,756 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING
)
06:43:03,757 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@13798213
06:43:03,757 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNN
ING)
06:43:03,757 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@4a957939
06:43:03,758 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in sta
te: RUNNING)
06:43:03,758 DEBUG TaskManager - Awaiting stop of: com.zendesk.maxwell.schema.PositionStoreThread@295d84f9
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:886)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:857)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:138)
        at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:68)
        at java.io.OutputStream.write(OutputStream.java:116)
        at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.write(PacketChannel.java:68)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:717)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:514)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:825)
        at java.lang.Thread.run(Thread.java:748)
06:43:03,759 DEBUG MysqlPositionStore - writing heartbeat: 1555569783757 (last heartbeat written: 1555569336778)
06:43:03,909 DEBUG TaskManager - Awaiting stop of: com.zendesk.maxwell.bootstrap.BootstrapController@13798213
06:43:04,009 DEBUG TaskManager - Awaiting stop of: com.zendesk.maxwell.replication.BinlogConnectorReplicator@4a957939

```

 update:
this related commit in https://github.com/shyiko/mysql-binlog-connector-java/pull/272  , and issue I request in https://github.com/shyiko/mysql-binlog-connector-java/issues/271 , looks Protocol::AuthSwitchRequest  implementation in mysql-binlog-connector-java cause this, hope after code merged in that and can fix this issue too. :)

Regards, Hua

**Comment by plutoid** [comment]
test the new version mysql-binlog-connector-java, solved now. great jobs!
