### ISSUE TITLE
When database add a new table maxwell crash with Couldn't find table exception

### ISSUE THREAD

**Issue by zengyongping** [zendesk/maxwell#1245]
When MySQL database add a new table, maxwell process crash with Couldn't find table exception.
#######################logs below######################
15:00:17,988 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
15:00:17,990 INFO  TaskManager - Stopping 4 tasks
15:00:17,990 ERROR TaskManager - cause:
**java.lang.RuntimeException: Couldn't find table hj_new_model in database XXXXXX**
        at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:33) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:462) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:568) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:174) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.20.0.jar:1.20.0]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.20.0.jar:1.20.0]

**Comment by OpenOpened** [comment]
Please check whether the hj_new_model table is in your maxwell database schemas table?

**Comment by zengyongping** [comment]
> Please check whether the hj_new_model table is in your maxwell database schemas table?

the hj_new_model table not in tables、schemas table，I manual insert table information about hj_new_model.But How maxwell can automatic capture new add tables metadata info?

**Comment by OpenOpened** [comment]
The information in the schame table comes from the data generated by binlog, make sure maxwell can capture binlog build statements or schema changes.

**Comment by zengyongping** [comment]
> generated



> The information in the schame table comes from the data generated by binlog, make sure maxwell can capture binlog build statements or schema changes.

I test many times, maxwell can automatic capture DDL statement, But in production I encounter many times it lost capture create table ddl statement.

**Comment by OpenOpened** [comment]
Please provide the corresponding version of mysql and maxwell and test DDL statements

**Comment by zengyongping** [comment]
> Please provide the corresponding version of mysql and maxwell and test DDL statements
CREATE TABLE `hj_new_model` (
  `pid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `id` varchar(64) NOT NULL DEFAULT '',
  `case_id` varchar(64) NOT NULL DEFAULT '',
  `customer_account` varchar(64) NOT NULL DEFAULT '' ,
  `val1` varchar(100) DEFAULT NULL ,
  `val2` varchar(100) DEFAULT NULL ,
  `status` varchar(10) DEFAULT NULL ,
  `create_by` varchar(64) DEFAULT NULL ,
  `create_date` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `update_by` varchar(64) DEFAULT NULL ,
  `update_date` datetime DEFAULT NULL ,
  `remarks` varchar(255) DEFAULT NULL,
  `version` varchar(64) DEFAULT NULL ,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `id` (`id`),
  KEY `index_create_date` (`create_date`),
  KEY `index_case_id` (`case_id`),
  KEY `index_customer_account` (`customer_account`)
) ENGINE=InnoDB CHARSET=utf8 COMMENT='new model data';

**Comment by kevinclcn** [comment]
yep, I experienced lots of times of this as well. Would it be feasible to ignore the tables aren't in the filter list? @osheroff 

```
java.lang.RuntimeException: Couldn't find table zlist_member_temp_XXX in database XXXX
        at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:28)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:397)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:491)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:150)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
```

**Comment by kevinclcn** [comment]
@osheroff since all my temp tables have a fixed pattern in their names, I think I can use the blacklist filter to skip them. However, I find a potential [memory leak point](https://github.com/zendesk/maxwell/blob/d972d766fb53ad98cf169f2448f70580049f90c7/src/main/java/com/zendesk/maxwell/replication/TableCache.java#L22) about the blacklist filter. It only add the blacklisted tables but won't remove it. It might a minor leak for others, but for me it is a major issue since everyday I will create lots of temp tables and drop them.

**Comment by kevinclcn** [comment]
I just open a PR here https://github.com/zendesk/maxwell/pull/1265

**Comment by osheroff** [comment]
sorry for the delay @kevinclcn.  I'm unclear on why exactly maxwell isn't picking up the new tables when you create them; can you provide SQL on how the temp tables are created?

**Comment by kevinclcn** [comment]
@osheroff, something like this `CREATE TABLE <table_name> LIKE zcustomer_tag_temp`

**Comment by osheroff** [comment]
@kevinclcn please be *very* specific.  what is the tables, what are the databases, what is the SQL, what is the error messge? 

Blacklisting is fine and all but we should fix the underlying issue.

**Comment by kevinclcn** [comment]
Hi @osheroff This kind of error does not happen constantly. I only saw them several times. These table name are not stable since they are temporary tables. I get name one from the error logs: `zlist_member_temp_600_443877273679044608_8323537`. 

The SQL is `CREATE TABLE zlist_member_temp_600_443877273679044608_8323537 LIKE zcustomer_tag_temp`, where `zcustomer_tag_temp` is a fixed table with only one column.

```sql
CREATE TABLE `zcustomer_tag_temp` (
  `customer_id` bigint(20) NOT NULL,
  UNIQUE KEY `idx_zcustomer_tag_temp_customer_id` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
The error message is:
![image](https://user-images.githubusercontent.com/1789301/59687473-6baa5300-920f-11e9-88a6-a463959416b3.png)

BTW, we usually create hundreds of this type of temp tables every night for customer segments calculation.

**Comment by osheroff** [comment]
interesting, so maybe a race condition or something?  do you have a stack trace as well?

**Comment by kevinclcn** [comment]
Unfortunately, there wasn't stack trace printed. It looks like a race condition.

**Comment by makiet** [comment]
I got a same issue, here is the error log, hope it helps.
> {
 insertId: "bxzyq5fxjkqvk"  
 labels: {…}  
 logName: "projects/custome-161813/logs/maxwell"  
 receiveTimestamp: "2019-11-08T04:32:41.680567510Z"  
 resource: {…}  
 severity: "ERROR"  
 textPayload: "04:32:34,273 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000044:175891480], lastHeartbeat=0] after applying "CREATE TABLE `backup`.`sp_2512_corp_bss` (   `global_id` char(12) COLLATE utf8_bin NOT NULL,   `reg_pgm_id` varchar(32) COLLATE utf8_bin NOT NULL,   `reg_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,   `upd_pgm_id` varchar(32) COLLATE utf8_bin DEFAULT NULL,   `upd_timestamp` timestamp NULL DEFAULT NULL,   `corp_id` int(11) NOT NULL DEFAULT '0',   `corp_frml_name_vch` varchar(400) COLLATE utf8_bin NOT NULL,   `corp_legal_name_vch` varchar(400) COLLATE utf8_bin DEFAULT NULL,   `legal_name_display_sgn` int(11) DEFAULT '0',   `corp_imfrml_name_vch` varchar(32) COLLATE utf8_bin DEFAULT NULL,   `eng_corp_imfrml_name_vch` varchar(64) COLLATE utf8_bin DEFAULT NULL,   `corp_name_kana_vch` varchar(128) COLLATE utf8_bin DEFAULT NULL,   `corp_name_eng_vch` varchar(400) COLLATE utf8_bin DEFAULT NULL,   `add_srch_name_vch` varchar(700) COLLATE utf8_bin DEFAULT NULL,   `srch_corp_name_vch` varchar(1000) COLLATE utf8_bin NOT NULL,   `corp_stts_id` int(1) NOT NULL DEFAULT '0',   `corp_stts_ap_typ` int(1) DEFAULT '0',   `list_sgn` int(1) NOT NULL DEFAULT '0',   `list_ymd` int(8) DEFAULT NULL,   `list_mkt_id` int(8) DEFAULT NULL,   `delist_ymd` int(8) DEFAULT NULL,   `sec_idnt_cd` varchar(5) COLLATE utf8_bin DEFAULT NULL,   `registration_num` varchar(50) COLLATE utf8_bin DEFAULT NULL,   `ticker` varchar(15) COLLATE utf8_bin DEFAULT NULL,   `tykz_corp_cd` char(6) COLLATE utf8_bin DEFAULT NULL,   `tnc_cd` char(10) COLLATE utf8_bin DEFAULT NULL,   `ms_company_id` char(10) COLLATE utf8_bin DEFAULT NULL,   `nice_kis_code` char(6) COLLATE utf8_bin DEFAULT NULL,   `tej_company_cd` varchar(12) COLLATE utf8_bin DEFAULT NULL,   `wvb_company_id` int(11) DEFAULT NULL,   `tsr_company_code` varchar(12) COLLATE utf8_bin DEFAULT NULL,   `edinet_cd` char(6) COLLATE utf8_bin DEFAULT NULL,   `cik` varchar(10) COLLATE utf8_bin DEFAULT NULL,   `corp_sgn` int(1) NOT NULL DEFAULT '0',   `inout_typ` int(1) NOT NULL DEFAULT '0',   `main_idst_id` varchar(12) COLLATE utf8_bin DEFAULT NULL,   `close_typ` int(1) DEFAULT NULL,   `data_digit_typ` int(1) DEFAULT NULL,   `estbl_ymd` int(8) DEFAULT NULL,   `acc_term_num` int(1) DEFAULT '0',   `most_rcnt_quarter_year` int(4) DEFAULT NULL,   `most_rcnt_quarter_period_num` int(6) DEFAULT NULL,   `most_rcnt_quarter_acc_sttl_cd` char(3) COLLATE utf8_bin DEFAULT NULL,   `most_rcnt_full_year_year` int(4) DEFAULT NULL,   `most_rcnt_full_year_period_num` int(6) DEFAULT NULL,   `co_emply_num` decimal(8,0) DEFAULT NULL,   `co_emply_acc_sttl_period_num` int(8) DEFAULT NULL,   `nc_emply_num` decimal(8,0) DEFAULT NULL,   `nc_emply_acc_sttl_period_num` int(8) DEFAULT NULL,   `conc_unknown_emply_num` decimal(8,0) DEFAULT NULL,   `conc_unknown_emply_acc_sttl_period_num` int(8) DEFAULT NULL,   `avg_annl_incm_num` decimal(12,2) DEFAULT NULL,   `avg_annl_incm_acc_sttl_period_num` int(6) DEFAULT NULL,   `avg_age_num` decimal(5,2) DEFAULT NULL,   `avg_age_acc_sttl_period_num` int(6) DEFAULT NULL,   `tosyo_33_idst_cd` char(4) COLLATE utf8_bin DEFAULT NULL,   `mv_num` double DEFAULT NULL,   `compare_target_changed_sgn` int(1) NOT NULL DEFAULT '1',   `country_id` char(3) COLLATE utf8_bin NOT NULL,   `global_option_typ` int(1) DEFAULT NULL,   `splr_id` int(2) DEFAULT NULL,   `eng_splr_id` int(11) DEFAULT NULL,   `currency_id` char(3) COLLATE utf8_bin DEFAULT NULL,   `credit_report_splr_id` int(11) DEFAULT NULL,   `active_typ` int(11) NOT NULL DEFAULT '1',   `dissolved_sgn` int(1) NOT NULL DEFAULT '0',   `country_id_legal` char(3) COLLATE utf8_bin DEFAULT NULL )" to speeda, new schema id is 2
"  
 timestamp: "2019-11-08T04:32:34.274510015Z"  
}

**Comment by wanghangyu817** [comment]
@zengyongping Has the problem been solved?The table was clearly in the database, but there was no such table in the schema. When I retried and restarted, I found that Maxwell could not be started. I had no choice but to delete the Maxwell library, which meant that all my synchronous links would have problems.I think this is a problem worth taking seriously.

**Comment by dalaopo** [comment]
> 值得

Now there is still this problem
