### ISSUE TITLE
event 'Gtid' error

### ISSUE THREAD

**Issue by along-npl** [zendesk/maxwell#1282]
Using kafka version: 1.0.0
16:35:28,448 INFO  Maxwell - Maxwell v1.21.1 is booting (RabbitmqProducer), starting at Position[BinlogPosition[mysql-bin.000419:36050366], lastHeartbeat=1562073872714]
16:35:28,566 INFO  MysqlSavedSchema - Restoring schema id 287 (last modified at Position[BinlogPosition[mysql-bin.000418:38373755], lastHeartbeat=1562072599988])
16:35:28,721 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.000058:11468639], lastHeartbeat=0])
16:35:28,799 INFO  MysqlSavedSchema - beginning to play deltas...
16:35:28,873 INFO  MysqlSavedSchema - played 286 deltas in 74ms
16:35:28,887 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000419:36050366
16:35:28,893 INFO  MaxwellHTTPServer - Maxwell http server starting
16:35:28,895 INFO  MaxwellHTTPServer - Maxwell http server started on port 8080
16:35:28,907 INFO  log - Logging initialized @1328ms
16:35:28,955 INFO  Server - jetty-9.3.25.v20180904, build timestamp: 2018-09-05T05:11:46+08:00, git hash: 3ce520221d0240229c862b122d2b06c12a625732
16:35:28,985 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@2939cd1b{/,null,AVAILABLE}
16:35:28,993 INFO  BinaryLogClient - Connected to 192.168.0.210:3306 at mysql-bin.000419/36050366 (sid:6379, cid:12102803)
16:35:28,993 INFO  BinlogConnectorLifecycleListener - Binlog connected.
16:35:28,995 INFO  AbstractConnector - Started ServerConnector@723c07f9{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
16:35:28,995 INFO  Server - Started @1417ms
16:35:29,048 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
16:35:29,049 INFO  TaskManager - Stopping 3 tasks
16:35:29,049 ERROR TaskManager - cause:
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:34) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:50) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:111) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:161) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:175) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:453) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:568) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:174) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.21.1.jar:1.21.1]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.21.1.jar:1.21.1]
16:35:29,051 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@3b5408f1
16:35:29,052 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
16:35:29,052 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@540d7f63
16:35:29,052 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
16:35:29,052 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@b9de07c
16:35:29,055 INFO  AbstractConnector - Stopped ServerConnector@723c07f9{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
16:35:29,056 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@2939cd1b{/,null,UNAVAILABLE}
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:34)
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:50)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:111)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:161)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:175)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:453)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:568)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:174)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
16:35:29,268 INFO  TaskManager - Stopped all tasks

**Comment by along-npl** [comment]
binlog postion value 'SET @@SESSION.GTID_NEXT= 'd235cd74-673d-11e9-b239-fa163eb261c1:6585641'
'

**Comment by osheroff** [comment]
what version of mysql?  looks like maybe your schema got out of sync.  but I'm not sure.  I'm going to put more information errors in the next version of maxwell because i'm sick of chasing these blind.

**Comment by along-npl** [comment]
MySQL 5.7.23
