### ISSUE TITLE
maxwell give error

### ISSUE THREAD

**Issue by laokan** [zendesk/maxwell#1297]
05:06:43,783 ERROR TaskManager - cause: 
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:32) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:48) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:108) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:158) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:172) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:382) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:491) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:149) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.19.2.jar:1.19.2]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.19.2.jar:1.19.2]
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:32)
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:48)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:108)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:158)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:172)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:382)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:491)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:149)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)

**Comment by osheroff** [comment]
often this means your schema is out of sync with your database.  You can try dropping the maxwell database and restarting, but is there anything odd you did with regard to maxwell's binlog position?
