### ISSUE TITLE
ERROR SchemaChange - Error parsing SQL: ALTER TABLE fnd_lookup_value_b MODIFY COLUMN fnd_lookup_value_b.attribute5 VARCHAR(500)

### ISSUE THREAD

**Issue by Daryl9441** [zendesk/maxwell#1303]
Maxwell is crashing with the following error today. Restarting it doesn't solve the problem unfortunately.

`
11:45:55,206 INFO  AppInfoParser - Kafka version : 1.0.0
11:45:55,206 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
11:45:55,272 INFO  Maxwell - Maxwell v1.22.3 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[binlog.002044:621154317], lastHeartbeat=1564629380074]
11:45:55,725 INFO  MysqlSavedSchema - Restoring schema id 5852 (last modified at Position[BinlogPosition[binlog.002044:508426497], lastHeartbeat=1564576776087])
11:45:56,147 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[binlog.001939:104765273], lastHeartbeat=0])
11:45:57,231 INFO  MysqlSavedSchema - beginning to play deltas...
11:45:58,042 INFO  MysqlSavedSchema - played 5851 deltas in 810ms
11:45:58,065 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: binlog.002044:621154317
11:45:58,159 INFO  BinaryLogClient - Connected to 10.92.1.102:3306 at binlog.002044/621154317 (sid:6379, cid:1711145)
11:45:58,159 INFO  BinlogConnectorLifecycleListener - Binlog connected.
11:45:58,358 ERROR MysqlParserListener - (data_type . attribute5 VARCHAR ( 500 ))
11:45:58,359 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE fnd_lookup_value_b MODIFY COLUMN fnd_lookup_value_b.attribute5 VARCHAR(500)'
11:45:58,359 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[binlog.002044:621154413], lastHeartbeat=1564629380074]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: .
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:89)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:101)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:309)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:331)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:603)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:175)
`

**Comment by osheroff** [comment]
https://github.com/zendesk/maxwell/pull/1329 will fix this one too.  Do note that eventually mysql stops supporting this (naming a column `table.col` inside an alter statement) and it's best to eventually stop doing it.

**Comment by osheroff** [comment]
fixed in v1.22.5
