### ISSUE TITLE
Unexpectedly asked to create existing database zendesk_development

### ISSUE THREAD

**Issue by bastien** [zendesk/maxwell#131]
After bootstrapping the docker images I can no longer start the maxwell image which throws this error:

```
13:06:09,458 DEBUG SchemaChange - SQL_PARSE ->   (parse (statement (create_database CREATE DATABASE (name (id `zendesk_development`)))) <EOF>)
com.zendesk.maxwell.schema.ddl.SchemaSyncError: Unexpectedly asked to create existing database zendesk_development
	at com.zendesk.maxwell.schema.ddl.DatabaseCreate.apply(DatabaseCreate.java:25)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:279)
	at com.zendesk.maxwell.MaxwellReplicator.getEvent(MaxwellReplicator.java:253)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:82)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:88)
13:06:09,460 INFO  SchemaPosition - Storing final position: null
```

Both @rbarfoed and I have been experiencing this error.

How to reproduce:

1) run `./bin/onboard` from the docker-images folder
2) `zdi maxwell start`

**Comment by jpeyper** [comment]
I have also been seeing this error while evaluating Maxwell in a fedora VM (not in a docker image).
```
09:25:53,554 DEBUG SchemaChange - SQL_PARSE <- "CREATE DATABASE /*! IF NOT EXISTS */ error"
09:25:53,556 DEBUG SchemaChange - SQL_PARSE ->   (parse (statement (create_database CREATE DATABASE (name (id error)))) <EOF>)
com.zendesk.maxwell.schema.ddl.SchemaSyncError: Unexpectedly asked to create existing database error
	at com.zendesk.maxwell.schema.ddl.DatabaseCreate.apply(DatabaseCreate.java:25)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:280)
	at com.zendesk.maxwell.MaxwellReplicator.getEvent(MaxwellReplicator.java:253)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
09:25:53,558 INFO  SchemaPosition - Storing final position: null
```

**Comment by osheroff** [comment]
@jpeyper that's interesting, a different issue than this one I think.  that's mysql's odd habits of embedding non-compatible SQL within sql "comments" that aren't actually comments.  Can you open a separate issue for it though?

**Comment by jpeyper** [comment]
new issue raised: https://github.com/zendesk/maxwell/issues/158

**Comment by osheroff** [comment]
thanks jpeyper

**Comment by osheroff** [comment]
this issue is very zendesk specific, closing.
