### ISSUE TITLE
ERROR Maxwell - SQLException: Communications link failure

### ISSUE THREAD

**Issue by wzwpinguo** [zendesk/maxwell#1324]
2019-08-27 11:36:15,196 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000064:511093499], lastHeartbeat=1566917148600] after applying "ALTER table yjyg.t_pt_online_order_marketing RENAME TO yjyg.t_pt_online_marketing" to , new schema id is 39

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Server shutdown in progress
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
	at snaq.db.CachedPreparedStatement.executeQuery(CachedPreparedStatement.java:143)
	at com.zendesk.maxwell.bootstrap.BootstrapController.getIncompleteTasks(BootstrapController.java:92)
	at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:57)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.MaxwellContext.lambda$getBootstrapController$0(MaxwellContext.java:392)
	at java.lang.Thread.run(Thread.java:748)
2019-08-27 12:14:43,779 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.000064:537402786], lastHeartbeat=1566922482768]
2019-08-27 12:14:43,782 ERROR PositionStoreThread - error storing final position: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2019-08-27 12:14:43,786 INFO  TaskManager - Stopping 5 tasks
2019-08-27 12:14:43,786 ERROR TaskManager - cause: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_131]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_131]
	at snaq.db.ConnectionPool.create(ConnectionPool.java:256) ~[dbpool-7.0-jdk7.jar:?]
	at snaq.db.ConnectionPool.create(ConnectionPool.java:71) ~[dbpool-7.0-jdk7.jar:?]
	at snaq.util.ObjectPool.checkOut(ObjectPool.java:377) ~[dbpool-7.0-jdk7.jar:?]
	at snaq.db.ConnectionPool.getConnection(ConnectionPool.java:385) ~[dbpool-7.0-jdk7.jar:?]
	at com.zendesk.maxwell.schema.MysqlPositionStore.set(MysqlPositionStore.java:62) ~[maxwell-1.22.3.jar:1.22.3]
	at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:97) ~[maxwell-1.22.3.jar:1.22.3]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.22.3.jar:1.22.3]
	at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40) ~[maxwell-1.22.3.jar:1.22.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	... 22 more
2019-08-27 12:14:43,799 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@79a422ed
2019-08-27 12:14:43,799 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: STOPPED)
2019-08-27 12:14:43,800 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@35dbc8af
2019-08-27 12:14:43,800 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
2019-08-27 12:14:43,804 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-08-27 12:14:43,817 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@2e146140
2019-08-27 12:14:43,817 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: STOPPED)
2019-08-27 12:14:43,817 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@2938ad2e
2019-08-27 12:14:43,817 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
2019-08-27 12:14:43,818 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@6f790ae7
2019-08-27 12:14:43,827 INFO  AbstractConnector - Stopped ServerConnector@77da7d28{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-08-27 12:14:43,831 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@2ab202a7{/,null,UNAVAILABLE}
2019-08-27 12:14:43,836 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
2019-08-27 12:14:45,257 INFO  TaskManager - Stopped all tasks
2019-08-27 12:14:45,259 ERROR Maxwell - SQLException: Communications link failure

**Comment by osheroff** [comment]
> com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Server shutdown in progress

server shutdown underneath maxwell here, crashing seems like what should happen.
