### ISSUE TITLE
ERROR：com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

### ISSUE THREAD

**Issue by wzwpinguo** [zendesk/maxwell#1327]
2019-08-28 16:28:16,428 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000065:276286711], lastHeartbeat=1567024094703] after applying "create table stu(name varchar(100),age int)" to oggtest, new schema id is 12
2019-08-28 17:56:20,779 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.000065:282043370], lastHeartbeat=1567029379746]
2019-08-28 17:56:20,784 ERROR PositionStoreThread - error storing final position: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2019-08-28 17:56:20,787 INFO  TaskManager - Stopping 5 tasks
2019-08-28 17:56:20,787 ERROR TaskManager - cause: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet successfully received from the server was 25 milliseconds ago.  The last packet sent successfully to the server was 25 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3905) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at snaq.db.CachedPreparedStatement.execute(CachedPreparedStatement.java:327) ~[dbpool-7.0-jdk7.jar:?]
	at com.zendesk.maxwell.schema.MysqlPositionStore.set(MysqlPositionStore.java:77) ~[maxwell-1.22.3.jar:1.22.3]
	at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:97) ~[maxwell-1.22.3.jar:1.22.3]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.22.3.jar:1.22.3]
	at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40) ~[maxwell-1.22.3.jar:1.22.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3014) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	... 13 more
2019-08-28 17:56:20,796 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@17ac771b
2019-08-28 17:56:20,797 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: STOPPED)
2019-08-28 17:56:20,797 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@3a2559c5
2019-08-28 17:56:20,797 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
2019-08-28 17:56:20,797 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-08-28 17:56:20,818 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@68395fff
2019-08-28 17:56:20,818 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNNING)
2019-08-28 17:56:20,818 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@cf1b7c3
2019-08-28 17:56:20,818 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
2019-08-28 17:56:20,818 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@78910de9
2019-08-28 17:56:20,830 INFO  AbstractConnector - Stopped ServerConnector@1002c4ec{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-08-28 17:56:20,836 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@1cf34bdf{/,null,UNAVAILABLE}
2019-08-28 17:56:20,848 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
2019-08-28 17:56:22,266 INFO  TaskManager - Stopped all tasks
2019-08-28 17:56:22,268 ERROR Maxwell - SQLException: Communications link failure

The last packet successfully received from the server was 25 milliseconds ago.  The last packet sent successfully to the server was 25 milliseconds ago.

**Comment by osheroff** [comment]
did you shutdown mysql out from underneath maxwell?

**Comment by osheroff** [comment]
closing issue due to inactivity, feel free to open with more information.
