### ISSUE TITLE
 output_primary_keys_columns is not a recognized option

### ISSUE THREAD

**Issue by zhangxinjian123** [zendesk/maxwell#1328]
My Maxwell version is 1.22.4

bin/maxwell --user='root' --password='passwor' --host='192.168.0.13'--producer=kafka --kafka.bootstrap.servers=192.168.0.9:9092,192.168.0.10:9092,192.168.0.11:9092 --kafka_topic=maxwell --output_primary_keys=true --output_primary_keys_columns=true
Using kafka version: 1.0.0
joptsimple.UnrecognizedOptionException: output_primary_keys_columns is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:449)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:381)
	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:330)
	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:149)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:228)

_Originally posted by @zhangxinjian123 in https://github.com/zendesk/maxwell/issues/1326#issuecomment-526434730_

**Comment by liquidgenius** [comment]
--output_primary_keys_columns is indeed not an option. Apologies on my previous bad advice. Use --output_primary_key_columns instead.
