### ISSUE TITLE
 ERROR MaxwellHTTPServer - Maxwell http server failure

### ISSUE THREAD

**Issue by wzwpinguo** [zendesk/maxwell#1331]
2019-09-05 18:57:47,148 INFO  AppInfoParser - Kafka version : 1.0.0
2019-09-05 18:57:47,149 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
2019-09-05 18:57:47,302 INFO  Maxwell - Maxwell v1.22.4 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mysql-bin.000207:34435756], lastHeartbeat=0]
2019-09-05 18:57:47,592 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
2019-09-05 18:57:50,390 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000207:34435756
2019-09-05 18:57:50,397 INFO  MaxwellHTTPServer - Maxwell http server starting
2019-09-05 18:57:50,402 INFO  MaxwellHTTPServer - Maxwell http server started on port 8080
2019-09-05 18:57:50,429 INFO  log - Logging initialized @6071ms
2019-09-05 18:57:50,506 INFO  BinaryLogClient - Connected to 10.60.59.62:30013 at mysql-bin.000207/34435756 (sid:6379, cid:5176)
2019-09-05 18:57:50,506 INFO  BinlogConnectorLifecycleListener - Binlog connected.
2019-09-05 18:57:50,546 INFO  Server - jetty-9.3.27.v20190418, build timestamp: 2019-04-19T02:11:38+08:00, git hash: d3e249f86955d04bc646bb620905b7c1bc596a8d
2019-09-05 18:57:50,624 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@349162d6{/,null,AVAILABLE}
2019-09-05 18:57:50,627 ERROR MaxwellHTTPServer - Maxwell http server failure
java.lang.RuntimeException: java.net.BindException: Address already in use
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.run(MaxwellHTTPServer.java:117) ~[maxwell-1.22.4.jar:1.22.4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_102]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_102]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_102]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_102]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_102]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.Server.doStart(Server.java:406) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.27.v20190418.jar:9.3.27.v20190418]
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.startServer(MaxwellHTTPServer.java:108) ~[maxwell-1.22.4.jar:1.22.4]
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.run(MaxwellHTTPServer.java:115) ~[maxwell-1.22.4.jar:1.22.4]
	... 1 more
2019-09-05 18:57:50,638 INFO  TaskManager - Stopping 5 tasks
2019-09-05 18:57:50,638 ERROR TaskManager - cause: 
java.lang.RuntimeException: java.net.BindException: Address already in use
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.run(MaxwellHTTPServer.java:117) ~[maxwell-1.22.4.jar:1.22.4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_102]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_102]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_102]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_102]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_102]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.server.Server.doStart(Server.java:406) ~[jetty-server-9.3.27.v20190418.jar:9.3.27.v20190418]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.27.v20190418.jar:9.3.27.v20190418]
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.startServer(MaxwellHTTPServer.java:108) ~[maxwell-1.22.4.jar:1.22.4]
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.run(MaxwellHTTPServer.java:115) ~[maxwell-1.22.4.jar:1.22.4]
	... 1 more
2019-09-05 18:57:50,644 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@5bce1018
2019-09-05 18:57:50,644 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
2019-09-05 18:57:50,644 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@5509e511
2019-09-05 18:57:50,644 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
2019-09-05 18:57:50,647 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-09-05 18:57:50,807 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@4765ea1c
2019-09-05 18:57:50,807 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNNING)
2019-09-05 18:57:50,808 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@741b1065
2019-09-05 18:57:50,808 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
2019-09-05 18:57:50,808 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@406517c1
2019-09-05 18:57:50,810 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
2019-09-05 18:57:50,815 INFO  AbstractConnector - Stopped ServerConnector@34672b54{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-09-05 18:57:50,819 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@349162d6{/,null,UNAVAILABLE}
2019-09-05 18:57:51,937 ERROR MaxwellKafkaProducer - Topic 'jgdatasync' name does not exist. Exception: java.lang.InterruptedException
2019-09-05 18:57:52,238 INFO  TaskManager - Stopped all tasks
java.lang.RuntimeException: java.net.BindException: Address already in use
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.run(MaxwellHTTPServer.java:117)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:406)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.startServer(MaxwellHTTPServer.java:108)
	at com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker.run(MaxwellHTTPServer.java:115)
	... 1 more

**Comment by wzwpinguo** [comment]
--http_port=8081,its ok to go to.

**Comment by osheroff** [comment]
Sorry did you figure out the problem?
