### ISSUE TITLE
Maxwell fails to load table cache

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1339]
I am using maxwell v.1.22.5 and MySQL v8.0.4. Maxwell is running within a docker container on an EC2 instance, and MySQL is running in a different EC2 instance.

I am running maxwell using docker

`sudo docker run -it --rm zendesk/maxwell bin/maxwell --user='maxwell' --password='XXXXXX' --host="X.X.X.X" --producer=stdout --init_position=master.000143:83923572`

I am giving init_position as it fails otherwise with following error com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file.

With init_position option, I get following error:

```
BinaryLogClient - Connected to 10.11.3.221:3306 at master.000143/839235728 (sid:6379, cid:1051309)
16:53:53,235 INFO  BinlogConnectorLifecycleListener - Binlog connected.
16:53:53,336 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
16:53:53,338 INFO  TaskManager - Stopping 3 tasks
16:53:53,339 ERROR TaskManager - cause:
java.lang.RuntimeException: Couldn't find database metabase
    at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:26) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:490) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:596) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:177) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:222) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.22.5.jar:1.22.5]
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:243) ~[maxwell-1.22.5.jar:1.22.5]
```
Can someone throw light on what seems to be the exact problem? PS: I checked within MySQL that a DB named 'metabase' exists. Also, I have another maxwell instance listening on the MySQL master which i am running via simple command line, something like `bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' --producer=stdout`

**Comment by osheroff** [comment]
if you want to run two maxwell instances on one host you need to separate them with two different `--client_id` flags.  I'm not sure this is the problem you have, but try that for a start.  

`--init_position` should not be necessary, it's almost definitely what's causing the "couldn't find database" error.

**Comment by Shukla-Ankur** [comment]
tried this but same issue. Anyway, if client_id was not unique, then it should not have connected to binlog in first place.

**Comment by osheroff** [comment]
drop the maxwell database and restart both clients with different client_ids.  the one that you're trying to start with "init_position" is picking up a bad position from the database.

**Comment by osheroff** [comment]
closing this issue, hope it was solved.  if not feel free to reopen.
