### ISSUE TITLE
om.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: page_compressed

### ISSUE THREAD

**Issue by YuQuan-Liu** [zendesk/maxwell#1360]
We use Maxwell(1.22.0) write binlog to kafka(0.11.0.3). The process is ok long time, but recent the DBA run sql like "alter table tb_img_server_flag page_compressed = 1" ,the process is stopped with error.

**The error log:**
`2019-10-17 18:13:54,776 - ERROR com.zendesk.maxwell.schema.ddl.MysqlParserListener - (alter_specification page_compressed = 1)
2019-10-17 18:13:54,805 - ERROR com.zendesk.maxwell.schema.ddl.SchemaChange - Error parsing SQL: 'alter table tb_img_server_flag page_compressed = 1'
2019-10-17 18:13:54,805 - ERROR com.zendesk.maxwell.schema.AbstractSchemaStore - Error on bin log position Position[BinlogPosition[master-bin.003374:480986641], lastHeartbeat=0]
2019-10-17 18:13:54,878 - ERROR com.zendesk.maxwell.util.TaskManager - cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: page_compressed
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.22.0.jar:1.22.0]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:89) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:101) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:309) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:331) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:603) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:175) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:222) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.22.0.jar:1.22.0]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:243) ~[maxwell-1.22.0.jar:1.22.0]`

**Comment by osheroff** [comment]
MariaDB is not supported (although it can limp along).  at some point will get a large test suite going for how it diverges from mysql.

**Comment by YuQuan-Liu** [comment]
OK. Thanks, I connect with our DBA , he help jump the page_compressed binlog , after modify binlog_position in position table,restart maxwell, it's Good again.

**Comment by HusTech1982** [comment]
@YuQuan-Liu  we are getting same error com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: `PAGE_COMPRESSED` . 
please advise the solution to skip the bin log position. is there a SQL statement for this? 

using mariaDB 10.4 and maxwell v1.38 

thanks in advance.
