### ISSUE TITLE
pubsub messages not generating from a slave db

### ISSUE THREAD

**Issue by GhostDZ9** [zendesk/maxwell#1367]
Below is the following architecture that I am trying to achieve. I would like to be able to hook up Maxwells Daemon to a Slave DB so that for every replication to the slave (done through binlogs) it would trigger a PubSub message via PubSub.

![Untitled Diagram](https://user-images.githubusercontent.com/873459/67973873-b9848e00-fbe7-11e9-93dc-5af5988ce4a1.jpg)

When I do the following connection on the slave server I don't receive any messages via pubsub.

**Command**
`bin/maxwell --user='XXXXX' --password='XXXXXX' --host='127.0.0.1' --producer=pubsub --pubsub_project_id='myproject' --pubsub_topic='mytopic' --pubsub_rpc_timeout_multiplier=5 --client_id='computer1'`

**OUTPUT**
 - No Messages received via pubsub

If I do the following I get the following error when executing the command to run MD on the slave.

**COMMAND**
`bin/maxwell --user='XXXXX' --password='XXXXX' --host='127.0.0.1' --producer=pubsub --pubsub_project_id='myproject' --pubsub_topic='mytopic' --pubsub_rpc_timeout_multiplier=5 --client_id='computer1' --gtid_mode=true --replication_host='XX.XXX.X.X' --replication_password='XXXXX' --replication_user='XXXX'`

**OUTPUT**
`Using kafka version: 1.0.0
15:50:00,234 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
15:50:00,834 INFO  TaskManager - Stopping 0 tasks
15:50:00,835 ERROR TaskManager - cause: 
com.zendesk.maxwell.MaxwellCompatibilityError: Could not check state for Mysql variable: gtid_mode
        at com.zendesk.maxwell.MaxwellMysqlStatus.getVariableState(MaxwellMysqlStatus.java:29) ~[maxwell-1.23.2.jar:1.23.2]
        at com.zendesk.maxwell.MaxwellMysqlStatus.ensureVariableState(MaxwellMysqlStatus.java:41) ~[maxwell-1.23.2.jar:1.23.2]
        at com.zendesk.maxwell.MaxwellMysqlStatus.ensureGtidMysqlState(MaxwellMysqlStatus.java:83) ~[maxwell-1.23.2.jar:1.23.2]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:176) ~[maxwell-1.23.2.jar:1.23.2]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.23.2.jar:1.23.2]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244) ~[maxwell-1.23.2.jar:1.23.2]
15:50:00,840 INFO  TaskManager - Stopped all tasks
com.zendesk.maxwell.MaxwellCompatibilityError: Could not check state for Mysql variable: gtid_mode
        at com.zendesk.maxwell.MaxwellMysqlStatus.getVariableState(MaxwellMysqlStatus.java:29)
        at com.zendesk.maxwell.MaxwellMysqlStatus.ensureVariableState(MaxwellMysqlStatus.java:41)
        at com.zendesk.maxwell.MaxwellMysqlStatus.ensureGtidMysqlState(MaxwellMysqlStatus.java:83)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:176)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)`

Can anyone point me in the right direction? I have verified that I am not receiving messages from the slave. Is there a parameter that I am missing or messed up?

`Master DB = MariaDB Version 10.1
Slave DB = MariaDB Version 10.1`

**Comment by osheroff** [comment]
1.  mariadb is not all-the-way-officially supported due to differences like this.
2. you probably need to turn on the `log_slave_updates` parameter (in mysqld.conf)

**Comment by GhostDZ9** [comment]
@osheroff Could you provide more information on `log_slave_updates`?

**Comment by GhostDZ9** [comment]
I got it to work thanks to @osheroff. 

I updated the my.cnf for mariadb to `log_slave_updates=1`

Then I ran the following command:
`bin/maxwell --user='XXXXXX' --password='XXXXX' --host='127.0.0.1' --producer=pubsub --pubsub_project_id='myproject' --pubsub_topic='mytopic' --pubsub_rpc_timeout_multiplier=5 --client_id='computer1' `

I am now seeing messages come into pubsub.
