### ISSUE TITLE
java.io.IOException: Unexpected packed number byte 255

### ISSUE THREAD

**Issue by DPGrev** [zendesk/maxwell#1374]
Our maxwell instance was running fine, however, after the instance got restarted we got the following error. We have tried the remove the maxwell database as well as every version from `maxwell-1.22.2` upwards. Every version is producing the same error:

```
java.io.IOException: Unexpected packed number byte 255
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readPackedNumber(ByteArrayInputStream.java:162) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readPackedInteger(ByteArrayInputStream.java:131) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readLengthEncodedString(ByteArrayInputStream.java:73) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.network.protocol.ResultSetRowPacket.<init>(ResultSetRowPacket.java:35) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.readResultSet(BinaryLogClient.java:1083) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.fetchBinlogChecksum(BinaryLogClient.java:916) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:533) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
```

The error is produced by the following lines of code: https://github.com/shyiko/mysql-binlog-connector-java/blob/d466f72f083cf6e1c17d2d481131fa2d68f8b26f/src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java#L149-L163

We are however unsure what causes it.

**Comment by ndeslandes** [comment]
we got the same exception this morning....

**Comment by DPGrev** [comment]
So after doing some research, it turn out that `mysql-binlog-connector-java` library does not handle errors properly. The piece of code actually tries to read a `Length-Encoded Integer Type` field within the bytestream. 

When byte 255 is encountered (`0xff`) it actually means the current packet is an ERR_Packet. As is described at the bottom of the following page: https://dev.mysql.com/doc/internals/en/integer.html
Meaning that it is an error packet which the `mysql-binlog-connector-java` library does not decode but simply fails upon.

In order to get the error code out, one could modify the code from the  `mysql-binlog-connector-java` library to actually decode the `ERR_Packet` for which the code already partly exists: https://github.com/shyiko/mysql-binlog-connector-java/blob/f698427b151aadacba8e6ec305dbc6b5c9d61aee/src/main/java/com/github/shyiko/mysql/binlog/network/protocol/ErrorPacket.java

The route that we ended up taking was to test the replication with https://github.com/noplay/python-mysql-replication. This uses pymysql which actually does catch the error code.

In our case we saw the following error code: 
```
Error: 1682 SQLSTATE: HY000 (ER_WRONG_NATIVE_TABLE_STRUCTURE)
```
I think that this is highly specific to our use case and the error was due to a bug within mysql. It turned out that the following stackoverflow answer solved our issue: https://stackoverflow.com/a/20262826

The point is the byte 255 simply links to an error packet, so try to get the error code out and you should be able to find the cause of why the replication fails.

**Comment by osheroff** [comment]
Nice investigation work @DPGrev.  I'm not sure what's up with mysql-binlog-connector these days, no commits for awhile.  i very much agree that this needs to throw a proper error.

**Comment by osheroff** [comment]
forked the library, we now throw a proper error message
