### ISSUE TITLE
Tests unable to start onetimeserver on windows

### ISSUE THREAD

**Issue by davidsheldon** [zendesk/maxwell#139]
If you're on Windows, and do mvn test, even under cygwin, you get the error

<pre>
java.io.IOException: Cannot run program "C:\.....\maxwell/src/test/onetimeserver": CreateProcess error=193, %1 is not a valid Win32 application
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.zendesk.maxwell.MysqlIsolatedServer.boot(MysqlIsolatedServer.java:34)
        at com.zendesk.maxwell.AbstractMaxwellTest.setUpBeforeClass(AbstractMaxwellTest.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
....
</pre>

Not sure what can be done about this.

**Comment by osheroff** [comment]
could maybe call `bash onetimeserver` -- it's a script that downloads a go binary which then downloads enough for a minimal mysql install: see https://github.com/osheroff/onetimeserver if you wanna take a whack at it.
