### ISSUE TITLE
Failed to deserialize data of EventHeaderV4

### ISSUE THREAD

**Issue by ypereirareis** [zendesk/maxwell#1432]
Hello (thanks once more for the tool),

- **Run as a docker container**: yes
- **Maxwell version**: 1.22.6
- **JAVA_OPTS**: -Xmx6g

Since a few days we have a lot of errors like this one in our logs : 
```
14:35:58,089 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1581815443000, eventType=EXT_UPDATE_ROWS, serverId=25, headerLength=19, dataLength=403, nextPosition=101887097, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_222]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeBlob(AbstractRowsEventDataDeserializer.java:383) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:186) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:138) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:71) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:294) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
14:35:58,187 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.082471:101886561 -- restarting
```

**Comment by ypereirareis** [comment]
And those are the binlog referenced in the given error


Log_name | Pos | Event_type | Server_id | End_log_pos | Info |  
-- | -- | -- | -- | -- | -- | --
mysql-bin.082471 | 101886561 | Table_map | 25 | 101886675 | table_id: 256222794 (dbname.my_super_long_table_name_here)
mysql-bin.082471 | 101886675 | Update_rows | 25 | 101887097 | table_id: 256222794 flags: STMT_END_F
mysql-bin.082471 | 101887097 | Xid | 25 | 101887128 | COMMIT /* xid=2049588606 */

Thanks in advance for your help.

**Comment by osheroff** [comment]
good bug report.

what version of mysql?  and can you dump the schema of the table referenced in the update row event plz?  

thanks!
-ben
