### ISSUE TITLE
SchemaChange Parse error:MaxwellSQLSyntaxError

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1438]
Maxwell version: v1.24.1
MySQL version: 8.0.15

I created a table with following query:
```
create table testPrimaryKeys2(lastname varchar(20), json_column json DEFAULT ('{"Name":"stdout"}'), derived_key VARCHAR(20) GENERATED ALWAYS AS(CONCAT("Name",`json_column` ->> '$.Name')),PRIMARY KEY(lastname))
```
This works and the binlog entry is correctly created. However, maxwell fails to parse this query, the json DEFAULT part of this.

```
ERROR MysqlParserListener - (default_value DEFAULT ( '{"Name":"stdout"}')
11:45:44,728 ERROR SchemaChange - Error parsing SQL: 'create table testPrimaryKeys2(lastname varchar(20), json_column json DEFAULT ('{"Name":"stdout"}'), derived_key VARCHAR(20) GENERATED ALWAYS AS(CONCAT("Name",`json_column` ->> '$.Name')),PRIMARY KEY(lastname))'
11:45:44,728 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[binlog.000004:9167], lastHeartbeat=1581334624893]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: (
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:106)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:316)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:338)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:610)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:223)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)
```

Based on some other queries for create table, I think that maxwell parser does not support DEFAULT values other than NULL in general, as it failed for following query also
```
CREATE TABLE `TableInfoTest` (
  `table_name` varchar(100) NOT NULL,
  `ttl` bigint(20) DEFAULT NULL,
  `namespace` varchar(100) NOT NULL,
  `environment` varchar(100) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  `primary_key` varchar(255) DEFAULT ('environment,namespace,table_name'),
  `table_schema` json DEFAULT NULL,
  `partition_key` varchar(100) DEFAULT NULL,
  `partition_strategy` enum('HASH_BASED','RANGE_BASED') DEFAULT NULL,
  `updated_time` bigint(20) DEFAULT NULL,
  `created_time` bigint(20) DEFAULT NULL,
  PRIMARY KEY (environment,namespace,table_name)
)
```

**Comment by osheroff** [comment]
i think it just hates the parenthesis.  might be a quick fix.  looking.

**Comment by osheroff** [comment]
fixed in the latest release
