### ISSUE TITLE
Bootstrap issue, exception java.sql.SQLException: YEAR

### ISSUE THREAD

**Issue by anasjaghoubbq** [zendesk/maxwell#1474]
When trying to bootstrap it fails and keeps restarting from the same offset every time. 

I've tried version 25.1 and version 24 both give same exception. 

java.sql.SQLException: YEAR
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:903)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1243)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:210)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.performBootstrap(SynchronousBootstrapper.java:69)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:39)
        at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:65)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.MaxwellContext.lambda$getBootstrapController$0(MaxwellContext.java:395)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.WrongArgumentException: YEAR
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:112)
        at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:50)
        at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromTimestamp(AbstractDateTimeValueFactory.java:87)
        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeTimestamp(MysqlTextValueDecoder.java:79)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:87)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
        at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: YEAR
        at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2648)
        at java.util.Calendar.updateTime(Calendar.java:3393)
        at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
        at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:108)
        ... 15 more

Help is required please.

**Comment by anasjaghoubbq** [comment]
@osheroff please have a look into this issue.

**Comment by osheroff** [comment]
can you give `show create table` info?  Also can you do like:

`select distinct(year_column) from table` and look for any non-normal looking values?

**Comment by anasjaghoubbq** [comment]
It's a magento EE sales_order table with ~200 columns inside. it'll be very hard to tell which date column has non-normal looking values. 

is it possible to output which column / data has corrupted data format?

**Comment by osheroff** [comment]
yeah I'll look into putting a patch into the next release.

**Comment by osheroff** [comment]
oops I missed that release.  damn.

**Comment by dcopl** [comment]
I'm also experiencing this issue. The error message would be really useful to pinpoint the exact values causing the problem.

**Comment by lucastex** [comment]
@osheroff this is probably related when reading non parseable dates. I got this problem in the past (non-maxwell issue).

Check this link: 
https://bugs.mysql.com/bug.php?id=94872

**Comment by lucastex** [comment]
@dcopl @anasjaghoubbq can you guys check if there are some date with this case (with year 0000) in the data being streamed to maxwell?

**Comment by anasjaghoubbq** [comment]
Thanks @lucastex for your help, actually as I mentioned earlier the table structure is very big and contains 200+ columns. very hard to tell which column exactly has invalid dates. 

One more thing since that date had been already stored in MySQL with no issues, I believe Maxwell should be able to stream it as is, at least as an Object type because at the consumer side it can be handled differently.

**Comment by osheroff** [comment]
@lucastex that was my thought too but if you read the bug report this is actually a `TIME` column (no date involved).  we try to parse it as a timestamp because it was the only way I could get the milliseconds out of them, but something is going wrong there.  

I've added some logging code to the 1.26.2 release.

**Comment by dcopl** [comment]
@osheroff Noted that this column type is `TIME` in this case. In my scenario, the offending column is of type `DATE`. Having checked the content of the column, there is dates in there outside the range of `1000-01-01` to `9999-12-31`. Would be great to have a way to handle this situation for a `DATE` column also. Would you like me to raise a new issue regarding this also affecting the `DATE` column type or keep discussion in here?

**Comment by osheroff** [comment]
@dcopi you must be getting a different stack trace?

**Comment by dcopl** [comment]
@osheroff Very similar but different, yes:

```
11:51:20,462 INFO  SynchronousBootstrapper - bootstrapping started for mollie.m_api_orders
java.sql.SQLException: YEAR
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getDate(ResultSetImpl.java:740)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1236)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:208)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.performBootstrap(SynchronousBootstrapper.java:69)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:39)
        at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:65)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.MaxwellContext.lambda$getBootstrapController$0(MaxwellContext.java:395)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.WrongArgumentException: YEAR
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDate(SqlDateValueFactory.java:85)
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDate(SqlDateValueFactory.java:50)
        at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromDate(AbstractDateTimeValueFactory.java:67)
        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDate(MysqlTextValueDecoder.java:71)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:90)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
        at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: YEAR
        at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2648)
        at java.util.Calendar.updateTime(Calendar.java:3393)
        at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDate(SqlDateValueFactory.java:82)
        ... 15 more
11:54:42,298 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1581594554000, eventType=EXT_UPDATE_ROWS, serverId=50, headerLength=19, dataLength=663, nextPosition=56250634, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_222]
        at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_222]
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
        ... 5 more
```

**Comment by osheroff** [comment]
@dcopi, I can't reproduce it with the dates that you gave me, but I think I can given the date '0000-01-01'.  does a date with the year zero appear in your dataset?

**Comment by osheroff** [comment]
fixes for the `DATE` issue went out in 1.26.3.  @anasjaghoubbq you get any logging back on the other one?

**Comment by anasjaghoubbq** [comment]
Thanks @osheroff for the update, I'll try it out. 

Actually the problem in our case was done by the QA team, they run a load test on DB without any kind of validation, and caused a lot of crashes on different corners. 

We reverted the DB to the previous version and everything works fine as before. 

Thanks a lot for your prompt response and for fixing it. We use this great tool at 2-major modules in our projects and works perfectly with Kafka.

**Comment by dcopl** [comment]
@osheroff I did check again and did indeed find 2 entries with 0000-01-01 as a date. As such, I tested the new release out and was able to successfully bootstrap the full table. Thanks very much for that!
