### ISSUE TITLE
Getting MySQLSyntaxError for DEFAULT keyword

### ISSUE THREAD

**Issue by VineetKillerX** [zendesk/maxwell#1483]
I am trying to Produce MySQL Changes to Kafka, using maxwell-docker. But sometimes it crashes while reading bin log files with the below stack trace:

06:54:19,504 ERROR SchemaChange - Error parsing SQL: 'CREATE DATABASE /*!32312 IF NOT EXISTS*/ `xyz` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */'
06:54:19,504 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.000051:16446422], lastHeartbeat=1589011084541]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: DEFAULT
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:92)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:104)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:316)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:338)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:610)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:223)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)
06:54:19,538 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
06:54:19,540 INFO  TaskManager - Stopping 5 tasks

**Comment by osheroff** [comment]
fixed in 1.26.2

**Comment by VineetKillerX** [comment]
Thanks a lot, will check with the official docker image.
Any plans to push avro or protobuff messages to kafka instead of plain json objects?

**Comment by osheroff** [comment]
no plans.  avro in particular has been discussed extensively in issues here.  I'm not sure how extensible protobuf is but my understand has been that it, like avro, is designed around parsing a fairly fixed schema, which is not easy to match up with a ever-changing schema.
