### ISSUE TITLE
ClassCastException: class java.lang.Integer cannot be cast to class [B

### ISSUE THREAD

**Issue by Sujay39** [zendesk/maxwell#1505]
Tried to read binlog from MySQL (version MySQL 8.0.17) from maxwell docker image (version maxwell-1.26.2)

Connection to binlog is successful, after which the following errors are thrown. 

`INFO BinaryLogClient - Connected to mysql-slave:3306 at mysql-bin.000596/77886832 (sid:4, cid:745724)
INFO BinlogConnectorLifecycleListener - Binlog connected.
INFO  BinlogConnectorLifecycleListener - Binlog disconnected. 
INFO  TaskManager - Stopping 5 tasks 
ERROR TaskManager - cause: 
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class [B (java.lang.Integer and [B are in module java.base of loader 'bootstrap') at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:72) at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:111) at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:161) at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:190) at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:483) at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:598) at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) at com.zendesk.maxwell.Maxwell.start(Maxwell.java:157) at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)`

**Comment by djetelina** [comment]
Hey, we just encountered the same issue, we suspect the following query (ip range censored) caused it:

```sql
UPDATE mysql.user SET Host="192.168.0.0/255.255.255.128" WHERE user='oa_user_entity_cz';
```

We had to change the gtid set to skip this query (and some extra, 'cause this is hard out of nowhere).

I can't seem to figure out why such query would produce something into the binlog that would be non-standard. I'd appreaciate any hints.
