### ISSUE TITLE
Bootstrap utility desn't work when replication_host is used

### ISSUE THREAD

**Issue by Stormhand** [zendesk/maxwell#1506]
Hello, 
Im trying to use the utility with different hosts for meta data and replication. The command line parameters include only **--host** (at least in the docs). When i give a --config to maxwell-bootstrap it actually tries to connect to the right host but fails:

> 08:04:19,934 INFO  MaxwellBootstrapUtility - counting rows
08:04:19,965 ERROR MaxwellBootstrapUtility - failed to connect to mysql server @ jdbc:mysql://REPLICATION-HOST:3306/maxwell
08:04:19,965 ERROR MaxwellBootstrapUtility - Table 'test.test' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'test.test' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility.calculateRowCount(MaxwellBootstrapUtility.java:156)
	at com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility.run(MaxwellBootstrapUtility.java:50)
	at com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility.main(MaxwellBootstrapUtility.java:244)

**Comment by osheroff** [comment]
fixed in v1.27.0
