### ISSUE TITLE
RROR BootstrapController - got SQLException trying to bootstrap com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

### ISSUE THREAD

**Issue by boy-xiaozhang** [zendesk/maxwell#1508]
```
ERROR BootstrapController - got SQLException trying to bootstrap
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 13 milliseconds ago.  The last packet sent successfully to the server was 13 mill
seconds ago.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.17
jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.
7]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.bootstrap.BootstrapController.getIncompleteTasks(BootstrapController.java:100) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.doWork(BootstrapController.java:66) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:58) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.MaxwellContext.lambda$getBootstrapController$0(MaxwellContext.java:400) ~[maxwell-1.26.1.jar:1.26.1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 13 milliseconds ago.  The last packet sent successfully to the server was 13 mill
seconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.17.
ar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:541) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:949) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1113) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        ... 8 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpected
y lost.
        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-java-8.0.17.jar:
.0.17]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-java-8.0.17.jar:
.0.17]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:535) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:949) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1113) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        ... 8 more
17:38:16,146 ERROR BootstrapController - got SQLException trying to bootstrap
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 0 millis
conds ago.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.17
jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.
7]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.bootstrap.BootstrapController.getIncompleteTasks(BootstrapController.java:100) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.doWork(BootstrapController.java:66) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:58) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.MaxwellContext.lambda$getBootstrapController$0(MaxwellContext.java:400) ~[maxwell-1.26.1.jar:1.26.1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 0 millis
conds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.17.
ar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:541) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:949) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1113) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        ... 8 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpected
y lost.
        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-java-8.0.17.jar:
.0.17]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-java-8.0.17.jar:
.0.17]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:535) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:949) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1113) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        ... 8 more
17:38:16,148 ERROR BootstrapController - got SQLException trying to bootstrap
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 0 millis
conds ago.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.17
jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.
7]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.bootstrap.BootstrapController.getIncompleteTasks(BootstrapController.java:100) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.doWork(BootstrapController.java:66) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:58) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.26.1.jar:1.26.1]
        at com.zendesk.maxwell.MaxwellContext.lambda$getBootstrapController$0(MaxwellContext.java:400) ~[maxwell-1.26.1.jar:1.26.1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 0 millis
conds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.17.
ar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:541) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:949) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1113) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        ... 8 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpected
y lost.
        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-java-8.0.17.jar:
.0.17]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-java-8.0.17.jar:
.0.17]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:535) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:650) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:949) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1113) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.17.jar:8.
.17]
        ... 8 more
```

**Comment by osheroff** [comment]
looks like your server keeps closing the connection.  I'm not sure why.  since this is happening at the JDBC level, it's very unlikely to be a maxwell bug.  I'd check the server for error messages.  let me know if you find anything more.  

Otherwise, I'd test the query against the server; it's like `select * from maxwell.bootstraps` (ish)

**Comment by boy-xiaozhang** [comment]
> 看起来您的服务器一直在关闭连接。我不知道为什么。由于这是在JDBC级别发生的，因此极不可能是maxwell错误。我会检查服务器上的错误消息。让我知道您是否还有发现。
> 
> 否则，我将针对服务器测试查询。就像`select * from maxwell.bootstraps`（ish）

Is there any way to prevent MaxWell's data loss

**Comment by boy-xiaozhang** [comment]
Is there any way to prevent MaxWell's data loss

> 看起来您的服务器一直在关闭连接。我不知道为什么。由于这是在JDBC级别发生的，因此极不可能是maxwell错误。我会检查服务器上的错误消息。让我知道您是否还有发现。
> 
> 否则，我将针对服务器测试查询。就像`select * from maxwell.bootstraps`（ish）

Is there any way to prevent MaxWell's data loss

**Comment by osheroff** [comment]
sorry, I'm closing this issue due to lack of new information.  please re-open if you have more info.
