### ISSUE TITLE
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by ByteDanceWYQ** [zendesk/maxwell#1520]
this error always  happens 

2:39:04,572 INFO  BinlogConnectorLifecycleListener - Binlog connected.
22:39:04,653 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
22:39:04,654 INFO  TaskManager - Stopping 4 tasks
22:39:04,654 ERROR TaskManager - cause: 
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:34) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:50) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:111) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:161) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:175) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:484) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:599) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:223) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.24.0.jar:1.24.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244) ~[maxwell-1.24.0.jar:1.24.0]
22:39:04,659 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@3b61fbe7
22:39:04,659 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
22:39:04,659 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@57161e22
22:39:04,659 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
22:39:04,662 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
22:39:04,666 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@4ed665a5
22:39:04,666 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNNING)
22:39:04,666 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@b25577e
22:39:04,666 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:34)
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:50)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:111)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:161)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:175)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:484)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:599)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:223)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)
22:39:06,089 INFO  TaskManager - Stopped all tasks
Using kafka version: 1.0.0

**Comment by osheroff** [comment]
I pushed some additional logging for this issue in the last release of maxwell.  update and let me know what it says?

**Comment by osheroff** [comment]
one of these days I'm gonna figure out why people's schemas can sometimes fall out of sync.  not today.
