### ISSUE TITLE
unhandled character set 'utf16le'

### ISSUE THREAD

**Issue by JerryCoders** [zendesk/maxwell#1537]
java.lang.RuntimeException: error: unhandled character set 'utf16le'
	at com.zendesk.maxwell.schema.columndef.StringColumnDef.charsetForCharset(StringColumnDef.java:61) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:75) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:112) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:162) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:191) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:477) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:617) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:176) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:245) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:175) ~[maxwell-1.27.0.jar:1.27.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:269) ~[maxwell-1.27.0.jar:1.27.0]

**Comment by JerryCoders** [comment]
Sorry, I found the utf16le settings in the column。Pit teammates！
