### ISSUE TITLE
The data of a field is too large and exceeds the maximum limit of Kafka [max.request.size]

### ISSUE THREAD

**Issue by liunancun** [zendesk/maxwell#1538]
Oversized error message
The message is 3264005 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.

Try to modify the startup parameters
docker run -it --rm zendesk/maxwell bin/maxwell --user=xxx --password=xxx --host=192.168.99.xxx --replication_host=192.168.99.xxx --replication_user=xxx --replication_password=xxx --filter='exclude: *.*, include: bessky_pss.t_product' --producer=kafka --kafka.bootstrap.servers=192.168.99.xxx:9092 --kafka.max.request.size=10485760 --kafka_topic=maxwell_%{database}_%{table}

Error message
joptsimple.UnrecognizedOptionException: kafka.max.request.size is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:374)
	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:169)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:254)

Modify the startup parameters again
docker run -it --rm zendesk/maxwell bin/maxwell --user=xxx --password=xxx --host=192.168.99.xxx --replication_host=192.168.99.xxx --replication_user=xxx --replication_password=xxx --filter='exclude: *.*, include: bessky_pss.t_product' --producer=kafka --kafka.bootstrap.servers=192.168.99.xxx:9092 --kafka.batch.size=10485760 --kafka_topic=maxwell_%{database}_%{table}

Error message
joptsimple.UnrecognizedOptionException: kafka.batch.size is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:374)
	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:169)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:254)

**Comment by osheroff** [comment]
kafka parameters need to be specified via `config.properties`
