### ISSUE TITLE
java.lang.IllegalStateException: BinaryLogClient is already connected

### ISSUE THREAD

**Issue by crispmark** [zendesk/maxwell#1543]
**Maxwell version**: v1.27.0
Running as a java dependency in a kubernetes deployment

This seems to be related to issue #1491 where maxwell stopped processing after encountering this error. The connection was flaky at the time (we had just experienced successive failovers of our mysql database on AWS).

It recovered a few times with
```
replicator stopped at position: mysql-bin-changelog.013673:4282788 -- restarting
```

before finally failing with:
```
Exception in thread "blc-mysql:3306" java.lang.IllegalStateException: BinaryLogClient is already connected
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:501)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:838)
	at java.lang.Thread.run(Thread.java:748)
```

The problem is that the container still appears as healthy even though no new messages are being processed.
Since this already has a best effort fix, would it be possible to either start failing the health check, or exit the process entirely when this exception occurs?

**Comment by crispmark** [comment]
I tried replicating this locally, and connect() will cause termination, however connect(5000) will absorb the error.
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L835-L843

**Comment by crispmark** [comment]
I have left a PR osheroff/mysql-binlog-connector-java#9 that may address this issue.

**Comment by osheroff** [comment]
so your binlog-connector PR would seem to address that we end up swallowing the binlog-already-connected error.  This feels like an improvement but not the whole story to me; this may have been what caused Maxwell to go zombied but not what triggered the race condition (binlog-already-connected) in the first place.  

Do you have more of the logs from the incident?  They may or may not help, but I had thought that I thunk that I thank through the edge cases of `connect()` re-entry the last time.

Anyway, thanks for your investigative work, I'll go merge your open-replicator pr.

**Comment by crispmark** [comment]
it looks like I broke one of the integration tests, I will have a PR out for that shortly. In the meantime here are the logs from the latest crash. AWS errors could be from kinesis client.

```
  | July 25th 2020, 04:47:22.302 | - | Exception in thread "blc-mysql:3306" java.lang.IllegalStateException: BinaryLogClient is already connected

  | July 25th 2020, 04:47:22.302 | - | at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:501)

  | July 25th 2020, 04:47:22.302 | - | at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:838)

  | July 25th 2020, 04:47:22.302 | - | at java.lang.Thread.run(Thread.java:748)

  | July 25th 2020, 04:47:22.302 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013843:2028], throwable=null]

  | July 25th 2020, 04:26:52.710 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013840:4305765], throwable=null]

  | July 25th 2020, 04:19:48.551 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013837:1887224], throwable=null]

  | July 25th 2020, 04:18:10.476 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013834:2580841], throwable=null]

  | July 25th 2020, 04:16:42.710 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013831:1798921], throwable=null]

  | July 25th 2020, 04:15:31.572 | warn | [2020-07-25 08:15:31.076176] [0x00000058][0x00007fa93ffff700] [warning] [AWS Log: WARN](AWSClient)If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
  | July 25th 2020, 04:15:31.423 | error | [2020-07-25 08:15:31.076163] [0x00000058][0x00007fa93ffff700] [error] [AWS Log: ERROR](AWSClient)HTTP response code: -1 Exception name:  Error message: Unable to connect to endpoint 0 response headers:

  | July 25th 2020, 04:15:31.248 | error | [2020-07-25 08:15:31.076101] [0x00000058][0x00007fa93ffff700] [error] [AWS Log: ERROR](CurlHttpClient)Curl returned error code 28 - Timeout was reached

  | July 25th 2020, 04:15:11.080 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013828:1868306], throwable=null]

  | July 25th 2020, 04:13:33.673 | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013825:4460197], throwable=null]
```

**Comment by crispmark** [comment]
got some additional logs
```
  | July 26th 2020, 16:20:19.200 | ohcm-kinesis-maxwell | info | [2020-07-26 20:20:19.094482] [0x00000096][0x00007ffa759e4700] [info] [processing_statistics_logger.cc:111] Stage 1 Triggers: { stream: '*****', manual: 0, count: 0, size: 0, matches: 0, timed: 0, UserRecords: 0, KinesisRecords: 0 }

  | July 26th 2020, 16:20:15.916 | ohcm-kinesis-maxwell | info | Binlog connected.

  | July 26th 2020, 16:20:15.861 | ohcm-kinesis-maxwell | - | at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:501)

  | July 26th 2020, 16:20:15.861 | ohcm-kinesis-maxwell | - | at java.lang.Thread.run(Thread.java:748)

  | July 26th 2020, 16:20:15.861 | ohcm-kinesis-maxwell | - | at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:838)

  | July 26th 2020, 16:20:15.861 | ohcm-kinesis-maxwell | - | Exception in thread "blc-mysql:3306" java.lang.IllegalStateException: BinaryLogClient is already connected

  | July 26th 2020, 16:20:15.860 | ohcm-kinesis-maxwell | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013894:2129], throwable=null]

  | July 26th 2020, 16:20:15.697 | ohcm-kinesis-maxwell | info | Connected to mysql:3306 at mysql-bin-changelog.013894/2129 (sid:1111, cid:182380)

  | July 26th 2020, 16:20:15.644 | ohcm-kinesis-maxwell | info | Binlog disconnected.

  | July 26th 2020, 16:20:14.770 | ohcm-kinesis-maxwell | info | Trying to restore lost connection to mysql:3306

  | July 26th 2020, 16:20:04.443 | ohcm-kinesis-maxwell | info | [2020-07-26 20:20:04.094317] [0x00000096][0x00007ffa759e4700] [info] [processing_statistics_logger.cc:129] (*****) Average Processing Time: 67.146742 ms
```

as well as what a successful reconnection looks like

```

  | July 26th 2020, 16:18:35.664 | ohcm-kinesis-maxwell | info | Binlog connected.

  | July 26th 2020, 16:18:35.556 | ohcm-kinesis-maxwell | info | Connected to mysql:3306 at mysql-bin-changelog.013891/4346176 (sid:1111, cid:182262)

  | July 26th 2020, 16:18:35.434 | ohcm-kinesis-maxwell | warn | ParameterizedMessage[messagePattern=replicator stopped at position: {} -- restarting, stringArgs=[mysql-bin-changelog.013891:4346176], throwable=null]

  | July 26th 2020, 16:18:35.184 | ohcm-kinesis-maxwell | info | Binlog disconnected.

  | July 26th 2020, 16:18:34.444 | ohcm-kinesis-maxwell | info | [2020-07-26 20:18:34.093043] [0x00000096][0x00007ffa759e4700] [info] [processing_statistics_logger.cc:129] (core--maxwell--prod) Average Processing Time: 71.78922 ms
```

**Comment by crispmark** [comment]
it looks in the instance where an error occurred, both zendesk/maxwell and binarylogclient were attempting to reconnect.

**Comment by crispmark** [comment]
There is a keep alive thread which will automatically reconnect by calling
```
terminateConnect();
connect(connectTimeout);
```
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L777-L790

this competes with maxwell's keep alive, and it defaults to true.
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L159

We can rely purely on maxwell for keepalive by setting this to false
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L378-L380

**Comment by crispmark** [comment]
Closing this issue as it will be fixed with next release.
