### ISSUE TITLE
Geoindex SRID type support

### ISSUE THREAD

**Issue by FanAs** [zendesk/maxwell#1567]
Hello guys,
Is it possible to make a quick fix for this behaviour?
Broked our production after creating a table with SRID type:

```
SchemaChange - Error parsing SQL: 'CREATE TABLE `locations` (
`id` int NOT NULL AUTO_INCREMENT,
`location` point NOT NULL SRID 4326,
...
```

We changed type to VARCHAR, but position in binlog was still the same, so error stayed.

```
AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.020128:19468174], lastHeartbeat=0]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: SRID
at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:92)
at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:104)
at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:316)
at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:338)
at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:637)
at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:178)
at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:245)
at com.zendesk.maxwell.Maxwell.start(Maxwell.java:175)
at com.zendesk.maxwell.Maxwell.main(Maxwell.java:269)
```
I tried to find how can it be done, but didn't find anything that could help us.

**Comment by FanAs** [comment]
Is it enough or should I do something else too? https://github.com/zendesk/maxwell/pull/1568

**Comment by osheroff** [comment]
fix merged
