### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned when mvn clean

### ISSUE THREAD

**Issue by bjo2008cnx** [zendesk/maxwell#1605]
"Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned" is reported  when run: mvn clean.
Could any one give some help? Thanks very much

**Comment by bjo2008cnx** [comment]
stack: 
constituent[45]: file:/Users/michael/softwares/software-green/maven/apache-maven-3.6.0/lib/jsr250-api-1.0.jar
constituent[46]: file:/Users/michael/softwares/software-green/maven/apache-maven-3.6.0/lib/wagon-file-3.2.0.jar
constituent[47]: file:/Users/michael/softwares/software-green/maven/apache-maven-3.6.0/lib/maven-core-3.6.0.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at com.google.inject.internal.MoreTypes.getGenericSupertype(MoreTypes.java:292)
	at com.google.inject.TypeLiteral.getSupertype(TypeLiteral.java:240)
	at org.eclipse.sisu.space.QualifiedTypeBinder.resolveTypeArguments(QualifiedTypeBinder.java:329)
	at org.eclipse.sisu.space.QualifiedTypeBinder.bindProviderType(QualifiedTypeBinder.java:219)
	at org.eclipse.sisu.space.QualifiedTypeBinder.hear(QualifiedTypeBinder.java:129)
	at org.eclipse.sisu.plexus.PlexusTypeBinder.hear(PlexusTypeBinder.java:55)
	at org.eclipse.sisu.space.QualifiedTypeVisitor.leaveClass(QualifiedTypeVisitor.java:128)
	at org.eclipse.sisu.plexus.PlexusTypeVisitor.leaveClass(PlexusTypeVisitor.java:117)
	at org.eclipse.sisu.space.SpaceScanner$1.visitEnd(SpaceScanner.java:180)
	at org.eclipse.sisu.space.asm.ClassReader.accept(ClassReader.java:697)
	at org.eclipse.sisu.space.asm.ClassReader.accept(ClassReader.java:506)
	at org.eclipse.sisu.space.SpaceScanner.accept(SpaceScanner.java:102)
	at org.eclipse.sisu.space.SpaceScanner.accept(SpaceScanner.java:78)
	at org.eclipse.sisu.space.SpaceModule.scanForElements(SpaceModule.java:168)
	at org.eclipse.sisu.space.SpaceModule.configure(SpaceModule.java:129)
	at org.eclipse.sisu.plexus.PlexusAnnotatedBeanModule.configure(PlexusAnnotatedBeanModule.java:102)
	at org.eclipse.sisu.plexus.PlexusBindingModule.configure(PlexusBindingModule.java:63)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.spi.Elements.getElements(Elements.java:96)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.discoverComponents(DefaultPlexusContainer.java:460)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.discoverPluginComponents(DefaultMavenPluginManager.java:436)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:879)
	at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:196)
	at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:100)
	at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
	at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1359)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:452)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:432)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:583)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:372)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:507)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 83 more

**Comment by bjo2008cnx** [comment]
version: 1.28.1

**Comment by osheroff** [comment]
does `mvn install` clean it up?

**Comment by bjo2008cnx** [comment]
no.

**Comment by bjo2008cnx** [comment]
maven version: 3.6.0

**Comment by bjo2008cnx** [comment]
Problem is found: nexus-staging-maven-plugin causes the problem. 
After nexus-staging-maven-plugin is commented, it works.

**Comment by osheroff** [comment]
ok... I *guess* I'll close this. i believe it's a real and weird problem, but I have no idea how to solve it.  If it comes up again I'll look.
