### ISSUE TITLE
Terminates after MaxwelSQLSyntaxError

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#161]
Running on maxwell-0.14.4
```
08:28:30,736 DEBUG SchemaChange - SQL_PARSE <- "CREATE TABLE 
					 `mvlogs` (table_schema varchar(50), 
                             table_name varchar(50), 
                             mvlog_name varchar(50),
                             active_flag boolean default true,
                             primary key(table_schema,table_name),
                             unique key(mvlog_name)
                     	) ENGINE=INNODB DEFAULT CHARSET=utf8"
line 5:57 no viable alternative at input 'true'
08:28:30,743 ERROR MysqlParserListener - (default_value default true)
08:28:30,743 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE 
					 `mvlogs` (table_schema varchar(50), 
                             table_name varchar(50), 
                             mvlog_name varchar(50),
                             active_flag boolean default true,
                             primary key(table_schema,table_name),
                             unique key(mvlog_name)
                     	) ENGINE=INNODB DEFAULT CHARSET=utf8'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: true
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:85)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:67)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:273)
	at com.zendesk.maxwell.MaxwellReplicator.getEvent(MaxwellReplicator.java:253)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
08:28:30,744 INFO  SchemaPosition - Storing final position: BinlogPosition[awmsphx90022-bin.000003:237982669]
08:28:30,745 DEBUG SchemaPosition - Writing binlog position to maxwell.positions: BinlogPosition[awmsphx90022-bin.000003:237982669]
```

**Comment by osheroff** [comment]
durn.  k.

**Comment by osheroff** [comment]
https://github.com/zendesk/maxwell/releases/tag/v0.14.5 fixes
