### ISSUE TITLE
JS filter: whether row.old_data.keySet() contain certain columns 

### ISSUE THREAD

**Issue by NiDHanWang** [zendesk/maxwell#1619]
Hi team Maxwell:
I tried JS filter to exclude the rows whose row.old_data.keySet() contain certain columns(This is part of a complicated filtering,so I didn't use 'exclude:...' command)
Here's the code:
```
function process_row(row) {
	if ( row.table == "yu_shops" && row.type == "update" ) {
		var arr=Object.keys(row.table.old_data.keySet());
		var len=arr.length;

                // Object.keys() would return array,so I used arr.includes()

		if (  arr.includes("modify_time")  && len==1) {
			row.suppress();
		} 
	}
};
```
I‘d like to exclude the row when the **'modify_time'** is the only updated column and keep it when other else columns are updated.

But I got the error:

```
16:11:21,990 INFO  TaskManager - Stopping 3 tasks
16:11:21,990 ERROR TaskManager - cause: 
jdk.nashorn.internal.runtime.ECMAException: TypeError: [modify_time] is not an Object
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:?]
	at jdk.nashorn.internal.objects.NativeObject.notAnObject(NativeObject.java:136) ~[nashorn.jar:?]
	at jdk.nashorn.internal.objects.NativeObject.keys(NativeObject.java:439) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$26A$\^eval\_.process_row(<eval>:3) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?]
	at com.zendesk.maxwell.scripting.Scripting.invoke(Scripting.java:57) ~[maxwell-1.28.0.jar:1.28.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:189) ~[maxwell-1.28.0.jar:1.28.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.28.0.jar:1.28.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:247) ~[maxwell-1.28.0.jar:1.28.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:175) ~[maxwell-1.28.0.jar:1.28.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:272) ~[maxwell-1.28.0.jar:1.28.0]
16:11:22,000 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@35a4ca94
16:11:22,001 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@362fb6b
16:11:22,001 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@2d332b3
<eval>:3 TypeError: [modify_time] is not an Object
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.objects.NativeObject.notAnObject(NativeObject.java:136)
	at jdk.nashorn.internal.objects.NativeObject.keys(NativeObject.java:439)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$26A$\^eval\_.process_row(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at com.zendesk.maxwell.scripting.Scripting.invoke(Scripting.java:57)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:189)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:247)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:175)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:272)
```
What could be the possible reason for this? @osheroff Thanks in advance!

**Comment by osheroff** [comment]
the javascript -> java bridge is certainly a bit funky and odd.  try this instead:

```
if ( row.old_data.containsKey("modify_time") )  {
```

**Comment by NiDHanWang** [comment]
I tried `row.old_data.containsKey("modify_time")`, but I still got the same error
I tested it on version 1.27.1 and 1.28.0

**Comment by osheroff** [comment]
can you show the whole of your filter.js?  this works for me locally.  Also what JVM are you running on?

**Comment by NiDHanWang** [comment]
This is my filter.js:
```
function process_row(row) {
	if ( row.table == "yu_shops" && row.type == "update" ) {
		var arr=Object.keys(row.old_data.keySet());
		var len=arr.length;
		if (row.old_data.containsKey("modify_time") && len==1) {
            row.suppress();
		} 
	}
    else if(row.table == "yu_member_report" && row.type == "update") {
			row.suppress();
	}
};
```
And my version of jvm is : `Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)`

**Comment by osheroff** [comment]
the problem is with the `Object.keys` call; `keySet` returns an array, not an object, so they're not compatible.  

try 
`var len = row.old_data.keySet().length` 
instead.
