### ISSUE TITLE
Crashed at 4 a.m

### ISSUE THREAD

**Issue by lixiongjie** [zendesk/maxwell#1620]
I use Alibaba Cloud 's MySQL database，Maxwell crashed at 4 a.m. 
Since December 18, the program crashes every night. I can only restart the service the next morning. I don't know what happens at 4:00 a.m ..  

**_maxwell log_**
04:00:11,572 ERROR C3P0ConnectionPool - got SQL Exception: The MySQL server is running with the --read-only option so it cannot execute this statement, retrying...
04:00:11,596 ERROR C3P0ConnectionPool - got SQL Exception: The MySQL server is running with the --read-only option so it cannot execute this statement, retrying...
04:00:11,608 ERROR PositionStoreThread - error storing final position: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
04:00:11,609 ERROR TaskManager - cause: 
java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1340) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:138) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.MysqlPositionStore.lambda$heartbeat$1(MysqlPositionStore.java:85) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.util.C3P0ConnectionPool.withSQLRetry(C3P0ConnectionPool.java:58) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.util.C3P0ConnectionPool.withSQLRetry(C3P0ConnectionPool.java:65) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:84) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:79) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:105) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:41) ~[maxwell-1.27.1.jar:1.27.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
04:00:13,025 ERROR Maxwell - SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
`order_sn` varchar(30) DEFAULT NULL COMMENT '订单号',
   `bank_no` varchar(32) DEFAULT NULL COMMENT '开户行行号',
   `bank_branch_name` varchar(32) DEFAULT NULL COMMENT '支行名称',
   `bank_acct_no` varchar(32) DEFAULT NULL COMMENT '卡号',
   `division_status` char(2) DEFAULT NULL COMMENT '分账状态（10=分账中、20=分账成功、30=分账失败）',
   `real_name` varchar(32) DEFAULT NULL COMMENT '真实姓名',
   `amount` decimal(18,4) DEFAULT NULL COMMENT '分账金额',
   `fee` decimal(18,4) DEFAULT NULL COMMENT '手续费',
   `real_amount` decimal(18,4) DEFAULT NULL COMMENT '实际到账',
   `fail_reason` varchar(255) DEFAULT NULL COMMENT '分账失败原因',
   `remarks` varchar(500) DEFAULT NULL COMMENT '描述说明',
   `del_flag` char(1) DEFAULT '0' COMMENT '删除标志',
   `create_by` varchar(32) NOT NULL COMMENT '创建者',
   `create_date` datetime NOT NULL COMMENT '创建时间',
   `update_by` varchar(32) NOT NULL COMMENT '更新者',
   `update_date` datetime NOT NULL COMMENT '更新时间',
   PRIMARY KEY (`id`),
   UNIQUE KEY `idx_ord_division_record_sn` (`sn`) USING BTREE,
   KEY `idx_ord_division_record_member_id` (`member_id`),
   KEY `idx_ord_division_record_statusud` (`division_status`,`update_date`),
   KEY `idx_ord_division_record_order_sn` (`order_sn`) USING BTREE,
   KEY `idx_ord_division_record_fc_no` (`from_company_no`) USING BTREE
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='分账记录'" to qiaoqing, new schema id is 238
04:00:11,502 INFO  BinlogConnectorReplicator - Binlog disconnected.
04:00:11,527 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000012:42081044 -- restarting
04:00:11,552 INFO  BinaryLogClient - Connected to xxxxxxx.aliyuncs.com:3306 at mysql-bin.000012/42081044 (sid:6379, cid:44281)
04:00:11,552 INFO  BinlogConnectorReplicator - Binlog connected.
04:00:11,553 WARN  BinlogConnectorReplicator - communications failure in binlog:
com.github.shyiko.mysql.binlog.network.ServerException: Client requested master to start replication from position > file size; the first event 'mysql-bin.000012' at 42081044, the last event read from '/home/mysql/data3020/mysql/mysql-bin.000012' at 4, the last byte read from '/home/mysql/data3020/mysql/mysql-bin.000012' at 4.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:926) [mysql-binlog-connector-java-0.23.2.jar:0.23.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) [mysql-binlog-connector-java-0.23.2.jar:0.23.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) [mysql-binlog-connector-java-0.23.2.jar:0.23.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
04:00:11,558 INFO  BinlogConnectorReplicator - Binlog disconnected.
04:00:11,560 ERROR C3P0ConnectionPool - got SQL Exception: The MySQL server is running with the --read-only option so it cannot execute this statement, retrying...
04:00:11,568 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.000012:42074676], lastHeartbeat=1608235210072]
04:00:11,579 ERROR C3P0ConnectionPool - got SQL Exception: The MySQL server is running with the --read-only option so it cannot execute this statement, retrying...
04:00:11,590 ERROR PositionStoreThread - error storing final position: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
04:00:11,591 INFO  TaskManager - Stopping 4 tasks
04:00:11,592 ERROR TaskManager - cause: 
java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1340) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:138) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.MysqlPositionStore.lambda$heartbeat$1(MysqlPositionStore.java:85) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.util.C3P0ConnectionPool.withSQLRetry(C3P0ConnectionPool.java:58) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.util.C3P0ConnectionPool.withSQLRetry(C3P0ConnectionPool.java:65) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:84) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:79) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:105) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:41) ~[maxwell-1.27.1.jar:1.27.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
04:00:11,592 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@c173bef
04:00:11,592 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@2d0c41d
04:00:11,592 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
04:00:11,595 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@6ef509f
04:00:11,595 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@43edce26
04:00:13,002 INFO  TaskManager - Stopped all tasks
04:00:13,003 ERROR Maxwell - SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement

**Comment by osheroff** [comment]
what does your config look like?  are you using a  separate replication_host from host?  

For whatever reason, your server is going read-only for some period of time each 4am.  I don't know if it's changing masters or taking a backup or something else, but maxwell can't continue to function if it can't write to the database.  

Until you figure out what's doing `set READ_ONLY=1`, I could suggest that you run maxwell inside a loop so that when it crashes, it restarts....

**Comment by lixiongjie** [comment]
> what does your config look like? are you using a separate replication_host from host?
> 
> For whatever reason, your server is going read-only for some period of time each 4am. I don't know if it's changing masters or taking a backup or something else, but maxwell can't continue to function if it can't write to the database.
> 
> Until you figure out what's doing `set READ_ONLY=1`, I could suggest that you run maxwell inside a loop so that when it crashes, it restarts....



Thanks Ben, 
I have two nodes, one master and one read-only. I use the master node. This is my config file, but I can't see anything wrong with it. I think it may be that alicloud backup caused the server to be read-only, but this problem did not occur tonight. I checked that the service is running normally today. It seems that this problem occurs randomly. T T



**_My config.properties_**

producer=kafka
kafka.bootstrap.servers=spark2:9092,spark3:9092
kafka_topic=ord_order



host=xxxxxxxxxxxxxxxxxxxxxx.aliyuncs.com
user=xxxxxxxx
password=xxxxxxxxxxxxxxxxxxx


filter= exclude: *.*, include:asm_order.ord_order
client_id=ord_order



kafka_partition_hash=murmur3
producer_partition_by=primary_key
