### ISSUE TITLE
producer=redis时报错

### ISSUE THREAD

**Issue by lizuoqiang** [zendesk/maxwell#1622]
`MaxwellRedisProducer - lost connection to server, will try again with another connection from pool
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:234) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:15) ~[jedis-3.1.0.jar:?]
	at com.zendesk.maxwell.producer.MaxwellRedisProducer.getJedisResource(MaxwellRedisProducer.java:88) ~[maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.producer.MaxwellRedisProducer.sendToRedis(MaxwellRedisProducer.java:96) ~[maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.producer.MaxwellRedisProducer.push(MaxwellRedisProducer.java:163) [maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processRow(BinlogConnectorReplicator.java:280) [maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:191) [maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) [maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) [maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) [maxwell-1.29.0.jar:1.29.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) [maxwell-1.29.0.jar:1.29.0]
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
	at redis.clients.jedis.Protocol.processError(Protocol.java:132) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:166) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:220) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2229) ~[jedis-3.1.0.jar:?]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:119) ~[jedis-3.1.0.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889) ~[commons-pool2-2.6.2.jar:2.6.2]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424) ~[commons-pool2-2.6.2.jar:2.6.2]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.6.2.jar:2.6.2]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50) ~[jedis-3.1.0.jar:?]`

**Comment by lizuoqiang** [comment]
bin/maxwell --user='root' --password='123456' --host='127.0.0.1' --producer=redis --redis_host=127.0.0.1 --redis_type=lpush --redis_database=3

**Comment by osheroff** [comment]
"ERR Client sent AUTH, but no password is set at"

does your redis server require auth?

**Comment by lizuoqiang** [comment]
local redis, no password

**Comment by osheroff** [comment]
can you send your redis server config?

**Comment by lizuoqiang** [comment]
`
version:stable 4.0.14
`

`
cat /usr/local/etc/redis.conf | grep ^[^#]
`
```
bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis_6379.pid
loglevel notice
logfile ""
databases 200
always-show-logo yes
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /usr/local/var/db/redis/
slave-serve-stale-data yes
slave-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
slave-priority 100
maxclients 10000
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
slave-lazy-flush no
appendonly no
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble no
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
aof-rewrite-incremental-fsync yes
```

**Comment by lijiawen** [comment]
@osheroff , can you take a look at this issue: https://github.com/zendesk/maxwell/issues/1627, thanks so much.
