### ISSUE TITLE
java.lang.NullPointerException after few seconds

### ISSUE THREAD

**Issue by broudy3** [zendesk/maxwell#1624]
Hi,
I tried to upgrade Maxwell to newest version 1.29.1 (from version 1.17.1), but I encountered a problem. After few seconds I'm getting a exception and process ends:

```
3478 [INFO] BinlogConnectorReplicator: Binlog disconnected.
3488 [INFO] TaskManager: Stopping 3 tasks
3488 [ERROR] TaskManager: cause:
java.lang.NullPointerException: null
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:320) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:338) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:637) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:178) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.29.1.jar:1.29.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.29.1.jar:1.29.1]
3498 [INFO] TaskManager: Stopping: com.zendesk.maxwell.schema.PositionStoreThread@4f07cf04
3501 [INFO] TaskManager: Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@6ad1b8b3
3517 [INFO] TaskManager: Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@6a73d46c
java.lang.NullPointerException
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:320)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:338)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:637)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:178)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
3836 [INFO] TaskManager: Stopped all tasks
```

I'm using command line option --replay , so maybe it is related to this exception.

I don't know anything about Java, but looking at the source code, couldn't be the problem that the called function setCurrentSchemaID has argument of type "long" instead of "Long"?

**Comment by broudy3** [comment]
Could someone please fix this bug, please.
Stacktrace from version 1.33.0:
```
33631 [INFO] BinlogConnectorReplicator: Binlog disconnected.
33641 [INFO] TaskManager: Stopping 3 tasks
33642 [ERROR] TaskManager: cause:
java.lang.NullPointerException: null
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:334) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.33.0.jar:1.33.0]
33644 [INFO] TaskManager: Stopping: com.zendesk.maxwell.schema.PositionStoreThread@10dcfdd4
33651 [INFO] TaskManager: Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@7b5a81b
33658 [INFO] TaskManager: Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@50bb339
java.lang.NullPointerException
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:334)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
33960 [INFO] TaskManager: Stopped all tasks
```
