### ISSUE TITLE
filtering pattern not work, filter=exclude:*.*,include:gateway.*

### ISSUE THREAD

**Issue by lijiawen** [zendesk/maxwell#1627]
this pattern means only replicate database 'gateway', but it will not work.

only with blacklist config, it will work well, but i have 100+ databases,the config looks so unfriendly

my maxwell version:1.29.1

the error message:
17:15:03,337 DEBUG TaskManager - Awaiting stop of: com.zendesk.maxwell.schema.PositionStoreThread@6de45d9d
java.lang.RuntimeException: Couldn't find database funds
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:26)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:502)

▽

	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:626)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:178)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)

**Comment by lijiawen** [comment]
@takeo , @nickpad  , @baxter , @zdennis , please have a look ,thanks so much.

**Comment by wenyisheng** [comment]
@lijiawen 
I had the same problem, RuntimeException: Couldn't find database, but it has been sloved. 
Please try this: http://maxwells-daemon.io/quickstart/ ->
`mysql> GRANT **SELECT**, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'maxwell'@'%';`
