### ISSUE TITLE
CREATE SCHEMA causes MaxwellSQLSyntaxError

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#164]
Running Maxwell 0.14.5
```
15:19:53,024 DEBUG SchemaChange - SQL_PARSE <- "CREATE SCHEMA product_service_test"
line 1:7 no viable alternative at input 'CREATESCHEMA'
15:19:53,026 ERROR MysqlParserListener - (statement CREATE SCHEMA product_service_test)
15:19:53,026 ERROR SchemaChange - Error parsing SQL: 'CREATE SCHEMA product_service_test'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:85)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:67)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:273)
	at com.zendesk.maxwell.MaxwellReplicator.getEvent(MaxwellReplicator.java:253)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
15:19:53,028 INFO  SchemaPosition - Storing final position: null
```

**Comment by osheroff** [comment]
Fixed in the 0.14.6
