### ISSUE TITLE
Error when running multiple binlog-reader against same maxwell database

### ISSUE THREAD

**Issue by SyedSulaimanM** [zendesk/maxwell#1641]
I am trying to run 2 binlog-readers against a binlog-file, and I am trying to do this with single database for binlog-readers. So I am having a single maxwell database, and 2 binlog-readers both set with 2 unique client_ids, when I start the servers, one server is up and running fine, but getting below error in another server

`com.github.shyiko.mysql.binlog.network.ServerException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin-changelog.103963' at 1038, the last event read from '/rdsdbdata/log/binlog/mysql-bin-changelog.103963' at 1038, the last byte read from '/rdsdbdata/log/binlog/mysql-bin-changelog.103963' at 1038.
                             at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882) [mysql-binlog-connector-java-0.13.0.jar:0.13.0]
                             at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.13.0.jar:0.13.0]
                             at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) [mysql-binlog-connector-java-0.13.0.jar:0.13.0]
                             at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

My sql server version is - 5.6 and 
Binlog reader using the docker image - zendesk/maxwell:v1.13.2

Can you please let me know, whether this kind of scenario is possible or do I need to setup any extra configuration for making this work.

**Comment by osheroff** [comment]
give each instance a unique value for `--replica_server_id`.
