### ISSUE TITLE
Communications failure error since version 1.30.0

### ISSUE THREAD

**Issue by Liban-H** [zendesk/maxwell#1651]
Hi osheroff, you previously helped my colleague by adding amqps support to maxwell #1636 
Many thanks for that however since using v.1.30.0 we've been getting the following error whenever maxwell starts:

```
2021-02-12 13:09:03 WARN  communications failure in binlog:
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1613088300000, eventType=EXT_WRITE_ROWS, serverId=1, headerLength=19, dataLength=8155, nextPosition=36253167, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:209) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at java.io.InputStream.read(InputStream.java:271) ~[?:?]
	at java.io.InputStream.skip(InputStream.java:531) ~[?:?]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:236) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:305) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	... 5 more
2021-02-12 13:09:03 INFO  Binlog disconnected.
2021-02-12 13:09:03 WARN  replicator stopped at position: mysql-bin.004733:36244993 -- restarting
2021-02-12 13:09:03 INFO  Connected to x.x.x.x:3306 at mysql-bin.004733/36244993 (sid:6379, cid:2950017)
2021-02-12 13:09:03 INFO  Binlog connected.
```

Any idea what this could be about?

**Comment by osheroff** [comment]
were you on a functional version previously?  which one?

**Comment by Liban-H** [comment]
We were previously on v1.23.3

**Comment by osheroff** [comment]
does that error happen each time you boot maxwell?  is it at the same binlog position?  does maxwell continue to operate normally after the first error?   

If it's happening at the same position, I'd love to get a hexdump of the binlog.

What server version?

**Comment by Liban-H** [comment]
Yes it happens every time maxwell boots. It happens at different binlog positions and continues to operate normally afterwards although I may need to run a few more tests to confirm this.

Currently using Ubuntu 16.04

**Comment by osheroff** [comment]
> Currently using Ubuntu 16.04

No, sorry, what version of mysql are you connecting to?

**Comment by Liban-H** [comment]
Currently using mysql 5.7

**Comment by osheroff** [comment]
what JVM?

**Comment by osheroff** [comment]
is it possible to get a tcpdump of the mysql connection while maxwell boots?

I've been down the code paths, but I don't have any theories why this would happen.  `skipToTheEndOfTheBlock` where the EOFException is being thrown is there to consume any data that hasn't been read by the data deserializer.  So the deserializer for the write-rows-event could be failing in some sort of interesting way, or the overall length could be wrong, I *suppose* a packet could be corrupted...

I have no real earthly idea.  

I also don't know why in sam hell the connection would fix itself after one crash.

**Comment by osheroff** [comment]
@Liban-H any chance you can get a tcpdump?  this feels like an issue I'd love to track down, but I'm very much in the dark without more info.

**Comment by Liban-H** [comment]
Hi @osheroff , I've been running more tests and maxwell seems to stabilize after initially crashing. Strange behaviour as a few days ago it would crash constantly. 

I'll continue running tests but i'll make sure to update you some time next week.

Thanks for checking up on this issue.

**Comment by Liban-H** [comment]
Hi @osheroff here's a tcpdump

```12:26:05.858360 IP (tos 0x0, ttl 64, id 41210, offset 0, flags [DF], proto TCP (6), length 228)
    192.168.80.2.60014 > 10.160.0.133.3306: Flags [P.], cksum 0x1ca6 (incorrect -> 0xe773), seq 24670:24846, ack 130737, win 2474, options [nop,nop,TS val 2073113237 ecr 2073113237], length 176
12:26:05.897887 IP (tos 0x0, ttl 64, id 41211, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60014 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd4a3), seq 24846, ack 131757, win 2474, options [nop,nop,TS val 2073113247 ecr 2073113237], length 0
12:26:05.897900 IP (tos 0x0, ttl 64, id 41211, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60014 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd4a3), seq 24846, ack 131757, win 2474, options [nop,nop,TS val 2073113247 ecr 2073113237], length 0
12:26:06.319418 IP (tos 0x0, ttl 64, id 15034, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x3fdf), seq 0, ack 1, win 806, options [nop,nop,TS val 2073113352 ecr 2073064529], length 0
12:26:06.319439 IP (tos 0x0, ttl 64, id 15034, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x3fdf), seq 0, ack 1, win 806, options [nop,nop,TS val 2073113352 ecr 2073064529], length 0
12:26:06.339274 IP (tos 0x0, ttl 64, id 15035, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x46a4), seq 0, ack 14481, win 1300, options [nop,nop,TS val 2073113357 ecr 2073113352], length 0
12:26:06.339294 IP (tos 0x0, ttl 64, id 15035, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x46a4), seq 0, ack 14481, win 1300, options [nop,nop,TS val 2073113357 ecr 2073113352], length 0
12:26:06.361147 IP (tos 0x0, ttl 64, id 15036, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd3c8), seq 0, ack 43441, win 1733, options [nop,nop,TS val 2073113362 ecr 2073113357], length 0
12:26:06.361165 IP (tos 0x0, ttl 64, id 15036, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd3c8), seq 0, ack 43441, win 1733, options [nop,nop,TS val 2073113362 ecr 2073113357], length 0
12:26:06.380976 IP (tos 0x0, ttl 64, id 15037, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xf437), seq 0, ack 100433, win 1963, options [nop,nop,TS val 2073113367 ecr 2073113362], length 0
12:26:06.380994 IP (tos 0x0, ttl 64, id 15037, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xf437), seq 0, ack 100433, win 1963, options [nop,nop,TS val 2073113367 ecr 2073113362], length 0
12:26:06.400525 IP (tos 0x0, ttl 64, id 15038, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x2f91), seq 0, ack 216273, win 1990, options [nop,nop,TS val 2073113372 ecr 2073113367], length 0
12:26:06.400537 IP (tos 0x0, ttl 64, id 15038, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x2f91), seq 0, ack 216273, win 1990, options [nop,nop,TS val 2073113372 ecr 2073113367], length 0
12:26:06.408402 IP (tos 0x0, ttl 64, id 15039, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd2d2), seq 0, ack 371209, win 1859, options [nop,nop,TS val 2073113374 ecr 2073113372], length 0
12:26:06.408412 IP (tos 0x0, ttl 64, id 15039, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd2d2), seq 0, ack 371209, win 1859, options [nop,nop,TS val 2073113374 ecr 2073113372], length 0
12:26:06.437925 IP (tos 0x0, ttl 64, id 15040, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x728b), seq 0, ack 527593, win 1182, options [nop,nop,TS val 2073113382 ecr 2073113374], length 0
12:26:06.437933 IP (tos 0x0, ttl 64, id 15040, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x728b), seq 0, ack 527593, win 1182, options [nop,nop,TS val 2073113382 ecr 2073113374], length 0
12:26:06.477905 IP (tos 0x0, ttl 64, id 15041, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x25fa), seq 0, ack 678889, win 539, options [nop,nop,TS val 2073113392 ecr 2073113382], length 0
12:26:06.477914 IP (tos 0x0, ttl 64, id 15041, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x25fa), seq 0, ack 678889, win 539, options [nop,nop,TS val 2073113392 ecr 2073113382], length 0
12:26:06.517902 IP (tos 0x0, ttl 64, id 15042, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1a80), seq 0, ack 747881, win 0, options [nop,nop,TS val 2073113402 ecr 2073113392], length 0
12:26:06.517913 IP (tos 0x0, ttl 64, id 15042, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1a80), seq 0, ack 747881, win 0, options [nop,nop,TS val 2073113402 ecr 2073113392], length 0
12:26:06.585103 IP (tos 0x0, ttl 64, id 15043, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1762), seq 0, ack 747881, win 782, options [nop,nop,TS val 2073113418 ecr 2073113392], length 0
12:26:06.585113 IP (tos 0x0, ttl 64, id 15043, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1762), seq 0, ack 747881, win 782, options [nop,nop,TS val 2073113418 ecr 2073113392], length 0
12:26:06.592088 IP (tos 0x0, ttl 64, id 15044, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x8fe1), seq 0, ack 847977, win 881, options [nop,nop,TS val 2073113420 ecr 2073113418], length 0
12:26:06.592098 IP (tos 0x0, ttl 64, id 15044, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x8fe1), seq 0, ack 847977, win 881, options [nop,nop,TS val 2073113420 ecr 2073113418], length 0
12:26:06.597579 IP (tos 0x0, ttl 64, id 15045, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xa83b), seq 0, ack 906970, win 1186, options [nop,nop,TS val 2073113421 ecr 2073113420], length 0
12:26:06.597589 IP (tos 0x0, ttl 64, id 15045, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xa83b), seq 0, ack 906970, win 1186, options [nop,nop,TS val 2073113421 ecr 2073113420], length 0
12:26:06.661306 IP (tos 0x0, ttl 64, id 15046, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [F.], cksum 0x1bf6 (incorrect -> 0x9d0f), seq 0, ack 906970, win 4029, options [nop,nop,TS val 2073113437 ecr 2073113420], length 0
12:26:06.661323 IP (tos 0x0, ttl 64, id 15046, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.80.2.60022 > 10.160.0.133.3306: Flags [F.], cksum 0x1bf6 (incorrect -> 0x9d0f), seq 0, ack 906970, win 4029, options [nop,nop,TS val 2073113437 ecr 2073113420], length 0
12:26:06.744029 IP (tos 0x0, ttl 64, id 41212, offset 0, flags [DF], proto TCP (6), length 57)
    192.168.80.2.60014 > 10.160.0.133.3306: Flags [P.], cksum 0x1bfb (incorrect -> 0xc4c3), seq 24846:24851, ack 131757, win 2474, options [nop,nop,TS val 2073113458 ecr 2073113237], length 5
12:26:06.744047 IP (tos 0x0, ttl 64, id 41212, offset 0, flags [DF], proto TCP (6), length 57)
    192.168.80.2.60014 > 10.160.0.133.3306: Flags [P.], cksum 0x1bfb (incorrect -> 0xc4c3), seq 24846:24851, ack 131757, win 2474, options [nop,nop,TS val 2073113458 ecr 2073113237], length 5
```
The error happens at 12:26:06, I noticed the seq number and length become 0 at that point.

**Comment by Liban-H** [comment]
Hi @osheroff , here's a tcpdump:

```12:26:05.858360 IP (tos 0x0, ttl 64, id 41210, offset 0, flags [DF], proto TCP (6), length 228)
    x.x.x.x.60014 > x.x.x.x.3306: Flags [P.], cksum 0x1ca6 (incorrect -> 0xe773), seq 24670:24846, ack 130737, win 2474, options [nop,nop,TS val 2073113237 ecr 2073113237], length 176
12:26:05.897887 IP (tos 0x0, ttl 64, id 41211, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60014 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd4a3), seq 24846, ack 131757, win 2474, options [nop,nop,TS val 2073113247 ecr 2073113237], length 0
12:26:05.897900 IP (tos 0x0, ttl 64, id 41211, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60014 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd4a3), seq 24846, ack 131757, win 2474, options [nop,nop,TS val 2073113247 ecr 2073113237], length 0
12:26:06.319418 IP (tos 0x0, ttl 64, id 15034, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x3fdf), seq 0, ack 1, win 806, options [nop,nop,TS val 2073113352 ecr 2073064529], length 0
12:26:06.319439 IP (tos 0x0, ttl 64, id 15034, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x3fdf), seq 0, ack 1, win 806, options [nop,nop,TS val 2073113352 ecr 2073064529], length 0
12:26:06.339274 IP (tos 0x0, ttl 64, id 15035, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x46a4), seq 0, ack 14481, win 1300, options [nop,nop,TS val 2073113357 ecr 2073113352], length 0
12:26:06.339294 IP (tos 0x0, ttl 64, id 15035, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x46a4), seq 0, ack 14481, win 1300, options [nop,nop,TS val 2073113357 ecr 2073113352], length 0
12:26:06.361147 IP (tos 0x0, ttl 64, id 15036, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd3c8), seq 0, ack 43441, win 1733, options [nop,nop,TS val 2073113362 ecr 2073113357], length 0
12:26:06.361165 IP (tos 0x0, ttl 64, id 15036, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd3c8), seq 0, ack 43441, win 1733, options [nop,nop,TS val 2073113362 ecr 2073113357], length 0
12:26:06.380976 IP (tos 0x0, ttl 64, id 15037, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xf437), seq 0, ack 100433, win 1963, options [nop,nop,TS val 2073113367 ecr 2073113362], length 0
12:26:06.380994 IP (tos 0x0, ttl 64, id 15037, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xf437), seq 0, ack 100433, win 1963, options [nop,nop,TS val 2073113367 ecr 2073113362], length 0
12:26:06.400525 IP (tos 0x0, ttl 64, id 15038, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x2f91), seq 0, ack 216273, win 1990, options [nop,nop,TS val 2073113372 ecr 2073113367], length 0
12:26:06.400537 IP (tos 0x0, ttl 64, id 15038, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x2f91), seq 0, ack 216273, win 1990, options [nop,nop,TS val 2073113372 ecr 2073113367], length 0
12:26:06.408402 IP (tos 0x0, ttl 64, id 15039, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd2d2), seq 0, ack 371209, win 1859, options [nop,nop,TS val 2073113374 ecr 2073113372], length 0
12:26:06.408412 IP (tos 0x0, ttl 64, id 15039, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xd2d2), seq 0, ack 371209, win 1859, options [nop,nop,TS val 2073113374 ecr 2073113372], length 0
12:26:06.437925 IP (tos 0x0, ttl 64, id 15040, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x728b), seq 0, ack 527593, win 1182, options [nop,nop,TS val 2073113382 ecr 2073113374], length 0
12:26:06.437933 IP (tos 0x0, ttl 64, id 15040, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x728b), seq 0, ack 527593, win 1182, options [nop,nop,TS val 2073113382 ecr 2073113374], length 0
12:26:06.477905 IP (tos 0x0, ttl 64, id 15041, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x25fa), seq 0, ack 678889, win 539, options [nop,nop,TS val 2073113392 ecr 2073113382], length 0
12:26:06.477914 IP (tos 0x0, ttl 64, id 15041, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x25fa), seq 0, ack 678889, win 539, options [nop,nop,TS val 2073113392 ecr 2073113382], length 0
12:26:06.517902 IP (tos 0x0, ttl 64, id 15042, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1a80), seq 0, ack 747881, win 0, options [nop,nop,TS val 2073113402 ecr 2073113392], length 0
12:26:06.517913 IP (tos 0x0, ttl 64, id 15042, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1a80), seq 0, ack 747881, win 0, options [nop,nop,TS val 2073113402 ecr 2073113392], length 0
12:26:06.585103 IP (tos 0x0, ttl 64, id 15043, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1762), seq 0, ack 747881, win 782, options [nop,nop,TS val 2073113418 ecr 2073113392], length 0
12:26:06.585113 IP (tos 0x0, ttl 64, id 15043, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x1762), seq 0, ack 747881, win 782, options [nop,nop,TS val 2073113418 ecr 2073113392], length 0
12:26:06.592088 IP (tos 0x0, ttl 64, id 15044, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x8fe1), seq 0, ack 847977, win 881, options [nop,nop,TS val 2073113420 ecr 2073113418], length 0
12:26:06.592098 IP (tos 0x0, ttl 64, id 15044, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0x8fe1), seq 0, ack 847977, win 881, options [nop,nop,TS val 2073113420 ecr 2073113418], length 0
12:26:06.597579 IP (tos 0x0, ttl 64, id 15045, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xa83b), seq 0, ack 906970, win 1186, options [nop,nop,TS val 2073113421 ecr 2073113420], length 0
12:26:06.597589 IP (tos 0x0, ttl 64, id 15045, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [.], cksum 0x1bf6 (incorrect -> 0xa83b), seq 0, ack 906970, win 1186, options [nop,nop,TS val 2073113421 ecr 2073113420], length 0
12:26:06.661306 IP (tos 0x0, ttl 64, id 15046, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [F.], cksum 0x1bf6 (incorrect -> 0x9d0f), seq 0, ack 906970, win 4029, options [nop,nop,TS val 2073113437 ecr 2073113420], length 0
12:26:06.661323 IP (tos 0x0, ttl 64, id 15046, offset 0, flags [DF], proto TCP (6), length 52)
    x.x.x.x.60022 > x.x.x.x.3306: Flags [F.], cksum 0x1bf6 (incorrect -> 0x9d0f), seq 0, ack 906970, win 4029, options [nop,nop,TS val 2073113437 ecr 2073113420], length 0
12:26:06.744029 IP (tos 0x0, ttl 64, id 41212, offset 0, flags [DF], proto TCP (6), length 57)
    x.x.x.x.60014 > x.x.x.x.3306: Flags [P.], cksum 0x1bfb (incorrect -> 0xc4c3), seq 24846:24851, ack 131757, win 2474, options [nop,nop,TS val 2073113458 ecr 2073113237], length 5
12:26:06.744047 IP (tos 0x0, ttl 64, id 41212, offset 0, flags [DF], proto TCP (6), length 57)
    x.x.x.x.60014 > x.x.x.x.3306: Flags [P.], cksum 0x1bfb (incorrect -> 0xc4c3), seq 24846:24851, ack 131757, win 2474, options [nop,nop,TS val 2073113458 ecr 2073113237], length 5
    ```
    The error happens at 12:26:06 where I noticed the sequence number and length drop to 0.

**Comment by osheroff** [comment]
sorry, should have been more specific, I meant a full-data tcpdump with
like `-w dumpfile -s 0`, so we can pick apart what's happening inside...

**Comment by Liban-H** [comment]
Hi @osheroff the issue seems to have settled. Many thanks for your help.
