### ISSUE TITLE
trying to restore/load schema from no longer existing database

### ISSUE THREAD

**Issue by mpviau** [zendesk/maxwell#1653]
**Scenario:**

1. Launch maxwell with multiple db schema that will be capured correctly
2. Stop maxwell
3. Drop one of the database
4. Restart maxwell

**Expected result:**

Maxwell starts correctly

**Actual result:**

Logs state:

...
INFO MysqlSavedSchema - beginning to play deltas...
INFO TaskManager - Stopping 1 tasks
ERROR TaskManager - cause:
...
Caused by: com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find database 'somedeletedb'
at com.zendesk.maxwell.schema.Schema.findDatabaseOrThrow(Schema.java:52) ~[maxwell-1.31.0.jar:1.31.0]
at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:22) ~[maxwell-1.31.0.jar:1.31.0]
at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreDerivedSchema(MysqlSavedSchema.java:394) ~[maxwell-1.31.0.jar:1.31.0]
at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreFromSchemaID(MysqlSavedSchema.java:409) ~[maxwell-1.31.0.jar:1.31.0]
at com.zendesk.maxwell.schema.MysqlSavedSchema.restore(MysqlSavedSchema.java:307) ~[maxwell-1.31.0.jar:1.31.0]
at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:68) ~[maxwell-1.31.0.jar:1.31.0]

**Comment by mpviau** [comment]
Workaround is to clean the schema info from maxwell schema db prior to restarting, but that's a pain.

**Comment by osheroff** [comment]
no, something is going wrong.  Either the database didn't get captured in the first place, or... something else.  Are you doing a delete in `maxwell`.`databases` or something?

Do you have a more precise repro?
