### ISSUE TITLE
No ObjectCodec defined for the generator, ... (type passed java.sql.Time)

### ISSUE THREAD

**Issue by io41** [zendesk/maxwell#166]
I'm experimenting a little with maxwell, following the getting started guide and appear to have hit an issue while processing an event generated by the following row:

```
mysql> select * from events where event_id = 5;
+----------+--------------+---------------------+----------------------------------+-----------+---------+----------------------------------+--------------+
| event_id | business_ref | when                | what_ref                         | what_type | action  | who_ref                          | deleted_name |
+----------+--------------+---------------------+----------------------------------+-----------+---------+----------------------------------+--------------+
|        5 |            1 | 2015-11-25 23:59:00 | 785d226973bf4eae9bfc903f0b9f2033 | Task      | updated | d4ed50fe84ba473fb2690b149e7f2933 | NULL         |
+----------+--------------+---------------------+----------------------------------+-----------+---------+----------------------------------+--------------+`
```

From the stack trace it appears that maxwell has trouble with the `when` column, which is of type `datetime`:

```
08:54:57,083 ERROR MaxwellReplicator - Got an unexpected row-event: WriteRowsEvent[header=BinlogEventV4HeaderImpl[timestamp=1448495940000,eventType=23,serverId=1,eventLength=290,nextPosition=2705491,flags=0,timestampOfReceipt=1448528097073],tableId=332,reserved=1,columnCount=10,usedColumns=1111111111,rows=[Row[columns=[560, 1, Wed Nov 25 23:59:00 UTC 2015, 785d226973bf4eae9bfc903f0b9f2033, Task, d4ed50fe84ba473fb2690b149e7f2933, webapp, null, BlobColumn[value=[B@7c417213], b4a678826df0408d869346ff67275627]]]]
java.lang.IllegalStateException: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.sql.Time)
	at com.fasterxml.jackson.core.JsonGenerator._writeSimpleObject(JsonGenerator.java:1725)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:327)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1415)
	at com.zendesk.maxwell.RowMap.toJSON(RowMap.java:91)
	at com.zendesk.maxwell.MaxwellAbstractRowsEvent.toJSONStrings(MaxwellAbstractRowsEvent.java:257)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducer.push(MaxwellKafkaProducer.java:86)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:97)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
08:54:57,147 INFO  SchemaPosition - Storing final position: null
```

Have I recognised the problem correctly, or is it likely that the problem lies elsewhere?

---

Version info:
MySQL: 5.5.44
Maxwell: 0.14.5
Java: 1.8.0_66
OS: OS X 10.11.1

**Comment by osheroff** [comment]
fixed in 0.14.6
