### ISSUE TITLE
NoClassDefFoundError: jdk/nashorn/api/scripting/ScriptObjectMirror

### ISSUE THREAD

**Issue by t3link** [zendesk/maxwell#1683]
I'm using zulu `jdk16`, and an exception occurs here.

```bash
λ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode, sharing)
```
```
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/ScriptObjectMirror
        at com.zendesk.maxwell.row.MaxwellJson.writeValueToJSON(MaxwellJson.java:69)
        at com.zendesk.maxwell.row.RowMap.writeMapToJSON(RowMap.java:130)
        at com.zendesk.maxwell.row.RowMap.toJSON(RowMap.java:242)
        at com.zendesk.maxwell.producer.StdoutProducer.push(StdoutProducer.java:13)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processRow(BinlogConnectorReplicator.java:294)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:193)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.ScriptObjectMirror
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 10 more
20:18:35,958 INFO  TaskManager - Stopped all tasks
```

The `jdk.scripting.nashorn`  module has been removed since jdk15. 

Is there any plan or solution to support the latest jdk version? 😃

**Comment by osheroff** [comment]
so I've looked into this, none of the solutions are great.  nashorn was a decent javascript engine and it's gone now.

- We can *try* to do something with GraalVM, I was working on it here https://github.com/zendesk/maxwell/pull/1692 but the Graal stuff when running on anything not-graal is sort of impentrably janky. 

- Or we can throw up our hands and use the old, slow Rhino implementation where needed.  

If there's another reasonably fast javascript via the jvm library I'm all ears.  Maybe there's some bridge world where we lazy-load the scripting stuff and trying to figure out in runtime which is the best option.  dunno.

**Comment by constantijn** [comment]
Would it be an option to just add nashorn back in?

https://github.com/openjdk/nashorn

<dependency>
    <groupId>org.openjdk.nashorn</groupId>
    <artifactId>nashorn-core</artifactId>
    <version>15.2</version>
</dependency>
