### ISSUE TITLE
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: START

### ISSUE THREAD

**Issue by zcw5116** [zendesk/maxwell#1686]
version: maxwell-1.33.0
MySQL: mysql-8.0.24

step 1: start maxwell
./bin/maxwell --password 123456

step 2: DDL 
mysql> create table test as select * from t_test limit 5;

then error occurs, detail following:

23:55:48,701 INFO  BinaryLogClient - Connected to localhost:3306 at binlog.000007/20243 (sid:6379, cid:213)
23:55:48,702 INFO  BinlogConnectorReplicator - Binlog connected.
23:55:48,815 INFO  Server - jetty-9.4.37.v20210219; built: 2021-02-19T15:16:47.689Z; git: 27afab2bd37780d179836e313e0fe11bc4fa0ce9; jvm 11.0.11+9-LTS-194
23:55:48,939 ERROR MysqlParserListener - (parse (statement (create_table (create_table_preamble CREATE TABLE (table_name (name (id `test`)))) (create_specifications ( (create_specification (column_definition (name (id `id`)) (data_type (signed_type int (column_options (default_value DEFAULT (literal_with_weirdo_multistring NULL))))))) , (create_specification (column_definition (name (id `name`)) (data_type (string_type varchar (length ( 200 )) (column_options (default_value DEFAULT (literal_with_weirdo_multistring NULL))))))) )))) START TRANSACTION)
23:55:48,940 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE `test` (
  `id` int DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL
) START TRANSACTION'
23:55:48,940 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@332ada20{/,null,AVAILABLE}
23:55:48,940 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[binlog.000007:20809], lastHeartbeat=1619536894013]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: START
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:106)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:539)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:645)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
23:55:49,156 INFO  BinlogConnectorReplicator - Binlog disconnected.
23:55:49,164 INFO  AbstractConnector - Started ServerConnector@45740206{HTTP/1.1, (http/1.1)}{0.0.0.0:8081}
23:55:49,164 INFO  Server - Started @7234ms
23:55:49,183 INFO  TaskManager - Stopping 5 tasks
23:55:49,183 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: START
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.33.0.jar:1.33.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17) ~[antlr4-runtime-4.8-1.jar:4.8-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:106) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:539) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:645) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.33.0.jar:1.33.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.33.0.jar:1.33.0]
23:55:49,208 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@6cd4fe6f
23:55:49,211 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@683df2ac
23:55:49,214 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
23:55:49,226 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@6e3aa3ad
23:55:49,227 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@6e7a7c3e
23:55:49,228 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@610d553a
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: START
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:106)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:539)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:645)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
23:55:49,242 INFO  AbstractConnector - Stopped ServerConnector@45740206{HTTP/1.1, (http/1.1)}{0.0.0.0:8081}
23:55:49,249 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@332ada20{/,null,STOPPED}

**Comment by osheroff** [comment]
it's very odd that you encountered this.  There is no mention of anything resembling this in the documentation.  I've accepted your PR on faith and it'll go into the next release.
