### ISSUE TITLE
truncate is an exception when using the same table in different databases

### ISSUE THREAD

**Issue by wanghangyu817** [zendesk/maxwell#1705]
**I have two databases, both of which are in one MySQL instance, both of which have tables with the same table name,When I used truncate to truncate a table DB1.yw_user_real_time_data (DB2.yw_user_real_time_data is the table that Maxwell collected), Maxwell got an exception**

**exception info：**

-------------------------------------------------------------------------------------------------------------
11:09:56,886 ERROR MysqlParserListener - (parse truncate `yw_user_real_time_data`)
11:09:56,886 ERROR SchemaChange - Error parsing SQL: '/* Query from DMS-DATA_CORRECT-2782403-executeKey_5482825_410 by user 227234486515028425 */
truncate`yw_user_real_time_data`'
11:09:56,886 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[110a3bc3-0162-11ea-b135-98039b157d22:1-214500852,3e552284-0162-11ea-b136-98039b2be2bc:1-820351569,3f0f8543-b801-11e9-92b9-506b4bfe4614:1-74789
44,6246ba7b-7af0-11ea-89db-7cd30ae4124a:1-595923921,668dd13f-b801-11e9-92ba-506b4bc275b2:1-637496885,b4d83b63-1878-11e9-826f-506b4b3fc486:1-179604638,b4e0c88a-1878-11e9-826f-98039b081794:1-36765182,fa75f858-c6b3-11e9-b290-506b4b486aa
c:1-276505,4861035d-8b19-11ea-b33a-7cd30ae45e3c:1-902935389,9961cfa1-d5f0-11ea-9b41-6c92bf5c7bd6:1-5363888549], lastHeartbeat=1623294369386]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: truncate
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:92)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:104)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:315)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:337)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:609)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:157)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
11:09:56,926 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: truncate
-------------------------------------------------------------------------------------------------------------

I was wondering if the exception was caused by the failure to parse the binlog database. I was using version 1.24.0

**Comment by wanghangyu817** [comment]
How can this be avoided or solved, and I need help right now

**Comment by redcape** [comment]
Seems like the parser could use some work on this case. The parser is supposed to just ignore DDL like truncate.

If it's possible, change:
```
truncate`yw_user_real_time_data`
```
to
```
truncate `yw_user_real_time_data`
```

See the space between truncate and `.

**Comment by redcape** [comment]
You may want to consider upgrading to the latest released version as well. There's been at least one fix for multi-line C-style comments since then: https://github.com/zendesk/maxwell/pull/1638/files - while it doesn't appear to affect your use-case (you have a single-line c-style comment), upgrading would be better to get all the latest fixes.

**Comment by redcape** [comment]
Similar to that PR, modifying `SchemaChange`'s TRUNCATE line on the blacklist should fix it.

From:

		SQL_BLACKLIST.add(Pattern.compile("\\A\\s*TRUNCATE\\s+", Pattern.CASE_INSENSITIVE | Pattern.MULTILINE));

To:

		SQL_BLACKLIST.add(Pattern.compile("\\A\\s*TRUNCATE(\\s+|`)", Pattern.CASE_INSENSITIVE | Pattern.MULTILINE));

**Comment by wanghangyu817** [comment]
> 似乎解析器可以在这种情况下使用一些工作。解析器应该像 truncate 一样忽略 DDL。
> 
> 如果可能，请更改：
> 
> ```
> truncate`yw_user_real_time_data`
> ```
> 
> 至
> 
> ```
> truncate `yw_user_real_time_data`
> ```
> 
> 查看 truncate 和 ` 之间的空格。但这对您当前的问题没有帮助，因为它已经写入二进制日志。

Our DBA executes the command "truncate `yw_user_real_time_data` "with space in the middle. I don't understand why it is resolved to a statement with no space

**Comment by wanghangyu817** [comment]
> Pattern

Has this PR been incorporated into the latest version (1.33.0) or do I need to change it and redeploy it to my server

**Comment by wanghangyu817** [comment]
> Similar to that PR, modifying `SchemaChange`'s TRUNCATE line on the blacklist should fix it.
> 
> From:
> 
> ```
> 	SQL_BLACKLIST.add(Pattern.compile("\\A\\s*TRUNCATE\\s+", Pattern.CASE_INSENSITIVE | Pattern.MULTILINE));
> ```
> 
> To:
> 
> ```
> 	SQL_BLACKLIST.add(Pattern.compile("\\A\\s*TRUNCATE(\\s+|`)", Pattern.CASE_INSENSITIVE | Pattern.MULTILINE));
> ```

Has this PR been incorporated into the latest version (1.33.0) or do I need to change it and redeploy it to my server
