### ISSUE TITLE
Maxwell shuts down when reaching a large transaction in binlog

### ISSUE THREAD

**Issue by lpmarques** [zendesk/maxwell#1711]
Hi!

I'm a huge fan of Maxwell's and have been testing it as a candidate for replicating of a production database.
After I deployed it in a K8s cluster, it worked just fine, producing events into a PubSub topic for two days, but at some point it would just repeatedly shut down after timing out "waiting for heartbeat 1624316267996".

First, I tried to solve it by pulling its position back to 0 in the same binlog file where it shut down, but again it would only produce events up until position 18297288, time out and shut down repeatedly. Only by forwarding Maxwell to the following binlog file I could get it to work without new interruptions, but at cost of data integrity in the target.

Looking through the problematic binlog file, I noticed 18297288 is the last position before a huge transaction that spans to 355276377, with tens of thousands of row updates.

Is Maxwell not able to deal with such large transactions by default?
Is that really a transaction timeout problem or some issue regarding the PubSub producer specifically?
If it is a timeout problem, is there any way I can increase the time limit that causes this behavior?

Full log output:
```
Using kafka version: 1.0.0
22:57:14,822 INFO  Maxwell - Starting Maxwell. maxMemory: 28320661504 bufferMemoryUsage: 0.25
22:57:16,363 INFO  Maxwell - Maxwell v1.33.1 is booting (MaxwellPubsubProducer), starting at Position[BinlogPosition[mysql-bin-changelog.047599:18297288], lastHeartbeat=0]
22:57:16,761 INFO  MysqlSavedSchema - Restoring schema id 2 (last modified at Position[BinlogPosition[mysql-bin-changelog.045905:219], lastHeartbeat=0])
22:57:16,872 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin-changelog.045552:38883615], lastHeartbeat=0])
22:57:16,934 INFO  MysqlSavedSchema - beginning to play deltas...
22:57:16,941 INFO  MysqlSavedSchema - played 1 deltas in 2ms
22:57:16,970 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin-changelog.047599:18297288
22:57:16,974 INFO  MaxwellHTTPServer - Maxwell http server starting
22:57:16,977 INFO  MaxwellHTTPServer - Maxwell http server started on port 8080
22:57:16,994 INFO  log - Logging initialized @6862ms to org.eclipse.jetty.util.log.Slf4jLog
22:57:17,093 INFO  Server - jetty-9.4.37.v20210219; built: 2021-02-19T15:16:47.689Z; git: 27afab2bd37780d179836e313e0fe11bc4fa0ce9; jvm 11.0.10+9
22:57:17,147 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@337021df{/,null,AVAILABLE}
22:57:17,163 INFO  AbstractConnector - Started ServerConnector@17a0ff8c{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
22:57:17,163 INFO  Server - Started @7032ms
22:57:17,763 INFO  BinaryLogClient - Connected to rdsproductionbee.supermercadonow.com:3306 at mysql-bin-changelog.047599/18297288 (sid:6379, cid:11136)
22:57:17,764 INFO  BinlogConnectorReplicator - Binlog connected.
22:57:47,999 INFO  MaxwellContext - Sending final heartbeat: 1624316267996
22:57:54,113 WARN  MaxwellContext - Timed out waiting for heartbeat 1624316267996
22:57:54,118 INFO  TaskManager - Stopping 5 tasks
22:57:54,118 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellPubsubProducerWorker@49b86d71
22:57:54,123 ERROR MaxwellContext - Exception occurred during shutdown:
java.lang.IllegalStateException: Cannot shut down a publisher already shut-down.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[guava-30.1.1-jre.jar:?]
        at com.google.cloud.pubsub.v1.Publisher.shutdown(Publisher.java:583) ~[google-cloud-pubsub-1.108.6.jar:1.108.6]
        at com.zendesk.maxwell.producer.MaxwellPubsubProducerWorker.requestStop(MaxwellPubsubProducer.java:226) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.util.TaskManager.stop(TaskManager.java:48) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.MaxwellContext.shutdown(MaxwellContext.java:191) [maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.MaxwellContext$1$1.run(MaxwellContext.java:222) [maxwell-1.33.1.jar:1.33.1]
        at java.lang.Thread.run(Thread.java:834) [?:?]
22:57:54,129 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process
```

**Comment by lpmarques** [comment]
Btw, I'm using Maxwell v1.33.1

**Comment by osheroff** [comment]
no we should definitely be able to deal with large transactions.  They have to spool out to disk so are a bit out of the totally-normal-flow of operations but they certainly shouldn't cause a shutdown.  How's memory and CPU usage during these events?  It could be a GC-thrashing kind of situation, maybe. 

the error messages you're seeing are a bit misleading, I think.  this line:
```
22:57:47,999 INFO  MaxwellContext - Sending final heartbeat: 1624316267996
```

means that Maxwell is already trying to shut down.  So the timeout that happens after that is not the cause of the issue.   If maxwell had caught an exception and was trying to shut down that way, if would have logged the exception.

So by my reading of the code, it *seems* like the JVM initiated its own shutdown procedure?  This could happen if like:
- it got a TERM signal
- some other JVM-initiated shutdown i'm not aware of; maybe an out-of-memory condition? 
- the OOM killer on linux?  (I didn't think it was ever gentle enough to send a TERM)

The quite-large amount of memory allocated really makes it seem like memory shouldn't be an issue.  And actually, as near as I can tell, the code that triggers a large transaction to overflow to disk isn't kicking in either (there should be an INFO message if it does). 

Does maxwell stall out for awhile before crashing?

**Comment by osheroff** [comment]
no we should definitely be able to deal with large transactions.  They have to spool out to disk so are a bit out of the totally-normal-flow of operations but they certainly shouldn't cause a shutdown.  How's memory and CPU usage during these events?  It could be a GC-thrashing kind of situation, maybe. 

the error messages you're seeing are a bit misleading, I think.  this line:
```
22:57:47,999 INFO  MaxwellContext - Sending final heartbeat: 1624316267996
```

means that Maxwell is already trying to shut down.  So the timeout that happens after that is not the cause of the issue.   If maxwell had caught an exception and was trying to shut down that way, if would have logged the exception.

So by my reading of the code, it *seems* like the JVM initiated its own shutdown procedure?  This could happen if like:
- it got a TERM signal
- some other JVM-initiated shutdown i'm not aware of; maybe an out-of-memory condition? 
- the OOM killer on linux?  (I didn't think it was ever gentle enough to send a TERM)

The quite-large amount of memory allocated really makes it seem like memory shouldn't be an issue.  And actually, as near as I can tell, the code that triggers a large transaction to overflow to disk isn't kicking in either (there should be an INFO message if it does). 

Does maxwell stall out for awhile before crashing?

**Comment by lpmarques** [comment]
Hey, @osheroff, thanks for your reply!

Got it! So the reason Maxwell is trying to shut down to begin with is totally unclear at this point... ok. 
I don't think memory is the issue either, but I'll try to reproduce the event and monitor node's memory usage.

If I got your question correctly, Maxwell stalls for just as long the log timestamps indicate: ~30 secs, between connecting to binlog and starting to shut down.

I could also recover part of the logs in debug mode, but couldn't make much sense out of it. Would these logs be of any help?

**Comment by osheroff** [comment]
> I could also recover part of the logs in debug mode, but couldn't make much sense out of it. Would these logs be of any help?

Maybe.  Couldn't hurt to post them.

Thanks for pointing out 30 seconds.  That's an interesting timing, and *maybe* relates to the database connection pool.  If you're going to turn on debug logging you may want to edit log4j2.xml to also enable logging for "com.mchange.v2" (the C3P0 pooling code)

**Comment by lpmarques** [comment]
So, by the metrics I could collect, there's no evidence the pod surpasses ~1 CPU core or 3MiB of memory consumption while running.

I'm appending the debug logs generated, with C3P0 pooling included.

Not sure how informative this observation is but, speaking of 30 seconds, the log lines containing IdleTimeout code caught my eye, always mentioning "30000ms remaining". E.g:
```
22:00:29,602 DEBUG IdleTimeout - SocketChannelEndPoint@78cfa1f1{l=/10.212.97.113:8080,r=/10.212.97.65:45962,OPEN,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=0}-><null> idle timeout check, elapsed: 0 ms, remaining: 30000 ms
```
[maxwell_debug_logs.txt](https://github.com/zendesk/maxwell/files/6697653/maxwell_debug_logs.txt)

Thanks again and please let me know if the logs were of any help!

**Comment by osheroff** [comment]
oh.  what's the kubernetes liveness check that's happening? could it be that maxwell isn't making any progress for a little while and maybe is reporting itself dead back to kubernetes?

**Comment by osheroff** [comment]
(just a guess.  the logs didn't really tell me anything)

**Comment by lpmarques** [comment]
Hey, @osheroff, you nailed it!

Apparently, while Maxwell is reading a transaction both /ping and /healthcheck endpoints become unresponsive.
Meanwhile, kubernetes was trying to check /ping and, after some deadline exceeded, liveness probe failed and triggered container restart.

By disabling the liveness probe I could get Maxwell to read a transaction with 5 million rows seamlessly.
It's still not the desired setup, but at least it solved the shut down problem. Is there any config today that allows Maxwell to concurrently process transactions and respond to http requests?

Nevertheless, thank you for the insight!

**Comment by lpmarques** [comment]
Just a minor correction/update: at this point, the 5 million rows are being produced but not 100% seamlessly. Up to now, I've got 17 failed messages after errors of this sort:
```
ERROR PubsubCallback - io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3.796987905s. [remote_addr=pubsub.googleapis.com/64.233.170.95:443]
```

Any clue on this? What configurations could I tweak with to avoid such failures?

**Comment by osheroff** [comment]
> Apparently, while Maxwell is reading a transaction both /ping and /healthcheck endpoints become unresponsive.

That really really shouldn't happen.  I'm not the most incredibly familiar with those parts of the code TBH, but i'll look.

**Comment by osheroff** [comment]
I know, I know, delays...

I couldn't repro this locally.  I spooled up a giant transaction to disk and the HTTP endpoint stayed perfectly alive during the whole thing.  Wondering if you observed a literal non-responsiveness from the http endpoint or if it returned a "failed" state?  I mean I guess the http thread could be hugely starved for cpu or locked out or something.

FWIW the `/ping` endpoint does *nothing* that interacts with the rest of maxwell -- it really just answers "is maxwell alive"?  So if it's not responding the whole JVM has gone catatonic...
