### ISSUE TITLE
ERROR MysqlParserListener - (statement CREATE SEQUENCE 99999999999903_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999 CYCLE)

### ISSUE THREAD

**Issue by saisanthosh23** [zendesk/maxwell#1714]
I'm getting this error frequently in my sync. I need your support in fixing it.
Detailing error listed in docker.

ersion: 1.0.0
09:17:06,097 ERROR MysqlParserListener - (statement CREATE SEQUENCE 99999999999903_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999 CYCLE)
09:17:06,106 ERROR SchemaChange - Error parsing SQL: 'CREATE SEQUENCE 99999999999903_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999 CYCLE'
09:17:06,107 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.000014:358878227], lastHeartbeat=1624612625194]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:106)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
09:17:06,131 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.33.0.jar:1.33.0]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:106) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.33.0.jar:1.33.0]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.33.0.jar:1.33.0]

**Comment by saisanthosh23** [comment]
Kindly help me to fix this at earliest
