### ISSUE TITLE
Table created during schema capture causes failure

### ISSUE THREAD

**Issue by redcape** [zendesk/maxwell#1715]
The database instance I'm using is under constant change since it has a per-tenant DB model. What you'll see is a new database and tables are being created and dropped frequently.  What happened here is that after loading ~14K databases in a dev environment, it fails to catch up the binlog with an `Unexpectedly asked to create existing table` error. I presume because the table was processed during schema capture (reading INFORMATION_SCHEMA.SCHEMATA can take 10+ mins on larger instances that recently started and haven't cached the DB list yet), but it was also created after the binlog starting position was stored.

The error is caused by a table already existing and trying to recreate it in `ResolvedTableCreate#apply`. Is this check necessary? Can we change this to replace the table instead (with potentially older, but up-to-date per the binlog) data?

I expect similar errors could happen with `ResolvedTableCreate`/`ResolvedTableDrop` if the database or table was dropped while loading. While the verification points make sense, I think there needs to be some sort of leniency mode during initial catchup

```
2021/06/29 17:50:04.983 DEBUG SchemaChange: SQL_PARSE <- "CREATE TABLE `foo_34252432`.`bar_table` (
    `id` INT NOT NULL,
    `success` BOOL NOT NULL,
    -- Add the primary key as part of the CREATE TABLE statement in case `innodb_force_primary_key` is enabled
    CONSTRAINT `bar_pk`PRIMARY KEY (`id`)
) ENGINE=InnoDB"
```

```
2021/06/29 17:50:05.085 ERROR MaxwellContext: Terminating due to error
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Unexpectedly asked to create existing table bar_table
	at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:25)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:287)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by osheroff** [comment]
interesting.  I had always known about this race condition's possibility but never encountered it in the wild before.   I've resisted implementing one sort of hacky-but-possible solution for years which is that if a schema-desync condition happens we should simply re-capture the table in question.  Mostly I've been resisting because it has the potential to mask over more serious bugs where we might miss or corrupt a schema change.

However.

I think it's been enough years of stability that we can go ahead and implement something that will sort of auto-fix schema errors as well as handle this race situation.  Will have to think about all the different things that can happen and how we want to treat them... your solution of treating alters as semi-idempotent if they happen in a capture window makes sense... 

hm.  more later.

**Comment by redcape** [comment]
I think re-capture makes sense too, I'm a little worried they can also cause damage though by reading the future which might cause the same type of issue to happen again.

Here's what I was thinking:

1. store `schema capture start` binlog offset (how it works today)
2. capture schema (how it works today)
3. store `schema capture end` binlog offset
4. read starting from `schema capture start` to `schema capture end`, applying only DDL changes and not processing rows
 - not sure if not processing rows is important, but I'm not sure what happens when it encounters an unexpected database, table, or column field.
 - table, database CREATE/DROP can be applied based on DDL alone
 - column add/remove can be safely applied if table exists, else recapture from current (should we move `schema capture end` to the now current binglog offset?)
 - column rename can be safely applied if table/column exists for rename and no overwrite, else recapture from current (should we move `schema capture end` to the now current binlog offset?)
5. reach `schema capture end` and store schema, save offsets, continue from here with normal processing


I'm not super-well versed in all of this, but I'm hoping if something like this was done, we'd be able to have a consistent schema snapshot while avoiding locking prior to data being written externally.

**Comment by redcape** [comment]
Alternative to special rules for table/database/columns, we can re-fetch and reset `schema capture end` on conflict/InvalidSchemaException until reaching `schema capture end`. When reached, we think we are caught up and no more leniency.

**Comment by osheroff** [comment]
i think you're right and that we can't output any data (effectively) until schema-capture-end.  We'd have a potential mismatch between the data and the schema.  

I'm wondering if it'd be enough to simply catch and ignore `InvalidSchemaException` until we've reached the capture-end position -- The issue is only ever in trying to apply an already-applied DDL statement, so:

- db/table/column create when already created?  ok, ignoring is fine I think.  assume that the captured copy represents already having the change.
- drop when already dropped? fine, ignore
- change column type / other metadata? yeah, that's idempotent and probably won't fail.

**Comment by osheroff** [comment]
so I was thinking about this a bit. 

Here's the only thing I think might be truly free of bugs or data/schema mismatch:

- take current position: BEGIN_SNAPSHOT
- capture schema
- take current position: END_SNAPSHOT
- now, play binlog from BEGIN_SNAPSHOT to END_SNAPSHOT but *don't* process any rows.  just apply any DDL statements, ignoring any errors.
- start replicating from END_SNAPSHOT. 

there may be cases where a DDL statement played twice might silently corrupt data rather than throw an error, would have to think through it though.

Would delaying the start of replication until the end-of-capture position be detrimental in your env?
