### ISSUE TITLE
Error parsing SQL: 'CREATE SEQUENCE 21692141453801_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999 CYCLE'

### ISSUE THREAD

**Issue by saisanthosh23** [zendesk/maxwell#1722]
09:29:34,281 ERROR MysqlParserListener - (statement CREATE SEQUENCE 21692141453801_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999 CYCLE)
09:29:34,287 ERROR SchemaChange - Error parsing SQL: 'CREATE SEQUENCE 21692141453801_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999 CYCLE'
09:29:34,288 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.000016:83500771], lastHeartbeat=1625733221254]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
09:29:34,385 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.33.1.jar:1.33.1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.33.1.jar:1.33.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.33.1.jar:1.33.1]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)

I'm getting this error frequently, I'm running multiple maxwell instances with different id's. But still all maxwell instances were gets failed. When this error occurs

**Comment by cs6402** [comment]
I believe that you are using MariaDB.
Please refer to  http://maxwells-daemon.io/compat
