### ISSUE TITLE
MySQL 8.0.23 breaks the underlying binlog reader when using binlog-row-metadata=FULL

### ISSUE THREAD

**Issue by avaitla** [zendesk/maxwell#1724]
We're noticing the following error messages:

```
01:02:14,739 WARN  BinlogConnectorReplicator - cause: 
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at java.lang.Thread.run(Thread.java:834) [?:?]
01:02:14,794 WARN  BinlogConnectorReplicator - Event deserialization failure.
java.lang.NullPointerException: null
  at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:50) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:47) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:27) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
  at java.lang.Thread.run(Thread.java:834) [?:?]
```

This has started happening now that our MySQL cluster was upgraded from 8.0.17 to 8.0.23

I believe it is related to this underlying issue: https://github.com/osheroff/mysql-binlog-connector-java/pull/41

**Comment by osheroff** [comment]
fixed in 0.25.3
