### ISSUE TITLE
custom_producer.* does not works

### ISSUE THREAD

**Issue by lancelock** [zendesk/maxwell#1728]
even if i use the args in config.properties.example，it cause an error:

./bin/maxwell --custom_producer.custom_prop=foo
Using kafka version: 1.0.0
joptsimple.UnrecognizedOptionException: custom_producer.custom_prop is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:501)
	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:180)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:265)

maxwell version: 1.33.0

**Comment by lugavin** [comment]
Use **--custom_producer.factory=xxx.xxx.ProducerFactory**
