### ISSUE TITLE
 Use 'bin/maxwell-bootstrap' command to display "ERROR MaxwellBootstrapUtility"

### ISSUE THREAD

**Issue by wavefly666** [zendesk/maxwell#1732]
In a production environment, when I use the maxwell-bootstrap command to synchronize historical data, the error is reported as follows：

`connecting to jdbc:mysql://s####.sh.mysql.m.com:####/maxwell?allowPublicKeyRetrieval=true&connectTimeout=5000&serverTimezone=Asia%2FShanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
16:35:20,524 ERROR MaxwellBootstrapUtility - failed to connect to mysql server @ jdbc:mysql://s####.sh.mysql.m.com:####/maxwell?allowPublicKeyRetrieval=true&connectTimeout=5000&serverTimezone=Asia%2FShanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
16:35:20,528 ERROR MaxwellBootstrapUtility - Connections could not be acquired from the underlying database!
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at com.zendesk.maxwell.util.C3P0ConnectionPool.getConnection(C3P0ConnectionPool.java:18)
	at com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility.run(MaxwellBootstrapUtility.java:40)
	at com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility.main(MaxwellBootstrapUtility.java:253)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 4 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:150)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:947)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817)
	... 12 more
Caused by: java.net.UnknownHostException: null
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:132)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 15 more`

I counldn't find the reason for the error, counld help me find the reason，thanks!

**Comment by osheroff** [comment]
> Caused by: java.net.UnknownHostException: null

what does your configuration look like?

**Comment by wavefly666** [comment]
> > Caused by: java.net.UnknownHostException: null
> 
> what does your configuration look like?

The host is our company's mysql，but there is no such problem when testing locally

**Comment by GPXie** [comment]
I have the same problem，

**Comment by GPXie** [comment]
I have the same problem, After running this
/xmt/libs/maxwell/bin/maxwell-bootstrap --user root --password  *****  --host 10.*****  --port ****   --database **** --table  channe --client_id  cms1

**Comment by wavefly666** [comment]
> I have the same problem, but I can connect MySQL in this server , After running this
> maxwell/bin/maxwell-bootstrap --user root --password ***** --host 10.***** --port **** --database **** --table channe --client_id cms1
> 
> version: 1.29.2

I speculate that the operation and maintenance personnel of our company may have changed some of the MySQL operation and maintenance problems.

**Comment by GPXie** [comment]
now, i can use sql to begin maxwell-bootstrap, for example:
insert into maxwell.bootstrap (database_name, table_name, client_id) values ('cms', 'channel', 'cms');

**Comment by wavefly666** [comment]
> now, i can use sql to begin maxwell-bootstrap, for example:
> insert into maxwell.bootstrap (database_name, table_name, client_id) values ('cms', 'channel', 'cms');


I did this too, but it didn't work

**Comment by adleylcm** [comment]
bin/maxwell-bootstrap command  an error occurs as described above
this is OK:
Alternatively you can insert a row in the maxwell.bootstrap table to trigger a bootstrap.
mysql> insert into maxwell.bootstrap (database_name, table_name) values ('fooDB', 'barTable');

**Comment by FelexTriz** [comment]
any else one worked?

**Comment by FelexTriz** [comment]
> bin/maxwell-bootstrap 命令 如上所述发生错误，这是可以的：或者，您可以在 maxwell.bootstrap 表中插入一行来触发引导。 mysql> insert into maxwell.bootstrap （database_name， table_name） values （'fooDB'， 'barTable'）;



> 
感谢广东大哥，我手动写引导了
