### ISSUE TITLE
Error Parsing: ALTER TABLE broker.table ADD PARTITION /__MAXWELL__/ NOT EXISTS

### ISSUE THREAD

**Issue by daledude** [zendesk/maxwell#1741]
Mariadb 10.3.31
Maxwell 1.33.1 (docker)

```
21:20:36,408 ERROR MysqlParserListener - (parse (statement (alter_table (alter_table_preamble ALTER TABLE (table_name (db_name (name (id broker))) . (name_all_tokens (id table )))) (alter_partition_specification ADD PARTITION (skip_parens /__MAXWELL__/)))) NOT EXISTS ( partition p20210912 VALUES LESS THAN ( 738411 ) ))
21:20:36,410 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE broker.table ADD PARTITION /__MAXWELL__/ NOT EXISTS (partition p20210912 VALUES LESS THAN (738411))'
21:20:36,411 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.000163:995015680], lastHeartbeat=0]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: NOT
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)

```

**Comment by osheroff** [comment]
can you recover the original SQL that triggered this?

**Comment by daledude** [comment]
```
ALTER TABLE broker.table ADD PARTITION IF NOT EXISTS (partition p20210912 VALUES LESS THAN (738411))
```
