### ISSUE TITLE
Issue while upgrading maxwell from 1.16.1 to 1.29.2

### ISSUE THREAD

**Issue by rohitsahay2000** [zendesk/maxwell#1752]
Maxwell stops immediately after 1.29.2 is run with the following logs : 
`[ERROR] 2021-09-27 10:20:58.108 [maxwell-bootstrap-controller] MaxwellContext - exception in thread: maxwell-bootstrap-controller

java.lang.NullPointerException: null

    at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.getTableForTask(SynchronousBootstrapper.java:75) ~[maxwell-1.29.2.jar:1.29.2]

    at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.performBootstrap(SynchronousBootstrapper.java:90) ~[maxwell-1.29.2.jar:1.29.2]

    at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:49) ~[maxwell-1.29.2.jar:1.29.2]

    at com.zendesk.maxwell.bootstrap.BootstrapController.doWork(BootstrapController.java:74) ~[maxwell-1.29.2.jar:1.29.2]

    at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:58) ~[maxwell-1.29.2.jar:1.29.2]

    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.29.2.jar:1.29.2]

    at com.zendesk.maxwell.MaxwellContext.lambda$startTask$0(MaxwellContext.java:266) ~[maxwell-1.29.2.jar:1.29.2]

    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by osheroff** [comment]
looks like maybe you asked maxwell to bootstrap in a missing database.  I should make this throw a better error though.

**Comment by osheroff** [comment]
actually this is weird.  what does `select * from maxwell.bootstrap` say?
