### ISSUE TITLE
Alter table reorganize partition kills Maxwell

### ISSUE THREAD

**Issue by tcpecheanu** [zendesk/maxwell#1764]
**Describe the bug**
Maxwell stopped working after reorganize the table partition on a table.

**To Reproduce**
1. Alter table and reorganize the partition:
`ALTER TABLE `test_table`
REORGANIZE PARTITION START INTO
    (
    PARTITION PAST VALUES LESS THAN (0)
    );`
2. See the output:
`05:44:42,947 INFO  Server - Started @4485ms
05:44:59,167 ERROR MysqlParserListener - (parse (statement (alter_table (alter_table_preamble alter table (table_name (name (id test_table)))) (alter_partition_specification reorganize partition))) start into ( partition past values less than ( 0 ) ))
05:44:59,169 ERROR SchemaChange - Error parsing SQL: '/* ApplicationName=DataGrip 2021.2.4 */ alter table test_table
reorganize partition start into(
    partition past values less than (0)
    )'
05:44:59,170 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[9114eabd-8297-11eb-a9bf-00259086a1b0:1-70498221,9cb20ac2-18c5-11e9-8cab-002590c93b84:1-2491796028], lastHeartbeat=1635591877299]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: start
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
05:44:59,279 INFO  BinlogConnectorReplicator - Binlog disconnected.
05:44:59,285 INFO  TaskManager - Stopping 4 tasks
05:44:59,285 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: start
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.33.1.jar:1.33.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17) ~[antlr4-runtime-4.8-1.jar:4.8-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.33.1.jar:1.33.1]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.33.1.jar:1.33.1]
05:44:59,296 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@eccf2e3
05:44:59,296 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@3c586148
05:44:59,297 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@3d96790c
05:44:59,297 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@8a302f8
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: start
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:330)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:352)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:656)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
05:44:59,332 INFO  AbstractConnector - Stopped ServerConnector@584a5e62{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
05:44:59,334 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@48cc4d47{/,null,STOPPED}
05:44:59,637 INFO  TaskManager - Stopped all tasks`

**Expected behavior:**
`08:08:21,060 INFO  Server - Started @4504ms
08:08:31,372 INFO  LogInputStreamReader - [2021-11-01 08:08:31.371544] [0x00000047][0x00007fcb9ad4d700] [info] [kinesis_producer.cc:200] Created pipeline for stream "test-stream"
08:08:31,372 INFO  LogInputStreamReader - [2021-11-01 08:08:31.371656] [0x00000047][0x00007fcb9ad4d700] [info] [shard_map.cc:87] Updating shard map for stream "test-stream"
08:08:31,522 INFO  LogInputStreamReader - [2021-11-01 08:08:31.522724] [0x00000047][0x00007fcb96543700] [info] [shard_map.cc:148] Successfully updated shard map for stream "test-stream" found 16 shards
08:08:46,372 INFO  LogInputStreamReader - [2021-11-01 08:08:46.371931] [0x00000047][0x00007fcb96d44700] [info] [processing_statistics_logger.cc:111] Stage 1 Triggers: { stream: 'test-stream', manual: 0, count: 0, size: 313, matches: 0, timed: 17, UserRecords: 26778, KinesisRecords: 330 }
08:08:46,373 INFO  LogInputStreamReader - [2021-11-01 08:08:46.371997] [0x00000047][0x00007fcb96d44700] [info] [processing_statistics_logger.cc:114] Stage 2 Triggers: { stream: 'test-stream', manual: 0, count: 0, size: 0, matches: 2, timed: 140, KinesisRecords: 265, PutRecords: 142 }
08:08:46,373 INFO  LogInputStreamReader - [2021-11-01 08:08:46.372013] [0x00000047][0x00007fcb96d44700] [info] [processing_statistics_logger.cc:129] (test-stream) Average Processing Time: 112.04286 ms`

**Environment:**
*Docker image zendesk/maxwell:v1.34.1e
*Docker version 17.03.3-ce, build e19b718
*CentOS Linux release 7.7.1908 (Core)
*MySQL Server version: 5.7.35-38-log Percona Server (GPL), Release 38, Revision 3692a61

**Maxwell server configuration:**
  MAXWELL_PRODUCER: kinesis
  MAXWELL_OPTIONS: --env_config_prefix=MAXWELL_
  MAXWELL_CLIENT_ID: maxwell_test
  MAXWELL_GTID_MODE: true
  MAXWELL_REPLICA_SERVER_ID: "1234"
  MAXWELL_RECAPTURE_SCHEMA: true
  MAXWELL_KINESIS_STREAM: test-stream
  MAXWELL_METRICS_TYPE: http
  MAXWELL_METRICS_JVM: true
  MAXWELL_HTTP_PORT: 8080
  MAXWELL_JDBC_OPTIONS: serverTimezone=UTC

**Comment by osheroff** [comment]
fixed in 1.35.0
