### ISSUE TITLE
Maxwell stuck (or in an infinite loop) if binlog file no more exists (live purge)

### ISSUE THREAD

**Issue by ypereirareis** [zendesk/maxwell#1766]
Hello !

I'm using maxwell with a database I have no administration privilege on.
Just using a "replication" user given by the database administrator and I don't really know what is the origin of my problem and all oprations they do on this database.

* Using maxwell from the official docker image
* Maxwell version 1.33.0

## The problem

* No message received in our rabbitmq dedicated queue.
* No errors in maxwell logs, everything seems to be OK.
* Maxwell binlog file and position seems to be stuck.

## Problem analysis

* Maxwell positions

```yaml
# maxwell.positions
-
  server_id: 188
  binlog_file: "mysql-bin.000234"
  binlog_position: 97091002
  client_id: "maxwell"
  last_heartbeat_read: 0
```

* Master binlog

```
SHOW BINARY LOGS;
| ----------------------- | --------------- |
| Log_name            | File_size     |
| ----------------------- | ---------------- |
| mysql-bin.000235 | 104861031 |
| mysql-bin.000236 | 63691127   |
| ------------------------ | --------------- |
```

**It seems that the binlog referenced in maxwell positions table, no more exists on the master.**
Maybe because of a hot binlog purge, but I don't really know.

## Workaround

* I tried to restart maxwell but in that case I had the following error.

```
Using kafka version: 1.0.0
Warning: Nashorn engine is planned to be removed from a future JDK release
14:53:21,983 WARN  BinlogConnectorReplicator - communications failure in binlog:
com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
    at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:937) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) [mysql-binlog-connector-java-0.24.0.jar:0.24.0]
    at java.lang.Thread.run(Thread.java:834) [?:?]
14:53:22,089 ERROR TaskManager - cause: 
com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
    at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:937) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
    at java.lang.Thread.run(Thread.java:834) [?:?]
14:53:22,099 ERROR Maxwell - Maxwell couldn't find the requested binlog, exiting...
```

* So I UPDATED maxwell binlog file to the next one `mysql-bin.000235` and position to 0. After that, everything started to work properly again.

# My question/problem is

Why is maxwell not throwing and error when a live binlog purge is done or more globally when maxwell no more has access to the current binary file ?

Thanks for your great work !!!!

**Comment by ypereirareis** [comment]
Hi !!

Maybe this information is important : Maxwell database (positions,...) is stored in a different mysql server than server the analyzed database is on.

Thanks !

**Comment by osheroff** [comment]
do you have logs from when maxwell got stuck?  It didn't log anything?

**Comment by ypereirareis** [comment]
Hi @osheroff !

No it didn't log anything, just as if everything was fine.
The only clue I had to say there was a problem is that I had no more message from maxwell in rabbitmq

**Comment by wanghangyu817** [comment]
> 嗨@osheroff！
> 
> 不，它没有记录任何东西，就好像一切都很好。 我不得不说有问题的唯一线索是我在rabbitmq中没有来自maxwell的消息



> Hi @osheroff !
> 
> No it didn't log anything, just as if everything was fine. The only clue I had to say there was a problem is that I had no more message from maxwell in rabbitmq

I repeated this problem in PolarDB-x, my downstream is Kafka, there is no new data in Kafka topic, I found the data in Kafka is incomplete (Figure 1)
I found the problem and restarted Maxwell...
Appear in log <[WARN] MaxwellContext: Timed out waiting for heartbeat 1639652202661>
maybe something went wrong at this point, but there was no exception in the log at all times  
--maxwell version:1.35.0
![d0adc61aef83d1c2b2941833f881bd2](https://user-images.githubusercontent.com/18672877/146373964-8f05269d-f437-4e29-861c-186db4ade1ac.png)

**Comment by wanghangyu817** [comment]
@osheroff 
I repeated this problem in the production environment. When the Maxwell process was jammed, I found that maxwell was reading mysql's binlog and was stuck in socket Read. For some reason, mysql was turning off or stopping binlog. If the Server error code(1236 or 1227) is not sent, the Maxwell process will remain in the read state. Perhaps we should do something when a non-standard error occurs
