### ISSUE TITLE
TableCache.class unable to process dropped tables

### ISSUE THREAD

**Issue by 16beer** [zendesk/maxwell#1778]
10:30:40,540 ERROR TaskManager - cause: 
java.lang.RuntimeException: Couldn't find table dicom_withdraw in database mirs
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:31) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:521) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:645) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) ~[classes/:?]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[classes/:?]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255) ~[classes/:?]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[classes/:?]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[classes/:?]

**Comment by perminov** [comment]
The scenario that i've experienced that problem was the following:
1. start maxwell for the first time (first time mean maxwell-database has not been created so far by maxwell)
2. do CREATE TABLE
3. do INSERT INTO that table => no problem
4. stop maxwell
5. start maxwell
6. do additional INSERT INTO that table => problem

The solution that helped me was to 
1. run the following sql queries before re-start maxwell
    `TRUNCATE maxwell.columns; TRUNCATE maxwell.databases; TRUNCATE maxwell.tables; TRUNCATE maxwell.schemas;`
3. re-start maxwell should be with `--recapture_schema true` arg
