### ISSUE TITLE
Maxwel Crashing when Altering table with ADD INDEX  specified by Order

### ISSUE THREAD

**Issue by danfiza** [zendesk/maxwell#178]
It looks like Maxwell is crashing when I ALTER a table with an ADD INDEX clause specified with an ORDER.

Ex:

ALTER TABLE `test` 
ADD COLUMN `test_col` ENUM('Y', 'N') NULL DEFAULT 'N',
ADD INDEX `test_col` (`test_col_index` ASC);

Results in an error stack like the below:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: ASC
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:85)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:67)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:273)
	at com.zendesk.maxwell.MaxwellReplicator.getEvent(MaxwellReplicator.java:253)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
16:59:24,374 INFO  SchemaPosition - Storing final position

**Comment by osheroff** [comment]
k.  I will look at this soon.

**Comment by osheroff** [comment]
fixed by https://github.com/zendesk/maxwell/pull/180

**Comment by danfiza** [comment]
Appreciate the quick work!
