### ISSUE TITLE
SQLException: Communications link failure after upgrade to v1.34+

### ISSUE THREAD

**Issue by jessedobbelaere** [zendesk/maxwell#1785]
I tried upgrading my Maxwell instance to the latest version (v1.35.1) because of the Log4j CVE. 
**I'm currently on v1.33.1, and I tried to upgrade to v1.34.x and then v1.35.1.**

When I bump to v1.34.x (`v1.34.2-pre3` is the [only tag I can find in docker hub](https://hub.docker.com/r/zendesk/maxwell/tags?page=1)) or latest version on Docker Hub ([v1.35.1](https://hub.docker.com/layers/zendesk/maxwell/v1.35.1/images/sha256-89035b8fe1dd769792f2c5577e1870624e6fea3b8d3749b3c9ff7044f2e2d689?context=explore)) I immediately get a SQLException.

This is the container output with loglevel set to `debug` but it doesn't tell me much:

```
Warning: Nashorn engine is planned to be removed from a future JDK release
17:51:39,485 INFO  Scripting - using function process_row from /etc/config/maxwell-filter.js
17:51:39,495 INFO  MaxwellMetrics - JMX metrics reporter enabled
17:51:39,495 WARN  MaxwellMetrics - JMX remote is disabled
17:51:39,497 INFO  MaxwellMetrics - Enabling UDP Datadog reporting with host datadog-agent.datadog.svc.cluster.local, port 8125
17:51:39,534 INFO  MaxwellMetrics - Datadog reporting enabled
17:51:40,912 ERROR Maxwell - SQLException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

I use an AWS Aurora MySQL (which is **MySQL 5.7.12**) for the maxwell internal DB, and the same for the replica server that Maxwell reads binlogs from. The MySQL DB has `--schema_ssl=REQUIRED` and `--ssl=REQUIRED` enabled in the Maxwell configuration. 

Any way I can debug that communications link failure further (it's already on loglevel=debug)? 
When I go back to `v1.33.1` it immediately boots up again, while with `v1.34.x` or `v1.35.x` it immediately crashes on startup. We haven't modified the Maxwell config since the last few versions. 

Since it started breaking in >v1.33, I'm thinking of a bug or incompatibility in the last two Maxwell versions?

edit: It still runs fine on docker hub tag `v1.34.1e` and `v1.34.2-pre` but it starts failing on docker tag `v1.34.2-pre3` and newer. https://hub.docker.com/r/zendesk/maxwell/tags?page=1&name=1.34
So the diff would be: https://github.com/zendesk/maxwell/compare/v1.34.2-pre...v1.34.2-pre3

**Comment by osheroff** [comment]
my wild-ass guess is that something in the docker environment changed and caused ssl verification to start failing. 

This is an out-there guess.  I've released 1.35.2 which should hopefully show you more context with that error, let me know what you find.

**Comment by jessedobbelaere** [comment]
Thanks for the quick action @osheroff ! And you're right about the SSL verification

I ran this container image and I get:

```
Warning: Nashorn engine is planned to be removed from a future JDK release
23:30:08,428 INFO  Scripting - using function process_row from /etc/config/maxwell-filter.js
23:30:08,441 INFO  MaxwellMetrics - JMX metrics reporter enabled
23:30:08,441 WARN  MaxwellMetrics - JMX remote is disabled
23:30:08,443 INFO  MaxwellMetrics - Enabling UDP Datadog reporting with host datadog-agent.datadog.svc.cluster.local, port 8125
23:30:08,468 INFO  MaxwellMetrics - Datadog reporting enabled
23:30:09,866 ERROR Maxwell - SQLException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696) ~[mchange-commons-java-0.2.19.jar:0.2.19]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:340) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:777) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:486) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:947) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 12 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170) ~[?:?]
	at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103) ~[?:?]
	at sun.security.ssl.TransportContext.kickstart(TransportContext.java:221) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421) ~[?:?]
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:316) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:331) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:777) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:486) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:947) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 12 more
```

So I compared both `v1.33.1` and `v1.35.2`:

* In `v1.33.1` maxwell used base image `maven:3.6-jdk-11` which has the following line in `$JAVA_HOME/conf/security/java.security`

```
# https://github.com/zendesk/maxwell/blob/a7260204240be663dac35a122c27ac39bb6b7d9e/Dockerfile#L1
jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, \
    EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
```

* In `v1.35.2` maxwell uses `openjdk:11-jdk-slim` 

```
# https://github.com/zendesk/maxwell/blob/master/Dockerfile#L22
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
```

**So tl;dr TLSv1 and TLSv1.1 got disabled.** 

However our Maxwell DB is using a `5.7.mysql_aurora.2.04.9` with parameter `tls_version=TLSv1, TLSv1.1, TLSv1.2` and TLS v1.2 is supported for Aurora 2 according to [the docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Security.html#AuroraMySQL.Security.SSL.TLS_Version)

Probably overwriting `$JAVA_HOME/conf/security/java.security` and removing TLSv1.1 from the disabled protocols on my setup will make it work again but I'll dig a bit further why TLS v1.2 is not being used. 

Thanks for the help! I think we can close this issue. I'll post an update what the issue was with TLS v1.2 and if we got it working.

**Comment by jessedobbelaere** [comment]
Ok found the issue 🎉; our Maxwell DB connection was using TLSv1.2, but the schema capturing (same as the replication DB, AWS Aurora) was to be still using TLSv1.1. 

And OpenJDK 11 disabled TLS 1.0 and 1.1 by default.  
I found out after adding `-Djavax.net.debug=ssl:handshake` and grepping the logs on `TLS` keyword, that some handshakes were still using TLS v1.1.

I fixed it by forcing TLSv1.2 on all 3 connections via the JDBC options:

```yaml
...
"--ssl=VERIFY_IDENTITY",
"--jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&enabledTLSProtocols=TLSv1.2",

"--schema_ssl=VERIFY_IDENTITY",
"--schema_jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&enabledTLSProtocols=TLSv1.2",

"--replication_ssl=VERIFY_IDENTITY",
"--replication_jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&enabledTLSProtocols=TLSv1.2",
```

Works like a charm now on the latest Maxwell version!

**Comment by osheroff** [comment]
glad your issue is fixed!  lemme re-open this issue, I feel like others shouldn't have to go through what you went through; maybe we should add `enabledTLSProtocols=1.2` by default given that the JDK we run on no longer supports them, or maybe simply revving connector-j will help something here.

**Comment by osheroff** [comment]
Meh, I couldn't reproduce the issue mentioned here.  I'll leave this open in case someone else finds it helpful.
