### ISSUE TITLE
Maxwell sometimes fails to create RabbitMQ producer

### ISSUE THREAD

**Issue by aaayun** [zendesk/maxwell#1798]
The Maxwell in my project sometimes fails to create RabbitMQ producer and it displays the following error message.

06:13:09,960 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
06:13:15,257 WARN  ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Socket closed)
06:13:15,261 INFO  TaskManager - Stopping 0 tasks
06:13:15,261 ERROR TaskManager - cause: 
java.lang.RuntimeException: java.util.concurrent.TimeoutException
      at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:38) ~[maxwell-1.23.2.jar:1.23.2]
      at com.zendesk.maxwell.MaxwellContext.getProducer(MaxwellContext.java:348) ~[maxwell-1.23.2.jar:1.23.2]
      at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:186) ~[maxwell-1.23.2.jar:1.23.2]
      at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.23.2.jar:1.23.2]
      at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244) ~[maxwell-1.23.2.jar:1.23.2]
Caused by: java.util.concurrent.TimeoutException
      at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:443) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:321) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:63) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:177) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1150) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1109) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1224) ~[amqp-client-4.8.3.jar:4.8.3]
      at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:33) ~[maxwell-1.23.2.jar:1.23.2]
      ... 4 more
06:13:15,272 INFO  TaskManager - Stopped all tasks
06:13:15,286 DEBUG MaxwellContext - Shutdown complete: true
java.lang.RuntimeException: java.util.concurrent.TimeoutException
      at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:38)
      at com.zendesk.maxwell.MaxwellContext.getProducer(MaxwellContext.java:348)
      at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:186)
      at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
      at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)
Caused by: java.util.concurrent.TimeoutException
      at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
      at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
      at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
      at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:443)
      at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:321)
      at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:63)
      at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:177)
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1150)
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1109)
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
      at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1224)
      at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:33)

I think my config is correct because this error occurs sometimes rather than all the time.
Can someone tell me why and how to resolve it?

**Comment by tadavid-cae** [comment]
@aaayun  did you find the solution? We are struggling with the exact same problem, without any solution

**Comment by osheroff** [comment]
maybe fixed with a longer timeout param in 1.38.0.  maybe not!  reopen if not.
