### ISSUE TITLE
1.35.5 this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by lctlover** [zendesk/maxwell#1807]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/zendesk/maxwell/Maxwell has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

java -version
java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

**Comment by lctlover** [comment]
alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           /app/jdk1.8.0_201/bin/java
*+ 2           /app/jdk-11.0.12/bin/java
   3           /app/jdk1.8.0_144/bin/java

**Comment by lctlover** [comment]
vim /etc/profile
JAVA_HOME=/app/jdk-11.0.12

4119 [WARN] BinlogConnectorReplicator: communications failure in binlog:
com.github.shyiko.mysql.binlog.network.ServerException: log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master; the first event 'mysql-bin.000004' at 684182644, the last event read from 'E:\mysql_data\mysql-bin.000004' at 123, the last byte read from 'E:\mysql_data\mysql-bin.000004' at 684182663.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:944) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
4224 [ERROR] TaskManager: cause: 
com.github.shyiko.mysql.binlog.network.ServerException: log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master; the first event 'mysql-bin.000004' at 684182644, the last event read from 'E:\mysql_data\mysql-bin.000004' at 123, the last byte read from 'E:\mysql_data\mysql-bin.000004' at 684182663.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:944) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
4235 [ERROR] Maxwell: Maxwell couldn't find the requested binlog, exiting...

**Comment by lctlover** [comment]
colse it;
maybe jdk wrong,and 
maxwell commend

**Comment by osheroff** [comment]
sorry, I built 1.35.5 probably with the wrong version of the jdk.  I will rebuild 1.35.6 with jdk11...
