### ISSUE TITLE
ignore_producer_alert not working for network_exception producer error.

### ISSUE THREAD

**Issue by xsfa** [zendesk/maxwell#1821]
I have set ignore_producer_alert to false in my config but when a network_exception is thrown in the Kafka producer, the context fails to terminate and instead waits for a TimeoutException. Could this have something to do with network_exception not being recognized as a producer error?

**Comment by osheroff** [comment]
send a stack trace, there's definitely exceptions that happen inside the kafka producer that never make it to the maxwell layer.

**Comment by xsfa** [comment]
```
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:50) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466) ~[?:?]
        at org.apache.kafka.common.network.SslTransportLayer.flush(SslTransportLayer.java:212) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:170) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:703) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:61) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.doClose(Selector.java:717) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.close(Selector.java:708) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:500) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:398) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by osheroff** [comment]
yeah so unfortunately maxwell simply doesn't receive these exceptions -- as you can see by the stack trace they're started by kafka and never actually bubble up to the maxwell layer.

**Comment by xsfa** [comment]
Interesting. Do you have any idea on where I could start for figuring out
how to let this exception bubble up?
