### ISSUE TITLE
com.zendesk.maxwell.MaxwellCompatibilityError: variable read_only must be set off

### ISSUE THREAD

**Issue by chengcxy** [zendesk/maxwell#1828]
01:10:24,319 ERROR TaskManager - cause:
com.zendesk.maxwell.MaxwellCompatibilityError: variable read_only must be set to 'OFF'
	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureVariableState(MaxwellMysqlStatus.java:42) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureMaxwellMysqlState(MaxwellMysqlStatus.java:77) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:193) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:175) ~[maxwell-1.27.1.jar:1.27.1]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:269) ~[maxwell-1.27.1.jar:1.27.1]
01:10:24,331 INFO  TaskManager - Stopped all tasks

**Comment by chengcxy** [comment]
sorry,it's mysql.conf set error
