### ISSUE TITLE
 Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#183]
I am testing Maxwell.
I am getting following error when started maxwell today. is there a way to fix this if my binary log files are rotated/deleted? 

```
12:04:14,048 INFO  AuthenticatorImpl - start to login, user: maxwell, host: localhost, port: 3306
12:04:14,051 INFO  AuthenticatorImpl - login successfully, user: maxwell, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
com.google.code.or.net.TransportException: Could not find first log file name in binary log index file
        at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:288)
        at com.google.code.or.OpenReplicator.start(OpenReplicator.java:104)
        at com.zendesk.maxwell.MaxwellReplicator.beforeStart(MaxwellReplicator.java:83)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:25)
        at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
12:04:14,079 INFO  SchemaPosition - Storing final position: null
```

**Comment by osheroff** [comment]
just do `drop database maxwell` and restart.  Maxwell will pick up from the current master position.

**Comment by xmlking** [comment]
thanks , I will try it.
I didn't had permissions to drop Maxwell database so   I tried to drop Maxwell tables but got error.
```
12:32:33,407 ERROR Maxwell - Table 'maxwell.schemas' doesn't exist
```
it would be nice if we can pass command-line argument to Maxwell to tell to pick up from the current master position.

**Comment by osheroff** [comment]
Yeah, you shouldn't drop the tables without dropping the database; the schema-creation code isn't actually smart enough to detect that case, apparently.  The other proper method for resetting maxwell is just doing `DELETE from maxwell.positions`.

a command line argument is reasonable, yeah.  I'll turn this issue into that.

**Comment by osheroff** [comment]
also we should catch `TransportException` and advise the user that they may reset the master postiion with the flag.

**Comment by jpeyper** [comment]
I also had this problem and was thing that it might be nice to have a setting to have a autoRecover option that would reset the master position if there was an issue (or start reading the next available log file) 

My environments here are setup so that system are deployed automatically in docker containers  and monitored, so knowing something went wrong is easy, but getting on the production dB to drop a column is not (not impossible though) and changing the command line is much harder.

I don't know how Maxwell should handle this, as these issues may be unique to my situation.

**Comment by jpeyper** [comment]
Sorry for the typos, I am on my phone and can't edit comments :(
