### ISSUE TITLE
SSLHandhshakeException with mysql 8.0.28

### ISSUE THREAD

**Issue by sauliusm** [zendesk/maxwell#1844]
Hi,

When trying to connect to mysql 8.0.28 over SSL, SSLHandshakeException exception occurs:

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:356) ~[?:?]
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:202) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.upgradeToSSL(PacketChannel.java:96) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.tryUpgradeToSSL(BinaryLogClient.java:697) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:535) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[mysql-binlog-connector-java-0.24.0.jar:0.24.0]
```

This very likely indicates TLS version mismatch as mysql 8.0.28 dropped support for TLSv1/TLSv1.1. 

I have found that `mysql-binlog-connector-java` uses TLSv1 in the default constructor:

https://github.com/zendesk/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/network/DefaultSSLSocketFactory.java#L33

Did not find where maxwell overwrites it, thus the SSLHandshakeException?

**Comment by osheroff** [comment]
you're looking at the wrong repo for mysql-binlog-connector-java.  you want to look here: 
https://github.com/osheroff/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/network/DefaultSSLSocketFactory.java

which has long since defaulted to v1.2.

What version of maxwell are you on?
