### ISSUE TITLE
Event deserialization failure. arraycopy: length -1 is negative

### ISSUE THREAD

**Issue by ypereirareis** [zendesk/maxwell#1854]
Hi !

Since a few days or weeks we are having this error logged by maxwell.

```
April 9th 2022, 03:22:20.416    01:22:14,877 WARN  BinlogConnectorReplicator - cause: 
April 9th 2022, 03:22:20.416    01:22:15,010 WARN  BinlogConnectorReplicator - replicator stopped at position: 015e4a08-6f01-11e7-a358-a4bf0117628c:1-299635477,0389c029-6f01-11e7-88dd-14187759a839:1-141748882,072f87e8-a852-11e7-b9da-a4bf0120ac84:1-1556542264,08fee647-0a02-11eb-9824-b42e99d023d8:1-1639,116310fb-4f47-11eb-92e0-0ef39a29fd7a:1-110618226,14bf194c-00e5-11ec-9989-d05099d46b38:8-200504349,34908bf9-fe88-11eb-a8b4-1866da79575c:2-109176050,3a496fe3-f6db-11e6-bbf6-1866da8e4fd8:1-1070433564,3c995bbe-87e7-11ea-8698-0cc47ad99b74:18-17455576,3d73c108-01ac-11ec-b0b0-fc3497b149b8:1-28536,3ea3b06e-f76b-11ea-8c19-b42e99d0153f:1-39381205,41d1bcd5-eee4-11eb-98df-801844ee6048:930-143552820,4367211d-ab70-11e6-ab60-0cc47aa89ffe:1-1084636750,46905466-2cfb-11e8-b54e-a4bf01254166:1-375594091,4ad6ec53-f23b-11e8-869b-44a8421c3eb5:48-372972649,4b3d4e11-ed74-11e8-b293-a4bf012984c9:1-582233165,50440fc2-75df-11e7-ac4f-14187741de2d:1-230415053,561ea54e-0fad-11eb-8cf3-b42e99a86c65:1-42933056,5b877982-ff79-11e6-b0c8-0cc47a828834:1-1011996457,6140c39b-b8a6-11e6-baa4-246e960bc9e4:1-3200659377,639ef847-1bb0-11e8-8c0d-1866da9d66af:1-146,63b6e72e-b4cb-11e6-8080-001e67e085ca:1-1067111003,63d966b5-04d1-11ec-9eac-fc3497b14b4e:18-413195635,65fefd3f-2938-11e9-98ab-14187750805c:720-339000428,681446c1-ab6e-11e6-825a-44a84222d63a:1-699484783,6ac9dd2a-833a-11eb-81d8-d05099dcf6cc:1-15393717,6ec064ef-8bc6-11eb-bdc3-d05099dc296e:17-9909735,6f2dabc8-ab74-11e6-a2e0-c81f66c9b1ab:1-131312907,6f6931cb-1169-11ec-88ac-801844eed71c:198-88536008,70f9c771-b02d-11e6-85ec-0cc47a86395c:1-12335507,71a08ce2-0f02-11ec-9971-fc3497b13407:7-79879555,71b1b2f4-c753-11e6-83d0-c81f66c9b1ab:1-158437926,71c483ea-ab70-11e6-97e5-408d5cdc30df:1-1150454009,728f411d-fa9c-11eb-9702-1866dab2e13a:201-47942531,77d5f325-0f81-11eb-a985-18c04d239ef0:1-217744,78f63009-c23d-11e6-a947-002590d9d560:1-716661285,7ad6f64a-0ca7-11ec-9dcb-fc3497b13563:1-261903:311872-100903229,7cd2e12b-ab70-11e6-9fca-0cc47a6c9820:1-1026960863,8068ff4b-288d-11e9-8f4f-a4bf0124f749:1-1492915,807f7a8c-ab74-11e6-845f-b083fee65ff3:1-862626997,81694e7d-ab70-11e6-aa44-408d5cdc31b9:1-4920397120,83bb2699-8bea-11eb-9e21-d05099dc2166:1-11657186,83d6923d-ab74-11e6-b407-e840f20b24e2:1-521369782,848bbcef-0fe8-11ec-b6c8-fc3497b054c5:1-1275,858ad5aa-e2af-11e8-b312-44a8421c3eb5:1-12,89ea8d12-1a9e-11eb-8e5f-509a4c7f1e5a:431-19479669,8e036e16-0ebe-11eb-8212-d05099dadb2b:1-91437631,972549bd-eb95-11eb-ba50-d05099d24453:1-614691718,98fa25be-ad66-11e9-98fa-c81f66c94b9f:3-35:628-748364265,9a86ba99-839c-11ea-aa4c-0cc47ab3b880:182086-8042125,a10b4a82-f159-11eb-9425-801844eda850:44-31610750,a373a457-0668-11ec-99fb-1866da938c5a:271-108313976,a63b3170-66e6-11eb-824f-d8c49765963f:5-78274758,a792a402-ad02-11e6-8a46-0cc47ab405a2:1-22,a7dad099-aca3-11eb-b380-1866da85d56a:488-13346591,aa42622c-ff61-11e6-90bb-0cc47a828834:1-5,aa663b66-0016-11ec-af51-d05099d22c58:1-43591498,af40c3f2-0f7c-11eb-aec6-d05099db0a4c:1-18408666,afe8e138-005c-11e8-b9c7-a4bf0124f749:1-370,b1e352db-1221-11ec-b311-1866da795968:50-59930968,b9d7bdf2-fc23-11eb-9f1c-1866daa8ff55:54-62502614,bc4d8659-b09b-11ea-8ad5-b42e99d023d8:1-8937330,bec6fe4a-ab70-11e6-a6c1-0cc47aa8a7aa:1-269491097,c310127b-ff4e-11eb-a820-d05099d20a97:10-119451697,c471aa8f-3674-11e9-a5d9-a4bf01233262:1-450293752,c472b7e4-041a-11ec-aae8-fc3497b14a12:29-89449636,ca93cda6-9401-11e8-be0d-0242ac120005:1-154,cb0f7d29-2c33-11e8-9d75-a4bf0124f749:1-773:1473-5375:5741-7570,cba2c2ed-ecb2-11e8-aa37-0cc47ab3b880:1-77036121,cff80a89-a11e-11eb-bb09-d05099db0a4c:1-154506501,d0b60c4b-7484-11e8-9335-0242ac120007:1-2817442,d0be18d3-8c89-11eb-bc36-d05099db0a4c:1-1555,d19c2eba-a80d-11e7-96fe-a4bf0120ac84:1-1,dd16f90f-0be3-11ec-aad4-fc3497b0bfc7:1-22446787,e5a72025-e08c-11eb-be16-d05099d20f85:13-259966947,ea63a0a9-63e7-11e8-a6be-ac1f6b473fd8:1-10:132-173537373,eb30d950-989f-11e7-b536-1866da8e5179:1-366268759,f5d95754-de67-11eb-bcbd-d05099d244b7:1-80519528,f7ca7df8-059a-11ec-b197-1866dab2e5dc:18-63178009,f8d5c866-fb67-11eb-8590-1866da8e5010:1-156718108,f9af2b99-072f-11ec-9b2f-1866da8e4ec0:1-20869,faad1d09-acad-11e6-a7c7-0cc47ada5a76:1-25632671,fedd31f2-ab70-11e6-8369-0cc47a6bd0f4:1-1116602497,8a979e7c-801c-11ec-b622-78ac442b8e18:12-576 -- restarting
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:952) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at java.lang.Thread.run(Thread.java:829) [?:?]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:280) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:305) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:65) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:241) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:262) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at java.lang.System.arraycopy(Native Method) ~[?:?]
April 9th 2022, 03:22:20.414        at java.io.InputStream.skip(InputStream.java:531) ~[?:?]
April 9th 2022, 03:22:20.413    01:22:14,870 WARN  BinlogConnectorReplicator - Event deserialization failure.
April 9th 2022, 03:22:20.413    java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
```

* **Maxwell version** : docer image zendesk/maxwell:v1.37.3
* **Mysql Version** : 5.7.37-log (protocol version 10)

Thanks a lot for your work and your upcoming answer.

**Comment by osheroff** [comment]
man, tough bug report, not a lot to go on... has anything changed in your setup recently?  I assume that maxwell crashes on this error, when it restarts does it keep crashing?  Do all the stack traces look exactly the same?  What JVM version?  I'd love to help and maybe if I was there with a debugger I could but this is pretty unsolvable from its current state...

**Comment by ypereirareis** [comment]
Hi,

A bit more info here, I hope it will give you some more clues to find a solution.

* Nothing has changed in my setup, maybe more transactions and so more binlog to deal with.
* After restart no more errors but positions and binlog file no more changing in database (stale connection).
* jvm 11.0.14.1+1

I switched the log level to INFO instead of WARN and I can give you this :

* Maxwell version

```
Maxwell - Maxwell v1.37.3 is booting (RabbitmqProducer)
```

* JVM info

```
14:48:43,636 INFO  Server - jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 11.0.14.1+1
```

* Scripts

We use some javascript to filter some messages containing BLOB data for instance.

```
14:48:40,831 INFO  Scripting - using function process_row from /config/filter.js
```

**Important**

With INFO log level we had an extra line this night when the same error occured once more.

```
April 12th 2022, 03:20:01.965 | 01:19:54,671 INFO  ListWithDiskBuffer - Overflowed in-memory buffer, spilling over into /tmp/maxwell10313699712581016150events
```

Then the same error than the one in my first message just after ListWithDiskBuffer info message:

```
01:22:21,608 WARN  BinlogConnectorReplicator - Event deserialization failure.
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
```

We activated the "binlog_heartbeat" possibility, and it seems it had an effect: 

* despite the same error it seems that everything is still working and binlog still processed

```


|April 12th 2022, 03:22:26.973 | 01:22:21,928 INFO  BinlogConnectorReplicator - Binlog connected.
  | April 12th 2022, 03:22:26.973 | 01:22:21,928 INFO  BinaryLogClient - Connected to dockerip:3307 at 015e4a08-6f01-11e7-a358-a4bf0117628c:1-299635477,0389c029-6f01-11e7-88dd-14187759a839:1-141748882,072f87e8-a852-11e7-b9da-a4bf0120ac84:1-1556542264 (sid:6380, cid:2744427)
  | April 12th 2022, 03:22:26.972 | 01:22:21,920 WARN  BinlogConnectorReplicator - replicator stopped at position: 015e4a08-6f01-11e7-a358-a4bf0117628c:1-299635477,0389c029-6f01-11e7-88dd-14187759a839:1-141748882,072f87e8-a852-11e7-b9da-a4bf0120ac84:1-1556542264 -- restarting
  | April 12th 2022, 03:22:26.972 | at java.lang.Thread.run(Thread.java:829) [?:?]
  | April 12th 2022, 03:22:26.972 | 01:22:21,920 INFO  BinlogConnectorReplicator - Reconnection attempt: 1 of 1
  | April 12th 2022, 03:22:26.972 | 01:22:21,613 INFO  BinlogConnectorReplicator - Binlog disconnected.
```

Thanks a lot !!!

**Comment by osheroff** [comment]
it took me a lot of head scratching here to realize that your log lines are out of order.  this is the stack trace reconstructed:

```
April 9th 2022, 03:22:20.415        at java.lang.Thread.run(Thread.java:829) [?:?]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:952) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.415        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:305) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:280) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at java.io.InputStream.skip(InputStream.java:531) ~[?:?]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:241) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:262) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:65) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
April 9th 2022, 03:22:20.414        at java.lang.System.arraycopy(Native Method) ~[?:?]
```

**Comment by osheroff** [comment]
> We activated the "binlog_heartbeat" possibility, and it seems it had an effect:

Does it still show the "length -1 is negative" error?  "replication stopped at position" is not a super-abnormal error.

do you have a replica attached to the master?  If so, can you reproduce the problem on the replica? 

How long have you been running 5.7.37?  

The evidence is that we're simply over-reading the buffer by 1 byte, but I have no idea why you're the first person in ~8 years of maxwell to encounter this.

**Comment by ypereirareis** [comment]
Hi !

* Still having the same error "length -1 is negative" error"
* I've been running  5.7.37 for a few weeks, could be corralated maybe.

Could it be related to this ? https://github.com/osheroff/mysql-binlog-connector-java/issues/66

* approximatively 2 min before this error occurs, I have a "Overflowed in-memory buffer" info log:

```
01:20:02,229 INFO  ListWithDiskBuffer - Overflowed in-memory buffer, spilling over into /tmp/maxwell317417271115259574events
```

* Looks like a memory "problem" and some buffer writen to disk

* Regarding this memory log, I updated my config as follow, but still having the error :

```
buffer_memory_usage: 0.35 (runtime  allocated mem is 6G)
binlog_event_queue_size: 3000
``` 

**IMPORTANT !** Always having the error at the same datetime during the night. Gonna check something related to binlog volume or infra kind of things.

Thanks.

**Comment by osheroff** [comment]
> Could it be related to this ? https://github.com/osheroff/mysql-binlog-connector-java/issues/66

yeah.  looks likely.

**Comment by osheroff** [comment]
> Could it be related to this ? https://github.com/osheroff/mysql-binlog-connector-java/issues/66

Having said that, I think this is a sort of bug-on-a-bug; the crash in `arraycopy` is happening because the system has reached EOF unexpectedly.

But hey, let's fix that one and see what it uncovers.

**Comment by ypereirareis** [comment]
Thanks a lot @osheroff.

If you can ping me once a docker image including the fix is ready, it would be very nice.

Good luck !

**Comment by ypereirareis** [comment]
Oh @osheroff  I can give you an extra info.

From the inside of my docker container still running after the error and the BinlogConnectorReplicator has reconnected, I still have a big tmp file named **maxwell317417271115259574events**.

```
01:20:02,229 INFO  ListWithDiskBuffer - Overflowed in-memory buffer, spilling over into /tmp/maxwell317417271115259574events
```
THEN (2 min later)

```
01:22:11,138 WARN  BinlogConnectorReplicator - Event deserialization failure.
     java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
01:22:11,145 INFO  BinlogConnectorReplicator - Binlog disconnected.
01:22:11,239 INFO  BinlogConnectorReplicator - Reconnection attempt: 1 of 1
01:22:11,251 INFO  BinlogConnectorReplicator - Binlog connected.
```

And my container file system this morning at Thu Apr 14 08:59:15 UTC 2022:

```
maxwell@79caa2a049bf:~$ date
Thu Apr 14 08:59:15 UTC 2022

maxwell@79caa2a049bf:~$ ls -alh /tmp
total 1.4G
[...]
-rw-r--r-- 1 maxwell maxwell 1.4G Apr 14 01:20 maxwell317417271115259574events
```

Sorry, I really don't want to spam you, maxwell is doing great things in our infra.

**Comment by osheroff** [comment]
no these are good clues, and do keep bugging me.  my day job isn't maxwell anymore so I have to catch where catch can as far as maintainence goes.

**Comment by osheroff** [comment]
are *all* of the messages preceded by large transactions?

**Comment by ypereirareis** [comment]
hello @osheroff .

> are all of the arraycopy errors preceded by the "overflowed buffer" message?

**YES**

> are all of the messages preceded by large transactions?

**YES**

Maxwell is plugged on a mysql slave in ROW mode config, but the master is in STATEMENT mode config.
And on this master, our partner is doing UPDATE queries on tables with millions of rows.
So on our side we receive millions of updates.


Thanks

**Comment by osheroff** [comment]
ok I released a new version v1.37.5, which fixes the bug in the binlog-replicator.  It may or may not uncover the actual problem, but I'm not sure.  My hope is that this patch will give us a position to go investigate.

**Comment by ypereirareis** [comment]
hi @osheroff.

Sorry I was off for a few days.
I deployed the latest version (1.37.5) yesterday I here are the logs I now have with this version.

```
2022-04-25T15:23:53.643686274Z 15:23:53,643 INFO  Server - Started @3591ms
2022-04-26T01:19:57.945602447Z 01:19:57,945 INFO  ListWithDiskBuffer - Overflowed in-memory buffer, spilling over into /tmp/maxwell12553035551160110144events
2022-04-26T01:21:49.527765325Z 01:21:49,521 WARN  BinlogConnectorReplicator - communications failure in binlog:
2022-04-26T01:21:49.527804061Z com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1650935917000, eventType=EXT_UPDATE_ROWS, serverId=1, headerLength=19, dataLength=507, nextPosition=13389472, flags=0}
2022-04-26T01:21:49.527811293Z 	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527817057Z 	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527822554Z 	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:952) [mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527828125Z 	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527846069Z 	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527851752Z 	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-04-26T01:21:49.527856478Z Caused by: java.io.EOFException: Failed to read remaining 2 of 5 bytes from position 1207312648. Block length: 114. Initial block length: 503.
2022-04-26T01:21:49.527861334Z 	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:115) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527866380Z 	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:105) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527871760Z 	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeDatetimeV2(AbstractRowsEventDataDeserializer.java:361) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527876980Z 	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:183) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527883073Z 	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:143) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527888343Z 	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:72) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527894369Z 	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527899726Z 	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527904415Z 	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303) ~[mysql-binlog-connector-java-0.25.6.jar:0.25.6]
2022-04-26T01:21:49.527909710Z 	... 5 more
2022-04-26T01:21:49.527917675Z 01:21:49,527 INFO  BinlogConnectorReplicator - Binlog disconnected.
2022-04-26T01:21:49.624416312Z 01:21:49,624 WARN  BinlogConnectorReplicator - replicator stopped at position: 015e4a08-6f01-11e7-a358-a4bf0117628c:1-299635477,0389c029-6f01-11e7-88dd-14187759a839:1-141748882,072f87e8-a852-11e7-b9da-a4bf0120ac84:1-1556542264,08fee647-0a02-11eb-9824-b42e99d023d8:1-1639,116310fb-4f47-11eb-92e0-0ef39a29fd7a:1-110618226,14bf194c-00e5-11ec-9989-d05099d46b38:8-211900090 -- restarting
2022-04-26T01:21:49.624457999Z 01:21:49,624 INFO  BinlogConnectorReplicator - Reconnection attempt: 1 of 1
2022-04-26T01:21:49.636637710Z 01:21:49,636 INFO  BinaryLogClient - Connected to dockerip:3307 at 015e4a08-6f01-11e7-a358-a4bf0117628c:1-299635477,0389c029-6f01-11e7-88dd-14187759a839:1-141748882,072f87e8-a852-11e7-b9da-a4bf0120ac84:1-1556542264,08fee647-0a02-11eb-9824-b42e99d023d8:1-1639,116310fb-4f47-11eb-92e0-0ef39a29fd7a:1-110618226,14bf194c-00e5-11ec-9989-d05099d46b38:8-211900090 (sid:6380, cid:5316768)
2022-04-26T01:21:49.636712341Z 01:21:49,636 INFO  BinlogConnectorReplicator - Binlog connected.
```

* It seems there is a problem reading events writtten to disk when bufffer memory threshold is reached.

**Comment by osheroff** [comment]
no problem with the delays, like i said maxwell is no longer my day job so i have delays too.

either something is going wrong with one of the rows there (seems kind of unlikely), or the server is dropping maxwell's connection while it's trying to process this huge update.  I suspect it's the latter.  can you check the mysql server for any error logs?  

It also looks like maybe the EOF happens about 100 or so seconds after the initial "buffering" message... I don't know when the actual transaction started processing but maybe there's a timeout variable server-side that's currently set sort of low?  Maybe in the 120-200 second range?  

I can see if I can try to reproduce the issue locally.  how many rows are updated at the same time?  and about how big are the rows?

**Comment by ypereirareis** [comment]
Hi @osheroff 

Indeed it looks like a timeout problem after 120s or so.
But no error logs on mysql at that particular time.

Answers to your questions: 
* between 500 000 and 600 000 rows are updated at the same time.
* each row has a size of 1200 bytes (mean over total rows.)
* Haproxy reverse proxy allows conn to stay up for more than a day. 
* Mysql config for timeouts is

connect_timeout | 10
-- | --
delayed_insert_timeout | 300
have_statement_timeout | YES
innodb_flush_log_at_timeout | 1
innodb_lock_wait_timeout | 1800
innodb_rollback_on_timeout | OFF
interactive_timeout | 86400
lock_wait_timeout | 31536000
net_read_timeout | 30
net_write_timeout | 60
rpl_stop_slave_timeout | 31536000
slave_net_timeout | 60
wait_timeout | 28800



Thanks.

**Comment by osheroff** [comment]
let's try increasing `net_write_timeout`.

**Comment by osheroff** [comment]
I think the other thing we really haven't looked at is:  do the other resources in the system look ok?  not memory or cpu or disk constrained during these events?  I've booted up a huge transaction update scenario on my laptop, nothing seems to obviously trigger -- maxwell buffers events to disk, nothing disconnects.
