### ISSUE TITLE
Renaming a VIEW results in InvalidSchemaError

### ISSUE THREAD

**Issue by chychkan** [zendesk/maxwell#1881]
When renaming a VIEW in MySQL we get the following error in Maxwell logs and the process dies:

```
15:17:06,904 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin-changelog.215273:21584009], lastHeartbeat=1655736438431]
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'view_XXX' in database schema_XXX
	at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55)
	at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:37)
	at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:378)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:400)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:723)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:228)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:301)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:336)
```

The BINLOG event on which this failed was this:
```
mysql-bin-changelog.215273, 21584009, Query, 1874342175, 21584200, use `schema_XXX`; rename table view_XXX to view_YYY
```

Our env:
```
MySQL version: 5.6
Maxwell image version: zendesk/maxwell:v1.37.6
```

In regard to this error:
1. Given Maxwell running in production, what is currently the easiest/fastest way to make Maxwell skip that BINLOG event? I could not find any instructions for this in the documentation, so would be grateful for a pointer if it's there.
2. What would it take to make Maxwell handle the view renaming gracefully? What would be the approach? I'm ready to prepare a PR if needed.

**Comment by v-zmiycharov** [comment]
We have similar issue, when trying to process alter table with encryption and compression. Information on how to skip the BINLOG event will be really useful.

**Comment by udyr-fire** [comment]
init_position=mysql-bin.012698:555734 ?

**Comment by acrois** [comment]
> We have similar issue, when trying to process alter table with encryption and compression. Information on how to skip the BINLOG event will be really useful.

For future reference:

If you are just skipping to the next position, see where it is failing, figure out the new position it should start from, and update it accordingly.

The way I currently deploy maxwell (single instance) makes it more challenging than useful to use `init_position` and just editing the start position in the DB is much easier.

It won't always work. Sometimes, depending on what happened - like 1M records with errors, you could find yourself changing the settings of maxwell to ignore such events. You could even find yourself patching the code or parser definitions.

You can stop maxwell (keep it from restarting), collect the file name and position from the `maxwell` schema `position` table record.

Once you know the name of the file and position:
https://dev.mysql.com/doc/refman/8.0/en/show-binlog-events.html

You can then decide to skip the event, which you will need to advance the `maxwell`.`position` record past the binlog event that is failing. You should set this to the start position of the next record.
