### ISSUE TITLE
Is there a solution to filtering a table with regex patterns 

### ISSUE THREAD

**Issue by Purnachandra66** [zendesk/maxwell#1898]
Is there a solution to filtering a table with regex patterns 
The table starts as follows: db_name._FKSAnnex_new

Because of the above table name in binlog file, race condition issue at maxwell(restarting).

ERROR	2022-08-06 02:33:54,732	22113	com.zendesk.maxwell.schema.AbstractSchemaStore	[main]	Error on bin log position Position[BinlogPosition[mysql-bin.013106:120083157], lastHeartbeat=0]
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table '_FKSAnnex_new' in database abc_db
	at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55)
	at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:37)
	at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:109)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:332)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:629)
	at [com.zendesk.maxwell.replication.BinlogConnectorReplicator.work](http://com.zendesk.maxwell.replication.binlogconnectorreplicator.work/)(BinlogConnectorReplicator.java:179)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:278)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:191)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:355)

**Comment by Purnachandra66** [comment]
Tried adding the filter condition as : .*\.\_.* but didn't work

**Comment by osheroff** [comment]
yes you can use regex patterns in either the database or table specification.  Enclose them in forward slashes.
--filter="include: /db_regex.*/./tbl_regex?[a-z]/'
