### ISSUE TITLE
create database and insert table ,than error: Couldn't find table yong_yin_apply in database contract_test.

### ISSUE THREAD

**Issue by polisomer** [zendesk/maxwell#1899]
java.lang.RuntimeException: Couldn't find table yong_yin_apply in database contract_test
        at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:31) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:586) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:712) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:228) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:301) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.37.6.jar:1.37.6]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:336) ~[maxwell-1.37.6.jar:1.37.6]
15:37:25,971 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@4f0386e8
15:37:25,971 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@366b3657
15:37:25,974 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
15:37:25,980 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@679bcfc6
15:37:25,981 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@396a3ebd
java.lang.RuntimeException: Couldn't find table yong_yin_apply in database contract_test
        at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:31)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:586)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:712)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:228)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:301)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:336)

**Comment by polisomer** [comment]
Then I git clone the latest source code and deployed the local test;
![image](https://user-images.githubusercontent.com/21126573/183239911-c6c5497b-326a-4259-ba8d-a241fa5f3693.png)


The first red box is the blacklist judgment. The newly added library will pass this judgment, and then execute the subsequent code. After the second red box, because there is no permission, the tableNames cannot be obtained, and an error will be reported directly.

 Couldn't find table yong_yin_apply in database contract_test

**Comment by polisomer** [comment]
![image](https://user-images.githubusercontent.com/21126573/183240105-ef5f39fd-68e8-4852-bb89-b18fb7493f96.png)

Adding an include judgment can solve the above problem

**Comment by polisomer** [comment]
I want to submit this code to the branch as a community contributor, but I don't know how to do it ！can you help me?

**Comment by leehand** [comment]
Then I git clone the latest source code and deployed the local test;
![image](https://user-images.githubusercontent.com/44566905/183243269-c783a1ae-6b7e-4175-83bf-e200b0e19fed.png)


The first red box is the blacklist judgment. The newly added library will pass this judgment, and then execute the subsequent code. After the second red box, because there is no permission, the tableNames cannot be obtained, and an error will be reported directly.
Couldn't find table yong_yin_apply in database contract_test

**Comment by leehand** [comment]
![image](https://user-images.githubusercontent.com/44566905/183243337-7bd7c306-60ac-4f3e-b7b8-cf402f2cb095.png)

Add an include judgment can solve the above problem

**Comment by nsveli** [comment]
I am having the exact same error for the same version of Maxwell. **Drop database is not an option**. Every time new row gets inserted into the table the error message appears the maxwell daemon stops. In order to fix it I have to update the record(binlog_file, binlog_position, and gtid_set) for that client_id in the positions table and start the daemon again. This leads to data loss for that not found table. Please Help :)

**Comment by perminov** [comment]
The scenario that i've experienced that problem was the following:
1. start maxwell for the first time (first time mean maxwell-database has not been created so far by maxwell)
2. do CREATE TABLE
3. do INSERT INTO that table => no problem
4. stop maxwell
5. start maxwell
6. do additional INSERT INTO that table => problem

The solution that helped me was to 
1. run the following sql queries before re-start maxwell
    `TRUNCATE maxwell.columns; TRUNCATE maxwell.databases; TRUNCATE maxwell.tables; TRUNCATE maxwell.schemas;`
3. re-start maxwell should be with `--recapture_schema true` arg

**Comment by dalaopo** [comment]
> ![image](https://user-images.githubusercontent.com/44566905/183243337-7bd7c306-60ac-4f3e-b7b8-cf402f2cb095.png)
> 
> Add an include judgment can solve the above problem

Hi！Also works for dealing with table not found issues?
