### ISSUE TITLE
mysql8:8.0.30  maxwell: v1.29.2 show error: unhandled character set 'utf8mb3'

### ISSUE THREAD

**Issue by EdenTian** [zendesk/maxwell#1916]
HI: my enveriment is mysql8:8.0.30  maxwell: v1.29.2    the error show :

java.lang.RuntimeException: error: unhandled character set 'utf8mb3'
        at com.zendesk.maxwell.schema.columndef.StringColumnDef.charsetForCharset(StringColumnDef.java:61)
        at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:75)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:112)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:162)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:176)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:486)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:626)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:178)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:255)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)

but my database use utf8mb4, so  what should i do can resolve the issue

**Comment by osheroff** [comment]
hi, I have a fix for this coming soon

**Comment by osheroff** [comment]
this should be fixed in 1.39.1

**Comment by Arpaaaa** [comment]
hey,I have same trouble, have you solved this issue?

**Comment by osheroff** [comment]
upgrade to 1.39.1 or later
