### ISSUE TITLE
health check endpoint failing in v1.39.0 and v1.39.1

### ISSUE THREAD

**Issue by 29swastik** [zendesk/maxwell#1935]
We have maxwell running on docker in our production and it is configured to listen to changes on MariadDb tables and push them to a kafka topic. Today we have upgraded maxwell version from v1.37.7 to v1.39.0 to get advantages of MariadDb support added in v1.39.0 and to solve the issue [#1931.](https://github.com/zendesk/maxwell/issues/1931). But looks like now `/healthcheck` endpoint is failing.

```
2022-11-02 11:53:59 WARN  HttpChannel - /healthcheck
maxwell    | java.lang.UnsupportedOperationException: Use .getMatched(String) instead
maxwell    | 	at org.eclipse.jetty.http.pathmap.PathMappings.getMatch(PathMappings.java:259) ~[jetty-http-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.servlet.ServletHandler.getMappedServlet(ServletHandler.java:572) ~[jetty-servlet-9.4.41.v20210516.jar:9.4.41.v20210516]
maxwell    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:468) ~[jetty-servlet-9.4.41.v20210516.jar:9.4.41.v20210516]
maxwell    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[jetty-server-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[jetty-io-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407) [jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.10.jar:10.0.10]
maxwell    | 	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by osheroff** [comment]
fixed in latest
