### ISSUE TITLE
NullPointerException at updateStatus on certain transactions

### ISSUE THREAD

**Issue by xsfa** [zendesk/maxwell#1938]
What is the potential cause of this error or what kind of transaction on the database could be yielding this.

Stack Trace:
```
2022-10-31,23:23:11,795 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@3d59c792
java.lang.NullPointerException
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.updateStatus(BinlogConnectorReplicator.java:662)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:610)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:182)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:157)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245)
2022-10-31,23:23:11,796 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@5738367
2022-10-31,23:23:11,802 INFO  AbstractConnector - Stopped ServerConnector@3d138360{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2022-10-31,23:23:11,804 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@51f056e5{/,null,UNAVAILABLE}
```

**Comment by osheroff** [comment]
you appear to be running a copy of maxwell that you've patched yourself -- there's never been an `updateStatus` function in BinlogConnectorReplicator (or in any of maxwell).

And then, when your function breaks, you're asking for support on it.  

sheesh!
