### ISSUE TITLE
can't start two maxwell in one host

### ISSUE THREAD

**Issue by zenoprod** [zendesk/maxwell#1942]
i am very appreciate you read this post,i have some problem when start second maxwell in one host
i want start two instance in one maxwell host, but it can't start the second maxwell ,i have changed server_id and client_id but it still can't start config2.properties maxwell it said 

> Using kafka version: 1.0.0
> 22:12:24,201 INFO  Maxwell - Starting Maxwell. maxMemory: 2289565696 bufferMemoryUsage: 0.25
> 22:12:24,226 INFO  TaskManager - Stopping 0 tasks
> 22:12:24,227 ERROR TaskManager - cause: 
> com.zendesk.maxwell.MaxwellCompatibilityError: server_id is '0'.  Maxwell will not function without a server_id being set.
> 	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureServerIDIsSet(MaxwellMysqlStatus.java:50) ~[maxwell-1.29.2.jar:1.29.2]
> 	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureReplicationMysqlState(MaxwellMysqlStatus.java:68) ~[maxwell-1.29.2.jar:1.29.2]
> 	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:200) ~[maxwell-1.29.2.jar:1.29.2]
> 	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.29.2.jar:1.29.2]
> 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.29.2.jar:1.29.2]
> 22:12:24,231 INFO  TaskManager - Stopped all tasks
> com.zendesk.maxwell.MaxwellCompatibilityError: server_id is '0'.  Maxwell will not function without a server_id being set.
> 	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureServerIDIsSet(MaxwellMysqlStatus.java:50)
> 	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureReplicationMysqlState(MaxwellMysqlStatus.java:68)
> 	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:200)
> 	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
> 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)

**my first configuration is：config.properties ** 

server_id=101
producer=stdout
host=192.168.10.103
user=maxwell
password=maxwell
port=3306

replication_host=192.168.10.102
replication_user=root
replication_password=123321
jdbc_options=useSSL=false&serverTimezone=Asia/Shanghai
client_id=maxwell101

**my second configuration is:config2.properties**

server_id=1012
producer=stdout
host=192.168.10.103
user=maxwell
password=maxwell
port=3306

replication_host=192.168.10.103
replication_user=root
replication_password=123321
jdbc_options=useSSL=false&serverTimezone=Asia/Shanghai

client_id=maxwell102

**Comment by zenoprod** [comment]
i've solve this question, it need to set replicate mysql server-id
