### ISSUE TITLE
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLSyntaxErrorException: Unknown column 'LEVEL' in 'where clause'

### ISSUE THREAD

**Issue by dalaopo** [zendesk/maxwell#1947]
I create a maxwell-1.39.1 to a new mariadb，but reported this error

```
2022-11-25 16:52:44 DEBUG SchemaCapturer - Starting schema capture of 15 databases...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 1/15 Capturing finance_tc...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 2/15 Capturing heimdallr...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 3/15 Capturing maxwell...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 4/15 Capturing members...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 5/15 Capturing meta...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 6/15 Capturing mysql...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 7/15 Capturing percona...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 8/15 Capturing recognize...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 9/15 Capturing recognize_daily...
2022-11-25 16:52:44 DEBUG SchemaCapturer - 10/15 Capturing recognize_test...
2022-11-25 16:52:45 DEBUG SchemaCapturer - 11/15 Capturing sso...
2022-11-25 16:52:45 DEBUG SchemaCapturer - 12/15 Capturing sys...
2022-11-25 16:52:45 DEBUG SchemaCapturer - 13/15 Capturing t8891...
2022-11-25 16:52:45 DEBUG SchemaCapturer - 14/15 Capturing test...
2022-11-25 16:52:45 DEBUG SchemaCapturer - 15/15 Capturing test_db...
2022-11-25 16:52:45 DEBUG SchemaCapturer - 15 database schemas captured!
2022-11-25 16:52:45 DEBUG SchemaCapturer - Capturing Default Charset
2022-11-25 16:52:45 INFO  TaskManager - Stopping 2 tasks
2022-11-25 16:52:45 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLSyntaxErrorException: Unknown column 'LEVEL' in 'where clause'
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:76) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:264) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:337) ~[maxwell-1.39.1.jar:1.39.1]
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'LEVEL' in 'where clause'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.schema.SchemaCapturer.detectMariaDBJSON(SchemaCapturer.java:309) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:141) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:84) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:71) ~[maxwell-1.39.1.jar:1.39.1]
        ... 5 more
2022-11-25 16:52:45 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@639b82d7
```

this is a new slave

**Comment by Myuujinn** [comment]
We had the same issue on our MariaDB cluster, you'll need to upgrade your MariaDB version to 10.5 or greater.

**Comment by dalaopo** [comment]
> 我们在 MariaDB 集群上遇到了同样的问题，您需要将 MariaDB 版本升级到 10.5 或更高版本。

Was the issue resolved when you upgraded，are there any errors in the future?

**Comment by lumixen** [comment]
Same happens for my with `mariadb:10.3.XX` ☝️

**Comment by Myuujinn** [comment]
> > 我们在 MariaDB 集群上遇到了同样的问题，您需要将 MariaDB 版本升级到 10.5 或更高版本。
> 
> Was the issue resolved when you upgraded，are there any errors in the future?

Yes upgrading solves this issue, though MariaDB is not officially supported (yet) by Maxwell so some errors might occur but we haven't seen any crashes on our side 👍

**Comment by lumixen** [comment]
Is there any chance this can be fixed for versions < 5.5? 
It looks like [this was the breaking change](https://github.com/zendesk/maxwell/commit/1121800fe8099ce45e78b614ce81bef088c57a86).

**Comment by dalaopo** [comment]
> > > 我们在MariaDB群上遇到了同样的问题，您需要将MariaDB版本升级到10.5或更高版本。
> > 
> > 
> > 你升级的时候问题解决了吗，以后有没有报错？
> 
> 是的，升级解决了这个问题，尽管管Maxwell尚未正确方式支持MariaDB，因此可能会出现一些错误，但我们还没有看到任何崩溃👍



> > > 我们在MariaDB群上遇到了同样的问题，您需要将MariaDB版本升级到10.5或更高版本。
> > 
> > 
> > 你升级的时候问题解决了吗，以后有没有报错？
> 
> 是的，升级解决了这个问题，尽管管理Maxwell尚未正确方式支持MariaDB，因此可能会出现一些错误，但我们还没有看到任何崩溃👍

thanks

**Comment by dalaopo** [comment]
> 对于< 5.5 的版本，有没有可能修复这个问题？ 看来[这是](https://github.com/zendesk/maxwell/commit/1121800fe8099ce45e78b614ce81bef088c57a86)更大的改动，仅自[MariaDB 10.5.10 后才](https://mariadb.com/kb/en/mariadb-10510-release-notes/)支持列表`LEVEL`。`INFORMATION_SCHEMA.CHECK_CONSTRAINTS`[](https://mariadb.com/kb/en/mariadb-10510-release-notes/)

thanks
