### ISSUE TITLE
An overlooked problem when maxwell bootstrap mysql

### ISSUE THREAD

**Issue by dalaopo** [zendesk/maxwell#1953]
hello!

When I use maxwell to export the mysql data in bootstrap,maxwell returns me an error
```
2022-12-07 10:52:27 ERROR MaxwellContext - exception in thread: maxwell-bootstrap-controller
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311) ~[?:?]
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717) ~[?:?]
        at java.time.LocalDate.of(LocalDate.java:269) ~[?:?]
        at java.time.LocalDateTime.of(LocalDateTime.java:361) ~[?:?]
        at com.mysql.cj.result.LocalDateTimeValueFactory.localCreateFromDatetime(LocalDateTimeValueFactory.java:86) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.result.LocalDateTimeValueFactory.localCreateFromDatetime(LocalDateTimeValueFactory.java:44) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromDatetime(AbstractDateTimeValueFactory.java:104) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDatetime(MysqlTextValueDecoder.java:90) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:86) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.result.ResultSetImpl.getLocalDateTime(ResultSetImpl.java:959) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1282) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:243) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.performBootstrap(SynchronousBootstrapper.java:104) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:49) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.doWork(BootstrapController.java:88) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.bootstrap.BootstrapController.work(BootstrapController.java:70) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.39.1.jar:1.39.1]
        at com.zendesk.maxwell.MaxwellContext.lambda$startTask$0(MaxwellContext.java:350) ~[maxwell-1.39.1.jar:1.39.1]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2022-12-07 10:52:27 INFO  TaskManager - Stopping 4 tasks
```

![e6ff63d2afb50f2b5731aa4598e8931d-23442](https://user-images.githubusercontent.com/48463475/206084063-f9b62a38-dcf0-481b-a2c0-4b4cddda9738.png)

This is the result I returned from querying the database. I am not sure if this is the cause of the error and how should I correct it?

**Comment by dalaopo** [comment]
mysql 10.5.18-MariaDB-log
JVM 11.0.17
Maxwell v1.39.1

**Comment by osheroff** [comment]
sorry, I can't repro locally.  what's your maxwell config and server config?

**Comment by dalaopo** [comment]
> 抱歉，我无法在本地复制。你的 maxwell 配置和服务器配置是什么？
[t8891.zip](https://github.com/zendesk/maxwell/files/10357134/t8891.zip)
This is maxwell config.The server config you mentioned is the server config of mysql?

**Comment by dalaopo** [comment]
> sorry, I can't repro locally. what's your maxwell config and server config?
[config.zip](https://github.com/zendesk/maxwell/files/10357883/config.zip)
This is maxwell config.The server config you mentioned is the server config of mysql?
