### ISSUE TITLE
this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by jayantworld** [zendesk/maxwell#1964]
I have installed maxwell for mariadb CDC, however getting this issue. 

[root@primary-db maxwell-1.39.4]# bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' --producer=stdout
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/zendesk/maxwell/Maxwell has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

We are using below java version
[root@primary-db maxwell-1.39.4]# rpm -qa | grep -i openjdk
java-1.8.0-openjdk-1.8.0.352.b08-2.el7_9.x86_64
java-1.8.0-openjdk-devel-1.8.0.352.b08-2.el7_9.x86_64
java-1.8.0-openjdk-headless-1.8.0.352.b08-2.el7_9.x86_64
[root@primary-db maxwell-1.39.4]#

**Comment by jayantworld** [comment]
upgraded to new java version. issue resolved.

yum install java-11-openjdk-devel
