### ISSUE TITLE
Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by jayantworld** [zendesk/maxwell#1966]
Hi,

I am facing new issue. Can someone guide how to resolve this.

2023-01-13 18:46:06 INFO  AppInfoParser - Kafka version : 1.0.0
2023-01-13 18:46:06 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
2023-01-13 18:46:06 INFO  Maxwell - Maxwell v1.39.4 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mysql-bin.000771:515878495], lastHeartbeat=0]
2023-01-13 18:46:06 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.000771:515878495], lastHeartbeat=0])
2023-01-13 18:46:06 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000771:515878495
2023-01-13 18:46:06 INFO  BinaryLogClient - Connected to 127.0.0.1:3306 at mysql-bin.000771/515878495 (sid:6379, cid:24)
2023-01-13 18:46:06 INFO  BinlogConnectorReplicator - Binlog connected.
2023-01-13 18:46:06 WARN  BinlogConnectorReplicator - communications failure in binlog:
com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
    at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043) [mysql-binlog-connector-java-0.27.4.jar:0.27.4]
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) [mysql-binlog-connector-java-0.27.4.jar:0.27.4]
    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) [mysql-binlog-connector-java-0.27.4.jar:0.27.4]
    at java.lang.Thread.run(Thread.java:829) [?:?]
2023-01-13 18:46:06 INFO  BinlogConnectorReplicator - Binlog disconnected.
2023-01-13 18:46:07 INFO  TaskManager - Stopping 4 tasks
2023-01-13 18:46:07 ERROR TaskManager - cause: 
com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
    at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043) ~[mysql-binlog-connector-java-0.27.4.jar:0.27.4]
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.4.jar:0.27.4]
    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.4.jar:0.27.4]
    at java.lang.Thread.run(Thread.java:829) [?:?]
2023-01-13 18:46:07 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@4c52e2bb
2023-01-13 18:46:07 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@5cebf4a2
2023-01-13 18:46:07 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2023-01-13 18:46:07 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@279b34be
2023-01-13 18:46:07 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@19f08010
2023-01-13 18:46:07 ERROR Maxwell - Maxwell couldn't find the requested binlog, exiting...
2023-01-13 18:46:08 INFO  TaskManager - Stopped all tasks

**Comment by osheroff** [comment]
this means that the last position maxwell was at (`mysql-bin.000771/515878495`) is now missing from your server.  you'll have to drop the maxwell database and restart. 

the logs were rotated while maxwell was stopped -- i advise you implement less agressive log rotation policy or try to keep maxwell running continuously.

**Comment by jayantworld** [comment]
Hi Ben,

We have dropped maxwell database and got new issue below: Please check


`# bin/maxwell --user='xxx' --password='xxxx' --host='x.x.x.x' --producer=kafka --kafka.bootstrap.servers=x.x.x.x:9092 --kafka_topic=ocean-cdc-topic --filter='exclude: *.*, include: prod.hl7_test' --producer_partition_by=column --producer_partition_columns='client_id' --producer_partition_by_fallback='column' --ignore_missing_schema=true --gtid_mode=true
2023-01-16 07:36:21 INFO  Maxwell - Starting Maxwell. maxMemory: 3107979264 bufferMemoryUsage: 0.25
2023-01-16 07:36:21 INFO  SchemaStoreSchema - Creating maxwell database
2023-01-16 07:36:21 INFO  ProducerConfig - ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [x.x.x.x:9092]
	buffer.memory = 33554432
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	enable.idempotence = false
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

2023-01-16 07:36:21 INFO  AppInfoParser - Kafka version : 1.0.0
2023-01-16 07:36:21 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
2023-01-16 07:36:21 INFO  Maxwell - Maxwell v1.39.4 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[0-1-139001647], lastHeartbeat=0]
2023-01-16 07:36:21 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
2023-01-16 07:36:21 INFO  TaskManager - Stopping 2 tasks
2023-01-16 07:36:21 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLException: Index 8 out of bounds for length 7
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:76) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:264) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:337) ~[maxwell-1.39.4.jar:1.39.4]
Caused by: java.sql.SQLException: Index 8 out of bounds for length 7
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:212) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:173) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:133) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:84) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:71) ~[maxwell-1.39.4.jar:1.39.4]
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1691) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1587) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1600) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1654) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1000) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:212) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:173) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:133) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:84) ~[maxwell-1.39.4.jar:1.39.4]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:71) ~[maxwell-1.39.4.jar:1.39.4]
	... 5 more
2023-01-16 07:36:21 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@66cb75b5
2023-01-16 07:36:21 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@22bc7451
2023-01-16 07:36:21 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2023-01-16 07:36:23 INFO  TaskManager - Stopped all tasks
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLException: Index 8 out of bounds for length 7
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:76)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:264)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:337)
Caused by: java.sql.SQLException: Index 8 out of bounds for length 7
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:212)
	at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:173)
	at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:133)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:84)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:71)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1691)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1587)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1600)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1654)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1000)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	... 13 more

`

**Comment by miaokela** [comment]
So do I need to delete the Maxwell metadata database every time I start it? Isn't there a way for Maxwell to automatically update the metadata tables upon startup? This manual approach seems rather inconvenient.
