### ISSUE TITLE
start up error,  java.sql.SQLException: Java heap space

### ISSUE THREAD

**Issue by UniqueDavidQian** [zendesk/maxwell#2006]
when I start maxwell v1.29.2 using jdk 1.8 with command line like : 
```
bin/maxwell --user='root' --password='xxxx' --host='127.0.0.1' --producer=stdout --filter='exclude: *.*, include: my_db.my_table'
``` 
startup results like : 
```
15:40:57,282 INFO  Maxwell - Starting Maxwell. maxMemory: 1823473664 bufferMemoryUsage: 0.25
15:40:57,341 INFO  Maxwell - Maxwell v1.29.2 is booting (StdoutProducer), starting at Position[BinlogPosition[mysql-bin.000364:208331986], lastHeartbeat=1683511826766]
15:40:58,207 INFO  MysqlSavedSchema - Restoring schema id 12574934 (last modified at Position[BinlogPosition[mysql-bin.000364:164655916], lastHeartbeat=1683509756412])
15:41:10,244 INFO  TaskManager - Stopping 1 tasks
15:41:10,245 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLException: Java heap space
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:76) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:220) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.29.2.jar:1.29.2]
Caused by: java.sql.SQLException: Java heap space
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.17.jar:8.0.17]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.schema.MysqlSavedSchema.buildSchemaMap(MysqlSavedSchema.java:338) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreDerivedSchema(MysqlSavedSchema.java:373) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreFromSchemaID(MysqlSavedSchema.java:409) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restore(MysqlSavedSchema.java:307) ~[maxwell-1.29.2.jar:1.29.2]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:68) ~[maxwell-1.29.2.jar:1.29.2]
        ... 5 more
15:41:10,250 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@62b2707e
15:41:10,360 INFO  TaskManager - Stopped all tasks
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLException: Java heap space
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:76)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:220)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
Caused by: java.sql.SQLException: Java heap space
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.buildSchemaMap(MysqlSavedSchema.java:338)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreDerivedSchema(MysqlSavedSchema.java:373)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreFromSchemaID(MysqlSavedSchema.java:409)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restore(MysqlSavedSchema.java:307)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:68)
        ... 5 more
```
What should I do to fix it ? Please help, thanks.

**Comment by osheroff** [comment]
how much memory do you have your jvm configured to use?  how big is your database in number of tables?
