### ISSUE TITLE
server_uuid/server_id is repeated

### ISSUE THREAD

**Issue by wanghangyu817** [zendesk/maxwell#2012]
Error message
```
1951927 [ERROR] TaskManager: cause:
com.github.shyiko.mysql.binlog.network.ServerException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.003671' at 84648327, the last event read from '../log/mysql-bin
.003671' at 156275922, the last byte read from '../log/mysql-bin.003671' at 156275922.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:944) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
        at java.lang.Thread.run(Thread.java:830) [?:?]
1951933 [ERROR] Maxwell: Maxwell couldn't find the requested binlog, exiting...
```
I tried to increase `--replica_server_id=9223372036854775`, but this did not solve the problem
I suspect that the value of `MASTER_HEARTBEAT_PERIOD` should be half of `slave_net_timeout`, but I'm not sure if I'm right.

https://dev.mysql.com/doc/refman/5.7/en/change-master-to.html

**Comment by Kur1ko** [comment]
There's a config.md in home directory. 

e.g.
#### Multiple Maxwell Instances

Maxwell can operate with multiple instances running against a single master, in
different configurations.  This can be useful if you wish to have producers
running in different configurations, for example producing different groups of
tables to different topics.  Each instance of Maxwell must be configured with a
unique `client_id`, in order to store unique binlog positions.

With MySQL 5.5 and below, each replicator (be it mysql, maxwell, whatever) must
also be configured with a unique `replica_server_id`.  This is a 32-bit integer
that corresponds to mysql's `server_id` parameter.  The value you configure
should be unique across all mysql and maxwell instances.

try **client_id** if your mysql version upper than 5.5.

**Comment by wanghangyu817** [comment]
This is probably not a clientid issue. My maxwell processes are all configured with unique clientid and replicaserverid. As I said, the default MASTER_HEARTBEAT_PERIOD and slave_net_timeout configurations can be the cause of this problem

**Comment by Kur1ko** [comment]
> This is probably not a clientid issue. My maxwell processes are all configured with unique clientid and replicaserverid. As I said, the default MASTER_HEARTBEAT_PERIOD and slave_net_timeout configurations can be the cause of this problem

I'm working with version v1.27.1, it works well. I'd see further if this error occur.

**Comment by Kevin-Ben** [comment]
我也遇到了同样的问题。

**Comment by Kevin-Ben** [comment]
slave_net_timeout | 60，MASTER_HEARTBEAT_PERIOD  Not Found @wanghangyu817
