### ISSUE TITLE
Support parsing CHECK( ... ) in CREATE TABLE

### ISSUE THREAD

**Issue by dingguitao** [zendesk/maxwell#203]
15:59:29,552 ERROR MysqlParserListener - (data_type ( valid IN ( 0)
15:59:29,553 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE `xxx` (
	id INTEGER NOT NULL AUTO_INCREMENT,
	...,
	valid BOOL,
        ...,
	PRIMARY KEY (id),
	CHECK (valid IN (0, 1))
)'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: (
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:88)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:74)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:288)
	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:268)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:91)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:97)
15:59:29,562 INFO  SchemaPosition - Storing final position: null

**Comment by osheroff** [comment]
yeah, this is an issue, although not entirely trivial to fix.  Will have to think about the best approach.  Just FYI, the `CHECK()` statement in mysql, while supported syntactically, does absolutely nothing.
