### ISSUE TITLE
the maxwell cannot start 

### ISSUE THREAD

**Issue by laokan** [zendesk/maxwell#2032]
version 1.40.2

db mariadb10.4

```
2023-07-27 11:01:40 ERROR Maxwell - Maxwell saw an exception and is exiting...
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLException: Index 8 out of bounds for length 7
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:76) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:264) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:337) [maxwell-1.40.1.jar:1.40.1]
Caused by: java.sql.SQLException: Index 8 out of bounds for length 7
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:212) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:173) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:133) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:84) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:71) ~[maxwell-1.40.1.jar:1.40.1]
        ... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
        at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1691) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1587) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1600) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1654) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1000) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[c3p0-0.9.5.5.jar:0.9.5.5]
        at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:212) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:173) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:133) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.captureAndSaveSchema(MysqlSchemaStore.java:84) ~[maxwell-1.40.1.jar:1.40.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:71) ~[maxwell-1.40.1.jar:1.40.1]

```

**Comment by osheroff** [comment]
this occurs with older versions of  mariadb.  if you can, upgrade maria
