### ISSUE TITLE
linux/arm64 docker image getting amd64 library problem

### ISSUE THREAD

**Issue by fvargasj** [zendesk/maxwell#2037]
When starting zendesk/maxwell:latest docker image on an Apple Silicon M1 chip, I am getting the following problem when using the correspondent platform. I even forced, in the docker-compose service definition, the platform to use without success.

```shell
2023-08-22 18:05:09 INFO  KinesisProducer - Restarting native producer process.
2023-08-22 18:05:09 WARN  LogInputStreamReader - qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
2023-08-22 18:05:10 ERROR KinesisProducer - Error in child process
java.lang.RuntimeException: Child process exited with code 255
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:533) [amazon-kinesis-producer-0.14.0.jar:?]
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:509) [amazon-kinesis-producer-0.14.0.jar:?]
	at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:487) [amazon-kinesis-producer-0.14.0.jar:?]
	at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63) [amazon-kinesis-producer-0.14.0.jar:?]
	at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133) [amazon-kinesis-producer-0.14.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The configuration that I am using is the following:

```shell
maxwell:
    image: zendesk/maxwell:latest
    platform: linux/arm64
    ports:
      - "9092:9092"
    working_dir: /app
    volumes:
      - "./docker/config/maxwell/kinesis-producer-library.properties:/app/kinesis-producer-library.properties"
    environment:
      MAXWELL_HOST: my-db
      MAXWELL_USER: root
      MAXWELL_PASSWORD: root
      MAXWELL_JDBC_OPTIONS: characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=false
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      MAXWELL_LOG_LEVEL: INFO
      MAXWELL_METRICS_TYPE: slf4j,http
      MAXWELL_HTTP_PORT: 9092
      MAXWELL_PRODUCER: kinesis
      MAXWELL_KINESIS_STREAM: kinesis-events
      MAXWELL_FILTER: "exclude: *.*, include: maxwell.*, include: docker_db.event.mark_for_delete=0"
    depends_on:
      - my-db
      - localstack
    command: bin/maxwell --env_config_prefix=MAXWELL_
    restart: always
```

I don't know if you found a way of solving this problem.

Thanks!

**Comment by osheroff** [comment]
I pushed an upgrade (to master) the AWS/kinesis java deps that fixes this *particular* issue (the /lib/ld file not found).  I cannot for the life of me figure out a decent localstack+maxwell docker-compose that actually works tho.   Please post it here if you pull one together.

**Comment by fvargasj** [comment]
I got this new error now:

```shell
023-08-28 11:23:17 2023-08-28 09:23:17 ERROR LogInputStreamReader - [2023-08-28 09:23:17.969739] [0x00000042][0x0000ffff8bfff020] [error] [pipeline.h:228] Failed to get StreamARN using STS GetCallerIdentity | Code: InvalidClientTokenId | Message: The security token included in the request is invalid. | Request was: Action=GetCallerIdentity&Version=2011-06-15
2023-08-28 11:23:17 2023-08-28 09:23:17 WARN  LogInputStreamReader - terminate called after throwing an instance of 'boost::wrapexcept<boost::exception_detail::error_info_injector<boost::log::v2s_mt_posix::system_error> >'
2023-08-28 11:23:17 2023-08-28 09:23:17 WARN  LogInputStreamReader -   what():  Failed to set TLS value: Invalid argument
2023-08-28 11:23:19 2023-08-28 09:23:18 ERROR KinesisProducer - Error in child process
2023-08-28 11:23:19 java.lang.RuntimeException: EOF reached during read
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:532) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:504) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.readSome(Daemon.java:553) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.receiveMessage(Daemon.java:243) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.access$500(Daemon.java:61) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon$3.run(Daemon.java:298) [amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-08-28 11:23:19     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-08-28 11:23:19     at java.lang.Thread.run(Thread.java:829) [?:?]
2023-08-28 11:23:19 2023-08-28 09:23:19 INFO  KinesisProducer - Restarting native producer process.
2023-08-28 11:23:19 2023-08-28 09:23:19 ERROR KinesisCallback - RuntimeException @ Position[BinlogPosition[master.000003:1012190], lastHeartbeat=1693214592882] -- docker_db
2023-08-28 11:23:19 2023-08-28 09:23:19 ERROR KinesisCallback - RuntimeException @ Position[BinlogPosition[master.000003:1008085], lastHeartbeat=1693214592882] -- docker_db
2023-08-28 11:23:19 2023-08-28 09:23:19 ERROR KinesisCallback - EOF reached during read
2023-08-28 11:23:19 2023-08-28 09:23:19 ERROR KinesisCallback - EOF reached during read
2023-08-28 11:23:19 2023-08-28 09:23:19 ERROR KinesisCallback - Exception during put
2023-08-28 11:23:19 java.lang.RuntimeException: EOF reached during read
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:532) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:504) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.readSome(Daemon.java:553) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.receiveMessage(Daemon.java:243) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.access$500(Daemon.java:61) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon$3.run(Daemon.java:298) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-08-28 11:23:19     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-08-28 11:23:19     at java.lang.Thread.run(Thread.java:829) [?:?]
2023-08-28 11:23:19 2023-08-28 09:23:19 ERROR KinesisCallback - Exception during put
2023-08-28 11:23:19 java.lang.RuntimeException: EOF reached during read
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:532) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:504) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.readSome(Daemon.java:553) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.receiveMessage(Daemon.java:243) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon.access$500(Daemon.java:61) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at com.amazonaws.services.kinesis.producer.Daemon$3.run(Daemon.java:298) ~[amazon-kinesis-producer-0.15.7.jar:?]
2023-08-28 11:23:19     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-08-28 11:23:19     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-08-28 11:23:19     at java.lang.Thread.run(Thread.java:829) [?:?]
```

This is the details for the docker-compose file that I am using to define a kinesis stream with local stack, a MySql db where Maxwell is connecting to, and, finally, an extra docker image that is going to be in charge of creating the kinesis stream that will be used by the Kinesis producer libraries.

```shell
version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db
    command: mysqld --character-set-server=utf8
    volumes:
      - "./docker/data/db/:/var/lib/mysql"
      - "./docker/config/db/my.cnf:/etc/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_password
    healthcheck:
      test: [ "CMD", "mysql" ,"-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"

  localstack:
    image: localstack/localstack:2.2.0
    container_name: localstack
    ports:
      - "4566:4566"
      - "8090:8090"
    expose:
      - "4566"
    environment:
      - SERVICES=kinesis
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - USE_SSL=false
      - DEFAULT_REGION=eu-west-1
    healthcheck:
      test: [ "CMD", "awslocal", "--no-verify-ssl", "--endpoint-url=http://localhost:4566", "kinesis", "list-streams" ]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  maxwell:
    image: zendesk/maxwell:latest
    container_name: maxwell
    ports:
      - "9092:9092"
    working_dir: /app
    volumes:
      - "./docker/config/maxwell/kinesis-producer-library.properties:/app/kinesis-producer-library.properties"
    environment:
      MAXWELL_HOST: db
      MAXWELL_USER: root
      MAXWELL_PASSWORD: root
      MAXWELL_JDBC_OPTIONS: characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=false
      AWS_ACCESS_KEY_ID: DEV_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: DEV_SECRET_KEY
      AWS_DEFAULT_REGION: eu-west-1
      MAXWELL_LOG_LEVEL: INFO
      MAXWELL_METRICS_TYPE: slf4j,http
      MAXWELL_HTTP_PORT: 9092
      MAXWELL_PRODUCER: kinesis
      MAXWELL_KINESIS_STREAM: event-out
      MAXWELL_FILTER: "exclude: *.*, include: maxwell.*, include: docker_db.event.mark_for_delete=0"
    depends_on:
      - db
      - localstack
    command: bin/maxwell --env_config_prefix=MAXWELL_
    restart: always

  cka-aws-cli:
    image: mesosphere/aws-cli
    platform: linux/x86_64
    entrypoint: sh -c 'aws --no-verify-ssl --endpoint-url=https://localstack:4566 kinesis create-stream --stream-name event-out" --shard-count 1'
    environment:
      AWS_ACCESS_KEY_ID: DEV_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: DEV_SECRET_KEY
      AWS_DEFAULT_REGION: eu-west-1
    depends_on:
      localstack:
        condition: service_healthy
```

The content for the file my.cnf that is present in the volume will be the following.

```shell
# MySQL server config
[mysqld]
socket=/var/run/mysqld/mysql.sock
datadir=/var/lib/mysql
server_id=1
log-bin=master
binlog_format=row
[client]
socket=/var/run/mysqld/mysql.sock
```

And for the file `kinesis-producer-library.properties` will be the following.

```shell
AggregationEnabled=false
AggregationMaxCount=4294967295
AggregationMaxSize=51200
CollectionMaxCount=500
CollectionMaxSize=5242880
ConnectTimeout=6000
KinesisEndpoint=localstack
FailIfThrottled=false
LogLevel=info
MaxConnections=24
MetricsGranularity=shard
MetricsLevel=none
MetricsNamespace=KinesisProducerLibrary
MetricsUploadDelay=60000
MinConnections=1
KinesisPort=4566
RateLimit=150
RecordMaxBufferedTime=100
RecordTtl=30000
Region=eu-west-1
RequestTimeout=6000
VerifyCertificate=false
```
I hope this information helps to find and fix the problem.

Thanks!
