### ISSUE TITLE
Uppercase default table character set causes problems

### ISSUE THREAD

**Issue by aquarapid** [zendesk/maxwell#206]
Ran into this error:

```
java.lang.NullPointerException: charset
  at java.lang.String.<init>(String.java:449)
  at java.lang.String.<init>(String.java:503)
  at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:62)
  at com.zendesk.maxwell.MaxwellAbstractRowsEvent.jsonMaps(MaxwellAbstractRowsEvent.java:203)
  at com.zendesk.maxwell.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:179)
  at com.zendesk.maxwe`ll.MaxwellReplicator.getRow(MaxwellReplicator.java:252)
  at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:87)
  at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
  at com.zendesk.maxwell.Maxwell.run(Maxwell.java:84)
  at com.zendesk.maxwell.Maxwell.main(Maxwell.java:90)
```

In my case, this turned out to be caused by a table where the default character set was capitalized, and this was being propagated into the maxwell schema tables.  Meanwhile StringColumnDef.charsetForEncoding() can only deal with lowercase character set names.

In my case to reproduce (note the uppercase encoding in the results):

```
create table foo (foo1 char(10)) engine=innodb, default charset=LATIN1;


[dev1] root@maxwell > select * from tables where id = 1473\G
*************************** 1. row ***************************
         id: 1473
  schema_id: 6
database_id: 33
       name: foo
   encoding: LATIN1
         pk: 
1 row in set (0.00 sec)

[dev1] root@maxwell > select * from columns where table_id = 1473\G
*************************** 1. row ***************************
         id: 12559
  schema_id: 6
   table_id: 1473
       name: foo1
   encoding: LATIN1
    coltype: char
  is_signed: 0
enum_values: NULL
```

Stopgap solution(s) in my case:
* update maxwell.columns to force all existing schema columns to have lowercase character set name.  This allowed Maxwell to start again.
* Patch charsetForEncoding() to just lowercase the encoding name before operating on it.  The better solution is probably to lowercase encodings as it enters the maxwell schema.

**Comment by osheroff** [comment]
funny that, I had https://github.com/zendesk/maxwell/pull/207/files#diff-b5b7a6cea93e466eeb9d398632a5cc5aL42 lying around in a branch that was me starting to stress maxwell's parser.

**Comment by osheroff** [comment]
fixed in https://github.com/zendesk/maxwell/releases/tag/v0.16.2
