### ISSUE TITLE
Failed to deserialize data of EventHeaderV4

### ISSUE THREAD

**Issue by hongshaoyang** [zendesk/maxwell#2067]
- Maxwell version: v1.23.0
- Mysql version: 5.7

Since a few days we have a lot of errors like this one in our logs :

```
02:06:50,268 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1701306405000, eventType=EXT_UPDATE_ROWS, serverId=10800226, headerLength=19, dataLength=1358131, nextPosition=631661181, flags=0}
    at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.io.EOFException
    at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_222]
    at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_222]
    at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
    ... 5 more
02:06:50,268 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
02:06:50,406 WARN  BinlogConnectorReplicator - replicator stopped at position: 5aaf32aa-bc81-11e8-acdd-42010a50000d:1-42,807e7be2-6130-ee16-655f-c99b53c466f6:1-396747422,8a008e83-bd27-ee17-623e-88435fc1375f:1-276304239,ba9ae991-f49b-11ed-b33c-0242ac120002:1-657755188,d0e8bbff-9cdc-11e9-8cde-42010a500021:1-2134354217 -- restarting
02:06:50,496 INFO  BinaryLogClient - Connected to 10.80.0.226:6333 at 5aaf32aa-bc81-11e8-acdd-42010a50000d:1-42,807e7be2-6130-ee16-655f-c99b53c466f6:1-396747422,8a008e83-bd27-ee17-623e-88435fc1375f:1-276304239,ba9ae991-f49b-11ed-b33c-0242ac120002:1-657755188,d0e8bbff-9cdc-11e9-8cde-42010a500021:1-2134354217 (sid:1082294, cid:152006202)
02:06:50,496 INFO  BinlogConnectorLifecycleListener - Binlog connected.
```

**Comment by hongshaoyang** [comment]
We are using GTID based replication (`gtid_mode=true`) so I cannot find the corresponding binlog event

**Comment by hongshaoyang** [comment]
Marking this as related to #1432

**Comment by osheroff** [comment]
does maxwell resume normally after the error?  I suspect there's a network issue; 

```
Caused by: java.io.EOFException
```

usually means "somehow the network connection got closed".  

It's also possible that your mysql server decided to close the connection.  might check its logs

**Comment by kousinti** [comment]
@hongshaoyang 
Did you fixed this question
I found the same question as this
I checked mysql logs  not found usable logs
