### ISSUE TITLE
Couldn't find chained schema

### ISSUE THREAD

**Issue by xiaomi-box** [zendesk/maxwell#2093]
09:29:26,655 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@7575785e
09:29:26,655 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@376dc617
09:29:26,657 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
09:29:27,878 INFO  TaskManager - Stopped all tasks
java.lang.RuntimeException: Couldn't find chained schema: 240
        at com.zendesk.maxwell.schema.MysqlSavedSchema.buildSchemaChain(MysqlSavedSchema.java:359)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreDerivedSchema(MysqlSavedSchema.java:374)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restoreFromSchemaID(MysqlSavedSchema.java:406)
        at com.zendesk.maxwell.schema.MysqlSavedSchema.restore(MysqlSavedSchema.java:305)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:68)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchemaID(MysqlSchemaStore.java:61)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:220)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:287)

**Comment by xiaomi-box** [comment]
It has happened for 3 consecutive days, and I cannot find the corresponding record in the schema table each time. What should I do

**Comment by xiaomi-box** [comment]
@takeo @nickpad @baxter @zdennis
