### ISSUE TITLE
Maxwell 1.8 does not support Mariadb 10.6 and errored out saying unhandled character set 'utf8mb3'

### ISSUE THREAD

**Issue by PurnaDevi9** [zendesk/maxwell#2126]
Howdy,

My current maxwell version is 1.8 and we upgraded Mariadb from 10.5 to 10.6.19 and we are facing below issue. To which version of maxwell should we upgarde.

2024-Oct-23 10:54:27,767 DEBUG Emailer - Email Body --config=configurations/qa/syncer_config_searchtrends_a.propertiesERROR is :java.lang.RuntimeException: error: unhandled character set 'utf8mb3' at com.zendesk.maxwell.schema.columndef.StringColumnDef.charsetForCharset(StringColumnDef.java:59) at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:74) at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:108) at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:158) at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:187) at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:199) at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:304) at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:164) at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:207) at com.zendesk.maxwell.Maxwell.start(Maxwell.java:157) at com.zendesk.maxwell.Maxwell.main(Maxwell.java:229)

**Comment by PurnaDevi9** [comment]
I found this solution already and will give it a try. Thanks @osheroff
https://github.com/zendesk/maxwell/issues/1839
