### ISSUE TITLE
Maxwell error after deleting "maxwell" database on MySQL 8.0.36 and Maxwell 1.42.0

### ISSUE THREAD

**Issue by marcomoauro** [zendesk/maxwell#2141]
Hi, i get this error when i relaunch maxwell after i drop the “maxwell” database.

MySQL: 8.0.36

Are there other things that need to be deleted to start from scratch?

2024-12-21 08:30:33 INFO  Maxwell - Starting Maxwell. maxMemory: 4194304000 bufferMemoryUsage: 0.25
2024-12-21 08:30:33 INFO  SchemaStoreSchema - Creating maxwell database
2024-12-21 08:30:33 INFO  TaskManager - Stopping 0 tasks
2024-12-21 08:30:33 ERROR TaskManager - cause: 
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LOG STATUS' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:327) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.zendesk.maxwell.replication.BinlogPosition.capture(BinlogPosition.java:49) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.replication.Position.capture(Position.java:27) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.getInitialPosition(Maxwell.java:179) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:259) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:337) ~[maxwell-1.42.0.jar:1.42.0]
2024-12-21 08:30:33 INFO  TaskManager - Stopped all tasks
2024-12-21 08:30:33 ERROR Maxwell - SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LOG STATUS' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LOG STATUS' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:327) ~[c3p0-0.9.5.5.jar:0.9.5.5]
	at com.zendesk.maxwell.replication.BinlogPosition.capture(BinlogPosition.java:49) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.replication.Position.capture(Position.java:27) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.getInitialPosition(Maxwell.java:179) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:259) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.42.0.jar:1.42.0]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:337) [maxwell-1.42.0.jar:1.42.0]

**Comment by osheroff** [comment]
sorry, problem with the latest release.  getting a patch out...

**Comment by osheroff** [comment]
ok fixed in 1.42.1, plz upgrade

**Comment by marcomoauro** [comment]
it works, thank you very much for the timely fix!
