### ISSUE TITLE
mysql json column type support.

### ISSUE THREAD

**Issue by murali-chevuri** [zendesk/maxwell#247]
For mysql json column type application is giving with below error message.

12:38:11,666 INFO  SchemaStore - Creating maxwell database
12:38:12,431 INFO  Maxwell - Maxwell is capturing initial schema
12:38:12,436 DEBUG SchemaStore - Capturing schema
java.lang.IllegalArgumentException: unsupported column type json
    at com.zendesk.maxwell.schema.columndef.ColumnDef.build(ColumnDef.java:75)
    at com.zendesk.maxwell.schema.SchemaCapturer.captureTable(SchemaCapturer.java:124)
    at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:94)
    at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:65)
    at com.zendesk.maxwell.Maxwell.initFirstRun(Maxwell.java:26)
    at com.zendesk.maxwell.Maxwell.run(Maxwell.java:63)
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:102)

**Comment by osheroff** [comment]
Hi, this is part of mysql 5.7 which is currently not supported by maxwell.  At some point in time I'll do the work to get maxwell 5.7 compatible.

**Comment by numtel** [comment]
Hello, I noticed this issue before starting to implement the JSON datatype on the ZongJi Node.js MySQL binlog tailer. I've got it working now. Hope this can be of some help for you.

https://github.com/nevill/zongji/commit/334291684e1d1ffbd86e1a1e206c8acf96f72dd2

**Comment by osheroff** [comment]
initial support in 1.7.0
