### ISSUE TITLE
Error Parsing Collate in Table Create Statement

### ISSUE THREAD

**Issue by danfiza** [zendesk/maxwell#255]
Received the following parse error today on the latest Maxwell Release(1.0.0)

```
14:01:43,455 DEBUG SchemaChange - SQL_PARSE <- "/* THIS SCRIPT CREATES A NEW TABLE TO  LOG UPDATES IN CASE WE NEED TO RUN IT AGAIN. */
CREATE TABLE IF NOT EXISTS `test`.`test_logs` (
	`id` 		INT(11) 	AUTO_INCREMENT PRIMARY KEY, 
	`zip`		VARCHAR(10)	CHARACTER SET `latin1` 		COLLATE `latin1_swedish_ci`	DEFAULT '' 	NOT NULL, 
	`date`		DATE						NOT NULL, 
	`data` 		BLOB						NULL, 
	`created_by`	INT(11) 	DEFAULT 0 			NOT NULL, 
	`created_date` 	DATETIME 	DEFAULT CURRENT_TIMESTAMP	NOT NULL 
) ENGINE = INNODB CHARACTER SET = `latin1` COLLATE = `latin1_swedish_ci`"
14:01:44,074 ERROR MysqlParserListener - (string `latin1_swedish_ci`)
14:01:44,075 ERROR SchemaChange - Error parsing SQL: '/* THIS SCRIPT CREATES A NEW TABLE TO  LOG UPDATES IN CASE WE NEED TO RUN IT AGAIN. */
CREATE TABLE IF NOT EXISTS `test`.`test_logs` (
	`id` 		INT(11) 	AUTO_INCREMENT PRIMARY KEY, 
	`zip`		VARCHAR(10)	CHARACTER SET `latin1` 		COLLATE `latin1_swedish_ci`	DEFAULT '' 	NOT NULL, 
	`date`		DATE						NOT NULL, 
	`data` 		BLOB						NULL, 
	`created_by`	INT(11) 	DEFAULT 0 			NOT NULL, 
	`created_date` 	DATETIME 	DEFAULT CURRENT_TIMESTAMP	NOT NULL 
) ENGINE = INNODB CHARACTER SET = `latin1` COLLATE = `latin1_swedish_ci`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: `latin1_swedish_ci`
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:96)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:72)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:84)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:300)
	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:280)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:101)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:100)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:106)
14:01:44,080 INFO  SchemaPosition - Storing final position: null
```

**Comment by osheroff** [comment]
mysql is just so lenient with how you quote things.  I'll look later today.

**Comment by osheroff** [comment]
fixed in PRE2
