### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by brycesub** [zendesk/maxwell#270]
Receive the following error during bootstrap operations.  Running the bootstrap a second time sometimes succeeds.
```
16:29:07,207 INFO  MaxwellReplicator - bootstrapping started for A.RelAttributes, binlog position is BinlogPosition[mysql-bin.012306:99702090]
java.lang.ArrayIndexOutOfBoundsException: 48
        at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:454)
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2333)
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2248)
        at java.util.Calendar.setTimeInMillis(Calendar.java:1140)
        at java.util.Calendar.setTime(Calendar.java:1106)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:955)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:948)
        at java.text.DateFormat.format(DateFormat.java:336)
        at com.zendesk.maxwell.schema.columndef.DateTimeColumnDef.formatValue(DateTimeColumnDef.java:39)
        at com.zendesk.maxwell.schema.columndef.DateTimeColumnDef.asJSON(DateTimeColumnDef.java:66)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:217)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:60)
        at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper$1.run(AsynchronousBootstrapper.java:70)
        at java.lang.Thread.run(Thread.java:724)
16:33:14,588 INFO  TransportImpl - disconnected from olaxpd-myv60.garmin.com:3306
16:33:14,642 INFO  SchemaPosition - Storing final position: BinlogPosition[mysql-bin.012306:103178588]

```

**Comment by nmaquet** [comment]
@brycesub This has just been fixed in master: https://github.com/zendesk/maxwell/pull/269
