### ISSUE TITLE
ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE .`users`

### ISSUE THREAD

**Issue by nmaquet** [zendesk/maxwell#272]
Maxwell is crashing with the following error today. Restarting it doesn't solve the problem unfortunately.

```
01:55:22,485 ERROR MysqlParserListener - (table_name . `users`)
01:55:22,485 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE .`users`
CHANGE COLUMN `password` `password` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT 'Length 60 for Bcrypt' ,
ADD COLUMN `password_scheme` ENUM('md5','bcrypt') NULL DEFAULT 'md5' AFTER `password`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: .
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:96)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:75)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:87)
        at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:310)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:290)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:101)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
        at com.zendesk.maxwell.Maxwell.run(Maxwell.java:103)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:109)
```

**Comment by osheroff** [comment]
fixed in 1.0.0-RC1
