### ISSUE TITLE
java.io.EOFException error

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#297]
I noticed `EOFException` errors in the `maxwell` logs. 
my Kafka version:     `kafka_2.11-0.9.0.0`
wonder anyone else seeing these errors? 

```
ffectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
11:44:24,999 WARN  Selector - Error in I/O with khost1/10.200.150.1
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62) ~[kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:248) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
11:44:26,140 WARN  Selector - Error in I/O with khost2/10.200.150.2
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62) ~[kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:248) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
12:09:26,432 WARN  Selector - Error in I/O with khost1/10.200.150.1
```

**Comment by nmaquet** [comment]
My understanding is that Kafka 0.8.x keeps consumer connections alive while 0.9.x will close them after some amount of inactivity, forcing consumers to reconnect.

**Comment by osheroff** [comment]
mmm @nmaquet care to cite your sources?   I see 

```
connections.max.idle.ms	600000	Idle connections timeout: the server socket processor threads close the connections that idle more than this.
```

in the kafka docs, but that's the same as 0.8.2. 

@xmlking

**Comment by osheroff** [comment]
@xmlking did you ever figure anything out here?

**Comment by xmlking** [comment]
@osheroff I haven't spend much time debugging this issue. I heard some users had connectivity issues with NiFi using older Kafka client API connecting to Kafka 0.9

**Comment by osheroff** [comment]
without much more to go on, gonna close the issue.  sadly.

**Comment by radek1st** [comment]
I'm hitting the exact same issue now
