### ISSUE TITLE
Duplicate process detection

### ISSUE THREAD

**Issue by MartinAmps** [zendesk/maxwell#358]
Hi!

It seems during restarting maxwell I got stuck in this state:

```
2016-06-06_22:46:04.12516 com.google.code.or.net.TransportException: Client requested master to start replication from impossible position; the first event 'mysql-bin.001154' at 0, the last event read from './mysql-bin.001154' at 4, the last byte read from './mysql-bin.001154' at 4.
2016-06-06_22:46:04.12524 	at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:322)
2016-06-06_22:46:04.12532 	at com.google.code.or.OpenReplicator.start(OpenReplicator.java:111)
2016-06-06_22:46:04.12544 	at com.zendesk.maxwell.MaxwellReplicator.ensureReplicatorThread(MaxwellReplicator.java:92)
2016-06-06_22:46:04.12552 	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:308)
2016-06-06_22:46:04.12558 	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:120)
2016-06-06_22:46:04.12566 	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
2016-06-06_22:46:04.12571 	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:98)
2016-06-06_22:46:04.12576 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:104)
2016-06-06_22:46:04.12687 15:46:04,126 INFO  MysqlPositionStore - Storing final position: null
```

This is running from the master branch.

The schemas table was showing mysql-bin.001154 at position 27940. I tried setting it to this position, that allowed it to resume until it got stuck:

```
2016-06-06_22:51:32.25796 15:51:32,254 ERROR AbstractBinlogParser - failed to parse binlog
2016-06-06_22:51:32.25799 java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
2016-06-06_22:51:32.25800 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:95) ~[open-replicator-1.4.2.jar:?]
2016-06-06_22:51:32.25800 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:125) ~[open-replicator-1.4.2.jar:?]
2016-06-06_22:51:32.25800 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.4.2.jar:?]
2016-06-06_22:51:32.25801 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-06-06_22:51:32.31970 15:51:32,319 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:429928 -- restarting
```

And then it bails out, and loops this:

```
2016-06-06_22:51:32.32974 15:51:32,329 WARN  MaxwellReplicator - Started replication stream outside of transaction.  This shouldn't normally happen.
2016-06-06_22:51:32.36774 15:51:32,367 ERROR AbstractBinlogParser - failed to parse binlog
2016-06-06_22:51:32.36777 java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
2016-06-06_22:51:32.36777 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:95) ~[open-replicator-1.4.2.jar:?]
2016-06-06_22:51:32.36778 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:125) ~[open-replicator-1.4.2.jar:?]
2016-06-06_22:51:32.36778 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.4.2.jar:?]
2016-06-06_22:51:32.36778 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

It's currently stuck at position 431633 which is an insert, I ran the test insert and it replicated to the real slave just fine.

```
#160606 15:59:10 server id 2887124831  end_log_pos 431633 	Write_rows: table id 33 flags: STMT_END_F
```

Seems as if it could be related to the move to MysqlSchemaStore. I guess two questions:

1) How can I resume without dataloss (can it be done?).
2) Is there a "safe" way to stop/start maxwell?

**Comment by osheroff** [comment]
- if it's stuck at 431633, it should be the item in the binlog directly *after* the event you pasted.  What is that event? 

- what are the messages maxwell output before the first restart?  (the "impossible position" restart).

- save the binlog file.  should be good for debugging later.

1. Your method of resetting maxwell's position back to a "known good" one should be fine, but my suspicion is that either your binlog is corrupt, or... something.
2. Generally a simple SIGTERM should let maxwell shutdown and restart just fine.

**Comment by MartinAmps** [comment]
**spoiler**: Skip to the end of this pointless post for the answer.

Ah, sorry, here are the next couple of events:

```
# at 431633
#160606 15:59:10 server id 2887124831  end_log_pos 431660       Xid = 6755565
COMMIT/*!*/;
# at 431660
#160606 15:59:10 server id 2887124831  end_log_pos 431742       Query   thread_id=1888362       exec_time=0     error_code=0
SET TIMESTAMP=1465253950/*!*/;
BEGIN
/*!*/;
# at 431742
# at 431808
```

The slave is still going strong, so I don't think it's _corrupt_ but it does seem odd it's coming from open replicator?


* The first crash showed:

```
   2016-06-06_22:44:43.83974 15:44:43,836 ERROR AbstractBinlogParser - failed to parse binlog
   2016-06-06_22:44:43.83977 java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2050]
   2016-06-06_22:44:43.83977   at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:95) ~[open-replicator-1.4.2.jar:?]
   2016-06-06_22:44:43.83977   at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:125) ~[open-replicator-1.4.2.jar:?]
   2016-06-06_22:44:43.83978   at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.4.2.jar:?]
   2016-06-06_22:44:43.83978   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
   2016-06-06_22:44:43.85170 15:44:43,851 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428283 -- restarting
```

Interestingly, it restarted and errored at a different spot:

```
   2016-06-06_22:44:43.86439 15:44:43,864 WARN  MaxwellReplicator - Started replication stream outside of transaction.  This shouldn't normally happen.
   2016-06-06_22:44:44.02135 15:44:44,020 ERROR AbstractBinlogParser - failed to parse binlog
   2016-06-06_22:44:44.02137 java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
   2016-06-06_22:44:44.02137   at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:95) ~[open-replicator-1.4.2.jar:?]
   2016-06-06_22:44:44.02138   at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:125) ~[open-replicator-1.4.2.jar:?]
   2016-06-06_22:44:44.02138   at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.4.2.jar:?]
   2016-06-06_22:44:44.02138   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
   2016-06-06_22:44:44.06493 15:44:44,064 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428420 -- restarting
```

And continued to do so:


```
   2016-06-06_22:44:44.19380 15:44:44,193 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428447 -- restarting
   2016-06-06_22:44:44.31804 15:44:44,317 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:0 -- restarting
```

With some dispersed errors after that:


````
  2016-06-06_22:44:44.34221 com.google.code.or.net.TransportException: Client requested master to start replication from impossible position; the first event 'mysql-bin.001154' at 0, the      last event read from './mysql-bin.001154' at 4, the last byte read from './mysql-bin.001154' at 4.
  2016-06-06_22:44:44.34227   at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:322)
  2016-06-06_22:44:44.34230   at com.google.code.or.OpenReplicator.start(OpenReplicator.java:111)
  2016-06-06_22:44:44.34233   at com.zendesk.maxwell.MaxwellReplicator.ensureReplicatorThread(MaxwellReplicator.java:92)
  2016-06-06_22:44:44.34238   at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:308)
  2016-06-06_22:44:44.34242   at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:120)
  2016-06-06_22:44:44.34246   at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
  2016-06-06_22:44:44.34249   at com.zendesk.maxwell.Maxwell.run(Maxwell.java:98)
  2016-06-06_22:44:44.34253   at com.zendesk.maxwell.Maxwell.main(Maxwell.java:104)
  2016-06-06_22:44:44.34329 15:44:44,343 INFO  MysqlPositionStore - Storing final position: BinlogPosition[mysql-bin.001154:427336]
```

* saved the output of mysqlbinlog -vv for that one, can keep the raw if necessary, otherwise it'll disappear in a few days.

I'm mostly confused at this little cycle it is stuck in:

```
2016-06-06_22:44:43.85170 15:44:43,851 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428283 -- restarting
2016-06-06_22:44:44.06493 15:44:44,064 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428420 -- restarting
2016-06-06_22:44:44.19380 15:44:44,193 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428447 -- restarting
2016-06-06_22:44:44.31804 15:44:44,317 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:0 -- restarting
2016-06-06_22:44:47.25488 15:44:47,254 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428283 -- restarting
2016-06-06_22:44:47.38109 15:44:47,381 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428420 -- restarting
2016-06-06_22:44:47.50733 15:44:47,507 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:428447 -- restarting
2016-06-06_22:44:47.74251 15:44:47,742 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.001154:0 -- restarting
```

At *428283*, it's maxwell:

```
# at 428283
# at 428338
#160606 15:16:00 server id 2887124831  end_log_pos 428338       Table_map: `maxwell`.`positions` mapped to number 43
#160606 15:16:00 server id 2887124831  end_log_pos 428420       Update_rows: table id 43 flags: STMT_END_F
```


At *428420* / *428447*....:

```
# at 428420
#160606 15:16:00 server id 2887124831  end_log_pos 428447       Xid = 6662889
COMMIT/*!*/;
# at 428447
#160606 15:49:27 server id 2887124831  end_log_pos 428518       Query   thread_id=1881855       exec_time=0     error_code=0
SET TIMESTAMP=1465253367/*!*/;
SET @@session.sql_mode=0/*!*/;
/*!\C utf8 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=33,@@session.collation_server=8/*!*/;
BEGIN
/*!*/;
# at 428518
# at 428573
#160606 15:49:27 server id 2887124831  end_log_pos 428573       Table_map: `maxwell`.`positions` mapped to number 43
#160606 15:49:27 server id 2887124831  end_log_pos 428655       Update_rows: table id 43 flags: STMT_END_F
```


maxwell.positions currently shows:
```
+------------+------------------+-----------------+
| server_id  | binlog_file      | binlog_position |
+------------+------------------+-----------------+
| 2887124831 | mysql-bin.001161 |        73362987 |
+------------+------------------+-----------------+
```

schemas:
```
+----+------------------+-----------------+----------------+--------+------------+---------+---------+---------+
| id | binlog_file      | binlog_position | base_schema_id | deltas | server_id  | charset | version | deleted |
+----+------------------+-----------------+----------------+--------+------------+---------+---------+---------+
|  2 | mysql-bin.001154 |           27940 |           NULL | NULL   | 2887124831 | latin1  |       1 |       0 |
+----+------------------+-----------------+----------------+--------+------------+---------+---------+---------+
```


Oh dear. Thanks for getting this far, I just realized those numbers didn't make sense --- turns out, I had another rogue instance running maxwell by accident....... Which brings a great question- has anyone considered having a lock around the binlog advancing, or sharding, so multiple instances could run concurrently? It'd be good for redundancy.

**Comment by MartinAmps** [comment]
Hopefully that will help the next fool that does the same thing... Another follow-up question: think I lost any rows during that commotion? Not a big deal, just curious.

**Comment by osheroff** [comment]
It couldn't hurt to replay again from wherever you crashed.

I've definitely shot myself in this foot in development mode.  There's been talk about doing some HA stuff inside Maxwell here: https://github.com/zendesk/maxwell/issues/248, but nothing ever seemed to come of it.  @ Zendesk we run our maxwell instances inside `consul lock`, preventing this kind of stuff. 

I would like however to at least detect the case of two maxwell processes running and die gracefully, rather than doing this sort of stuff.  I'll see if I can't build some dupe-process detection into `MysqlPositionStore` (unless you want to take a whack at a patch @MartinAmps)

**Comment by MartinAmps** [comment]
@osheroff how do you envision that would work / be structured?

**Comment by osheroff** [comment]
@MartinAmps thinking that when we go to set the position in `maxwell.positions` we have an opportunity to check to see if someone else has updated the row underneath us and crash... so where it now says `INSERT INTO positions ... on duplicate key`, it'd be:

```
   SELECT * from positions
     if no row, try insert
        if insert duplications, crash
     else if row, UPDATE where position = [old_position] and file = [old_file] and id = [id]
        if update hits zero rows, we are a dupe process, crash
```

**Comment by MartinAmps** [comment]
Sounds logical-- I have put some similar locking in place to prevent me repeating history, wouldn't be a bad idea to implement this regardless though. May have some time this coming weekend to hammer it out!

**Comment by osheroff** [comment]
some of this mess sorted out in v1.1.5
