### ISSUE TITLE
mysterious localhost for kafka producer

### ISSUE THREAD

**Issue by felixgao** [zendesk/maxwell#360]
the options that I am passing into maxwell is
```
exec java $JAVA_OPTS -Dfile.encoding=UTF-8 \
 -Dlog4j.shutdownCallbackRegistry=com.djdch.log4j.StaticShutdownCallbackRegistry \
 -cp $CLASSPATH com.zendesk.maxwell.Maxwell \
 --user=$MYSQL_USER \
 --password=$MYSQL_PASSWORD \
 --host=$MYSQL_HOST \
 --port=$MYSQL_PORT \
 --producer=kafka \
 --kafka.bootstrap.servers=$KAFKA_HOST:$KAFKA_PORT \
 --log_level=$LOG_LEVEL
```
where $KFAKF_HOST is setup to the value of kafka,  the first ProducerConfg is output is correct for the bootstrap server.  However, soon, it seems that localhost is added to the list
```
 02:54:54,166 DEBUG NetworkClient - Sending metadata request ClientRequest(expectResponse=true, payload=null, request=RequestSend(header={api_key=3,api_version=0,correlation_id=0,client_id=producer-1}, body={topics=[maxwell]})) to node -1
maxwell_1  | 02:54:54,175 DEBUG Metadata - Updated cluster metadata version 2 to Cluster(nodes = [Node(0, localhost, 9092)], partitions = [Partition(topic = maxwell, partition = 0, leader = 0, replicas = [0,], isr = [0,]])
```

The full logs is showing below

```
maxwell_1  | 02:54:53,084 INFO  ProducerConfig - ProducerConfig values:
maxwell_1  | 	compression.type = gzip
maxwell_1  | 	metric.reporters = []
maxwell_1  | 	metadata.max.age.ms = 300000
maxwell_1  | 	metadata.fetch.timeout.ms = 5000
maxwell_1  | 	acks = 1
maxwell_1  | 	batch.size = 16384
maxwell_1  | 	reconnect.backoff.ms = 1000
maxwell_1  | 	bootstrap.servers = [kafka:9092]
maxwell_1  | 	receive.buffer.bytes = 32768
maxwell_1  | 	retry.backoff.ms = 1000
maxwell_1  | 	buffer.memory = 33554432
maxwell_1  | 	timeout.ms = 30000
maxwell_1  | 	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
maxwell_1  | 	retries = 0
maxwell_1  | 	max.request.size = 1048576
maxwell_1  | 	block.on.buffer.full = true
maxwell_1  | 	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
maxwell_1  | 	metrics.sample.window.ms = 30000
maxwell_1  | 	send.buffer.bytes = 131072
maxwell_1  | 	max.in.flight.requests.per.connection = 5
maxwell_1  | 	metrics.num.samples = 2
maxwell_1  | 	linger.ms = 0
maxwell_1  | 	client.id =
maxwell_1  |
maxwell_1  | 02:54:53,096 DEBUG Metadata - Updated cluster metadata version 1 to Cluster(nodes = [Node(kafka, 9092)], partitions = [])
maxwell_1  | 02:54:53,107 WARN  ProducerConfig - The configuration value.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
maxwell_1  | 02:54:53,107 WARN  ProducerConfig - The configuration key.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
maxwell_1  | 02:54:53,107 DEBUG KafkaProducer - Kafka producer started
maxwell_1  | 02:54:53,107 DEBUG Sender - Starting Kafka producer I/O thread.
maxwell_1  | 02:54:54,099 DEBUG NetworkClient - Trying to send metadata request to node -1
maxwell_1  | 02:54:54,100 DEBUG NetworkClient - Init connection to node -1 for sending metadata request in the next iteration
maxwell_1  | 02:54:54,101 DEBUG NetworkClient - Initiating connection to node -1 at kafka:9092.
maxwell_1  | 02:54:54,159 DEBUG NetworkClient - Completed connection to node -1
maxwell_1  | 02:54:54,159 DEBUG NetworkClient - Trying to send metadata request to node -1
maxwell_1  | 02:54:54,166 DEBUG NetworkClient - Sending metadata request ClientRequest(expectResponse=true, payload=null, request=RequestSend(header={api_key=3,api_version=0,correlation_id=0,client_id=producer-1}, body={topics=[maxwell]})) to node -1
maxwell_1  | 02:54:54,175 DEBUG Metadata - Updated cluster metadata version 2 to Cluster(nodes = [Node(0, localhost, 9092)], partitions = [Partition(topic = maxwell, partition = 0, leader = 0, replicas = [0,], isr = [0,]])
maxwell_1  | 02:54:54,176 INFO  Maxwell - Maxwell is booting (MaxwellKafkaProducer), starting at BinlogPosition[mysql-bin.000004:15340]
maxwell_1  | 02:54:54,350 DEBUG SchemaStore - looking to restore schema at target position BinlogPosition[mysql-bin.000004:15340]
maxwell_1  | 02:54:54,353 INFO  SchemaStore - Restoring schema id 1 (last modified at BinlogPosition[mysql-bin.000004:15340])
maxwell_1  | 02:54:54,398 INFO  ProducerConfig - ProducerConfig values:
maxwell_1  | 	compression.type = gzip
maxwell_1  | 	metric.reporters = []
maxwell_1  | 	metadata.max.age.ms = 300000
maxwell_1  | 	metadata.fetch.timeout.ms = 5000
maxwell_1  | 	acks = 1
maxwell_1  | 	batch.size = 16384
maxwell_1  | 	reconnect.backoff.ms = 1000
maxwell_1  | 	bootstrap.servers = [kafka:9092]
maxwell_1  | 	receive.buffer.bytes = 32768
maxwell_1  | 	retry.backoff.ms = 1000
maxwell_1  | 	buffer.memory = 33554432
maxwell_1  | 	timeout.ms = 30000
maxwell_1  | 	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
maxwell_1  | 	retries = 0
maxwell_1  | 	max.request.size = 1048576
maxwell_1  | 	block.on.buffer.full = true
maxwell_1  | 	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
maxwell_1  | 	metrics.sample.window.ms = 30000
maxwell_1  | 	send.buffer.bytes = 131072
maxwell_1  | 	max.in.flight.requests.per.connection = 5
maxwell_1  | 	metrics.num.samples = 2
maxwell_1  | 	linger.ms = 0
maxwell_1  | 	client.id =
maxwell_1  |
maxwell_1  | 02:54:54,399 DEBUG Metadata - Updated cluster metadata version 1 to Cluster(nodes = [Node(kafka, 9092)], partitions = [])
maxwell_1  | 02:54:54,403 WARN  ProducerConfig - The configuration value.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
maxwell_1  | 02:54:54,403 WARN  ProducerConfig - The configuration key.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
maxwell_1  | 02:54:54,403 DEBUG Sender - Starting Kafka producer I/O thread.
maxwell_1  | 02:54:54,404 DEBUG KafkaProducer - Kafka producer started
maxwell_1  | 02:54:55,400 DEBUG NetworkClient - Trying to send metadata request to node -1
maxwell_1  | 02:54:55,400 DEBUG NetworkClient - Init connection to node -1 for sending metadata request in the next iteration
maxwell_1  | 02:54:55,401 DEBUG NetworkClient - Initiating connection to node -1 at kafka:9092.
maxwell_1  | 02:54:55,401 DEBUG NetworkClient - Completed connection to node -1
maxwell_1  | 02:54:55,401 DEBUG NetworkClient - Trying to send metadata request to node -1
maxwell_1  | 02:54:55,402 DEBUG NetworkClient - Sending metadata request ClientRequest(expectResponse=true, payload=null, request=RequestSend(header={api_key=3,api_version=0,correlation_id=0,client_id=producer-2}, body={topics=[maxwell]})) to node -1
maxwell_1  | 02:54:55,405 DEBUG Metadata - Updated cluster metadata version 2 to Cluster(nodes = [Node(0, localhost, 9092)], partitions = [Partition(topic = maxwell, partition = 0, leader = 0, replicas = [0,], isr = [0,]])
maxwell_1  | 02:54:55,418 INFO  TransportImpl - connecting to host: jabba-mysql, port: 3306
maxwell_1  | 02:54:55,501 INFO  TransportImpl - connected to host: jabba-mysql, port: 3306, context: AbstractTransport.Context[threadId=45,scramble=*E\}$6$PFN5\Sh3d}hs),protocolVersion=10,serverHost=jabba-mysql,serverPort=3306,serverStatus=2,serverCollation=8,serverVersion=5.6.30-log,serverCapabilities=63487]
maxwell_1  | 02:54:55,502 INFO  AuthenticatorImpl - start to login, user: root, host: jabba-mysql, port: 3306
maxwell_1  | 02:54:55,508 INFO  AuthenticatorImpl - login successfully, user: root, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
maxwell_1  | 02:54:55,571 DEBUG NetworkClient - Initiating connection to node 0 at localhost:9092.
maxwell_1  | 02:54:55,573 WARN  Selector - Error in I/O with localhost/127.0.0.1
maxwell_1  | java.net.ConnectException: Connection refused
maxwell_1  | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_92]
maxwell_1  | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_92]
maxwell_1  | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:238) [kafka-clients-0.8.2.0.jar:?]
maxwell_1  | 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.0.jar:?]
maxwell_1  | 	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.0.jar:?]
maxwell_1  | 	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.0.jar:?]
maxwell_1  | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
maxwell_1  | 02:54:55,577 DEBUG NetworkClient - Node 0 disconnected.
maxwell_1  | 02:54:56,403 DEBUG NetworkClient - Give up sending metadata request since no node is available
```

**Comment by osheroff** [comment]
the problem is that your kafka broker thinks its own hostname is `localhost`.  See the log line:

```
02:54:55,405 DEBUG Metadata - Updated cluster metadata version 2 to Cluster(nodes = [Node(0, localhost, 9092)], partitions = [Partition(topic = maxwell, partition = 0, leader = 0, replicas = [0,], isr = [0,]])
```

and then check out the `advertised.host.name` or `advertised.listeners	` broker config...

**Comment by felixgao** [comment]
thanks for the information, after some digging we are accidentally passing in advertised.host.name as localhost, so once that is changed everything is fine.  

Thanks

**Comment by prabhukumarasamy7** [comment]
updating the advertised.listener value to the actual hostname solved the issue. it was really helpful @osheroff
