### ISSUE TITLE
Error when parse delete

### ISSUE THREAD

**Issue by abo** [zendesk/maxwell#374]
MySQL 5.5.50, JDK 1.8

```
bin/maxwell --host='192.168.1.106' --user='xxx' --password='xxx' --producer=stdout --include_dbs='webcastraw'
```

maxwell log this and exit:

```
14:08:05,554 ERROR MysqlParserListener - (parse DELETE FROM `webcast` . `gs_lock`)
14:08:05,554 ERROR SchemaChange - Error parsing SQL: 'DELETE FROM `webcast`.`gs_lock`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: DELETE
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:79)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:91)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:33)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:47)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:324)
	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:303)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:114)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:76)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:82)
```

**Comment by osheroff** [comment]
generally this means you have an old client attached to your mysql server -- in order to fully turn on row-based replication you must disconnect all active mysql clients.  

I should probably turn INSERT/UPDATE/DELETE into warnings, though.

**Comment by abo** [comment]
Got it, tks
