### ISSUE TITLE
MySQL index rename is erroring 

### ISSUE THREAD

**Issue by leeparayno** [zendesk/maxwell#376]
When performing Rails migrations one of our migrations is performing a MySQL index rename, and the syntax is failing to be parsed and maxwell exits.

6:02:52,432 INFO  AbstractSchemaStore - storing schema @BinlogPosition[master.000001:173968538] after applying "ALTER TABLE `quote_request_follow_on_data` CHANGE `model_name` `model_class_name` varchar(255) DEFAULT NULL"
16:02:52,493 ERROR MysqlParserListener - (table_name INDEX `index_quote_request_follow_on_data_on_model_name` TO `index_quote_request_follow_on_data_on_model_class_name`)
16:02:52,494 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE `quote_request_follow_on_data` RENAME INDEX `index_quote_request_follow_on_data_on_model_name` TO `index_quote_request_follow_on_data_on_model_class_name`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: INDEX
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:79)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:91)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:33)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:47)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:324)
	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:303)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:114)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:76)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:82)

**Comment by osheroff** [comment]
ok, this is new syntax in 5.7 it seems.  Will fix this, need to also generate a bunch of test SQL from 5.7's test suite.

**Comment by osheroff** [comment]
fixed in https://github.com/zendesk/maxwell/releases/tag/v1.1.3
