### ISSUE TITLE
Error: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#386]
I noticed Maxwell 1.1.2 crashing frequently with MySQL connection error.  
Wonder if this is due to new MySQL driver?. anyone else experiencing this issue?

`My Env:  Percona XtraDB Cluster  5.6.24-72.2`

```
23:54:26,706 INFO  MaxwellReplicator - storing schema @BinlogPosition[binarylog.04444:2222] after applying "ALTER TABLE ..."
03:57:26,268 WARN  Selector - Error in I/O with dbhost1/100.100.100.1
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62) ~[kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:248) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
10:02:16,989 ERROR SchemaScavenger - SchemaScavenger thread aborting after exception: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
10:10:31,284 ERROR SchemaPosition - received SQLException while trying to save to maxwell.positions:
10:10:31,288 ERROR SchemaPosition - Lock wait timeout exceeded; try restarting transaction
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:950)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
        at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3833)
        at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3283)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2297)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)                                                              
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at snaq.db.ConnectionPool.create(ConnectionPool.java:256)
        at snaq.db.ConnectionPool.create(ConnectionPool.java:71)
        at snaq.util.ObjectPool.checkOut(ObjectPool.java:377)
        at snaq.db.ConnectionPool.getConnection(ConnectionPool.java:385)
        at com.zendesk.maxwell.schema.SchemaPosition.getConnection(SchemaPosition.java:153)
        at com.zendesk.maxwell.schema.SchemaPosition.store(SchemaPosition.java:95)
        at com.zendesk.maxwell.schema.SchemaPosition.work(SchemaPosition.java:77)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
        at com.zendesk.maxwell.schema.SchemaPosition.run(SchemaPosition.java:63)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by xmlking** [comment]
Crashed again today :(

```
MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
18:29:19,164 INFO  MaxwellReplicator - storing schema @BinlogPosition[binarylog.044826:20100] after applying "ALTER TABLE xxx ADD CONSTRAINT x FOREIGN KEY (xxx) REFERENCES xxx (xxx)"
18:29:50,229 ERROR SchemaPosition - received SQLException while trying to save to maxwell.positions:
18:29:50,229 ERROR SchemaPosition - Could not retrieve transation read-only status server
java.sql.SQLException: Could not retrieve transation read-only status server
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:877)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:873)
        at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3603)
        at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3572)
        at com.mysql.jdbc.PreparedStatement.checkReadOnlySafeStatement(PreparedStatement.java:1117)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1137)
        at snaq.db.CachedPreparedStatement.execute(CachedPreparedStatement.java:327)
        at com.zendesk.maxwell.schema.SchemaPosition.store(SchemaPosition.java:105)
        at com.zendesk.maxwell.schema.SchemaPosition.work(SchemaPosition.java:77)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
        at com.zendesk.maxwell.schema.SchemaPosition.run(SchemaPosition.java:63)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
```

**Comment by osheroff** [comment]
hmph.   Trying to reason through this one, but it's very very odd -- neither stack trace appears to be from a place in a stack that should be susceptible to deadlock, so unless I'm doing something exceedingly stupid (leaving a transaction open, accidentally sharing a connection between two threads, something like that) I'm a bit stumped.

What was the version you were running before 1.1.2?

**Comment by xmlking** [comment]
I think I was using v1.1.0 before. I am seeing crashes regularly since upgraded to 1.1.2 . If you are interested,  I can post more logs that may be helpful for debugging 
I am guessing mySQL 5.1.35 driver  may be not compatible  with Percona XtraDB Cluster 5.6.24-72.2
Thanks

**Comment by osheroff** [comment]
Ok, can you test that theory?  Simply replacing `lib/mysql-connector-java-5.1.39.jar` with the previous version's jar should be fine for testing...

**Comment by xmlking** [comment]
Sure I will test.
By the way I am using my fork at https://github.com/xmlking/maxwell
This is maxwell version  1.1.2 merged with your DDL  output changes. 
Concern I  might be doing some stupid mistake when I merged DDL code !
Can you please validate this repo ? I really need DDL output for my project.
Thanks

**Comment by osheroff** [comment]
I can't really validate your fork; it's in conflict with master and the diff is too wide.

**Comment by showwayer** [comment]
@xmlking I am also getting "Lock wait timeout exceeded.." error. I also upgraded mysql version (mysql-connector-java-5.1.40-bin.jar) recently, is this error related to mysql driver upgrade? 

Thanks for your time!
