### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by Nash897** [zendesk/maxwell#401]
**My producer is kafka and I am able to connect to it. But connecting to mysqldb is giving me this error :**

20:45:38,534 INFO  AuthenticatorImpl - login successfully, user: maxwell, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
java.io.EOFException
        at com.google.code.or.io.util.ActiveBufferedInputStream.read(ActiveBufferedInputStream.java:177)
        at com.google.code.or.io.impl.XInputStreamImpl.doFill(XInputStreamImpl.java:237)
        at com.google.code.or.io.impl.XInputStreamImpl.read(XInputStreamImpl.java:214)
        at com.google.code.or.net.impl.TransportInputStreamImpl.read(TransportInputStreamImpl.java:88)
        at com.google.code.or.io.impl.XInputStreamImpl.readInt(XInputStreamImpl.java:142)
        at com.google.code.or.io.impl.XInputStreamImpl.readInt(XInputStreamImpl.java:62)
        at com.google.code.or.net.impl.TransportInputStreamImpl.readPacketHeader(TransportInputStreamImpl.java:72)
        at com.google.code.or.net.impl.TransportInputStreamImpl.readPacket(TransportInputStreamImpl.java:57)
        at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:319)
        at com.google.code.or.OpenReplicator.start(OpenReplicator.java:111)
        at com.zendesk.maxwell.MaxwellReplicator.beforeStart(MaxwellReplicator.java:104)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:25)
        at com.zendesk.maxwell.Maxwell.run(Maxwell.java:76)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:82)
20:45:38,555 INFO  MysqlPositionStore - Storing final position: null

**Comment by osheroff** [comment]
I've seen similar errors caused by trying to run multiple copies of maxwell on one server.  possible?

**Comment by Nash897** [comment]
Hi, I am sure I am running only one instance of maxwell. I am new to maxwell and not sure what I am doing wrong. Please help me debug

**Comment by osheroff** [comment]
what version of mysql?  what's your setup?

**Comment by Nash897** [comment]
I figured it out. Error was coming as I had not configured my.cnf properly. Thanks!

**Comment by osheroff** [comment]
care to share what had gone wrong?  maybe I can detect it in a future maxwell rev.

**Comment by Nash897** [comment]
Sure. my mysql server id was wrong/missing in my.cnf. 
I tried with kafka mysql connect and in errors it showed server id warning. So I did the changes and could run maxwell. 
I would suggest better logging information in future could help.

**Comment by osheroff** [comment]
fixed this to crash better when server_id is missing.
