### ISSUE TITLE
DDL statement parsing error "MaxwellSQLSyntaxError: InnoDB"

### ISSUE THREAD

**Issue by powerLambda** [zendesk/maxwell#418]
Full error stack as below:

3:50:50,710 INFO AbstractSchemaStore - storing schema @BinlogPosition[mysql-bin.003981:29180028] after applying "DROP TABLE IF EXISTS xxx_asset_access_audit /* generated by server */"
23:50:50,777 ERROR MysqlParserListener - (creation_engine ENGINE = InnoDB)
23:50:50,777 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE xxx_asset_access_audit (
id int(11) NOT NULL,
partner_id varchar(31) NOT NULL ,
partner_product_id varchar(31) NOT NULL ,
log_date datetime NOT NULL ,
batch_id varchar(64) NOT NULL ,
order_id varchar(64) NOT NULL ,
audit_status tinyint(4) NOT NULL ,
audit_reason varchar(255) DEFAULT NULL ,
remark varchar(255) DEFAULT ',
is_deleted char(1) NOT NULL DEFAULT 'N' ,
gmt_created datetime NOT NULL ,
creator varchar(32) NOT NULL ,
gmt_modified datetime NOT NULL ,
modifier varchar(32) NOT NULL ,
PRIMARY KEY (id),
UNIQUE UN_ORDER (partner_product_id, batch_id, order_id) comment ''
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: InnoDB
at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:79)
at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:91)
at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:33)
at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:47)
at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:344)
at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:321)
at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:113)
at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:32)
at com.zendesk.maxwell.Maxwell.run(Maxwell.java:76)
at com.zendesk.maxwell.Maxwell.main(Maxwell.java:82)
23:50:50,823 INFO PositionStoreThread - Storing final position: BinlogPosition[mysql-bin.003981:29179353]

**Comment by osheroff** [comment]
fixed in v1.1.5
