### ISSUE TITLE
how to use it kafka0.9?

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#431]
I am interested in using Kafka 0.9 
 
documentation says `By default, maxwell runs with kafka clients 0.9.0.1`
but when I am running Maxwell 1.2.0 without any flags , I am still getting errors! that says it is using `0.8.2.2.jar`

```
18:52:37,506 WARN  Selector - Error in I/O with avcd123/11.206.156.18
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62) ~[kafka-clients-0.8.2.2.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:248) [kafka-clients-0.8.2.2.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.2.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.2.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.2.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by osheroff** [comment]
cc @dadah89

**Comment by osheroff** [comment]
what does the output of `bash -x bin/maxwell` say?

**Comment by xmlking** [comment]
```
 bash -x bin/maxwell
++ dirname bin/maxwell
+ base_dir=bin/..
+ KAFKA_08_VERSION=0.8.2.2
+ KAFKA_09_VERSION=0.9.0.1
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/antlr4-runtime-4.5.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/commons-codec-1.5.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/commons-lang3-3.4.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/dbpool-7.0-jdk7.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/jackson-annotations-2.6.0.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/jackson-core-2.6.3.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/jackson-databind-2.6.3.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/jopt-simple-4.9.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/jts-1.13.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/kafka-clients-0.8.2.2.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/kafka-clients-0.9.0.1.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/log4j-api-2.1.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/log4j-core-2.1.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/log4j-slf4j-impl-2.1.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/log4j-staticshutdown-1.1.0.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/lz4-1.2.0.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/maxwell-1.2.0.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/mysql-connector-java-5.1.39.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/open-replicator-1.5.0.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar:lib/open-replicator-1.5.0.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/org.abego.treelayout.core-1.0.1.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar:lib/open-replicator-1.5.0.jar:lib/org.abego.treelayout.core-1.0.1.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/slf4j-api-1.7.6.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar:lib/open-replicator-1.5.0.jar:lib/org.abego.treelayout.core-1.0.1.jar:lib/slf4j-api-1.7.6.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! lib/snappy-java-1.1.1.7.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=:bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar:lib/open-replicator-1.5.0.jar:lib/org.abego.treelayout.core-1.0.1.jar:lib/slf4j-api-1.7.6.jar:lib/snappy-java-1.1.1.7.jar
+ for file in 'lib/*.jar' 'target/dependency/*.jar'
+ [[ '' == *--kafka0.8* ]]
+ [[ ! '' == *--kafka0.8* ]]
+ [[ ! target/dependency/*.jar == \t\a\r\g\e\t\/\d\e\p\e\n\d\e\n\c\y\/\k\a\f\k\a\-\c\l\i\e\n\t\s\-\0\.\8\.\2\.\2\.\j\a\r ]]
+ CLASSPATH=':bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar:lib/open-replicator-1.5.0.jar:lib/org.abego.treelayout.core-1.0.1.jar:lib/slf4j-api-1.7.6.jar:lib/snappy-java-1.1.1.7.jar:target/dependency/*.jar'
+ '[' -z '' ']'
+ JAVA=java
+ exec java -Dfile.encoding=UTF-8 -Dlog4j.shutdownCallbackRegistry=com.djdch.log4j.StaticShutdownCallbackRegistry -cp ':bin/../target/classes:../open-replicator/target/classes:lib/antlr4-runtime-4.5.jar:lib/commons-codec-1.5.jar:lib/commons-lang3-3.4.jar:lib/dbpool-7.0-jdk7.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.3.jar:lib/jackson-databind-2.6.3.jar:lib/jopt-simple-4.9.jar:lib/jts-1.13.jar:lib/kafka-clients-0.8.2.2.jar:lib/kafka-clients-0.9.0.1.jar:lib/log4j-api-2.1.jar:lib/log4j-core-2.1.jar:lib/log4j-slf4j-impl-2.1.jar:lib/log4j-staticshutdown-1.1.0.jar:lib/lz4-1.2.0.jar:lib/maxwell-1.2.0.jar:lib/mysql-connector-java-5.1.39.jar:lib/open-replicator-1.5.0.jar:lib/org.abego.treelayout.core-1.0.1.jar:lib/slf4j-api-1.7.6.jar:lib/snappy-java-1.1.1.7.jar:target/dependency/*.jar' com.zendesk.maxwell.Maxwell
12:53:45,890 INFO  ProducerConfig - ProducerConfig values:
  compression.type = gzip
  metric.reporters = []
  metadata.max.age.ms = 300000
  metadata.fetch.timeout.ms = 5000
  acks = 1
  batch.size = 16384
  reconnect.backoff.ms = 10
  bootstrap.servers = [aaa:9092, yyy:9092, xxxx:9092]
  receive.buffer.bytes = 32768
  retry.backoff.ms = 100
  buffer.memory = 33554432
  timeout.ms = 30000
  key.serializer = class org.apache.kafka.common.serialization.StringSerializer
  retries = 1
  max.request.size = 1048576
  block.on.buffer.full = true
  value.serializer = class org.apache.kafka.common.serialization.StringSerializer
  metrics.sample.window.ms = 30000
  send.buffer.bytes = 131072
  max.in.flight.requests.per.connection = 5
  metrics.num.samples = 2
  linger.ms = 0
  client.id =

12:53:45,928 WARN  ProducerConfig - The configuration value.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
12:53:45,928 WARN  ProducerConfig - The configuration key.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
12:53:46,095 INFO  Maxwell - Maxwell v1.2.0 is booting (MaxwellKafkaProducer), starting at BinlogPosition[binarylog.050100:2352]
12:53:46,149 INFO  OpenReplicator - starting replication at binarylog.050100:2352
12:53:46,151 ERROR MaxwellReplicator - Missing binlog 'binarylog.050100' on dbsrs0880
12:53:46,151 ERROR MaxwellReplicator - Transport exception #1236
com.google.code.or.net.TransportException: Could not find first log file name in binary log index file
  at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:343)
  at com.google.code.or.OpenReplicator.start(OpenReplicator.java:115)
  at com.zendesk.maxwell.MaxwellReplicator.startReplicator(MaxwellReplicator.java:127)
  at com.zendesk.maxwell.MaxwellReplicator.beforeStart(MaxwellReplicator.java:142)
  at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:29)
  at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
  at com.zendesk.maxwell.Maxwell.main(Maxwell.java:180)
```

**Comment by osheroff** [comment]
bah, bummer.  @dadah89 your code works in development but not in a release tarball.

**Comment by xmlking** [comment]
btw I build tarball myself from master branch  with 
 
```
make clean
make package
```

**Comment by dadah89** [comment]
Now I understand the issue =\ Working on a fix
