### ISSUE TITLE
Rework shutdown process in case of exception

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#441]
Installed 1.2.1 version yesterday, re-created the Maxwell schema and started up Maxwell. It failed with the below error about 9:30 hours later. 

There is another client for the same source database with a different client ID that did not fail. That node is a fail-over, so does not receive as much data in the binlogs.

Here is the error:
===========
22:29:24,265 WARN  MaxwellReplicator - no heartbeat heard from server in 2002ms.  restarting replication.
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at com.google.code.or.io.impl.SocketFactoryImpl.create(SocketFactoryImpl.java:37)
        at com.google.code.or.net.impl.TransportImpl.connect(TransportImpl.java:71)
        at com.google.code.or.OpenReplicator.start(OpenReplicator.java:106)
        at com.zendesk.maxwell.MaxwellReplicator.ensureReplicatorThread(MaxwellReplicator.java:127)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:369)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:153)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:180)
12:56:00,757 INFO  PositionStoreThread - Storing final position: BinlogPosition[binarylog.051165:86837]
12:56:00,768 ERROR PositionStoreThread - Hit com.zendesk.maxwell.errors.DuplicateProcessException exception in MysqlPositionStore thread.
com.zendesk.maxwell.errors.DuplicateProcessException: Expected a heartbeat value of 1474480534734 but didn't find it.  Is another Maxwell process running with the same client_id?
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:111)
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:63)
        at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:87)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:32)
        at java.lang.Thread.run(Thread.java:745)

**Comment by osheroff** [comment]
what's the contents of `maxwell.positions`?

**Comment by osheroff** [comment]
oh I imagine you probably restarted it.  hm.

**Comment by osheroff** [comment]
is the other client also 1.2.1?

**Comment by bmichaud** [comment]
Yes all versions are the same.

**Comment by osheroff** [comment]
ok, so yeah.  the crash happened because of the timeout error, but then there's problems in the shutdown process.  I'm trying to do far too much inside of a shutdown-hook, need to rework the exception handling here.

**Comment by osheroff** [comment]
fixed the shutdown hook in 1.4.0
