### ISSUE TITLE
alter table / drop column not supported error

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#448]
Maxwell 1.2.1, MySQL 5.6

The stack trace seems to suggest that we are dropping the primary key column, but this column is not the PK. Isn't that nteresting? I was not the one performing the DDL change, so I could be wrong. This was done in a performance test playground, so it is possible some crazy stuff is going on here. 

However, the message indicates that a rather crucial alter table operation is not supported. Is it telling the truth or just guessing as to the nature of the failure?

`13:11:53,705 INFO  AbstractSchemaStore - storing schema @BinlogPosition[binarylog.016281:199768] after applying "ALTER TABLE tableName DROP COLUMN columnName"
java.lang.UnsupportedOperationException
        at java.util.AbstractList.remove(AbstractList.java:161)
        at com.zendesk.maxwell.schema.Table.removePKColumn(Table.java:299)
        at com.zendesk.maxwell.schema.Table.removeColumn(Table.java:261)
        at com.zendesk.maxwell.schema.ddl.ChangeColumnMod.apply(ChangeColumnMod.java:19)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:52)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:57)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
        at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:427)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:395)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:153)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:180)
`

**Comment by osheroff** [comment]
Hi, 
this was fixed in v1.2.2, see: https://github.com/zendesk/maxwell/commit/0812300fdf0c1a235e7b4f14042e9a25e1d85966
