### ISSUE TITLE
Question: what might cause this?

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#452]
Could this be caused by out-of-date schema information in the Maxwell schema?

`java.lang.IndexOutOfBoundsException: Index: 50, Size: 50
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.zendesk.maxwell.ColumnWithDefinitionList$ColumnWithDefinitionIterator.next(ColumnWithDefinitionList.java:53)
        at com.zendesk.maxwell.ColumnWithDefinitionList$ColumnWithDefinitionIterator.next(ColumnWithDefinitionList.java:28)
        at com.zendesk.maxwell.MaxwellAbstractRowsEvent.jsonMaps(MaxwellAbstractRowsEvent.java:205)
        at com.zendesk.maxwell.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:275)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:393)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:153)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:180)`

**Comment by osheroff** [comment]
yes, looks like out-of-sync schema information.  the binlog row had more than 50 rows but maxwell only knew about 50.  mind sharing how you go to that point?

**Comment by bmichaud** [comment]
Maxwell crashes and has to be restarted fairly often, and I only find out that it crashes when someone tries to perform tests in a particular environment. During the time Maxwell is down, schema changes occur. This is a large database with many developers submitting changes, so the builds are constantly coming in and some of them change the schema. Often, Maxwell is restarted without truncating the meta-data schema first, so it is not aware of the changes that happened while it was down.

That is my best guess of what happened here. Now that I have a probably cause, I have some way of fixing it in the future. I actually guessed that it had something to do with our DB changes, rather than a bug in Maxwell, but I wanted some kind of corroboration from you. :+1:

**Comment by osheroff** [comment]
in theory, maxwell should be able to track all schema changes, but if you setup the position manually, or reset the master logs, or do schema changes with binlogs off, it could lose track.  

This is also possible (I think) if schema changes come in while maxwell is capturing the schema.   LMK if it happens again & we could hunt further.

**Comment by bmichaud** [comment]
Currently, our binlogs are only kept for 15 minutes, so we often have to delete the positions record and we lose data.
