### ISSUE TITLE
problems with CREATE TABLE like ? 

### ISSUE THREAD

**Issue by wayuki** [zendesk/maxwell#463]
16:31:46,372 INFO  Maxwell - Maxwell v1.4.2 is booting (StdoutProducer), starting at BinlogPosition[mysql-bin.000387:404255980]
16:31:46,435 INFO  OpenReplicator - starting replication at mysql-bin.000387:404255980
16:31:46,676 INFO  MysqlSavedSchema - Restoring schema id 7 (last modified at BinlogPosition[mysql-bin.000387:404255980])
16:31:46,782 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at BinlogPosition[mysql-bin.000387:4])
16:31:47,012 INFO  MysqlSavedSchema - beginning to play deltas...
16:31:47,033 INFO  MysqlSavedSchema - played 6 deltas in 21ms
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Unexpectedly asked to create existing table orders_mytest
        at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:26)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
        at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:462)
        at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:432)
        at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:160)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:181)
16:31:52,187 INFO  Maxwell - starting shutdown
16:31:52,290 INFO  PositionStoreThread - Storing final position: BinlogPosition[mysql-bin.000387:404255980]

**Comment by osheroff** [comment]
no, we should support `create table like`.  It looks like you found a bug where maxwell is trying to process the same `CREATE TABLE` statement twice (see the "last modified at" position matching the "starting replication" position).  

Do you have the logging output for the previous run of maxwell?

**Comment by wayuki** [comment]
no,I don't have , not support repeat running the same command?I just want to get output to stdout

**Comment by osheroff** [comment]
i can't reproduce this issue at all, nor am I really sure where to start.  I'll leave it open in case you can reproduce it again, or if someone else has problems...

**Comment by osheroff** [comment]
sigh, no repro.
