### ISSUE TITLE
Maxwell Schema Issues after 'ALTER TABLE foo MODIFY bar bartype AFTER baz;' like commands

### ISSUE THREAD

**Issue by Bradyta** [zendesk/maxwell#468]
In the process of adding some personalized changes I noticed that after doing a series of inserts in tandem with moving columns around that maxwell would start going wonky. I'm trying to get a definite replication scenario, but I've had errors where column values get flipped, a more recent one where it appears a set(varchar) and an int column got mixed up, something just seems strange.  Here's the stack trace for the set(varchar) and int column  
 
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:35)
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:51)
	at com.zendesk.maxwell.schema.ColumnWithDefinition.asJSON(ColumnWithDefinition.java:34)
	at com.zendesk.maxwell.replication.AbstractRowsEvent.jsonMaps(AbstractRowsEvent.java:207)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:281)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:428)
	at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:160)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:181)

While my query was:
mysql> INSERT INTO test.column_test3(name,id,id2,col) VALUES('abbis2',21,26,'b');
Query OK, 1 row affected (0.00 sec)

**Comment by Bradyta** [comment]
Following up with replication:
CREATE TABLE test (`col` set('a','b') DEFAULT NULL,
    ->   `id` int(11) NOT NULL DEFAULT '0',
    ->   `name` varchar(20) NOT NULL DEFAULT '',
    ->   `id2` int(11) NOT NULL DEFAULT '0',
    ->   PRIMARY KEY (`id`,`name`,`id2`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO test(col,id,name,id2) VALUES('a',1,'testName',2);
{"database":"test","table":"test","type":"insert","ts":1478195164,"xid":35015,"commit":true,"data":{"col":["a"],"id":1,"name":"testName","id2":2}}

ALTER TABLE test MODIFY id int(11) AFTER name;

13:01:24,983 INFO  AbstractSchemaStore - storing schema @BinlogPosition[mysql-bin.000107:30615] after applying "ALTER TABLE test MODIFY id int(11) AFTER name"  
  
INSERT INTO test(col,id,name,id2) VALUES('a',2,'testName',3);
{"database":"test","table":"test","type":"insert","ts":1478195241,"xid":35037,"commit":true,"data":{"col":["a"],"name":"testName","id2":2,"id":3}}  
  
So you can see that somehow Maxwell gives 'id' a value of 3 after the insert after the alter table which is incorrect, id should be 2, and id2 should be 3.

**Comment by osheroff** [comment]
yup, i can repro this, will work on it

**Comment by osheroff** [comment]
fixed in v1.5.0
