### ISSUE TITLE
Creating tables like blacklisted tables causes maxwell to crash

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#480]
So I'll start off by saying this is partly our own fault and I'm not sure how it should be handled, but I wanted to raise this issue somewhere so it's known and anyone else who experiences it can have some answers.

```mysql
CREATE TABLE included_schema.broken LIKE blacklisted_schema.some_table;
```
causes this error:
```
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'broken' in database 'blacklisted_schema
  at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55)
  at com.zendesk.maxwell.schema.ddl.TableCreate.resolveLikeTable(TableCreate.java:55)
  at com.zendesk.maxwell.schema.ddl.TableCreate.resolve(TableCreate.java:41)
  at com.zendesk.maxwell.schema.ddl.TableCreate.resolve(TableCreate.java:13)
  at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:56)
  at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
  at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:462)
  at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:432)
  at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
  at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
  at com.zendesk.maxwell.Maxwell.start(Maxwell.java:160)
  at com.zendesk.maxwell.Maxwell.main(Maxwell.java:181)
```
It makes perfect sense that this would happen when tracked down exactly which binlog it was falling over on, but it took us ages to figure out why this was happening as we were sure (and when we tested) tables in the blacklisted schema were correctly being ignored by Maxwell.

I'm not sure if it should be crashing or not or whether it possible to handle this case, and we decided it was quicker and easier to move the creation of table to the same blacklisted schema (as its deleted very shortly afterwards... it cant be properly TEMPORARY for other reasons), so I'm guessing this is kind of edge case and not worth spending a lot of time on.

**Comment by osheroff** [comment]
I didn't figure on anyone reading the warning label :)  

If you could catch other edge cases with some kind of "desperately try to recapture the schema and continue" mode, it might be worthwhile; when we fail to parse some SQL, or when stuff like this happens... I dunno.  It might be a nice thing to try to bungle ahead.  If you wanted to do a patch where a certain class of error gets thrown out of the Replicator (or SchemaStore), and then we try to re-capture, I'd be ok with trying it out.  Probably opt-in and first to see how it goes, since you can get weirder errors if you recapture the schema but that recapture is out of sync.

**Comment by osheroff** [comment]
<shrug> I dunno.  I guess put this under the header of "maybe we should add re-capturing code".  Or maybe it's "maybe we should remove the blacklist."  I dunno.
