### ISSUE TITLE
Couldn't find column for primary key after PK column rename

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#488]
Maxwell 1.3.0
We get this error upon renaming the PK column. Just prior to doing this, they renamed the table like this:
`ALTER TABLE myoldtable RENAME TO mynewtable`

```
08:46:03,039 INFO  AbstractSchemaStore - storing schema @BinlogPosition[binarylog.000011:59241264] after applying "ALTER TABLE mynewtable CHANGE myOldTableID myNewTableID BIGINT (19)"
java.lang.RuntimeException: Couldn't find column for primary-key: myOldTableID
        at com.zendesk.maxwell.schema.Table.normalizedColumnNames(Table.java:343)
        at com.zendesk.maxwell.schema.Table.getPKList(Table.java:295)
        at com.zendesk.maxwell.schema.Table.renamePKColumn(Table.java:321)
        at com.zendesk.maxwell.schema.Table.changeColumn(Table.java:279)
        at com.zendesk.maxwell.schema.ddl.ChangeColumnMod.apply(ChangeColumnMod.java:19)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:52)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:56)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
        at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:462)
        at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:432)
        at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:160)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:181)
```

**Comment by osheroff** [comment]
I can repro this in 1.3.0, but it was fixed (as a nice side effect) in 1.5.0 by https://github.com/zendesk/maxwell/pull/470/files
