### ISSUE TITLE
Communications Link Failure on Bootstrap

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#496]
Maxwell 1.5.1, MySQL 5.6

When we do a bootstrap on hundreds of tables, the bootstrap seems to consume too many database connections, then we get this error. I have restarted Maxwell repeatedly, but the same issue crops up each time. Is there some way to limit the parallel connections to MySQL?

Bootstrapper is set as follows: `bootstrapper=sync`
but the same error happens with "async" as the value.

Error is as follows:

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException:

 Communications link failure

The last packet successfully received from the server was 9 milliseconds ago.  The last packet sent successfully to the server was 8 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3552)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3452)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3893)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:875)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1712)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1228)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.getStreamingConnection(SynchronousBootstrapper.java:96)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:52)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.work(SynchronousBootstrapper.java:155)
        at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:175)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:184)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3001)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
        ... 25 more
08:36:53,588 INFO  Maxwell - starting shutdown
08:36:53,700 INFO  PositionStoreThread - Storing final position: BinlogPosition[binarylog.059977:16477513]

**Comment by bmichaud** [comment]
My colleague says that, in 1.3.0 of Maxwell, this behavior was not there. We never ran out of database sessions. Was there some recent change that caused this perhaps?

**Comment by osheroff** [comment]
i did a quick diff and nothing popped out; maxwell does indeed spin up a new connection per table: 

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/bootstrap/SynchronousBootstrapper.java#L52

but my understand of the `try ( ... ) ` block was that it was guaranteed to close the connection down at the end of the block; so in theory there should only ever be *1* connection open per query.

**Comment by osheroff** [comment]
are you using the standard `maxwell-bootstrap` utility or manually inserting rows into the database?

**Comment by osheroff** [comment]
and what does `show processlist` say about the connections during the bootstrap?

**Comment by bmichaud** [comment]
> but my understand of the try ( ... ) block was that it was guaranteed to close the connection down at the end of the block; so in theory there should only ever be 1 connection open per query.
Yes, I believe you are right.

> are you using the standard maxwell-bootstrap utility or manually inserting rows into the database?
We are inserting rows into the bootstrap table, as that is the mechanism we know about.

> and what does show processlist say about the connections during the bootstrap?
I don't know, but we can run a test and find out. Can I execute that in a SQL console? I assume so.

**Comment by osheroff** [comment]
> We are inserting rows into the bootstrap table, as that is the mechanism we know about.

there's also the supplied `maxwell-bootstrap` utility.  but either works.

> I don't know, but we can run a test and find out. Can I execute that in a SQL console? I assume so.

yeah, `show processlist` or `show full processlist` in a mysql console

**Comment by osheroff** [comment]
ever get anywhere on this?
