### ISSUE TITLE
EOFPacket error

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#514]
What might this mean?

Maxwell 1.5.1

18:45:26,872 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2050]
        at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) ~[open-replicator-1.6.0.jar:?]
        at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) ~[open-replicator-1.6.0.jar:?]
        at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
18:45:26,948 WARN  MaxwellReplicator - open-replicator stopped at position binarylog.062162:109547 -- restarting
java.io.EOFException
        at com.google.code.or.io.util.ActiveBufferedInputStream.read(ActiveBufferedInputStream.java:177)
        at com.google.code.or.io.impl.XInputStreamImpl.doFill(XInputStreamImpl.java:237)
        at com.google.code.or.io.impl.XInputStreamImpl.read(XInputStreamImpl.java:214)
        at com.google.code.or.net.impl.TransportInputStreamImpl.read(TransportInputStreamImpl.java:88)
        at com.google.code.or.io.impl.XInputStreamImpl.readInt(XInputStreamImpl.java:142)
        at com.google.code.or.io.impl.XInputStreamImpl.readInt(XInputStreamImpl.java:62)
        at com.google.code.or.net.impl.TransportInputStreamImpl.readPacketHeader(TransportInputStreamImpl.java:72)
        at com.google.code.or.net.impl.TransportInputStreamImpl.readPacket(TransportInputStreamImpl.java:57)
        at com.google.code.or.net.impl.TransportImpl.connect(TransportImpl.java:80)
        at com.google.code.or.OpenReplicator.start(OpenReplicator.java:106)
        at com.zendesk.maxwell.replication.MaxwellReplicator.ensureReplicatorThread(MaxwellReplicator.java:125)
        at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:414)
        at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:184)
18:45:28,883 INFO  Maxwell - starting shutdown

**Comment by osheroff** [comment]
means the mysql server kicked your connection off without warning.  I've seen this happen when you try to have multiple maxwell instances running on a single server with the same `client_id`.

**Comment by osheroff** [comment]
sorry, not `client_id`.  `--replica_server_id`.

**Comment by bmichaud** [comment]
Oh thanks. We do have multiple instances, but I am pretty sure the client IDs are different. I don't remember configuring the replica_server_id anywhere, so I will look into that. Is it supposed to represent the maxwell sever that is doing the replication or is it just some unique string we can make up?

**Comment by osheroff** [comment]
yeah, it lets maxwell "pretend" to be a mysql server.  It should be unique across your cluster.

btw, are you on 5.5 or 5.6?

**Comment by bmichaud** [comment]
5.6

**Comment by osheroff** [comment]
hmm, I don't think it's that then.  5.5 requires a unique server_id, but 5.6 uses a guid string that we generate.

**Comment by osheroff** [comment]
If my somewhat-out-of-it read of a the 1200 line `mysql_binlog_send` function is correct (and it's probably not), the only other way for a replica to receive an EOF packet (not an error packet) is for the replica thread to have been killed.

**Comment by osheroff** [comment]
did this recur?

**Comment by bmichaud** [comment]
I have been working on other things lately. I will check.

**Comment by marianogappa** [comment]
@osheroff fyi ran into this issue and fixed it by applying your suggested config change.

**Comment by bmichaud** [comment]
On what versions of maxwell and mysql?

**Comment by bmichaud** [comment]
Sorry, @marianogappa, what versions of mysql and maxwell did you do this, and which option did you configure, replica_server_id?

**Comment by marianogappa** [comment]
@bmichaud 

**Maxwell (via Docker image)**
maxwell:v1.7.0

**MariaDB**
Server version: 5.5.5-10.0.21-MariaDB-1~trusty-log mariadb.org binary distribution

Configured `replica_server_id`.

**Comment by osheroff** [comment]
thise was back int he open-replicator days, closing
