### ISSUE TITLE
Quickstart documentation is lacking

### ISSUE THREAD

**Issue by mmautner** [zendesk/maxwell#515]
Following the [quickstart](http://maxwells-daemon.io/quickstart/) guide, I (on my Macbook w/ homebrew-install mysql 5.7):

- download the maxwell release & unzip it
- modify my `/etc/my.cnf` and restart MySQL to reload the changes:
```shell
[mysqld]
server-id=1
log-bin=master
binlog_format=row
```
- perform the following:
```shell
$ mysql -uroot
mysql> GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE on *.* to 'maxwell'@'localhost' identified by 'XXXXXX';
mysql> GRANT ALL on maxwell.* to 'maxwell'@'localhost';
$ bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' --producer=stdout
Fri Dec 23 12:12:02 PST 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
java.sql.SQLException: Access denied for user 'maxwell'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:875)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1712)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1228)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at snaq.db.ConnectionPool.create(ConnectionPool.java:256)
	at snaq.db.ConnectionPool.create(ConnectionPool.java:71)
	at snaq.util.ObjectPool.checkOut(ObjectPool.java:377)
	at snaq.db.ConnectionPool.getConnection(ConnectionPool.java:385)
	at com.zendesk.maxwell.MaxwellContext.getReplicationConnection(MaxwellContext.java:71)
	at com.zendesk.maxwell.MaxwellContext.getServerID(MaxwellContext.java:159)
	at com.zendesk.maxwell.MaxwellContext.<init>(MaxwellContext.java:62)
	at com.zendesk.maxwell.Maxwell.<init>(Maxwell.java:30)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:177)
```
This is despite me being able to login w/ the MySQL CLI:
```shell
$ mysql -umaxwell -ppassword maxwell
..
mysql>
```

Seems like the "quickstart" is missing some critical steps about creating a user/permissions, and the never-referenced `./bin/maxwell-bootstrap` script.

A little more documentation would go a long way towards making it easier for non-core devs to use this project--I'm happy to update the docs but could use a little guidance about what all intermediate steps are missing here.

@osheroff

**Comment by osheroff** [comment]
I'm not 100% sure this is the problem, but mysql 5.7 isn't supported as of yet.

**Comment by mmautner** [comment]
Thanks--I'll give it another shot with 5.6, missed these docs: http://maxwells-daemon.io/compat/

Maybe it's worth moving these compatibility req's to the front page of the docs?

**Comment by osheroff** [comment]
sure, I can buy that.  re-open the issue if that doesn't solve it.
