### ISSUE TITLE
How to ignore MaxwellSQLSyntaxError

### ISSUE THREAD

**Issue by seua** [zendesk/maxwell#529]
Today I found a maxwell instance quit because of it can not parse some sql ddl.
The ddl is a part of gerrit  (the code review)  database.

I think it reasonable enough to let user decide whether to ignore or just quit .

Is  there some configuration to achieve it? 

`06:15:15,113 ERROR MysqlParserListener - (string_type CHAR (length ( 1 )) (column_options (default_value DEFAULT (literal (string_literal 'N')))) (column_options (nullability NOT NULL)) CHECK ( visible_to_all IN ( 'Y')

06:15:15,114 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE account_groups (
name VARCHAR(255) BINARY DEFAULT '' NOT NULL,

description TEXT,

visible_to_all CHAR(1) DEFAULT 'N' NOT NULL  CHECK (visible_to_all IN ('Y','N')),

group_uuid VARCHAR(255) BINARY DEFAULT '' NOT NULL,

owner_group_uuid VARCHAR(255) BINARY DEFAULT '' NOT NULL,

group_id INT DEFAULT 0 NOT NULL

,PRIMARY KEY(group_id)

)'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CHECK
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:47)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:71)
	at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:369)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:344)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:125)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:168)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:189)
06:15:15,215 INFO  Maxwell - starting shutdown
06:15:15,456 INFO  PositionStoreThread - Storing final position: BinlogPosition[mysql-bin.000070:122725]`

**Comment by seua** [comment]
I use include_dbs but still got same error. The gerrit DB is not in the list
