### ISSUE TITLE
Unable to start maxwell with barebone options, issue with server_id

### ISSUE THREAD

**Issue by tankchintan** [zendesk/maxwell#556]
I am trying to use the quick start guide's example of starting maxwell service via docker but I am having troubles with `server_id`.

Here is output of running 2 commands.

```
➜  maxwell docker run -it --rm osheroff/maxwell bin/maxwell --user=maxwell --password=maxwell --host=W.X.Y.Z  --producer=stdout
com.zendesk.maxwell.MaxwellCompatibilityError: server_id is '0'.  Maxwell will not function without a server_id being set.
	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureServerIDIsSet(MaxwellMysqlStatus.java:50)
	at com.zendesk.maxwell.MaxwellMysqlStatus.ensureReplicationMysqlState(MaxwellMysqlStatus.java:68)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:142)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:199)
21:27:21,392 INFO  Maxwell - starting shutdown
```

So I decided to add a `server_id`, but still no luck.
```
➜  maxwell docker run -it --rm osheroff/maxwell bin/maxwell --user=maxwell --password=maxwell --host=W.X.Y.Z --server_id=1 --producer=stdout
joptsimple.UnrecognizedOptionException: server_id is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:449)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:381)
	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:227)
	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:72)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:183)
```

**Comment by tankchintan** [comment]
Found the issue. 

Issue was that `server_id` is actually fetched from the mysql server & not from any configuration passed to maxwell. Since my local mysql was not setup to have any server_id it was being set to 0.

To resolve this, I updated my `my.cnf` file to have `server_id=1` & restarted mysql. Now its good to go.
