### ISSUE TITLE
Maxwell crash with NullPointerException

### ISSUE THREAD

**Issue by abo** [zendesk/maxwell#569]
mysql: 5.5.50
maxwell: 1.1.3
output to kafka

```
13:58:06,344 INFO  TransportImpl - connecting to host: 172.17.1.133, port: 3306
13:58:06,355 INFO  TransportImpl - connected to host: 172.17.1.133, port: 3306, context: AbstractTransport.Context[threadId=8103170,scramble=*+9z}'Da;BwT}8?p9j+4,protocolVersion=10,serverHost=172.17.1.133,serverPort=3306,serverStatus=2,serverCollation=33,serverVersion=5.5.50-log,serverCapabilities=63487]
13:58:06,355 INFO  AuthenticatorImpl - start to login, user: maxwell_sync, host: 172.17.1.133, port: 3306
13:58:06,356 INFO  AuthenticatorImpl - login successfully, user: maxwell_sync, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
13:58:06,358 WARN  MaxwellReplicator - Unhandled QueryEvent inside transaction: QueryEvent[header=BinlogEventV4HeaderImpl[timestamp=1487599041000,eventType=2,serverId=5,eventLength=64,nextPosition=1756064,flags=8,timestampOfReceipt=1487599086358],threadId=13126,elapsedTime=105,databaseNameLength=0,errorCode=0,statusVariablesLength=26,statusVariables=[QFlags2Code[flags=0], QSQLModeCode[sqlMode=0], QAutoIncrement[autoIncrementIncrement=10,autoIncrementOffset=5], QCharsetCode[characterSetClient=33,collationConnection=33,collationServer=33]],databaseName=,sql=BEGIN]
13:58:22,980 WARN  MaxwellReplicator - no heartbeat heard from server in 3889ms.  restarting replication.
13:58:22,980 INFO  TransportImpl - disconnected from 172.17.1.133:3306
13:58:22,980 INFO  TransportImpl - connecting to host: 172.17.1.133, port: 3306
13:58:22,992 INFO  TransportImpl - connected to host: 172.17.1.133, port: 3306, context: AbstractTransport.Context[threadId=8103179,scramble=aN@723J[k*-ABcPC@VrY,protocolVersion=10,serverHost=172.17.1.133,serverPort=3306,serverStatus=2,serverCollation=33,serverVersion=5.5.50-log,serverCapabilities=63487]
13:58:22,992 INFO  AuthenticatorImpl - start to login, user: maxwell_sync, host: 172.17.1.133, port: 3306
13:58:22,992 INFO  AuthenticatorImpl - login successfully, user: maxwell_sync, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
13:58:23,196 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin.000365:2222456 -- restarting
java.lang.NullPointerException
        at com.google.code.or.OpenReplicator.setupChecksumState(OpenReplicator.java:270)
        at com.google.code.or.OpenReplicator.start(OpenReplicator.java:109)
        at com.zendesk.maxwell.MaxwellReplicator.ensureReplicatorThread(MaxwellReplicator.java:88)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:283)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:118)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
        at com.zendesk.maxwell.Maxwell.run(Maxwell.java:76)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:82)
13:58:23,198 INFO  MysqlPositionStore - Storing final position: BinlogPosition[mysql-bin.000357:911040044]
```

**Comment by osheroff** [comment]
best as I can deduce mysql somehow returned an empty result set for `SELECT @@global.binlog_checksum` instead of throwing an error as it generally does.  Generally though I'm moving away from open-replicator and relying instead on shyko's binlog-connector library, so I'd prefer to not sink too too much time here. 

Suggest you upgrade and use the `--binlog_connector=true` flag

**Comment by Hackeruncle** [comment]
I also has this error.

11:53:18,881 INFO  TaskManager - stopping 3 tasks
11:53:18,881 ERROR TaskManager - cause: 
java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_45]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_45]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_45]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_45]
        at com.zendesk.maxwell.MaxwellFilter.filterListsInclude(MaxwellFilter.java:101) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.MaxwellFilter.matchesTable(MaxwellFilter.java:123) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.MaxwellFilter.matches(MaxwellFilter.java:127) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.MaxwellFilter.matches(MaxwellFilter.java:149) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.schema.ddl.ResolvedSchemaChange.shouldOutput(ResolvedSchemaChange.java:26) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:106) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:300) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:275) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:189) ~[maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:137) [maxwell-1.10.3.jar:1.10.3]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:209) [maxwell-1.10.3.jar:1.10.3]

**Comment by osheroff** [comment]
old open-replicator problem.  or something.  closing.
