### ISSUE TITLE
After attempting to bootstrap an invalid table maxwell is stuck forever

### ISSUE THREAD

**Issue by marianogappa** [zendesk/maxwell#572]
Steps to reproduce
```
INSERT INTO bootstrap (database_name, table_name) VALUES ("valid_db", "invalid_table")
```

```
21:38:15,354 INFO  OpenReplicator - starting replication at mysql-bin.006449:417502478
java.lang.RuntimeException: Couldn't find table invalid_table
	at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.findTable(SynchronousBootstrapper.java:166)
	at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:44)
	at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper$1.run(AsynchronousBootstrapper.java:74)
	at java.lang.Thread.run(Thread.java:745)
21:38:17,501 INFO  Maxwell - starting shutdown
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1219)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:340)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:682)
	at com.zendesk.maxwell.replication.MaxwellReplicator.pollV4EventFromQueue(MaxwellReplicator.java:371)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:219)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:346)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:127)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:178)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:199)
21:38:22,882 INFO  PositionStoreThread - Storing final position: BinlogPosition[mysql-bin.006449:417502478]
```

Workaround is to drop the maxwell database. Even truncating the bootstrap table doesn't work, because maxwell reads that table off the binlog apparently.

**Comment by osheroff** [comment]
@nmaquet can you look?

**Comment by yosefrat** [comment]
This from @nmaquet  code looks fairly straight forward, is it possible to add it to the main code base?

**Comment by osheroff** [comment]
fixed long ago
