### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by sergioatzori** [zendesk/maxwell#574]
Hello, I'm trying to connect to the master using ssl, but no luck.
I haven't found any doc explaining how to do this.
I'm succesfully connecting using the replication user with mysql cli:
```
mysql> status
--------------
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

Connection id:          288
Current database:
Current user:           shadow@XXX.XXX.XXX.XXX
SSL:                    Cipher in use is DHE-RSA-AES256-SHA
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.6.28-76.1-log Percona Server (GPL), Release 76.1, Revision 5759e76
Protocol version:       10
Connection:             xxxxxxx.xxxxxxxxxxxxxx.it via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:               56665
Uptime:                 40 min 46 sec

Threads: 16  Questions: 21977  Slow queries: 0  Opens: 120  Flush tables: 1  Open tables: 113  Queries per second avg: 8.984
```
But when I try to connect with maxwell I get:
```
bin/maxwell --config ../maxwell-config.properties 
java.sql.SQLException: Access denied for user 'shadow'@'XXX.XXX.XXX.XXX' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:875)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1712)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1228)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at snaq.db.ConnectionPool.create(ConnectionPool.java:256)
        at snaq.db.ConnectionPool.create(ConnectionPool.java:71)
        at snaq.util.ObjectPool.checkOut(ObjectPool.java:377)
        at snaq.db.ConnectionPool.getConnection(ConnectionPool.java:385)
        at com.zendesk.maxwell.MaxwellContext.getReplicationConnection(MaxwellContext.java:71)
        at com.zendesk.maxwell.MaxwellContext.getServerID(MaxwellContext.java:159)
        at com.zendesk.maxwell.MaxwellContext.<init>(MaxwellContext.java:62)
        at com.zendesk.maxwell.Maxwell.<init>(Maxwell.java:36)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:188)
```

Please help!

EDIT: my maxwell version is 1.7.2

**Comment by sergioatzori** [comment]
Sorry, but...bump!
I guess there's not ssl support.

**Comment by osheroff** [comment]
got ssl support in v1.13.0
