### ISSUE TITLE
"int(11) COLLATE utf8_unicode_ci    "  when i run the sql  ,,the maxwell is error ,how can i modify that ? my maxwell's version is 1.5.0

### ISSUE THREAD

**Issue by rongyousu** [zendesk/maxwell#587]
ALTER TABLE `you` ADD  `feee` int(11) COLLATE utf8_unicode_ci  NOT NULL DEFAULT '0' COMMENT 'eee' AFTER `id`
ALTER TABLE `you` ADD  `ddd` int COLLATE utf8_unicode_ci  NOT NULL DEFAULT '0' COMMENT 'eee' AFTER `id`

14:36:22,471 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE `you` ADD  `ddd` int COLLATE utf8_unicode_ci  NOT NULL DEFAULT '0' COMMENT 'eee' AFTER `id`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: COLLATE
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:79)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:91)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:47)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
	at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:465)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:435)
	at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:184)

**Comment by rongyousu** [comment]
the version 1.8.1 is also that:

16:55:13,628 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE `you` ADD  `dddooo` int COLLATE utf8_unicode_ci  NOT NULL DEFAULT '0' COMMENT 'eee' AFTER `id`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: COLLATE
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:91)
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:71)
	at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:376)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:350)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:127)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:182)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:203)
16:55:13,644 INFO  Maxwell - starting shutdown

**Comment by osheroff** [comment]
int fields can have collation, eh?  jesus mysql.  Ok, will look into a patch.

**Comment by osheroff** [comment]
this is fixed in 1.8.2
