### ISSUE TITLE
ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE

### ISSUE THREAD

**Issue by hamidrezasattari** [zendesk/maxwell#589]
Hi
maxwell fails in following create table command. Is there any way to fix this issue: 

ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE XXXXXXXXXXX_XXXXXXXX_XXXXXXX_XXXXXX

  (location_name varchar(50) NOT NULL DEFAULT '0',
   district_name varchar(100) NOT NULL DEFAULT '',
   school_name varchar(100) NOT NULL DEFAULT '',
   user_id mediumint(8) unsigned NOT NULL DEFAULT '0',
   student_id varchar(70) NOT NULL DEFAULT '',
   grade_level tinyint(2) unsigned NOT NULL DEFAULT '0',
   program_language varchar(10) not null DEFAULT '',
   users_native_language varchar(10) not null DEFAULT '',
   race varchar(70) NOT NULL DEFAULT '',
   ethnicity varchar(70) NOT NULL DEFAULT '',
   ell char(1) NOT NULL DEFAULT 'N',
   special_classification varchar(255) NOT NULL DEFAULT '',
   ses char(255) NOT NULL DEFAULT 'N',
   parent_language varchar(10) not null DEFAULT '',
   sped char(100) NOT NULL DEFAULT 'N',   
   gender char(1) NOT NULL DEFAULT '',
   math_level tinyint(2) NOT NULL DEFAULT '0',
   editions varchar(255) NOT NULL DEFAULT '',
   pretest_date varchar(20) NOT NULL DEFAULT '',
   pretest_level tinyint(2) unsigned NOT NULL DEFAULT '0',
   pretest_form varchar(10) NOT NULL DEFAULT '',
   pretest_score smallint(5) NOT NULL DEFAULT '0',
   current_lexile smallint(5) NOT NULL DEFAULT '0',
   current_uncertainty smallint(5) unsigned NOT NULL DEFAULT '0',
   last_adjustment_date varchar(20) NOT NULL DEFAULT '',
   levelset_writing_start_date1 varchar(20) NOT NULL DEFAULT '',
   levelset_writing_enddate1 varchar(20) NOT NULL DEFAULT '',
   levelset_writing_prompt_id1 varchar(20) NOT NULL DEFAULT '',
   levelset_writing_prompt1_grade_form_type varchar(30) NOT NULL DEFAULT '',
   levelset_writing_essay_text1 mediumtext NOT NULL,
   levelset_writing_minutes1 smallint(5) unsigned NOT NULL DEFAULT '0',
   levelset_writing_prior_measure1 smallint(5) NOT NULL DEFAULT 0, 
   levelset_writing_prior_sigma1 smallint(5) unsigned NOT NULL DEFAULT '0', 
   levelset_writing_score1 smallint(5) NOT NULL DEFAULT '0',
   levelset_writing_uncertainty1 smallint(5) NOT NULL DEFAULT '0',
   levelset_writing_measure1 smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_measure_uncertainty1 smallint(5) unsigned NOT NULL DEFAULT '0',
   levelset_writing_start_date2 varchar(20) NOT NULL DEFAULT '',
   levelset_writing_enddate2 varchar(20) NOT NULL DEFAULT '',
   levelset_writing_prompt_id2 varchar(20) NOT NULL DEFAULT '',
   levelset_writing_prompt2_grade_form_type varchar(30) NOT NULL DEFAULT '',
   levelset_writing_essay_text2 mediumtext NOT NULL,
   levelset_writing_minutes2 smallint(5) unsigned NOT NULL DEFAULT '0',
   levelset_writing_prior_measure2 smallint(5) NOT NULL DEFAULT -000, 
   levelset_writing_prior_sigma2 smallint(5) unsigned NOT NULL DEFAULT '0', 
   levelset_writing_score2 smallint(5) NOT NULL DEFAULT '0',
   levelset_writing_uncertainty2 smallint(5) NOT NULL DEFAULT '0',
   levelset_writing_measure2 smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_measure_uncertainty2 smallint(5) unsigned NOT NULL DEFAULT '0',
   log_id int(10) unsigned NOT NULL DEFAULT '0',
   levelset_writing_measure_fall smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_measure_fall_uncertainty smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_measure_winter smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_measure_winter_uncertainty smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_fall_to_winter_change smallint(5) NOT NULL DEFAULT 0,
   levelset_writing_reported_measure varchar(20) NOT NULL DEFAULT '',
   PRIMARY KEY (`user_id`,`log_id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: -
   at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:86)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
   at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
   at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:102)
   at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
   at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:91)
   at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:71)
   at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:376)
   at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:350)
   at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:127)
   at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
   at com.zendesk.maxwell.Maxwell.start(Maxwell.java:182)
   at com.zendesk.maxwell.Maxwell.main(Maxwell.java:203)
15:27:08,830 INFO  Maxwell - starting shutdown

**Comment by osheroff** [comment]
fixes for negative numbers as default values went into 1.9.0
