### ISSUE TITLE
alter table drop partition problem

### ISSUE THREAD

**Issue by Exus** [zendesk/maxwell#600]
maxwell 1.8.1, MySQL 5.6.23-72.1 (percona)

I've found issue with handling partitioned tables. We are using partitions for fast deleting data by dropping old partitions. Here is example of table:

```sql
CREATE TABLE `sas` (
  `sub` bigint(20) unsigned NOT NULL,
  `mes` bigint(20) unsigned NOT NULL,
  `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC
/*!50100 PARTITION BY RANGE (UNIX_TIMESTAMP(`created_on`))
(PARTITION sas_1474675200 VALUES LESS THAN (1474675200) ENGINE = InnoDB,
 PARTITION sas_1474761600 VALUES LESS THAN (1474761600) ENGINE = InnoDB,
 PARTITION sas_1474848000 VALUES LESS THAN (1474848000) ENGINE = InnoDB,
 PARTITION sas_1474934400 VALUES LESS THAN (1474934400) ENGINE = InnoDB,
 ...)
```

Here are query for creating new partition and dropping old:

```sql
ALTER TABLE `sa` ADD PARTITION (PARTITION `sas_1490313600` VALUES LESS THAN (1490313600);
ALTER TABLE `sas` DROP PARTITION `sas_1474588800`;
```

Maxwell handles adding partition, but exits on drop

```
08:47:47,615 INFO  AbstractSchemaStore - storing schema @BinlogPosition[4e38178c-cbf7-11e4-ba38-f04da2754ae4:1-1613103420,c7909cd5-76f2-11e4-8fd5-f04da2754ae4:1-3096] after applying "ALTER TABLE `sa`     ADD PARTITION (         PARTITION `sas_1490313600`         VALUES LESS THAN (1490313600)     )"
08:47:47,624 ERROR MysqlParserListener - (partition_names `sas_1474588800`)
08:47:47,624 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE `sas`
    DROP PARTITION `sas_1474588800`'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: `sas_1474588800`
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:91)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:71)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:289)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:264)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:127)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:182)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:203)
08:47:47,762 INFO  Maxwell - starting shutdown
```

**Comment by wojtekzw** [comment]
+1

**Comment by macio** [comment]
+1
