### ISSUE TITLE
running kafka producer reading logs from binlogs throws exception

### ISSUE THREAD

**Issue by sabdullah** [zendesk/maxwell#602]
Run this command after setting up a user on mysql and granting permission to read aa1 database

sudo docker run -it --rm osheroff/maxwell bin/maxwell --user=$MYSQL_USERNAME --password=$MYSQL_PASSWORD --host=$MYSQL_HOST --producer=kafka --kafka.bootstrap.servers=$KAFKA_HOST:$KAFKA_PORT

Result:
java.lang.RuntimeException: Couldn't find database aa1
    at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:24)
    at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:42)
    at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:250)
    at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:346)
    at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:127)
    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:178)
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:199)
21:44:01,715 INFO  Maxwell - starting shutdown
21:44:01,833 INFO  PositionStoreThread - Storing final position: BinlogPosition[mysql-bin-changelog.004443:1373

**Comment by sabdullah** [comment]
the issue seems to be stale maxwell database. it was wiped and recreated and error was gone.
