### ISSUE TITLE
Missing Default Constructor in RowMap

### ISSUE THREAD

**Issue by komibajaj** [zendesk/maxwell#604]
I am trying to use Dozer for transforming from entity into RowMap and received the following exception, as RowMap is missing default no arg constructor.

[ERROR] [03/23/2017 11:23:59.482] [etl-akka-akka.actor.default-dispatcher-3] [akka://etl-akka/user/transformActor] java.lang.NoSuchMethodException: com.zendesk.maxwell.row.RowMap.<init>()
org.dozer.MappingException: java.lang.NoSuchMethodException: com.zendesk.maxwell.row.RowMap.<init>()
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82)
	at org.dozer.factory.ConstructionStrategies$ByConstructor.newInstance(ConstructionStrategies.java:261)
	at org.dozer.factory.ConstructionStrategies$ByConstructor.create(ConstructionStrategies.java:245)
	at org.dozer.factory.DestBeanCreator.create(DestBeanCreator.java:65)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:177)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:124)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:119)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
	at com.webpt.actor.TransformActor.onReceive(TransformActor.java:32)
	at com.webpt.actor.TransformActor$$FastClassBySpringCGLIB$$7bab0b85.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.webpt.actor.TransformActor$$EnhancerBySpringCGLIB$$1ac4d0c6.onReceive(<generated>)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
	at akka.actor.UntypedActor$$FastClassBySpringCGLIB$$eab15c2b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.webpt.actor.TransformActor$$EnhancerBySpringCGLIB$$1ac4d0c6.aroundReceive(<generated>)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NoSuchMethodException: com.zendesk.maxwell.row.RowMap.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.dozer.factory.ConstructionStrategies$ByConstructor.newInstance(ConstructionStrategies.java:257)
	... 39 more

**Comment by komibajaj** [comment]
The workaround I did to go around this is do dual transform.

So instead of MyObject => RowMap

I had to do MyObject => JSONObject => RowMap -> using RowMapDeserializer functionality.

Not a bad solution. Deserializer works great and also acts as Validator so that is good.

If it is closed or lowered in priority it will be OK.

**Comment by osheroff** [comment]
looks like we fixed this one
