### ISSUE TITLE
Assertion failure in InflightMessageList

### ISSUE THREAD

**Issue by nzwalker** [zendesk/maxwell#613]
Hey folks,

We ran into an issue today where a restarted replication stream caused an NPE within the Inflight Message Tracking:

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/producer/InflightMessageList.java#L38

```
2017-04-09T19:53:34.518941+00:00 <host> maxwell[21910]: 19:53:27,727 WARN  MaxwellReplicator - no heartbeat heard from server in 2446ms.  restarting replication.
2017-04-09T19:53:45.604717+00:00 <host> maxwell[21910]: 	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
2017-04-09T19:53:45.604728+00:00 <host> maxwell[21910]: 19:53:45,175 ERROR RecordBatch - Error executing user-provided callback on message for topic-partition maxwell-group-01-0:
2017-04-09T19:53:45.604733+00:00 <host> maxwell[21910]: java.lang.NullPointerException
2017-04-09T19:53:45.604737+00:00 <host> maxwell[21910]: 	at com.zendesk.maxwell.producer.InflightMessageList.completeMessage(InflightMessageList.java:40) ~[maxwell-1.8.1.jar:1.8.1]
2017-04-09T19:53:45.604741+00:00 <host> maxwell[21910]: 	at com.zendesk.maxwell.producer.AbstractAsyncProducer$CallbackCompleter.markCompleted(AbstractAsyncProducer.java:23) ~[maxwell-1.8.1.jar:1.8.1]
2017-04-09T19:53:45.604745+00:00 <host> maxwell[21910]: 	at com.zendesk.maxwell.producer.KafkaCallback.onCompletion(MaxwellKafkaProducer.java:60) ~[maxwell-1.8.1.jar:1.8.1]
2017-04-09T19:53:45.604749+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.RecordBatch.done(RecordBatch.java:97) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604752+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:299) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604755+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:260) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604762+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.Sender.access$100(Sender.java:56) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604767+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.Sender$1.onComplete(Sender.java:342) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604770+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:274) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604774+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:216) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604777+00:00 <host> maxwell[21910]: 	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:128) [kafka-clients-0.9.0.1.jar:?]
2017-04-09T19:53:45.604780+00:00 <host> maxwell[21910]: 	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
```

Our downstream services detected the fact that this caused messages to be dropped - but I'm not entirely sure of the mechanism that causes that.

It's quite hard to work out whats happening post-hoc, but I think order of events is:

- Message at position P is added to IFML, sent to broker async
- Replication thread restarts (RDS networking!)
- Replicator resends the same event, resulting in another message P being added to IFML
- Message 1 completes callback, removes from IFML
- Message 2 completes callback - NPE!

Note that the `assert` is supposed to guard against this, but this requires that assertions are turned on. Plus, this is the only instance of assert in the non-test codebase!

I'm hopefully going to fix this in our fork by disallowing duplicate messages to be added to the map (via `putIfAbsent`), but I'm not sure if this fits in with upstream. Happy to take suggestions!

**Comment by timbertson** [comment]
`putIfAbsent` would remove duplicates in the list, but it sounds like the real issue comes from publishing a message with the same offset twice? Unless you prevent the second callback, you're still going to get a NPE. In which case you would need to both `putIfAbsent` and then explicitly ignore the null when the second callback can't find an InFlightMessage. Which I _think_ ought to be safe.

**Comment by nzwalker** [comment]
Yes, you're right in the sense that you need to prevent the double sent at the time it adds it into the inflight message list. Luckily, the message is added *before* its sent via Kafka, so I have modified it to simply throw an exception if the message is already in the list.

Kind of related, I've seen that the replication restart can cause some serious issues around transaction attribution, but haven't been able to track down a replication / test case. I can only infer whats happening from the output topic.

Here is a small sample of the output:

```
{"table":"a","type":"delete","ts":1491742023,"xid":526008347,"position":"mysql-bin-changelog.035446:687107"}
{"table":"a","type":"insert","ts":1491742023,"xid":526008347,"position":"mysql-bin-changelog.035446:687226","commit":true}
{"table":"b","type":"update","ts":1491742026,"xid":526008347,"position":"mysql-bin-changelog.035446:702075"}
{"table":"c","type":"insert","ts":1491742026,"xid":526008347,"position":"mysql-bin-changelog.035446:702880"}
{"table":"d","type":"insert","ts":1491742026,"xid":526008347,"position":"mysql-bin-changelog.035446:703279"}
{"table":"e","type":"insert","ts":1491742026,"xid":526008347,"position":"mysql-bin-changelog.035446:703468"}
{"table":"a","type":"delete","ts":1491742023,"xid":526008347,"position":"mysql-bin-changelog.035446:687107"}
{"table":"a","type":"insert","ts":1491742023,"xid":526008347,"position":"mysql-bin-changelog.035446:687226","commit":true}
```

Note how the second transaction "time travels" and changes its XID to one from an earlier transaction. I suspect whats happening is that earlier row events are being replayed somehow through the replication stream which causes the transaction rows to be misattributed. This is probably possible because the replication position is checkpointed by `setPosition`, which I assume means that when the replication thread restarts it can start emitting messages that are already sitting in the `MaxwellReplicator` event queue.

I'm currently testing this theory in our environment by adding a check for monotonicity in the binlog position for the event processing. It'll be interesting to see how often this case occurs, as I can see replication threads are regularly restarted in our RDS environment - so hopefully this case will be triggered!

```java
	private RowMapBuffer getTransactionRows() throws Exception {
		BinlogEventV4 v4Event;
		com.zendesk.maxwell.replication.AbstractRowsEvent event;

		RowMapBuffer buffer = new RowMapBuffer(MAX_TX_ELEMENTS);
		BinlogPosition lastPosition = null;

		while ( true ) {
			v4Event = pollV4EventFromQueue();

			// currently to satisfy the test interface, the contract is to return null
			// if the queue is empty.  should probably just replace this with an optional timeout...
			if (v4Event == null) {
				ensureReplicatorThread();
				continue;
			}

			setReplicatorPosition((AbstractBinlogEventV4) v4Event);
			BinlogPosition current = eventBinlogPosition((AbstractBinlogEventV4) v4Event);

			if (lastPosition != null && lastPosition.newerThan(current)) {
				// Monotonicity violation!
				LOGGER.error("Monotonicity violation in binlog processing, last event was {} current event {}", lastPosition.toString(), current.toString());
				throw new RuntimeException("Monotonicity violation in row grouping");
			}
```

**Comment by nzwalker** [comment]
So looks like the detector worked - discovered this today:

```
23:28:56,364 WARN  MaxwellReplicator - no heartbeat heard from server in 4106ms.  restarting replication.
23:29:05,585 ERROR MaxwellReplicator - Monotonicity violation in binlog processing, last event was BinlogPosition[mysql-bin-changelog.046876:4150394] current event BinlogPosition[mysql-bin-changelog.046876:0]
java.lang.RuntimeException: Monotonicity violation in row grouping
```

Its a bit unusual that the position goes to 0 in this case - still checking that out.

**Comment by timbertson** [comment]
@nzwalker have you experimented with the newer `--binlog_connector` mode? We've been digging into the replicator restart behaviour, and we think the messages are probably overlapping because the replicator's position is managed asynchronously (it doesn't get updated until a different thread on the other side of of a queue handles the message). The binlog_connector code manages its position internally (and synchronously), so that may be a simpler way to avoid replayed events.

**Comment by nzwalker** [comment]
@timbertson I haven't experimented with the binlog_connector, but I will give it a go on our test cluster and see if the incidence decreases! Thanks very much for looking into it, I was just tearing my hair out trying to figure out exactly where the bug was!
