### ISSUE TITLE
Exception in thread "maxwell-kafka-worker: java.lang.IllegalStateException: Memory records is not writable

### ISSUE THREAD

**Issue by timbertson** [zendesk/maxwell#621]
```
Exception in thread "maxwell-kafka-worker" java.lang.RuntimeException: java.lang.IllegalStateException: Memory records is not writable
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.run(MaxwellKafkaProducer.java:123)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Memory records is not writable
	at org.apache.kafka.common.record.MemoryRecords.append(MemoryRecords.java:93)
	at org.apache.kafka.clients.producer.internals.RecordBatch.tryAppend(RecordBatch.java:69)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:168)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:435)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.sendAsync(MaxwellKafkaProducer.java:163)
	at com.zendesk.maxwell.producer.AbstractAsyncProducer.push(AbstractAsyncProducer.java:63)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.run(MaxwellKafkaProducer.java:121)
	... 1 more
```

The underlying exception seems to be a kafka issue (which is fixed in 0.10), but maxwell as of 1.7.0 used to crash and come back up. As of 1.7.1 it only causes the producer thread to die, but maxwell doesn't terminate (resulting in no further messages).

Already fixed by #615, but filing as an issue so I can link to it.

**Comment by vmishra** [comment]
I got this issue on the latest version of Maxwell. I'm on Kafka 0.10.2. The Maxwell daemon stopped with following exception in the log.
```

0:22:39,940 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: RUNNING)
00:22:39,951 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[bin-log.000296:17140914], lastHeartbeat=0]
00:22:39,991 INFO  ServerConnector - Stopped ServerConnector@1ea07980{HTTP/1.1}{0.0.0.0:9190}
00:22:40,007 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@57a02e8f{/,null,UNAVAILABLE}
00:22:40,210 INFO  TaskManager - stopped all tasks
java.lang.IllegalStateException: Memory records is not writable
	at org.apache.kafka.common.record.MemoryRecords.append(MemoryRecords.java:93)
	at org.apache.kafka.clients.producer.internals.RecordBatch.tryAppend(RecordBatch.java:69)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:168)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:435)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.sendAsync(MaxwellKafkaProducer.java:217)
	at com.zendesk.maxwell.producer.AbstractAsyncProducer.push(AbstractAsyncProducer.java:108)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.run(MaxwellKafkaProducer.java:172)
	at java.lang.Thread.run(Thread.java:745)
```
