### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#638]
i received the following errros. not sure, if this is the correct way to run the docker for maxwell.
would you point me to the right instructions, please.

> 

$ docker pull osheroff/maxwell
Using default tag: latest
latest: Pulling from osheroff/maxwell
Digest: sha256:8df8f1a0fd668dbf02e8214ec29d6c4f27944cf0bb9f679f0e6e2350939260ee
Status: Image is up to date for osheroff/maxwell:latest

$ docker run osheroff/maxwell
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at snaq.db.ConnectionPool.create(ConnectionPool.java:256)
	at snaq.db.ConnectionPool.create(ConnectionPool.java:71)
	at snaq.util.ObjectPool.checkOut(ObjectPool.java:377)
	at snaq.db.ConnectionPool.getConnection(ConnectionPool.java:385)
	at com.zendesk.maxwell.MaxwellContext.getReplicationConnection(MaxwellContext.java:71)
	at com.zendesk.maxwell.MaxwellContext.getServerID(MaxwellContext.java:159)
	at com.zendesk.maxwell.MaxwellContext.<init>(MaxwellContext.java:62)
	at com.zendesk.maxwell.Maxwell.<init>(Maxwell.java:36)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:188)
Caused by: java.net.UnknownHostException: --producer=kafka: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1269)
	at java.net.InetAddress.getAllByName(InetAddress.java:1185)
	at java.net.InetAddress.getAllByName(InetAddress.java:1119)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 23 more

**Comment by liulikun** [comment]
You need to have `mysql` running in docker first, then run:

```
docker run -it --net docker -e MYSQL_HOST\=mysql -e MYSQL_USERNAME\=xxx -e MYSQL_PASSWORD\=xxx osheroff/maxwell
```

**Comment by sreev** [comment]
docker: Error response from daemon: network docker not found.

would you share full instructions, please. @liulikun

**Comment by liulikun** [comment]
How did you run `mysql` in the docker? The docker can be setup in many different ways, so the way I run it may not work for you (like I have a user defined network `docker`). But essentially, you need to pass a few env vars to the container as specified here: https://github.com/zendesk/maxwell/blob/master/Dockerfile#L22, also you'll need to have kafka running in the docker too. Otherwise you'll need to edit `Dockerfile` and build your own image locally.

**Comment by timbertson** [comment]
Just a FYI, the docker image is a bit out of date too (see #601) - it should still work, but you'll need to build the Dockerfile yourself to get the latest and greatest right now.

**Comment by sreev** [comment]
looks like we need a Dockerfile with all the components needed to get started.
zookeeper for kafka (default localhost)
kafka (default localhost)
mysql (option to select a version, default localhost)
load a sample db
config changes required for maxwell to work
a small jdbc jar that runs few sql statements, so binlog is created.
maxwell to put it on kafka
a small kafka client jar to output those messages from kafka.

anything missing ?

**Comment by timbertson** [comment]
@sreev I don't think it makes sense to put all that in one Dockerfile - the point of a maxwell container is to run maxwell. There are presumably docker images for mysql + kafka etc already, trying to combine them into one image would just duplicate those efforts. What could be useful is a set of instructions on running maxwell + mysql + kafka containers together (including config) though.

**Comment by tankchintan** [comment]
@timbertson is there a plan as of right now to transparently update docker image tags, as soon as a new version is cut?

This way we can just inherit from Docker image, rather than building the maxwell docker on our own.

**Comment by timbertson** [comment]
@tankchintan yes, we'd prefer to automate this rather than manually pushing each release.

**Comment by liulikun** [comment]
Zendesk has just published the new docker image built from the latest code: https://hub.docker.com/r/zendesk/maxwell/, and docker hub will auto build the latest image in the future.
