### ISSUE TITLE
An error occurred at maxwell startup

### ISSUE THREAD

**Issue by AlvinYang-2017** [zendesk/maxwell#663]
The following is the error message：

> 14:52:58,485 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
14:52:58,489 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
14:52:58,526 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
14:52:58,526 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: STOPPED)
14:52:59,034 ERROR MaxwellKafkaProducer - Topic 'maxwell' name does not exist. Exception: java.lang.InterruptedException
14:52:59,234 INFO  TaskManager - stopped all tasks
java.lang.IndexOutOfBoundsException: Index: 58, Size: 58
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.zendesk.maxwell.schema.ColumnWithDefinitionList$ColumnWithDefinitionIterator.next(ColumnWithDefinitionList.java:52)
        at com.zendesk.maxwell.schema.ColumnWithDefinitionList$ColumnWithDefinitionIterator.next(ColumnWithDefinitionList.java:27)
        at com.zendesk.maxwell.replication.AbstractRowsEvent.jsonMaps(AbstractRowsEvent.java:166)
        at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:233)
        at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:337)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:141)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:30)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:212)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:151)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:236)

I checked that kafka included maxwell topic，somebody tell me what‘s the other reason for this error? thanks!

**Comment by liulikun** [comment]
It seems maxwell might have lost tracks of some schema changes due to some exceptions. If you check `schemas` table, you should be able to see the schema change history, especially check `base_schema_id` column, if the value in that column is not continuous, it might indicate the issue.

**Comment by AlvinYang-2017** [comment]
when i debugger the code, i found the table columns size not equal row columns size so cause the java.lang.IndexOutOfBoundsException, when AbstractSchemaStore the other table is ok, i don't know  my binlog file is a problem, or the code has a bug , i used maxwell version is 1.10.0 .
Hope to help me, thank you !

**Comment by liulikun** [comment]
It's hard to solve this problem without access to maxwell tables and logs. I think maxwell lost track a db migration to the table. Did you know if there was a new column added? Again if you can check `schemas` table which tracks the migration history, you may have a clue. 

Also I recommend to set `binlog_connector=true` in your config file to switch to binlog connector library which we found more reliable.

**Comment by AlvinYang-2017** [comment]
thanks for the help!

Do you how can i record the "posion" binlog message and any trace/data when issue happens again? We've checked journalctl log, it doesn't gave more hints.

We've published maxwell to our production service, it has been running fine for weeks, but this issue happens again today.

**Comment by liulikun** [comment]
Maxwell will exit and log the final binlog position on this error, then you can decode the actual binlog file and find that final position to see the actual SQL command.  BTW, which version are you running, did you set `binlog_connector=true`? Also did you have database master failover before the error?

**Comment by AlvinYang-2017** [comment]
I found postition table  get  last binlog_file and binlog_position "28542868" then use mysqlbinlog decode get the following
![11](https://user-images.githubusercontent.com/12343433/28855938-9e621706-7772-11e7-8131-2323746ba442.png)

Does maxwell can handle TEMPORARY TABLE？

I didn't set **binlog_connector=true** ， i not found this config in http://maxwells-daemon.io/config/. 

I think maxwell can get binlog at that time but can't handle TEMPORARY TABLE,
How can i specify maxwell read this binlogfile replay this question?

**Comment by liulikun** [comment]
Yes, maxwell can parse `DROP TEMPORARY TABLE`. The last position seems just a commit event, check the last couple of events before and after this position. I'm feeling there is a migration happened and maxwell failed to capture that migration (also check the logs, the log on INFO level should contain some information related to this). All the migrations should be captured in `schemas` table.

**Comment by liulikun** [comment]
Also recommend to use `binlog_connector=true`, or update maxwell to 1.10.5, which makes `binlog_connector` the only replicator.

**Comment by AlvinYang-2017** [comment]
Ok , thanks , i'm using maxwell 1.10.1 now , i'll upgrade it to 1.10.5.

Then I reappear the problem at test environment and i found the real cause of the problem.

We using Ali cloud MySqlRDS, when i insert into a record in the table without primay key, binlog will auto generate a internal key and cause columns number inconsistent.  maxwell running to ColumnWithDefinitionList.next() function will throw java.lang.IndexOutOfBoundsException exception. 

Here is my test method.
```
CREATE  TABLE  test(
name varchar(50)
);
INSERT test(name) VALUES('no primary key');
```

![11](https://user-images.githubusercontent.com/12343433/28864440-209ac3ea-779f-11e7-8ffe-fe73723bd541.png)

I don't know the reason is not the use of Ali cloud or maxwell can't handle this situation, If you can reappear the problem, help fix it, thanks a lot!

**Comment by liulikun** [comment]
Good find! It's not straightforward to fix this. I guess you can have a workaround by adding a primary key to all tables.
