### ISSUE TITLE
how to run two maxwell?

### ISSUE THREAD

**Issue by jayws** [zendesk/maxwell#669]
## # hi,all!who can help me?when i want to run two maxwell but the other procedure is stop
 1. the execute statement：
    (1) bin/maxwell --user='maxwell' --password='123456' --host='127.0.0.1' --include_tables test_q --producer=kafka --kafka.bootstrap.servers=data:9092 --kafka_topic testmaxwell
    (2)bin/maxwell --user='maxwell' --password='123456' --host='127.0.0.1' --producer=kafka --kafka.bootstrap.servers=data:9092 --kafka_topic test_maxwell1 --include_tables test
     
2. the error message：
     
     17:29:40,921 INFO  TaskManager - stopping 3 tasks
17:29:40,924 ERROR TaskManager - cause: 
com.zendesk.maxwell.errors.DuplicateProcessException: Expected a heartbeat value of 1496309370635 but didn't find it.  Is another Maxwell process running with the same client_id?
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:149) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:89) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:83) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:110) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40) [maxwell-1.10.1.jar:1.10.1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
17:29:41,417 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
17:29:41,628 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
17:29:42,244 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: STOPPED)
17:29:42,389 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: RUNNING)
17:29:43,256 INFO  TaskManager - stopped all tasks
com.zendesk.maxwell.errors.DuplicateProcessException: Expected a heartbeat value of 1496309370635 but didn't find it.  Is another Maxwell process running with the same client_id?
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:149)
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:89)
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:83)
        at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:110)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40)
        at java.lang.Thread.run(Thread.java:745)

thanks!!!

**Comment by osheroff** [comment]
pass unique `--client_id` parameters to each maxwell.

**Comment by jayws** [comment]
thanks, i have set --client_id,but the kafka topic is not data,can you give me an example?
 this is my procedure:
    bin/maxwell --user='maxwell' --password='123456' --host='127.0.0.1' --include_tables=test_q --producer=kafka --kafka.bootstrap.servers=data:9092 --kafka_topic=testmaxwell --include_dbs=test --client_id=111 --schema_database=test

**Comment by saup007** [comment]
--client_id=100 --replical_server_id=100

**Comment by pragyagoel04** [comment]
tiny typo up there, it's `replica_server_id`
