### ISSUE TITLE
Maxwell: Keep getting failed to parse bin log,  java.lang.RuntimeException: assertion failed!  We left -xxx unconsumed bytes and couple of other warnings.

### ISSUE THREAD

**Issue by anandaverma** [zendesk/maxwell#686]
Running maxwell agaisnt RDS master node. Don't have any replica yet. Master node is backed up daily. When I am running the same on my dev server with my own mariaDB instance it works file. But on prod server with RDS recieving following errors and warnings. Also, it is crashing very often.  

```
maxwell_1  | 07:30:25,558 ERROR AbstractBinlogParser - failed to parse binlog
maxwell_1  | java.lang.RuntimeException: assertion failed!  We left -2153 unconsumed bytes in the buffer for event: BinlogEventV4HeaderImpl[timestamp=1498721400000,eventType=24,serverId=1860260942,eventLength=158,nextPosition=11633,flags=0,timestampOfReceipt=1498721425558]
maxwell_1  | 	at com.google.code.or.net.impl.EventInputStream.finishEvent(EventInputStream.java:73) ~[open-replicator-1.6.0.jar:?]
maxwell_1  | 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:166) ~[open-replicator-1.6.0.jar:?]
maxwell_1  | 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
maxwell_1  | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
maxwell_1  | 07:30:25,662 WARN  MaxwellReplicator - open-replicator stopped at position mysql-bin-changelog.123894:11633 -- restarting
maxwell_1  | 07:30:25,676 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123894:11633
maxwell_1  | 07:30:27,681 WARN  MaxwellReplicator - no heartbeat heard from server in 2002ms.  restarting replication.
maxwell_1  | 07:30:27,696 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123894:11755
maxwell_1  | 07:30:27,698 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721400000,eventType=24,serverId=1860260942,eventLength=112,nextPosition=11867,flags=0,timestampOfReceipt=1498721427698]
maxwell_1  | 07:30:29,702 WARN  MaxwellReplicator - no heartbeat heard from server in 2003ms.  restarting replication.
maxwell_1  | 07:30:29,719 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:449
maxwell_1  | 07:30:29,720 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721400000,eventType=24,serverId=1860260942,eventLength=158,nextPosition=607,flags=0,timestampOfReceipt=1498721429720]
maxwell_1  | 07:30:31,724 WARN  MaxwellReplicator - no heartbeat heard from server in 2002ms.  restarting replication.
maxwell_1  | 07:30:31,740 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:731
maxwell_1  | 07:30:31,741 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721400000,eventType=24,serverId=1860260942,eventLength=146,nextPosition=877,flags=0,timestampOfReceipt=1498721431741]
maxwell_1  | 07:30:33,745 WARN  MaxwellReplicator - no heartbeat heard from server in 2003ms.  restarting replication.
maxwell_1  | 07:30:33,759 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:1001
maxwell_1  | 07:30:33,760 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721400000,eventType=24,serverId=1860260942,eventLength=146,nextPosition=1147,flags=0,timestampOfReceipt=1498721433760]
maxwell_1  | 07:30:35,763 WARN  MaxwellReplicator - no heartbeat heard from server in 2002ms.  restarting replication.
maxwell_1  | 07:30:35,779 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:1269
maxwell_1  | 07:30:35,781 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721400000,eventType=24,serverId=1860260942,eventLength=112,nextPosition=1381,flags=0,timestampOfReceipt=1498721435781]
maxwell_1  | 07:30:35,789 INFO  SynchronousBootstrapper - bootstrapping started for STARFOX.INSTANCE_DISTRIBUTION_RESPONSE, binlog position is Position[BinlogPosition[mysql-bin-changelog.123895:1855], lastHeartbeat=0]
maxwell_1  | 07:30:36,622 INFO  SynchronousBootstrapper - bootstrapping ended for STARFOX.INSTANCE_DISTRIBUTION_RESPONSE
maxwell_1  | 07:32:02,017 WARN  MaxwellReplicator - no heartbeat heard from server in 2004ms.  restarting replication.
maxwell_1  | 07:32:02,061 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:8910
maxwell_1  | 07:32:02,063 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721520000,eventType=24,serverId=1860260942,eventLength=146,nextPosition=9056,flags=0,timestampOfReceipt=1498721522063]
maxwell_1  | 07:32:04,067 WARN  MaxwellReplicator - no heartbeat heard from server in 2003ms.  restarting replication.
maxwell_1  | 07:32:04,099 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:9178
maxwell_1  | 07:32:04,101 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721520000,eventType=24,serverId=1860260942,eventLength=146,nextPosition=9324,flags=0,timestampOfReceipt=1498721524101]
maxwell_1  | 07:32:06,106 WARN  MaxwellReplicator - no heartbeat heard from server in 2002ms.  restarting replication.
maxwell_1  | 07:32:06,222 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:9446
maxwell_1  | 07:32:06,223 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721520000,eventType=24,serverId=1860260942,eventLength=158,nextPosition=9604,flags=0,timestampOfReceipt=1498721526223]
maxwell_1  | 07:32:08,227 WARN  MaxwellReplicator - no heartbeat heard from server in 2003ms.  restarting replication.
maxwell_1  | 07:32:08,241 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:9726
maxwell_1  | 07:32:08,243 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721520000,eventType=24,serverId=1860260942,eventLength=146,nextPosition=9872,flags=0,timestampOfReceipt=1498721528243]
maxwell_1  | 07:32:10,246 WARN  MaxwellReplicator - no heartbeat heard from server in 2003ms.  restarting replication.
maxwell_1  | 07:32:10,263 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:9996
maxwell_1  | 07:32:10,266 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721520000,eventType=24,serverId=1860260942,eventLength=146,nextPosition=10142,flags=0,timestampOfReceipt=1498721530266]
maxwell_1  | 07:32:12,269 WARN  MaxwellReplicator - no heartbeat heard from server in 2003ms.  restarting replication.
maxwell_1  | 07:32:12,285 INFO  OpenReplicator - starting replication at mysql-bin-changelog.123895:10266
maxwell_1  | 07:32:12,287 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1498721520000,eventType=24,serverId=1860260942,eventLength=158,nextPosition=10424,flags=0,timestampOfReceipt=1498721532287]
```

**Comment by liulikun** [comment]
Can you try to use binlog_connector mode (add `binlog_connector=true` to your config file or set it in command line)? There are some issues with open replication restarting process, and we're planning to switch it over to binlog_connector by default.

**Comment by anandaverma** [comment]
Thanks, @liulikun, added  `binlog_connector=true` and the above error seems gone. I still see lot of warn though - 

```
maxwell_1  | 12:05:56,608 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
maxwell_1  | 12:05:56,653 INFO  BinaryLogClient - Connected to proddbmumbai.cwlfcif9i1tn.ap-south-1.rds.amazonaws.com:3306 at mysql-bin-changelog.000021/193465 (sid:6379, cid:5746)
maxwell_1  | 12:05:56,792 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
maxwell_1  | 12:05:56,836 INFO  BinaryLogClient - Connected to proddbmumbai.cwlfcif9i1tn.ap-south-1.rds.amazonaws.com:3306 at mysql-bin-changelog.000021/193465 (sid:6379, cid:5747)
maxwell_1  | 12:05:56,976 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
maxwell_1  | 12:05:57,021 INFO  BinaryLogClient - Connected to proddbmumbai.cwlfcif9i1tn.ap-south-1.rds.amazonaws.com:3306 at mysql-bin-changelog.000021/193465 (sid:6379, cid:5748)
maxwell_1  | 12:05:57,160 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
```

Let me know is above seems fine.

**Comment by liulikun** [comment]
That doesn't seem very healthy. Are those logs repeated continuously? Can you check maxwell `positions` table to see if the `binlog_position` is progressing?

**Comment by anandaverma** [comment]
Yes, it is coming continuously and bootstrapping is not working. I don't see any event is being read and pushed to Kafka. Definitely an issue. I had to revert back previous since it was failing but pushing events. 

Will get back to you on  binlog_position  progressing.

**Comment by anandaverma** [comment]
No binlog position is not progressing. It going in an infinite loop.

**Comment by liulikun** [comment]
This may be caused by the bad maxwell state from the previous issue. If you can find a known good binlog position from the logs, and use `--init_position` to make maxwell start from that position, that could fix this issue. Also upgrade to the latest version if you can.

**Comment by osheroff** [comment]
@liulikun is likely correct here.  The earlier crash (about unconsumed bytes) left a poison position for maxwell.  There's enough problems with the old open-replicator that I'm gonna open a PR to remove it.
