### ISSUE TITLE
Allow configuration of overflow-buffer storage

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#709]
mysql 1.2G binlog , the maxwell thorw this message.
```
ListWithDiskBuffer - Overflowed in-memory buffer, spilling over into /tmp/maxwell5576784165633561239events
Tue Jul 25 14:27:43 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

**Comment by osheroff** [comment]
normal behavior when maxwell encounters a large transaction - maxwell uses a disk buffer to prevent using far too much memory.

**Comment by djuntgen** [comment]
this is nice, but can the disk buffer location be configurable?  '/tmp/' doesn't always have enough storage.

```
15:07:27,586 INFO  ListWithDiskBuffer - Overflowed in-memory buffer, spilling over into /tmp/maxwell7629848652301154625events
15:10:47,075 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
15:10:47,081 ERROR TaskManager - cause:
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method) ~[?:1.8.0_161]
        at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[?:1.8.0_161]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_161]
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126) ~[?:1.8.0_161]
        at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877) ~[?:1.8.0_161]
        at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786) ~[?:1.8.0_161]
        at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1580) ~[?:1.8.0_161]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351) ~[?:1.8.0_161]
        at com.zendesk.maxwell.util.ListWithDiskBuffer.evict(ListWithDiskBuffer.java:100) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.row.RowMapBuffer.evict(RowMapBuffer.java:39) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.row.RowMapBuffer.evict(RowMapBuffer.java:7) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.util.ListWithDiskBuffer.add(ListWithDiskBuffer.java:31) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.row.RowMapBuffer.add(RowMapBuffer.java:29) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:184) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:283) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.12.0.jar:?]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.12.0.jar:?]
15:10:47,086 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@412d50a
15:10:47,086 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
15:10:47,087 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@282a8324
15:10:47,087 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
java.io.IOException: No space left on device
```

**Comment by djuntgen** [comment]
I should note that I was able to find that the `tmp` directory is configurable during program start by passing in this java CLI option `-Djava.io.tmpdir=/location/of/new/tmp/dir/`

**Comment by osheroff** [comment]
Ah good call.  Maybe we just document this and move on?
