### ISSUE TITLE
Infiniti loop try to connect to a missing binlog file

### ISSUE THREAD

**Issue by suclogger** [zendesk/maxwell#714]
I'm using the latest 1.10.5 hosted in docker, MySQL version 5.7

Problems seems to  occure by : 
1. exception thrown during parsing a JSON filed
2. task stoped
3. docker try to restart container automatically 
4. read position from mysql, but the binlog file has been removed during restart (I'm using some IAAS like AWS)
5. try to connect to the missing binlog infinitely

There are some place we can optimize:
1. fix json error, it collapse the program everytime
2. try to recapture newest binlog file after several fail retry

```
# ...
# running normally

02:19:38,589 INFO  TaskManager - Stopping 3 tasks
02:19:38,589 ERROR TaskManager - cause: 
java.lang.ArrayIndexOutOfBoundsException: 26477
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonStringFormatter.appendString(JsonStringFormatter.java:218) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonStringFormatter.value(JsonStringFormatter.java:111) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseString(JsonBinary.java:639) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:247) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:400) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:211) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:148) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204) ~[maxwell-1.10.5.jar:1.10.5]
02:19:38,596 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@27b5ebc8
02:19:38,597 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
02:19:38,597 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@188aabd6
02:19:38,597 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
02:19:38,597 INFO  TaskManager - Stopping: com.zendesk.maxwell.metrics.MaxwellHTTPServerWorker@38177b30
02:19:38,610 INFO  ServerConnector - Stopped ServerConnector@27656044{HTTP/1.1}{0.0.0.0:8080}
02:19:38,622 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@618a01be{/,null,UNAVAILABLE}
java.lang.ArrayIndexOutOfBoundsException: 26477
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonStringFormatter.appendString(JsonStringFormatter.java:218)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonStringFormatter.value(JsonStringFormatter.java:111)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseString(JsonBinary.java:639)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:247)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:400)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:211)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:148)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
02:19:38,827 INFO  TaskManager - Stopped all tasks
02:19:42,783 INFO  MysqlSavedSchema - Restoring schema id 7 (last modified at Position[BinlogPosition[mysql-bin.000297:85039611], lastHeartbeat=1501062167862])
02:19:42,956 INFO  MysqlSavedSchema - Restoring schema id 6 (last modified at Position[BinlogPosition[mysql-bin.000297:76625391], lastHeartbeat=1501060501478])
02:19:44,998 INFO  MysqlSavedSchema - beginning to play deltas...
02:19:45,000 INFO  MysqlSavedSchema - played 1 deltas in 2ms
02:19:45,031 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000298:33003126
02:19:45,077 INFO  MaxwellMetrics - Metrics http server starting
02:19:45,081 INFO  MaxwellMetrics - Metrics http server started on port 8080
02:19:45,103 INFO  log - Logging initialized @5176ms
02:19:45,201 INFO  Server - jetty-9.2.21.v20170120
02:19:45,282 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@3c31bc6a{/,null,AVAILABLE}
02:19:45,291 INFO  ServerConnector - Started ServerConnector@2251460c{HTTP/1.1}{0.0.0.0:8080}
02:19:45,291 INFO  Server - Started @5366ms
02:19:45,340 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888572)
02:19:45,443 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000298:33003126 -- restarting
02:19:45,674 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888573)
02:19:45,775 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000298:33003126 -- restarting
02:19:45,971 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888574)
02:19:46,072 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000298:33003126 -- restarting
02:19:46,213 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888575)
02:19:46,313 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000298:33003126 -- restarting
02:19:46,538 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888576)
02:19:46,638 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000298:33003126 -- restarting
02:19:46,845 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888578)
02:19:46,946 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000298:33003126 -- restarting
02:19:47,123 INFO  BinaryLogClient - Connected to example.com:3306 at mysql-bin.000298/33003126 (sid:6379, cid:888579)
# begin infiniti loop 
```

**Comment by shyiko** [comment]
This looks like an issue that was fixed in mysql-binlog-connector-java@[0.8.1](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#081---2016-01-10). An upgrade to mysql-binlog-connector-java@[0.13.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#0130---2017-06-04) should fix this (json deserialization part).

**Comment by suclogger** [comment]
@shyiko Thanks for reply, binlog-connector-java@0.13.0 does solve json deserialization exception. 
There are several issues concern about missing binlog file, a automatic and safe mechanism is quite in urge. 

By the way, I added a [rocketmq](https://github.com/apache/incubator-rocketmq) producer within my [fork](https://github.com/suclogger/maxwell), do you think it needs to be merged?

Thanks for your great work!

**Comment by shyiko** [comment]
@suclogger Sorry but I can't really say anything with regards to rocketmq producer because I'm not the maintainer of maxwell. I'm sure @osheroff or someone else from the Zendesk will respond as soon as they can.

**Comment by ericwush** [comment]
@suclogger Please provide detailed example or a JSON that caused this error.
