### ISSUE TITLE
data size does not match column size causing ClassCastException

### ISSUE THREAD

**Issue by suclogger** [zendesk/maxwell#717]
Using latest 1.10.5, mysql 5.7.
 
logs:

```
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:35) ~[classes/:?]
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:51) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:163) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160) ~[classes/:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271) ~[classes/:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[classes/:?]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[classes/:?]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183) ~[classes/:?]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134) ~[classes/:?]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204) ~[classes/:?]
11:39:57,214 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@51d424bc
11:39:57,214 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
11:39:57,214 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@5f13c0f6
11:39:57,214 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
11:39:57,214 INFO  TaskManager - Stopping: com.zendesk.maxwell.metrics.MaxwellHTTPServerWorker@5b2c4fcc
11:39:57,221 INFO  ServerConnector - Stopped ServerConnector@75ac2097{HTTP/1.1}{0.0.0.0:8080}
11:39:57,223 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@59231937{/,null,UNAVAILABLE}
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:35)
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:51)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:163)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
```

debug shows:

![image](https://user-images.githubusercontent.com/8472155/28761979-751761e6-75e5-11e7-9114-372ef659553a.png)

Column size is 14 while data size is 15.

Maybe we should load all column everytime we start the program.

**Comment by ericwush** [comment]
@suclogger Thanks for addressing the issue. But for this kind of problem it's essential to include some examples/steps regarding how to reproduce the error. Look forward to your response.

**Comment by AlvinYang-2017** [comment]
@suclogger  
I encountered the same issue  #663，i set **binlog_connector=true** solved this issue
Because of binlog parse to sql get columns number  more than  original columns
This problem occurs when the table does not have a primary key, 
Don't know what your situation is like my

**Comment by osheroff** [comment]
these are generally issues with a schema somehow out-of-sync.  I think there's one known issue where maxwell "borrows" the wrong schema if there's multiple client_ids.  but this is old and stale and the original reporter has wandered off so I'm closing.
