### ISSUE TITLE
Crash with EOFException on certain valid JSON column operations

### ISSUE THREAD

**Issue by danmactough** [zendesk/maxwell#722]
maxwell v1.10.5
mysql v5.7.15

If I try to `INSERT` into a table with a JSON column but don't specify any value for the JSON column, maxwell crashes with an EOFException:

```
19:18:14,714 INFO  TaskManager - Stopping 2 tasks
19:18:14,714 ERROR TaskManager - cause:
java.lang.RuntimeException: java.io.EOFException
```

<details>
<summary>Click for complete stack trace</summary>

```
19:18:14,714 INFO  TaskManager - Stopping 2 tasks
19:18:14,714 ERROR TaskManager - cause:
java.lang.RuntimeException: java.io.EOFException
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:26) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:148) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204) ~[maxwell-1.10.5.jar:1.10.5]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readValueType(JsonBinary.java:975) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23) ~[maxwell-1.10.5.jar:1.10.5]
	... 10 more
19:18:14,724 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@1cba73fc
19:18:14,724 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
19:18:14,725 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@1514b420
19:18:14,727 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
java.lang.RuntimeException: java.io.EOFException
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:26)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:148)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readValueType(JsonBinary.java:975)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23)
	... 10 more
19:18:14,939 INFO  TaskManager - Stopped all tasks
```
</details>

-----

I can easily reproduce the error with the following setup:

- `` CREATE DATABASE `maxwell-exception` ``
- `` CREATE TABLE `test_table` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT) ``
- `` ALTER TABLE `test_table` ADD `props` JSON  NOT NULL  AFTER `id` ``

And the queries:

- This INSERT is OK: `` INSERT INTO test_table (props) VALUES ('null')``
- This INSERT causes maxwell to crash `` INSERT INTO test_table () VALUES () ``
- But it's a valid query: `` SELECT * FROM test_table ``

```
id	props
1	null
2	null
```

<details><summary>Here's the full output of maxwell (using the stdout producer).</summary>

```
19:14:52,248 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
Tue Aug 01 19:14:52 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Aug 01 19:14:52 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
19:14:52,754 INFO  SchemaStoreSchema - Creating maxwell database
Tue Aug 01 19:14:52 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
19:14:53,083 INFO  Maxwell - Maxwell v1.10.5 is booting (StdoutProducer), starting at Position[BinlogPosition[mysql-bin.000001:5765467], lastHeartbeat=0]
Tue Aug 01 19:14:53 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
19:14:53,360 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
19:14:54,291 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000001:5765467
19:14:54,427 INFO  BinaryLogClient - Connected to socialtables_mysql57_1:3306 at mysql-bin.000001/5765467 (sid:6379, cid:886)
19:15:45,283 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000001:5814858], lastHeartbeat=1501614935330] after applying "CREATE DATABASE `maxwell-exception`" to maxwell-exception, new schema id is 2
19:16:07,124 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000001:5817525], lastHeartbeat=1501614957381] after applying "CREATE TABLE `test_table` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT)" to maxwell-exception, new schema id is 3
19:16:40,891 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000001:5821731], lastHeartbeat=1501614999485] after applying "ALTER TABLE `test_table` ADD `props` JSON  NOT NULL  AFTER `id`" to maxwell-exception, new schema id is 4
{"database":"maxwell-exception","table":"test_table","type":"insert","ts":1501615078,"xid":44684,"commit":true,"data":{"id":1,"props":null}}
19:18:14,714 INFO  TaskManager - Stopping 2 tasks
19:18:14,714 ERROR TaskManager - cause: 
java.lang.RuntimeException: java.io.EOFException
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:26) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:148) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134) ~[maxwell-1.10.5.jar:1.10.5]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204) ~[maxwell-1.10.5.jar:1.10.5]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readValueType(JsonBinary.java:975) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168) ~[mysql-binlog-connector-java-0.7.3.jar:?]
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23) ~[maxwell-1.10.5.jar:1.10.5]
	... 10 more
19:18:14,724 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@1cba73fc
19:18:14,724 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
19:18:14,725 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@1514b420
19:18:14,727 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
java.lang.RuntimeException: java.io.EOFException
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:26)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:148)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readValueType(JsonBinary.java:975)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:23)
	... 10 more
19:18:14,939 INFO  TaskManager - Stopped all tasks

```
</details>

**Comment by shyiko** [comment]
@danmactough https://github.com/zendesk/maxwell/issues/714#issuecomment-318263128

**Comment by ericwush** [comment]
@danmactough I was trying to use mysql v5.7.19 and follow your steps exactly to reproduce the error but looks like your example is invalid. 
```
INSERT INTO test_table () VALUES ()	Error Code: 1364. Field 'props' doesn't have a default value	0.00058 sec
```
Even if I removed `NOT NULL` for column `props` I couldn't see any error occur.
Please double check.

**Comment by osheroff** [comment]
@ericwush there's might be a "strict-mode" setting that you could disable that would allow you to perform these goofy kinda inserts in mysql.  just a guess.

**Comment by danmactough** [comment]
@osheroff That's correct. I am running with config that matches the default config for AWS RDS:

```
[mysqld]
# These settings match defaults provided on Amazon AWS RDS and that affect compatability
explicit_defaults_for_timestamp=1
innodb_file_per_table=1
sql_mode=NO_ENGINE_SUBSTITUTION
# These settings match our custom parameter group on Amazon AWS RDS
general_log=1
log_bin_trust_function_creators=1
log_queries_not_using_indexes=1
log_throttle_queries_not_using_indexes=60
long_query_time=5
max_allowed_packet=16777216
performance_schema=1
slow_query_log=1
transaction-isolation=READ-COMMITTED
# These are needed for maxwell's daemon
server-id=1
log-bin=mysql-bin
binlog-row-image=FULL
```
