### ISSUE TITLE
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Could not find column 订单号 in a_wd

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#757]
**table:** a_wd
**column:** 订单号   (the MySQL DB of third-party company , designing this chinese column)
```
01:44:33,642 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Could not find column  订单号 in a_wd
        at com.zendesk.maxwell.schema.ddl.ColumnMod.originalIndex(ColumnMod.java:16) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.schema.ddl.RemoveColumnMod.apply(RemoveColumnMod.java:12) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:52) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:104) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:300) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:275) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134) ~[maxwell-1.10.5.jar:1.10.5]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204) ~[maxwell-1.10.5.jar:1.10.5]
```

**Comment by Hackeruncle** [comment]
@liulikun Thanks, I firstly close this question.
