### ISSUE TITLE
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'a_wd' in database omsprd

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#758]
```
11:18:42,303 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@19fd7e5c{/,null,UNAVAILABLE}
**com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'a_wd' in database omsprd**
        at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:37)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:104)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:300)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:275)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
11:18:43,746 INFO  TaskManager - Stopped all tasks
```

**Comment by liulikun** [comment]
Is this related to https://github.com/zendesk/maxwell/issues/757? Do you have any context for this error? From the error message, it seems there are some db migrations not being captured by maxwell.

**Comment by Hackeruncle** [comment]
@liulikun YES, the maxwell  will check the all databases and tables ?

**Comment by bjpwg** [comment]
??

**Comment by chen56** [comment]
How to deal with this error？
