### ISSUE TITLE
BinlogConnectorReplicator - replicator stopped at position

### ISSUE THREAD

**Issue by magnusboman** [zendesk/maxwell#769]
maxwell goes in to infinit loop with message, trying to sync from AWS RDS database server:

```
00:19:01,641 DEBUG MysqlPositionStore - Writing binlog position to maxwell.positions: Position[BinlogPosition[mysql-bin-changelog.066612:16301824], lastHeartbeat=1506644340628], last heartbeat read: 1506644340628
00:19:01,873 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.066612:16362224 -- restarting
00:19:01,915 INFO  BinaryLogClient - Connected to xyz.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com:3306 at mysql-bin-changelog.066612/16362224 (sid:6379, cid:240725)
00:19:02,055 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.066612:16362224 -- restarting
00:19:02,095 INFO  BinaryLogClient - Connected to xyz.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com:3306 at mysql-bin-changelog.066612/16362224 (sid:6379, cid:240732)
00:19:02,252 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.066612:16362224 -- restarting
00:19:02,291 INFO  BinaryLogClient - Connected to xyz.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com:3306 at mysql-bin-changelog.066612/16362224 (sid:6379, cid:240742)
00:19:02,441 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.066612:16362224 -- restarting

```
There's been similar issues reported here, and it turned out to be missing binlog files, however, that doesn't seem to be the issue here:

```
mysql> show binary logs;
+----------------------------+-----------+
| Log_name                   | File_size |
+----------------------------+-----------+
| mysql-bin-changelog.066598 |  11217654 |
| mysql-bin-changelog.066599 |  22279800 |
| mysql-bin-changelog.066600 |  17963841 |
| mysql-bin-changelog.066601 |   2256492 |
| mysql-bin-changelog.066602 |   7814246 |
| mysql-bin-changelog.066603 |  11136747 |
| mysql-bin-changelog.066604 |  11392968 |
| mysql-bin-changelog.066605 |  11858738 |
| mysql-bin-changelog.066606 |  12059420 |
| mysql-bin-changelog.066607 |  12115845 |
| mysql-bin-changelog.066608 |  10037413 |
| mysql-bin-changelog.066609 |  10148374 |
| mysql-bin-changelog.066610 |  16899542 |
| mysql-bin-changelog.066611 |  10075944 |
| mysql-bin-changelog.066612 |  20315183 |
| mysql-bin-changelog.066613 |  16896556 |
| mysql-bin-changelog.066614 |   1147276 |
+----------------------------+-----------+

```

**Comment by liulikun** [comment]
Is the issue resolved yet? I'm not sure what happened there. I can only guess the network connection issue. @shyiko do you have ideas why the client is disconnected constantly?

**Comment by shyiko** [comment]
@liulikun When binlogclient loses connection lifecycle listener is notified about an error. Without seeing that error I can only guess.

**Comment by magnusboman** [comment]
@liulikun Yes it is still happening. I have cleaned everything up and started from scratch numerous times without success. Error happens within a minute of starting maxwell.
I don't have any connection issues when using mysql, nor does other instances have any connectivity issues to RDS.

@shyiko I've set logs to DEBUG but don't get any more info about the error than what I pasted above. Is there any other settings I can use to get errors from the "lifecycle listener"?

**Comment by liulikun** [comment]
We don't have lifecycle listener in maxwell currently. Will add it on later. Meanwhile, I wrote a simple debugger to test the connectivity with mysql server using binlog connector: https://github.com/liulikun/mysql-binlog-connector-debugger/blob/master/src/main/java/MysqlBinlogConnectorDebugger.java, it has lifecycle listener, you can compile and run it see if you get any error messages.

**Comment by magnusboman** [comment]
@liulikun Thanks. here's the output:

```
Sep 30, 2017 1:01:57 AM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to xyz.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com:3306 at mysql-bin-changelog.066893/4096536 (sid:65535, cid:8615545)
POS:4096536, TS:0, EVENT TYPE:ROTATE
POS:4096536, TS:1506728100000, EVENT TYPE:FORMAT_DESCRIPTION
POS:4096536, TS:1506728214000, EVENT TYPE:TABLE_MAP
CommunicationFailure: Failed to deserialize data of EventHeaderV4{timestamp=1506728214000, eventType=WRITE_ROWS, serverId=838571610, headerLength=19, dataLength=53, nextPosition=4096672, flags=0}
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1506728214000, eventType=WRITE_ROWS, serverId=838571610, headerLength=19, dataLength=53, nextPosition=4096672, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:216)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:184)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:890)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
        at java.io.InputStream.read(InputStream.java:170)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeBlob(AbstractRowsEventDataDeserializer.java:377)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:180)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:132)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:210)
        ... 5 more

```

**Comment by liulikun** [comment]
@shyiko Does that error message help?

**Comment by liulikun** [comment]
Did you pass the debugger with binlog file `mysql-bin-changelog.066612`, and binlog position `16362224`? That's where maxwell got stuck. The error message showed the position `4096536`, which is no where near position `16362224`. The other solution is to use mysql utility `mysqlbinlog` to inspect the binlog file and find the position `16362224` and see what is that event and next event  which crashed binlog connector.  

You can run`mysqlbinlog` remotely  to download the binlog file like this:

```
mysqlbinlog -vv --base64-output=decode-rows -R -h xxx -u xxx -p your_binlog_file > your_binlog_file.log
```

Once you find the position `16362224`, you can skip that position by updating `maxwell.positions` table for this maxwell client_id with a position of `Xid` event (the end of the MySql transaction) next to `16362224` in the binlog, then restart maxwell.

**Comment by magnusboman** [comment]
@liulikun I start from scratch each time (ie, dropping the maxwell DB) hence the difference between the two logs.

mysqlbinlog comes back with the following:

```
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!40019 SET @@session.max_insert_delayed_threads=0*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 16362224
#170929  0:15:00 server id 838571610  end_log_pos 0     Start: binlog v 4, server v 10.0.24-MariaDB created 170929  0:15:00
# at 16362224
# at 16362288
#170929  0:19:01 server id 838571610  end_log_pos 16362288      Table_map: `db`.`table` mapped to number 133
#170929  0:19:01 server id 838571610  end_log_pos 16362360      Write_rows: table id 133 flags: STMT_END_F
### INSERT INTO `db`.`table`
### SET
###   @1=1111111
###   @2='aaaaa'
###   @3='bbbbbb'
###   @4=22222
###   @5=333
###   @6=1972489561
###   @7=***Corrupted replication event was detected. Not printing the value***
# at 16362360
```

Checking that record in the DB comes back with:
```
+---------+-------------+------------+-----------+------------+----------------------------+------+
| f1      | f2          | f3         | f4        | f5         | f6                         | f7   |
+---------+-------------+------------+-----------+------------+----------------------------+------+
| 1111111 | aaaaa       | bbbbbb     |     22222 |        333 | 2017-09-29 00:19:01.756678 | []   |
+---------+-------------+------------+-----------+------------+----------------------------+------+
```

Explain Table:
```
+-------------+---------------------+------+-----+----------------------+----------------+
| Field       | Type                | Null | Key | Default              | Extra          |
+-------------+---------------------+------+-----+----------------------+----------------+
| f1          | bigint(20) unsigned | NO   | PRI | NULL                 | auto_increment |
| f2          | varchar(100)        | NO   | MUL |                      |                |
| f3          | varchar(100)        | NO   |     | NULL                 |                |
| f4          | int(10) unsigned    | NO   |     | NULL                 |                |
| f5          | int(10) unsigned    | NO   | MUL | NULL                 |                |
| f6          | timestamp(6)        | NO   |     | CURRENT_TIMESTAMP(6) |                |
| f7          | text                | YES  |     | NULL                 |                |
+-------------+---------------------+------+-----+----------------------+----------------+
```

**Comment by magnusboman** [comment]
@liulikun Also, these "corrupted replication events" seem to be fairly frequent so constantly modifying maxwell.positions isn't really a workable solution.
I just remembered that I had the same issue when trying out Debezium:
https://github.com/debezium/debezium/pull/242

**Comment by liulikun** [comment]
Are you using MariaDB? And with GTID enabled? That might be the issue. See if this is relevant: https://github.com/shyiko/mysql-binlog-connector-java/pull/50.  Both Debezium and Maxwell are using the same mysql binlog connector library, so the same error could happen.

**Comment by magnusboman** [comment]
No, not using GTID:

```
*************************** 20. row ***************************
      Id: 9953228
    User: maxwell
    Host: 1.1.1.1:1
      db: NULL
 Command: Binlog Dump
    Time: 33
   State: Sending binlog event to slave
    Info: NULL
Progress: 0.000
```

**Comment by liulikun** [comment]
This feels like MariaDB replication issue, you'll need to fix it on MariaDB.

**Comment by shyiko** [comment]
MariaDB isn't supported by mysql-binlog-connector-java and most definitely isn't going to work (we have a bunch of PRs that if merged would result in at least some level of compatibility with MariaDB but so far I was reactant to have them in the core for sustainability reasons). Sorry.

**Comment by liulikun** [comment]
@magnusboman I'll close this for now as MariaDB is not supported yet.

**Comment by jackylee92** [comment]
mysql:
    use maxwell;
    drop table position;
    drop table databases;
    drop table clomns;
     .......
     drop all table in maxwell;
exit;
 run your maxwell
