### ISSUE TITLE
Maxwell stuck on a position.

### ISSUE THREAD

**Issue by mayanksamrat** [zendesk/maxwell#775]
I am getting an issue that maxwell is stuck on a position since last 2-3 hrs, In position table binlog_position is not changing. Although tables are being modified. 

```
mysql> select * from positions ;
+-----------+------------------+-----------------+----------+-----------+--------------+---------------------+
| server_id | binlog_file      | binlog_position | gtid_set | client_id | heartbeat_at | last_heartbeat_read |
+-----------+------------------+-----------------+----------+-----------+--------------+---------------------+
|      4082 | mysql-bin.000007 |        34037021 | NULL     | catalog   |         NULL |                   0 |
+-----------+------------------+-----------------+----------+-----------+--------------+---------------------+
```

Even there is no error in maxwell logs, log-level is Info.

```
{"date" : "08:31:33,539","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645945)"}
{"date" : "08:31:33,739","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:34,139","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645947)"}
{"date" : "08:31:34,339","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:34,739","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645963)"}
{"date" : "08:31:34,940","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:35,339","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645964)"}
{"date" : "08:31:35,539","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:35,939","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645965)"}
{"date" : "08:31:36,139","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:36,539","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645966)"}
{"date" : "08:31:36,739","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:37,139","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645967)"}
{"date" : "08:31:37,339","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:37,739","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645968)"}
{"date" : "08:31:37,939","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:38,339","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645969)"}
{"date" : "08:31:38,539","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
{"date" : "08:31:38,939","level" : "INFO ","logger" : "BinaryLogClient","message" : "Connected to 10.254.40.82:3306 at mysql-bin.000007/4060348416 (sid:6379, cid:4645970)"}
{"date" : "08:31:39,139","level" : "WARN ","logger" : "BinlogConnectorReplicator","message" : "replicator stopped at position: mysql-bin.000007:4060348416 -- restarting"}
```

Please let me know if anyone found same issue, and how we can track it.

**Comment by ericwush** [comment]
@mayanksamrat We had same issue. It was because for some reason the last binlog position stored in maxwell's `positions` table didn't exist in that binlog file. For example the last position known by maxwell is 123 and the last position in the actual binlog file is 100 somehow. We ended up updating the `positions` table to 100 so maxwell could find it and continue processing. 

In your case, I'd suggest you looking into your binlog file by either `mysqlbinlog` util or `show binary logs` in mysql and look for mysql-bin.000007 to check whether position 4060348416 exists.

As mentioned in #769 , adding binlog connector lifecycle listener will provide more visibility as in why "replicator stopped at position". Hope it helps.

**Comment by mayanksamrat** [comment]
HI @ericwush  Thank for your reply,  It seems the issue is not that you have faced, In my case the position, where maxwell stuck exists. There is an update statement on that position. 
 
I am getting this frequently, and the interesting part is when I restart the maxwell, it works fine.

**Comment by mayanksamrat** [comment]
Getting this to in old logs.
```
com.github.shyiko.mysql.binlog.network.AuthenticationException: Got packets out of order
        at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:702) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:494) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

```

**Comment by mthakkar77** [comment]
I am getting same issue with maxwell-1.10.8. It works fine for sometime and when I stop maxwell and start it again then I noticed that it takes forever to find position. Another issue is I have to always run maxwell-bootstrap separately. It never starts with maxwell --boostrapper=async option. On running maxwell-bootstrap, it sends all binlog information from beginning on kafka. In that case I cannot call it change data capture ( CDC ).
