### ISSUE TITLE
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'wms_policy_query' in database wms

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#780]
**Current architecture:**
MySQL(master) --> MySQL(slave) -->maxwell -->kafka

The architecture running of a long time is ok.
But ,when creating a **new table**  of 'wms_policy_query'  in **MySQL(master)**, then maxwell process is stopped.

**These error log:**
```
09:39:54,504 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@22f0ef3f{/,null,UNAVAILABLE}
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'wms_policy_query' in database wmsb35
        at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:37)
        at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:104)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:300)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:275)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
09:39:55,852 INFO  TaskManager - Stopped all tasks
```

**Comment by osheroff** [comment]
this is odd;  this is definitely a table alter, not a table create;  any idea of the SQL statements that preceded this crash?

**Comment by bokelo** [comment]
Has this issue been resolved? Have the same issue and the preceding SQL was a DROP statement.

**Comment by osheroff** [comment]
some chance that your issue was resolved in v1.13.0, https://github.com/zendesk/maxwell/pull/853.  But to really know would have to do a bit of debugging or get a dump of your `maxwell` database and see.

**Comment by dongxiaohe** [comment]
I can reproduce the issue locally. It is really rare, but if do happen, maxwell would be in the crash loop. Here are the steps:

```
CREATE TABLE test (name VARCHAR(100));  // DDL Binlog Position: 1
insert into test values('1');   // DML Binlog Position: 2
rename table test to test1  // DDL Binlog Position:  3
```

- If I change the position to point to **1 (DDL)**, maxwell will be in the crash loop. 

```
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Unexpectedly asked to create existing table test
    at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:25)
    at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:60)
    at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
    at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:319)
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:294)
    at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
    at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
```

- If I change the position to point to **2 DML**, maxwell is running successfully without any issues.

- If I change the position to point to **3 DDL**, maxwell will be in the crash loop as well.

```
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'test' in database zendesk_development_shard_1
    at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55)
    at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:37)
    at com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12)
    at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
    at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
    at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:319)
    at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:294)
    at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
    at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
    at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
```

I will create a pull request to fix that soon.

**Comment by osheroff** [comment]
I think this was fixed awhile back with resolving where we pointed binlog position.
