### ISSUE TITLE
The parameter of "ignore_producer_error = true" is not work

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#781]
I configure the parameter of "ignore_producer_error = true", is not work, can't be ignored,can't skipped.

**The error log:**

```
13:25:20,441 INFO  Server - Started @3071ms
 ALTER TABLE wms_policy_query ADD INDEX idx_query_code(query_code)" to wmsb35, new schema id is 2:206047372], lastHeartbeat=1] after applying "-- add index
13:25:20,802 INFO  TaskManager - Stopping 4 tasks
13:25:20,802 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Unexpectedly asked to create existing table wms_do_loading
        at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:25) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:60) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:305) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:280) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.10.8.jar:?]
13:25:20,805 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@67b724fe
13:25:20,805 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
13:25:20,805 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@4660ed01
13:25:20,805 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
13:25:20,806 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.000253:206054980], lastHeartbeat=1]
13:25:20,807 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
13:25:20,810 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@66fe3a3e
13:25:20,810 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
13:25:20,811 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@146d9ee6
13:25:20,813 INFO  ServerConnector - Stopped ServerConnector@3f7cb6ef{HTTP/1.1}{0.0.0.0:8081}
13:25:20,815 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@3bfc9a56{/,null,UNAVAILABLE}
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Unexpectedly asked to create existing table wms_do_loading
        at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:25)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:60)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:305)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:280)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
13:25:22,207 INFO  TaskManager - Stopped all tasks
```

**Comment by xuebingli** [comment]
Hi @Hackeruncle, the exception in your log `com.zendesk.maxwell.schema.ddl.InvalidSchemaError` is not a Kafka producer error.
