### ISSUE TITLE
Ensure new client_id maxwells don't borrow incorrect schemas

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#782]
```
14:33:20,420 INFO  Server - Started @2886ms
14:33:20,635 INFO  TaskManager - Stopping 4 tasks
14:33:20,635 ERROR TaskManager - cause: 
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to [B
        at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:78) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:104) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:152) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:179) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:179) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:276) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.10.8.jar:?]
14:33:20,639 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@4b6b8148
14:33:20,639 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
14:33:20,639 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@66b81745
14:33:20,640 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
14:33:20,641 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
14:33:20,644 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@413870ef
14:33:20,645 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
14:33:20,645 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@1ae049dc
14:33:20,659 INFO  ServerConnector - Stopped ServerConnector@3f12571c{HTTP/1.1}{0.0.0.0:8081}
14:33:20,661 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@7364eb3b{/,null,UNAVAILABLE}
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to [B
        at com.zendesk.maxwell.schema.columndef.StringColumnDef.asJSON(StringColumnDef.java:78)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:104)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:152)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:179)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:179)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:276)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
14:33:22,021 INFO  TaskManager - Stopped all tasks
```

**Comment by Sonnbc** [comment]
We are seeing a similar problem:

**Comment by liulikun** [comment]
This looks like some db migrations are not captured by maxwell. Can you reproduce the error?

**Comment by geoff-addepar** [comment]
@Sonnbc and I work together, here are reproduction steps for our case:
1. Run maxwell and let it populate the schema tables
2. Stop maxwell
3. Run some database migrations (ALTER TABLE statements), in @Sonnbc's case we changed a BIGINT column to a VARCHAR
4. Start maxwell again with a different client ID
5. Insert data into the altered table

When a new client starts up, it should not assume that the latest saved schema corresponds to the current state of the database. I think it should re-query the current schema, the same as if there was no maxwell database at all, just in case there were schema changes.

I think there may be similar edge cases around setting an explicit --init_position that's in the future from the last processed event, but we haven't run into that yet.

**Comment by liulikun** [comment]
@geoff-addepar Thanks for providing reproduction steps. In this case if we were to recapture the current schema, it could break the old maxwell client if you start the old client again. So I think you can just keep the old client running while you run the migration.

**Comment by geoff-addepar** [comment]
Shouldn't the old client look in the maxwell.schemas table to find the most recent schema older than its position? It shouldn't just assume that the latest one is the one it should use.

**Comment by liulikun** [comment]
Yes, the old client will look up the schema change history to find the appropriate snapshot, only if the schema store hasn't been overwritten. In your case, to make the new client work, if we clean the current schema store and recapture schema again, the old client will have issues.

**Comment by timbertson** [comment]
@liulikun when we manually force schema recapture we delete the old schemas, but in the case of a new consumer ID coming up I believe we _should_ just be capturing a new schema and storing it alongside the existing ones. They're all keyed by schemaID so they can live happily alongside schemas created by other maxwells.

I could be wrong, but I think this is supposed to work (i.e. it's a bug, not a missing feature). Might take some digging to get to the bottom of it though.

**Comment by osheroff** [comment]
@timbertson no, @geoff-addepar is correct here.  There's a few different solutions here:

1.  When bringing up a new, never-seen before client_id, it must borrow the latest position possible in `maxwell.positions` (ensuring we don't miss schema updates)
2.  Have each client store their own copy of the schema (yuck).
3.  keep the behavior where the new client_id maxwell plays from current position, but do a supressed-output replay until current position to ensure we pick up all the schema changes.

I think (1) is probably the most bang for the buck.

**Comment by Hackeruncle** [comment]
`18:18:06,634 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@38c98bab{/,null,UNAVAILABLE}
java.lang.ClassCastException: [B cannot be cast to java.lang.Long
        at com.zendesk.maxwell.schema.columndef.BigIntColumnDef.toNumeric(BigIntColumnDef.java:26)
        at com.zendesk.maxwell.schema.columndef.BigIntColumnDef.asJSON(BigIntColumnDef.java:39)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:104)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:153)
        at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:165)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:179)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:276)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:292)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
18:18:08,023 INFO  TaskManager - Stopped all tasks`
