### ISSUE TITLE
Unable to start maxwell: java.net.SocketException: Broken pipe

### ISSUE THREAD

**Issue by tinynet** [zendesk/maxwell#786]
I was using maxwell successfully, but today I wasn't able to restart it.
I had to drop maxwell db and restart from scratch, and it worked. 
It's possible that I created a db and I included it in configuration when maxwell was not running,

Here the error:
```
10:55:48,702 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: master.000012:2180552
10:55:48,716 INFO  TaskManager - Stopping 2 tasks
10:55:48,716 ERROR TaskManager - cause: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_65]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_65]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132) ~[?:1.8.0_65]
	at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:68) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.writeInteger(ByteArrayOutputStream.java:41) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.write(PacketChannel.java:66) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:695) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:494) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
10:55:48,721 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@b2ce10f
10:55:48,722 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
10:55:48,722 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@305ce8ef
10:55:48,722 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
10:55:48,722 DEBUG TaskManager - Awaiting stop of: com.zendesk.maxwell.schema.PositionStoreThread@b2ce10f
10:55:48,725 DEBUG MysqlPositionStore - writing heartbeat: 1508144148723 (last heartbeat written: 1508144098487)
10:55:48,850 DEBUG TaskManager - Awaiting stop of: com.zendesk.maxwell.replication.BinlogConnectorReplicator@305ce8ef
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:68)
	at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.writeInteger(ByteArrayOutputStream.java:41)
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.write(PacketChannel.java:66)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:695)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:494)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
	at java.lang.Thread.run(Thread.java:745)
10:55:50,170 ERROR MaxwellContext - Exception occurred during shutdown:
java.util.concurrent.TimeoutException: Timed out trying waiting for com.zendesk.maxwell.replication.BinlogConnectorReplicator process to stop after 1000ms.
	at com.zendesk.maxwell.util.StoppableTaskState.awaitStop(StoppableTaskState.java:46) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.util.RunLoopProcess.awaitStop(RunLoopProcess.java:18) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.util.TaskManager.stop(TaskManager.java:54) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.MaxwellContext.shutdown(MaxwellContext.java:156) [maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.MaxwellContext.access$000(MaxwellContext.java:32) [maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.MaxwellContext$1$1.run(MaxwellContext.java:179) [maxwell-1.10.6.jar:1.10.6]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
10:55:50,170 DEBUG MaxwellContext - Shutdown complete: false
10:55:50,170 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process
10:55:50,171 ERROR MaxwellContext - Termination reason:
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_65]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_65]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132) ~[?:1.8.0_65]
	at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:68) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayOutputStream.writeInteger(ByteArrayOutputStream.java:41) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.write(PacketChannel.java:66) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:695) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:494) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]	
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by tinynet** [comment]
The problem seems to occur when I create a new db and I later modify the configuration to watch changes only from that db.
Maybe I don't understand the procedure.
What I'm doing is: 
maxwell is runnning, but watching db_A
I create db_B with some tables
I stop maxwell
I change the config to include_dbs=db_B
I restart maxwell
and either I'm not able to restart or I manage to restart (?resetting maxwell position to last master status) but changes  are not detected.

If I go back to include_dbs=db_A, it works fine

**Comment by xuebingli** [comment]
> The problem seems to occur when I create a new db and I later modify the configuration to watch changes only from that db.

Switching to a new database (presumably with a different schema) on the fly is not supported.

> I had to drop maxwell db and restart from scratch, and it worked.

Maxwell keeps a record of database schema in maxwell db (see "Schema storage" in [documentation](http://maxwells-daemon.io/schemas/) for details). When you switch to a different database db_B (with a different schema), Maxwell still uses the stored schema for the previous database db_A. Thus the errors.

After you drop maxwell db, Maxwell rebuilds a record of database schema for db_B, which is why it recovers from the database switch.

Hope it helps.
