### ISSUE TITLE
Maxwell crash in GTID model when test mysql HA 

### ISSUE THREAD

**Issue by sanguinar** [zendesk/maxwell#802]
I use maxwell point to an IP which point to a GTID model MySQL cluster. When testing HA, I stop the master of the cluster.  The IP maxwell pointed is not change(The IP point to the new master by itself). Then maxwell crashed. The Error message:
19:18:07,199 ERROR TaskManager - cause:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1,008 milliseconds ago.  The last packet sent successfully to the server was 7 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3552) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3452) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3893) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at snaq.db.CachedPreparedStatement.executeUpdate(CachedPreparedStatement.java:151) ~[dbpool-7.0-jdk7.jar:?]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:142) ~[maxwell-1.10.6.jar:1.10.6]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:89) ~[maxwell-1.10.6.jar:1.10.6]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:83) ~[maxwell-1.10.6.jar:1.10.6]
        at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:110) ~[maxwell-1.10.6.jar:1.10.6]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.6.jar:1.10.6]
        at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40) ~[maxwell-1.10.6.jar:1.10.6]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3004) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        ... 18 more
I have dropped the database maxwell in mysql and used the GTID model in maxwell and the log confirm it 
 19:17:08,936 INFO  BinlogConnectorReplicator - Setting initial gtid to: 188ab20d-be0f-11e7-af88-0a6da68da316:1-869,1af07dde-be0f-11e7-af88-066e1a4fa630:1-630643
I can guess that the error may occur when mysql master stop and the new master had not be pointed. If it is the actual reason and how can I solve it. Thanks!

**Comment by sanguinar** [comment]
I run a shell script to monitor and restart(after a few seconds) the maxwell, and it works well. I hope to know  if there are other graceful ways. Any help is appreciated. thanks!

**Comment by liulikun** [comment]
Your solution sounds good. Maxwell can recover after connecting to a new master (the previous slave).

**Comment by osheroff** [comment]
Hmmm, thinking it might be cool to add auto-reconnect functionality to cover this use case.  The shell script solution works but can duplicate a bit of data, it’d be far more elegant for maxwell to be able to reconnect and pick up the replication stream.

Thoughts likun?

**Comment by liulikun** [comment]
yes, this is definitely something worth investigating if it hasn't been tried before. If it works, we may not need heartbeats anymore?

**Comment by sanguinar** [comment]
@liulikun @osheroff Thank you very muck!
Recently, I had to face the problem once again. Maxwell is excellent and we want use it in product environment. Then we must make it robust. The machine which run maxwell may crash and we hope to impl maxwell HA or standby to ensure that there is one maxwell work, rather than restart maxwell by manual operation.
Our mysql standby is base on keepalived. I have no idea use it to impl maxwell HA. 
Really appreciate your help and suggestion!

**Comment by sanguinar** [comment]
#671

**Comment by osheroff** [comment]
There was a PR somewhere around that used Apache helix to do clustering / HA from the maxwell side.  It seemed overly complex but workable.  I wonder if there’s a simpler solution where we could use a table inside MySQL itself to do clustering...

**Comment by sanguinar** [comment]
Hope a simple solution where maxwell can work as HA or Standby rather than a cluster. Love the  simplicity of maxwell and not want to destroy it.

**Comment by sanguinar** [comment]
I have taken a look at the PR #415 and want to have a try. Thanks for you and the author of this PR!

**Comment by osheroff** [comment]
HA is implemented in 1.29.0
