### ISSUE TITLE
KinesisProducer - Restarting native producer process.

### ISSUE THREAD

**Issue by Big-Ele** [zendesk/maxwell#805]
08:21:42,478 ERROR KinesisCallback - UserRecordFailedException @ Position[BinlogPosition[mysql-bin-changelog.210392:26063273], lastHeartbeat=1510560992716] -- 1779e23ed6e0d9c23ab17cc9d05a83a8
08:21:42,478 ERROR KinesisCallback - null
08:21:42,478 ERROR KinesisCallback - Record failed to put - Expired : Record has reached expiration
08:21:42,478 ERROR KinesisCallback - Exception during put
com.amazonaws.services.kinesis.producer.UserRecordFailedException: null
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler.onPutRecordResult(KinesisProducer.java:195) [amazon-kinesis-producer-0.12.3.jar:?]
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler.access$000(KinesisProducer.java:129) [amazon-kinesis-producer-0.12.3.jar:?]
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler$1.run(KinesisProducer.java:136) [amazon-kinesis-producer-0.12.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Is there a way to fix this problem?

**Comment by liulikun** [comment]
This error is originated from Kinesis, I'd check if there is anything we can do to reduce this error on Kinesis side. If you need absolute message delivery guarantee, what we can do in maxwell is to configure `ignore_producer_error`  to `false` so that maxwell process will be terminated upon producer errors. You'll need a script to auto restart maxwell. Once maxwell is restarted,  it'll try to publish that failed message again. This way we introduce an unlimited publish retries effectively.
