### ISSUE TITLE
Pub/Sub producer throws exceptions when running with a sustained load

### ISSUE THREAD

**Issue by robertotena** [zendesk/maxwell#812]
I have been running some quick load tests producing messages to Pub/Sub, and after a short while it starts throwing exceptions like the following:

```
16:57:24,470 WARN  DefaultPromise - An exception was thrown by io.grpc.netty.NettyClientStream$Sink$1.operationComplete()
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@72f90b7e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@26377326[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 754000]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) ~[?:1.8.0_141]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) ~[?:1.8.0_141]
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:87) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:80) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:548) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:424) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:378) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:421) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.AbstractClientStream2$TransportState.closeListener(AbstractClientStream2.java:327) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.internal.AbstractClientStream2$TransportState.transportReportStatus(AbstractClientStream2.java:306) ~[grpc-core-1.4.0.jar:1.4.0]
	at io.grpc.netty.NettyClientStream$Sink$1.operationComplete(NettyClientStream.java:148) ~[grpc-netty-1.4.0.jar:1.4.0]
	at io.grpc.netty.NettyClientStream$Sink$1.operationComplete(NettyClientStream.java:142) ~[grpc-netty-1.4.0.jar:1.4.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.grpc.netty.NettyClientHandler$3.operationComplete(NettyClientHandler.java:456) [grpc-netty-1.4.0.jar:1.4.0]
	at io.grpc.netty.NettyClientHandler$3.operationComplete(NettyClientHandler.java:427) [grpc-netty-1.4.0.jar:1.4.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.http2.StreamBufferingEncoder$Frame.release(StreamBufferingEncoder.java:311) [netty-codec-http2-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.http2.StreamBufferingEncoder$PendingStream.close(StreamBufferingEncoder.java:292) [netty-codec-http2-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.http2.StreamBufferingEncoder.close(StreamBufferingEncoder.java:231) [netty-codec-http2-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:186) [netty-codec-http2-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:392) [netty-codec-http2-4.1.11.Final.jar:4.1.11.Final]
	at io.grpc.netty.NettyClientHandler.channelInactive(NettyClientHandler.java:345) [grpc-netty-1.4.0.jar:1.4.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:900) [netty-handler-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

After some quick digging, I have seen there was a related bug in `grpc` library used by `google-cloud-pubsub` library. I just tried to build a Docker image updating the `google-cloud-pubsub` version from `0.22.0-beta` to `0.30.0-beta`, and no exceptions are thrown now.

I am creating a pull request to update this, if that's ok.

**Comment by robertotena** [comment]
I have seen one of the checks in Travis failed. I do not understand the error very well, I tried to run the Travis script locally but no luck so far. Any guidance on this would be appreciated :)

**Comment by timbertson** [comment]
Apologies for the slow response. Unfortunately the tests are a bit flakey, I reran and it passed this time.

**Comment by robertotena** [comment]
No problem. Thanks! I have seen there has been released a new version recently. Do you have any idea about when would the next version be released? Just to get the image with the fix from docker hub instead of building it myself.
