### ISSUE TITLE
Drop table cause binlog disconnected

### ISSUE THREAD

**Issue by hoangbeatsb3** [zendesk/maxwell#831]
Hi all,
On my MariaDB config I have enabled option ansi_quotes (and I can't change this config because some reason of my team)
I start maxwell and run drop table on mariadb, then maxwell stop all 3 tasks.
Please help to check it. Thank you very much!
Here is my log:
15:15:10,410 INFO  BinlogConnectorLifecycleListener - Binlog connected.
15:16:58,676 ERROR MysqlParserListener - (table_name "kudu2")
15:16:58,676 ERROR SchemaChange - Error parsing SQL: 'DROP TABLE "kudu2" /* generated by server */'
15:16:58,677 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
15:16:58,678 INFO  TaskManager - Stopping 3 tasks
15:16:58,678 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: "kudu2"
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84) ~[maxwell-1.11.0.jar:?]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.11.0.jar:?]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.11.0.jar:?]
15:16:58,682 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@1a046e0d
15:16:58,682 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
15:16:58,682 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@6ddb4d3c
15:16:58,682 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
15:16:58,683 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
15:16:58,685 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@36561a2b
15:16:58,685 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: "kudu2"
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
15:16:59,995 INFO  TaskManager - Stopped all tasks

**Comment by osheroff** [comment]
@timbertson @liulikun I'd like to someday support mariadb, am tagging issues that come up;  maybe we can triage these and see how far we are?

**Comment by nminhquan** [comment]
Hi @osheroff , I think this error does not relate to MariaDB since we only got the issue when enabling the [ANSI_QUOTES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes) option. Removing this option we did not see the issue.

You can try replicating this error by enabling this option then try dropping some tables. You will see the error. When i executed:
DROP TABLE kudu2
It looks like somehow the double quotes (") were added and made the error:
15:16:58,676 ERROR SchemaChange - Error parsing SQL: 'DROP TABLE "kudu2" /* generated by server */'

Thanks,
Quan

**Comment by osheroff** [comment]
ah, thanks Quan.  I'll look into that.

**Comment by osheroff** [comment]
ansi-quoted tables fixed in v1.12.0

**Comment by hoangbeatsb3** [comment]
Thank you very much. I checked yesterday, it worked.

Vào Th 6, 12 thg 1, 2018 lúc 01:26 Ben Osheroff <notifications@github.com>
đã viết:
