### ISSUE TITLE
maxwell can't start

### ISSUE THREAD

**Issue by PengLyu** [zendesk/maxwell#838]
18:48:43,929 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000037:63470069
18:48:44,029 INFO  BinaryLogClient - Connected to 192.168.0.76:3306 at mysql-bin.000037/63470069 (sid:6379, cid:69823)
18:48:44,030 INFO  BinlogConnectorLifecycleListener - Binlog connected.
18:48:44,217 ERROR MysqlParserListener - (parse XA START X'6162616161336134363165303464653239313638626138343832636332363430' , X'6973616c65735f303031' , 1)
18:48:44,217 ERROR SchemaChange - Error parsing SQL: 'XA START X'6162616161336134363165303464653239313638626138343832636332363430',X'6973616c65735f303031',1'
18:48:44,303 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
18:48:44,304 INFO  TaskManager - Stopping 3 tasks
18:48:44,305 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: XA
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84) ~[maxwell-1.11.0.jar:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.11.0.jar:?]
18:48:44,310 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@379989df
18:48:44,310 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
18:48:44,310 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@5fe7be22
18:48:44,310 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
18:48:44,312 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
18:48:44,316 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@5ec4e9f8
18:48:44,316 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: XA
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
18:48:45,625 INFO  TaskManager - Stopped all tasks

bin/maxwell --host 192.168.0.197 --user root --password root --replication_host 192.168.0.76 --replication_user repl --replication_password repl --producer=kafka --kafka.bootstrap.servers=192.168.0.191:9092 --kafka_topic=db_76 --include_dbs=test

mysql InnoDB 5.7.18

**Comment by PengLyu** [comment]
I don't know whether to add this code in com.zendesk.maxwell.schema.ddl.SchemaChange.java is best way to solve this problem,but can start maxwell normally.

`SQL_BLACKLIST.add(Pattern.compile("\\s*XA\\s+", Pattern.CASE_INSENSITIVE | Pattern.MULTILINE));`

**Comment by osheroff** [comment]
@PengLyu yeah, that will get maxwell past the transactions, the problem is that I'm not sure about the format of the `XA` transactions, and I need to make sure maxwell processes them correctly -- I'll have to run some tests.

**Comment by PengLyu** [comment]
@osheroff I have another error like this:
09:53:01,264 ERROR MysqlParserListener - (parse ROLLBACK <EOF>)
09:53:01,264 ERROR SchemaChange - Error parsing SQL: 'ROLLBACK'
09:53:01,267 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
09:53:01,268 INFO  TaskManager - Stopping 3 tasks
09:53:01,268 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: ROLLBACK
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:87)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:89)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:101)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)

I guess it's the same error like "XA START" style transactions, could maxwell support to add a config properties for "SQL_BLACKLIST", not write "SQL_BLACKLIST" in java code  in the future?

**Comment by dbhatia2** [comment]
Team,

Can you please update on this. We are also seeing same issue with Maxwell and please suggest is there is any way to bypass this error ?

Transaction details from Binary [Log:]

DELIMITER /*!*/;
# at 397448717
#190707  4:13:38 server id 10178193  end_log_pos 397448884 CRC32 0x17e483d1 	Quer
y	thread_id=10260688	exec_time=0	error_code=0
SET TIMESTAMP=1562472818/*!*/;
SET @@session.pseudo_thread_id=10260688/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_c
hecks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1436549152/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=46,@@session.collation_connection=46,@@session.co
llation_server=192/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=192/*!*/;
XA START X'64316362666566352d303264652d346531352d393263642d3364356361333361356239623
a31',X'31',1


![Screen Shot 2019-07-08 at 3 31 33 PM](https://user-images.githubusercontent.com/22106315/60923286-74f96f00-a253-11e9-9370-aa191bae5606.png)

Thanks
Deepesh
