### ISSUE TITLE
RabbitMQ Producer doesnt support reconnect / diagnostics

### ISSUE THREAD

**Issue by mortensen** [zendesk/maxwell#840]
We are using Maxwell with RabbitMQ. Right now we have the problem that if RabbitMQ dies (or gets restarted), the RabbitMQ Producer in Maxwell dies, but Maxwell itself is still running (Forgivable..Exception). This doesn't really help as you can't monitor / restart maxwell in this case.

The producer should be either have more configuration to timeout and stop maxwell or maybe use diagnostics like in Kafka to check the latency. I am willing to look at it as we need it here. But I would be thankful for hints / discussions / best practises in Maxwell. (RabbitMQ Client params vs. Diagnostics...)

**Comment by osheroff** [comment]
Strange that you say “the producer dies”.  Can you be more specific about the symptoms?  Does maxwell throw a stack trace?  Or does it just block behind a call that never returns?

**Comment by mortensen** [comment]
`
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Chan
nel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced
 connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Chan
nel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced
 connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Chan
nel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced
 connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Chan
nel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced
 connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Chan
nel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced
 connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Channel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Channel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
08 Jan 2018 15:48:38 [AMQP Connection 192.168.33.234:5672] ERROR springframework.amqp.rabbit.connection.CachingConnectionFactory - Channel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
...
08 Jan 2018 15:48:41 [container-consumerMonitor-1] ERROR springframework.amqp.rabbit.listener.DirectMessageListenerContainer - Consumer
 canceled - channel closed SimpleConsumer [queue=tablexy, consumerTag=amq.ctag-JYk1g2L8ENqNyZS8RsvwHQ identity=5a187b9]
08 Jan 2018 15:48:41 [container-consumerMonitor-1] ERROR springframework.amqp.rabbit.listener.DirectMessageListenerContainer - Consumer
 canceled - channel closed SimpleConsumer [queue=tablexy, consumerTag=amq.ctag-WTAv-nUA-Gf6rKu22lbMCw identity=768be1c1]
08 Jan 2018 15:48:41 [container-consumerMonitor-1] ERROR springframework.amqp.rabbit.listener.DirectMessageListenerContainer - Consumer
 canceled - channel closed SimpleConsumer [queue=tablexy, consumerTag=amq.ctag-WVjdcRhOLRXdZqjGqZ4Afg identity=7a03c1ca]
08 Jan 2018 15:48:41 [container-consumerMonitor-1] ERROR springframework.amqp.rabbit.listener.DirectMessageListenerContainer - Consumer canceled - channel closed SimpleConsumer [queue=tablexy, consumerTag=amq.ctag-6k52mskN_n1BRZpcHZk_3A identity=75380bc1]
08 Jan 2018 15:48:41 [container-consumerMonitor-1] ERROR springframework.amqp.rabbit.listener.DirectMessageListenerContainer - Consumer canceled - channel closed SimpleConsumer [queue=tablexy, consumerTag=amq.ctag-oxqsr7iO-aygDTEj4SnudA identity=5266175e]
...
08 Jan 2018 15:48:44 [container-consumerMonitor-1] ERROR springframework.amqp.rabbit.listener.DirectMessageListenerContainer - Cannot connect to server
org.springframework.amqp.AmqpIOException: java.io.IOException
        at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71)
        at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:405)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:560)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:510)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:484)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:466)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1400(CachingConnectionFactory.java:94)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1084)
        at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.doConsumeFromQueue(DirectMessageListenerContainer.java:570)
        at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.lambda$actualStart$3(DirectMessageListenerContainer.java:414)
        at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer$$Lambda$822/751749858.run(Unknown Source)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126)
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122)
        at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:362)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:953)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:903)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1061)
        at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:387)
        ... 17 more
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
        at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
        at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:306)
        ... 21 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
        ... 1 more

`

**Comment by osheroff** [comment]
this is why a thread-pool model often sucks.  when the workers die, it's a total pain to get the upstream notified that anything happened. 

from [https://www.rabbitmq.com/api-guide.html](https://www.rabbitmq.com/api-guide.html), it looks like there's an `addShutdownListener` method that might help maxwell get the connection back to life in these cases.  I'm not sure what happens to any messages that might outstanding at that point, would have to check and see.

**Comment by mortensen** [comment]
ok thanks. can you assign the ticket to me? i will take a look these days

**Comment by osheroff** [comment]
you got it

**Comment by mortensen** [comment]
I just wanted to fix this and can't reproduce it anymore. Neither in our installed nor in the current master version. Other exception stack trace and maxwell is shutting down now... As it is no longer an issue, I am closing it for now.
