### ISSUE TITLE
DB name with "-" , maxwell stopped

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#911]
**SQL:**  CREATE DATABASE `iaccount-user` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

10:09:33,678 INFO  Server - Started @76174ms

**10:09:33,861 ERROR MysqlParserListener - (create_database CREATE DATABASE (name (id IACCOUNT)) - USER CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI)
10:09:33,861 ERROR SchemaChange - Error parsing SQL: 'CREATE DATABASE IACCOUNT-USER CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI'**

10:09:33,938 INFO  TaskManager - Stopping 4 tasks
10:09:33,938 ERROR TaskManager - cause: 

**com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: -**

        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84) ~[maxwell-1.10.8.jar:?]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:113) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:305) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:280) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:386) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.10.8.jar:?]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.10.8.jar:?]
10:09:33,943 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@ebed936
10:09:33,943 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
10:09:33,943 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@704cd8cf
10:09:33,944 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
10:09:33,947 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
10:09:33,950 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@38ba3df7
10:09:33,950 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
10:09:33,951 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@53d532ce
10:09:33,954 INFO  ServerConnector - Stopped ServerConnector@523b3bce{HTTP/1.1}{0.0.0.0:8081}
10:09:33,956 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@1312689b{/,null,UNAVAILABLE}

**Comment by osheroff** [comment]
Argh ok.  Will have to look Into the parser code.

**Comment by ashashwat** [comment]
When I tried to create the database with '-' character it failed.  

```
mysql> CREATE DATABASE iaccount-user /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-user /*!40100 DEFAULT CHARACTER SET utf8mb4 */' at line 1
```
From the [docs](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
) ASCII: [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore) are allowed in unquoted names.  Also, the general recommendation is to keep all identifiers consisting of A-Z,a-z,0-9 and _ characters.  Exotic names can be stored in a column or comment.

Upon using quotes, Maxwell works fine.

```
mysql> CREATE DATABASE `iaccount-user` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
Query OK, 1 row affected (0.02 sec)

08:40:46,918 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[1.000009:192589], lastHeartbeat=1520565043576] after applying "CREATE DATABASE `iaccount-user` /*!40100 DEFAULT CHARACTER SET utf8mb4 */" to iaccount-user, new schema id is 15
```

**Comment by Hackeruncle** [comment]
@ashashwat what is  your maxwell version?
my version is 1.10.8.

**Comment by Hackeruncle** [comment]
@ashashwat Thankyou, I test the maxwell 1.13.2, is ok, not throw this exception.

So,the maxwell first run ,will init the maxwell.database and maxwell.table metadata. But, when create database `iaccount-user` or  `iaccount`  ,this db name record is not existed in the maxwell.database metadata.

**Comment by ashashwat** [comment]
@Hackeruncle My maxwell version is 1.13.2.

**Comment by osheroff** [comment]
@Hackeruncle it's normal not to see it in `maxwell.databases` - maxwell will keep one full copy of a schema and then just track deltas to it in `maxwell.schemas`.

**Comment by osheroff** [comment]
ok I guess this was solved in a later maxwell version.
