### ISSUE TITLE
DDL statement parsing error "MaxwellSQLSyntaxError: float8"

### ISSUE THREAD

**Issue by jimymodi** [zendesk/maxwell#933]
Full error stack as below:

18:57:45,165 ERROR MysqlParserListener - (data_type float8)
18:57:45,166 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE xxxxx_xxxxx_data 
( 
`id` bigint(20),
	`login` varchar(128),
	`run_score` float8,
	`appeal` float8,
	`recorddate` date 
)'
18:57:45,179 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
18:57:45,184 INFO  TaskManager - Stopping 3 tasks
18:57:45,184 ERROR TaskManager - cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: float8
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84) ~[maxwell-1.11.0.jar:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.11.0.jar:?]
18:57:45,237 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@4b13f811
18:57:45,238 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
18:57:45,238 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@3b8254a6
18:57:45,239 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.008020:273254782], lastHeartbeat=0]
18:57:45,239 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
18:57:45,241 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
18:57:45,245 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@58c0860d
18:57:45,245 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: float8
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92)
	at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:310)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:285)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
18:57:46,574 INFO  TaskManager - Stopped all tasks

**Comment by ashashwat** [comment]
This seems to be an issue with Maxwell _v1.11.0_ and _v.1.12.0_.  Works fine with Maxwell _v1.13.0_ and above.  

```
22:39:07,539 INFO  BinlogConnectorLifecycleListener - Binlog connected.
22:41:01,725 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[1.000009:681363], lastHeartbeat=1522343460293] after applying "CREATE TABLE  xxxxx_xxxxx_data ( id bigint(20), login varchar(128), run_score float8, appeal float8, recorddate date )" to tick, new schema id is 17
```

**Comment by osheroff** [comment]
Yup we fixed this a few versions back
