### ISSUE TITLE
BInlog position not increasing

### ISSUE THREAD

**Issue by mayanksamrat** [zendesk/maxwell#945]
HI Getting below logs in maxwell, BInlog position is not increasing, can anybody help me here ?

```
Exception in thread "blc-xx.xx.xx.xx:3306" java.lang.IllegalStateException: BinaryLogClient is already connected
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:473)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
	at java.lang.Thread.run(Thread.java:745)
Thu Apr 19 01:44:36 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Exception in thread "blc-xx.xx.xx.xx:3306" java.lang.IllegalStateException: BinaryLogClient is already connected
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:473)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mayanksamrat** [comment]
Resolved, It was due to the same client id, I was using for 2 maxwell instances. My Bad.

**Comment by osheroff** [comment]
are there any other log messages?
