### ISSUE TITLE
maxwell fail to start with Couldn't find table rds_heartbeat2 in database mysql error after upgrading aurora

### ISSUE THREAD

**Issue by dfadid** [zendesk/maxwell#952]
hey,
i just upgrade the replicated  aurora db and maxwell failed to start afterwards with this error:

` [main]     com.zendesk.maxwell.Maxwell [?:?] maxwell encountered an exception
java.lang.RuntimeException: Couldn't find table rds_heartbeat2 in database mysql
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:29)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:197)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:293)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:41)
`

i saw there is an old issue with that table  and it was fixed in version 1.10 , im using 1.14.

**Comment by osheroff** [comment]
how are you running maxwell?  embedded mode by any chance?

The only way I can see this happening is if `filter` is null on line 17 somehow, and I don't see how that's possible running stock maxwell.

**Comment by dfadid** [comment]
hey,
yes you are right im running maxwell with embedded mode.

**Comment by osheroff** [comment]
Ok I’ll put in a fix for this but for now you can work around this by doing `config.filter = new MaxwellFilter()`

**Comment by osheroff** [comment]
Improved config validation so that we won't end up with a null `MaxwellFilter` in 1.14.1
