### ISSUE TITLE
Redis pubsub issues

### ISSUE THREAD

**Issue by jayhuang75** [zendesk/maxwell#955]
Hello all,

we are doing some testing for the Redis PubSub. actually its really good. however, every some 2 hour around I will get this error.

```
14:06:18,696 ERROR MaxwellContext - Exception occurred during shutdown:
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe (Write failed)
```

and here is how I start the Maxwell

```
maxwell --user='maxwell' --password='xxxxxxxx' --host='127.0.0.1' --producer=redis --redis_host='xxxxxxxxxxx' --redis_port='6379' --redis_pub_channel='maxwell_table_alert';
```

and I double check with the Redis monitor is good Redis server still running fine. and the code still running fine too.

Please advise.

**Comment by osheroff** [comment]
are there any other error messages?  It's strange that this message appears to occur after Maxwell is already shutting down...

**Comment by jayhuang75** [comment]
Hello Osheroff, thank you for your reply. Because the Maxwell and the MySql, currently I'm running locally but the Redis PubSub is running in one Linux box. I just want to know what happens. is it because the Maxwell shutting down or any other reason. here is the full error in logs
`10:53:40,578 ERROR MaxwellRedisProducer - Exception during put
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202) ~[jedis-2.9.0.jar:?]
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:151) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:215) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Jedis.publish(Jedis.java:2690) ~[jedis-2.9.0.jar:?]
	at com.zendesk.maxwell.producer.MaxwellRedisProducer.push(MaxwellRedisProducer.java:49) [maxwell-1.13.5.jar:1.13.5]
	at com.zendesk.maxwell.replication.AbstractReplicator.processRow(AbstractReplicator.java:180) [maxwell-1.13.5.jar:1.13.5]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:161) [maxwell-1.13.5.jar:1.13.5]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) [maxwell-1.13.5.jar:1.13.5]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202) [maxwell-1.13.5.jar:1.13.5]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152) [maxwell-1.13.5.jar:1.13.5]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223) [maxwell-1.13.5.jar:1.13.5]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_172]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_172]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_172]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_172]
	at java.net.SocketInputStream.read(SocketInputStream.java:127) ~[?:1.8.0_172]
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196) ~[jedis-2.9.0.jar:?]
`

**Comment by osheroff** [comment]
Some brief poking around shows that this is a pretty classic timeout - for whatever reason redis isn't responding before the default timeout of 2 seconds.  I'd be more than happy to accept a patch that increases the timeout...

**Comment by osheroff** [comment]
(or makes it configurable)

**Comment by osheroff** [comment]
the redis producer now has auto-reconnect code

**Comment by 526654341** [comment]
I am using Redis to modify the database data. Redis can't receive the message. I don't know why. Can you give me some help?
