### ISSUE TITLE
Maxwell shutsdown on `PARTITION`

### ISSUE THREAD

**Issue by ktalebian** [zendesk/maxwell#966]
I'm getting a `MaxwellSQLSyntaxError` that causes Maxwell to shutdown because of a PARTITION query:

```
2018-05-08_20:28:41.96364 2018-05-08 13:28:41 -0700 - [ERROR] - from com.zendesk.maxwell.schema.ddl.MysqlParserListener in main (data_type ( PARTITION p20180608 VALUES LESS THAN ( UNIX_TIMESTAMP ( '2018-06-09 00:00:00' ) ) ))
2018-05-08_20:28:42.55216 2018-05-08 13:28:42 -0700 - [ERROR] - from com.zendesk.maxwell.schema.ddl.SchemaChange in main Error parsing SQL: 'ALTER TABLE my-table ADD PARTITION ( PARTITION p20180608 VALUES LESS THAN ( UNIX_TIMESTAMP('2018-06-09 00:00:00') ) )'
2018-05-08_20:28:42.55328 com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: (
2018-05-08_20:28:42.55346 	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84)
2018-05-08_20:28:42.55351 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
2018-05-08_20:28:42.55389 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55394 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55399 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55401 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55406 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55411 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55415 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55421 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
2018-05-08_20:28:42.55425 	at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:79)
2018-05-08_20:28:42.55433 	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:91)
2018-05-08_20:28:42.55434 	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:354)
2018-05-08_20:28:42.55438 	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:334)
2018-05-08_20:28:42.55443 	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:120)
2018-05-08_20:28:42.55447 	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
2018-05-08_20:28:42.55452 	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:97)
2018-05-08_20:28:42.55456 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:103)
```

**Comment by osheroff** [comment]
what version of maxwell are you on? 

I'm having difficulty reproducing your issue locally -  `my-table` shouldn't be an allowed table name unless it's quoted (which it isn't in your query, unless you edited it?), and if I quote the table name the latest maxwell parses it just fine.

**Comment by osheroff** [comment]
closed for lack of activity and I suspect he's on an old version.
