### ISSUE TITLE
5.7 Error parsing syntax ALTER TABLE UPGRADE PARTITIONING

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#975]
Breaking on Maxwell v1.10.1 and v1.14.4

```
2018-05-14T15:48:14,057 ERROR com.zendesk.maxwell.schema.ddl.MysqlParserListener: (alter_specification UPGRADE PARTITIONING)
2018-05-14T15:48:14,057 ERROR com.zendesk.maxwell.schema.ddl.SchemaChange: Error parsing SQL: 'ALTER TABLE `ais`.`batcntrl` UPGRADE PARTITIONING'
2018-05-14T15:48:14,155 INFO  com.zendesk.maxwell.util.TaskManager: stopping 4 tasks
2018-05-14T15:48:14,155 ERROR com.zendesk.maxwell.util.TaskManager: cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: UPGRADE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:84) ~[maxwell-1.10.1.jar:1.10.1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:92) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:84) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:365) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:339) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:137) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:206) ~[maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:138) [maxwell-1.10.1.jar:1.10.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:226) [maxwell-1.10.1.jar:1.10.1]
2018-05-14T15:48:14,162 INFO  org.eclipse.jetty.server.ServerConnector: Stopped ServerConnector@c86e8f6{HTTP/1.1}{0.0.0.0:8080}
```

**Comment by jpeyper** [comment]
So quick, thanks :)
