### ISSUE TITLE
maxwell error on IF statemente

### ISSUE THREAD

**Issue by PsySkeletor** [zendesk/maxwell#976]
Hi.

After a couple of weeks working smooth, we got this error on this SQL statement:
`
11:36:21,623 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[master-binlog.000023:276279365], lastHeartbeat=0] after applying "ALTER TABLE `PaymentRequest` MODIFY COLUMN `id` BIGINT(20) NOT NULL AUTO_INCREMENT" to dev_Schema, new schema id is 327
11:36:21,631 ERROR MysqlParserListener - (name IF EXISTS `id`)
11:36:21,631 ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE `PaymentRequest`
    DROP PRIMARY KEY,
    DROP COLUMN IF EXISTS `id`,
    DROP COLUMN IF EXISTS `paymentAccount`,
    DROP COLUMN IF EXISTS `paymentRequestType`,
    DROP COLUMN IF EXISTS `paymentRequestStatus`,
    DROP COLUMN IF EXISTS `currency`'
11:36:21,631 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[master-binlog.000023:276293772], lastHeartbeat=0]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: IF
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:87)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:94)
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:322)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:297)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
11:36:21,726 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
11:36:21,728 INFO  TaskManager - Stopping 4 tasks
11:36:21,728 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: IF
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:87) ~[maxwell-1.14.0.jar:1.14.0]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.jar:4.5]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:88) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:100) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:94) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.replication.AbstractReplicator.processQueryEvent(AbstractReplicator.java:95) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:322) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:297) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152) ~[maxwell-1.14.0.jar:1.14.0]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223) ~[maxwell-1.14.0.jar:1.14.0]
`

It seems it fails on a ALTER TABLE STATEMENT.
Any ideas?

**Comment by osheroff** [comment]
MariaDB, yeah?
We don't currently offer full support for Maria.  I'll add this to that queue.

**Comment by PsySkeletor** [comment]
Yup you got me !
We are using mariadb 10.1.x would be nice to have support ;)
________________________________
