### ISSUE TITLE
BINARY / VARBINARY support

### ISSUE THREAD

**Issue by Komnomnomnom** [zendesk/maxwell#98]
Arose when testing #94.

Any love for `BINARY` and `VARBINARY` columns? I naively presume they could just be treated the same as `BLOB` and its variants?

```log
16:03:46,359 DEBUG SchemaChange - SQL_PARSE <- "ALTER TABLE `maxwell_blob_test`
	CHANGE COLUMN `blob` `blob` BINARY(50) NOT NULL AFTER `id`"
java.lang.IllegalArgumentException: unsupported column type binary
	at com.zendesk.maxwell.schema.columndef.ColumnDef.build(ColumnDef.java:81)
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.exitColumn_definition(MysqlParserListener.java:273)
	at com.zendesk.maxwell.schema.ddl.mysqlParser$Column_definitionContext.exitRule(mysqlParser.java:4370)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:67)
	at com.zendesk.maxwell.MaxwellParser.processQueryEvent(MaxwellParser.java:208)
	at com.zendesk.maxwell.MaxwellParser.getEvent(MaxwellParser.java:194)
	at com.zendesk.maxwell.MaxwellParser.getEvent(MaxwellParser.java:200)
	at com.zendesk.maxwell.MaxwellParser.run(MaxwellParser.java:100)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:69)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:75)
16:03:46,362 DEBUG SchemaPosition - Writing binlog position to maxwell.positions: BinlogPosition[mysql-binlog.000003:648414]
```

**Comment by osheroff** [comment]
yeah, easy enough.  in https://github.com/zendesk/maxwell/pull/97 now.

**Comment by Komnomnomnom** [comment]
Thanks just tried it out and working great :+1:

**Comment by osheroff** [comment]
fixed in https://github.com/zendesk/maxwell/releases/tag/v0.10.1

**Comment by seanlook** [comment]
How do I know the column value is a really string or a encoded base64 blob value when I parse the json data to replay or for other use ?

Retriving the meta data from source database ?

Thanks.
