### ISSUE TITLE
Maxwell doesnt connect due to timeout, increasing time doesnt work

### ISSUE THREAD

**Issue by ghost** [zendesk/maxwell#983]
Hi.

I continue fiddling with this piece of  art and we found that almost always, the maxwell daemon doesnt connect to the binlog because of the 5000ms that it has configured by default.

Event when i passed variables to increate this one, doesnt get affected.

`11:32:49,253 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@a804c62
11:32:49,253 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
11:32:49,254 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@447b342
11:32:49,254 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
11:32:49,258 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
11:32:49,266 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@35f48080
11:32:49,266 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
11:32:49,266 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@25554636
11:32:49,273 INFO  ServerConnector - Stopped ServerConnector@76abcc0f{HTTP/1.1}{0.0.0.0:18080}
11:32:49,276 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@d6c055c{/,null,UNAVAILABLE}
java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 5000ms
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.ensureReplicatorThread(BinlogConnectorReplicator.java:116)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:267)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
11:32:50,593 INFO  TaskManager - Stopped all taskszeroDateTimeBehavior=convertToNull&connectTimeout=10000 and it doesnt work :(
`

I passing the value as --jdbc_options=

**Comment by osheroff** [comment]
yeah, the replicator doesn't use jdbc, and thus doesn't use jdb_options.  Any chance you'd like to do a PR to support making the connection timeout configurable?

also, it takes you 5 seconds to connect to your db?  ouch :)

**Comment by PsySkeletor** [comment]
I still facing this problem, it took several tries to connect to my maxscale db proxy, but it eventually always does.
I dont understand why. The tries it takes are totally random, not network problems whatsoever, and when it is connected, it suddently stops.

More logs:

`09:29:43,991 INFO  AppInfoParser - Kafka version : 0.10.2.1
09:29:43,991 INFO  AppInfoParser - Kafka commitId : e89bffd6b2eff799
09:29:44,020 INFO  Maxwell - Maxwell v1.14.7 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[master-binlog.000036:748277417], lastHeartbeat=1528881892330]
09:29:44,287 INFO  MysqlSavedSchema - Restoring schema id 1067 (last modified at Position[BinlogPosition[master-binlog.000036:458140671], lastHeartbeat=1528869741271])
09:29:44,659 INFO  MysqlSavedSchema - Restoring schema id 3 (last modified at Position[BinlogPosition[master-binlog.000023:276293772], lastHeartbeat=0])
09:29:44,796 INFO  MysqlSavedSchema - beginning to play deltas...
09:29:44,859 INFO  MysqlSavedSchema - played 241 deltas in 63ms
09:29:44,896 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: master-binlog.000036:748277417
09:29:44,908 INFO  MaxwellHTTPServer - Maxwell http server starting
09:29:44,912 INFO  MaxwellHTTPServer - Maxwell http server started on port 9311
09:29:44,932 INFO  log - Logging initialized @2870ms
09:29:44,993 INFO  Server - jetty-9.2.21.v20170120
09:29:45,028 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@7f04298f{/,null,AVAILABLE}
09:29:45,038 INFO  ServerConnector - Started ServerConnector@15b446a1{HTTP/1.1}{0.0.0.0:9311}
09:29:45,038 INFO  Server - Started @2978ms
09:29:49,949 INFO  TaskManager - Stopping 4 tasks
09:29:49,949 ERROR TaskManager - cause:
java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 5000ms
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.startReplicator(BinlogConnectorReplicator.java:121) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.beforeStart(BinlogConnectorReplicator.java:126) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:23) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223) ~[maxwell-1.14.7.jar:1.14.7]
09:29:49,957 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@1638079b
09:29:49,957 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
09:29:49,958 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@2b5dd9d4
09:29:49,958 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
09:29:49,961 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
09:29:49,967 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@1b6ebe4b
09:29:49,967 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
09:29:49,967 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@75533307
09:29:49,972 INFO  ServerConnector - Stopped ServerConnector@15b446a1{HTTP/1.1}{0.0.0.0:9311}
09:29:49,975 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@7f04298f{/,null,UNAVAILABLE}
java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 5000ms
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.startReplicator(BinlogConnectorReplicator.java:121)        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.beforeStart(BinlogConnectorReplicator.java:126)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:23)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
09:29:52,305 ERROR MaxwellContext - Exception occurred during shutdown:
java.util.concurrent.TimeoutException: Timed out trying waiting for com.zendesk.maxwell.replication.BinlogConnectorReplicator process to stop after 1000ms.
        at com.zendesk.maxwell.util.StoppableTaskState.awaitStop(StoppableTaskState.java:46) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.util.RunLoopProcess.awaitStop(RunLoopProcess.java:18) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.util.TaskManager.stop(TaskManager.java:53) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.MaxwellContext.shutdown(MaxwellContext.java:164) [maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.MaxwellContext.access$000(MaxwellContext.java:31) [maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.MaxwellContext$1$1.run(MaxwellContext.java:187) [maxwell-1.14.7.jar:1.14.7]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
09:29:52,310 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process
09:29:52,310 ERROR MaxwellContext - Termination reason:
java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 5000ms
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.startReplicator(BinlogConnectorReplicator.java:121) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.beforeStart(BinlogConnectorReplicator.java:126) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:23) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223) ~[maxwell-1.14.7.jar:1.14.7]`

and then when connected and with a bootstraping process done
```
09:32:02,795 INFO  MaxwellMetrics - JMX metrics reporter enabled
09:32:02,849 INFO  MaxwellMetrics - JMX running on port 18081
09:32:03,840 INFO  ProducerConfig - ProducerConfig values:
        acks = 1
        batch.size = 16384
        block.on.buffer.full = false
        bootstrap.servers = [hadoop-1.dev1.domain.local:6667, hadoop-2.dev1.domain.local:6667, hadoop-3.dev1.domain.local:6667]
        buffer.memory = 33554432
        client.id =
        compression.type = snappy
        connections.max.idle.ms = 540000
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.fetch.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 0
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        timeout.ms = 30000
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer

09:32:03,942 INFO  AppInfoParser - Kafka version : 0.10.2.1
09:32:03,942 INFO  AppInfoParser - Kafka commitId : e89bffd6b2eff799
09:32:04,009 INFO  Maxwell - Maxwell v1.14.7 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[master-binlog.000036:748277417], lastHeartbeat=1528881892330]
09:32:04,534 INFO  MysqlSavedSchema - Restoring schema id 1067 (last modified at Position[BinlogPosition[master-binlog.000036:458140671], lastHeartbeat=1528869741271])
09:32:04,948 INFO  MysqlSavedSchema - Restoring schema id 3 (last modified at Position[BinlogPosition[master-binlog.000023:276293772], lastHeartbeat=0])
09:32:05,354 INFO  MysqlSavedSchema - beginning to play deltas...
09:32:05,569 INFO  MysqlSavedSchema - played 241 deltas in 204ms
09:32:05,658 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: master-binlog.000036:748277417
09:32:05,689 INFO  MaxwellHTTPServer - Maxwell http server starting
09:32:05,749 INFO  MaxwellHTTPServer - Maxwell http server started on port 9311
09:32:05,776 INFO  log - Logging initialized @6329ms
09:32:05,971 INFO  Server - jetty-9.2.21.v20170120
09:32:05,977 INFO  BinaryLogClient - Connected to bbdd.dev1.domain.local:3306 at master-binlog.000036/748277417 (sid:6379, cid:20380)
09:32:05,977 INFO  BinlogConnectorLifecycleListener - Binlog connected.
09:32:06,116 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@167f02fc{/,null,AVAILABLE}
09:32:06,127 INFO  ServerConnector - Started ServerConnector@3815e4e6{HTTP/1.1}{0.0.0.0:9311}
09:32:06,133 INFO  Server - Started @6687ms
09:32:06,129 INFO  SynchronousBootstrapper - bootstrapping started for <database>.<table>, binlog position is Position[BinlogPosition[master-binlog.000036:748279359], lastHeartbeat=1528881892330]
09:32:06,527 INFO  Replicator - async bootstrapping: queued table <database>.<table> for bootstrapping
09:32:06,607 INFO  Replicator - async bootstrapping: replaying 0 skipped rows...
09:32:06,607 INFO  Replicator - async bootstrapping: replay complete
09:32:06,607 INFO  SynchronousBootstrapper - bootstrapping ended for <database>.<table>
09:32:06,607 INFO  Replicator - async bootstrapping ended for <database>.<table>
09:32:06,670 INFO  SynchronousBootstrapper - bootstrapping started for <database>.<table>, binlog position is Position[BinlogPosition[master-binlog.000036:748540354], lastHeartbeat=1528882155072]
09:32:07,292 INFO  Replicator - async bootstrapping: replaying 0 skipped rows...
09:32:07,292 INFO  Replicator - async bootstrapping: replay complete
09:32:07,293 INFO  SynchronousBootstrapper - bootstrapping ended for <database>.<table>
09:32:07,313 INFO  Replicator - async bootstrapping ended for <database>.<table>
```

**Comment by PsySkeletor** [comment]
and after 5 minutes, it dies with this error.
```09:37:53,113 WARN  BinlogConnectorLifecycleListener - Communication failure.
java.io.EOFException: null
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventHeaderV4Deserializer.deserialize(EventHeaderV4Deserializer.java:35) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventHeaderV4Deserializer.deserialize(EventHeaderV4Deserializer.java:27) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:196) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:890) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
09:37:53,123 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
09:37:53,127 WARN  BinlogConnectorReplicator - replicator stopped at position: master-binlog.000036:749359356 -- restarting
09:37:58,132 INFO  TaskManager - Stopping 4 tasks
09:37:58,132 ERROR TaskManager - cause:
java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 5000ms
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.ensureReplicatorThread(BinlogConnectorReplicator.java:116) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:267) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152) ~[maxwell-1.14.7.jar:1.14.7]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223) ~[maxwell-1.14.7.jar:1.14.7]
09:37:58,133 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@2648c234
09:37:58,133 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
09:37:58,133 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@288f288d
09:37:58,133 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
09:37:58,137 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
09:37:58,144 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@71c2e6e5
09:37:58,145 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
09:37:58,145 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@99dddf9
09:37:58,160 INFO  ServerConnector - Stopped ServerConnector@3815e4e6{HTTP/1.1}{0.0.0.0:9311}
09:37:58,164 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@167f02fc{/,null,UNAVAILABLE}
java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 5000ms
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.ensureReplicatorThread(BinlogConnectorReplicator.java:116)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:267)
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:153)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223)
09:37:59,486 INFO  TaskManager - Stopped all tasks```

**Comment by PsySkeletor** [comment]
Still facing this problem, very weird indeed. It only happens when tries to connect throught mariadb maxscale.

**Comment by osheroff** [comment]
maxscale, huh.  how far away is your proxy from your server (ping times?)

**Comment by PsySkeletor** [comment]
Same segment. Different subnet. It took several tries to connect. There no option to increase the time ???

saludos, regards..

######################
From my mobile phone

________________________________

**Comment by PsySkeletor** [comment]
just a tracert and ping from maxscale host to mariadb maxscale cluster

`<<< PRO2 >>> root@kafka-2:/opt/kafkaMaxwell/daemon# ping bbdd.pro2.domain.tld
PING bbdd.pro2.domain.tld    (10.41.30.150) 56(84) bytes of data.
64 bytes from bbdd.pro2.domain.tld (10.41.30.150): icmp_seq=1 ttl=64 time=0.204 ms
64 bytes from bbdd.pro2.domain.tld (10.41.30.150): icmp_seq=2 ttl=64 time=0.222 ms
`

**Comment by osheroff** [comment]
So the first error appears to be the maxscale proxy randomly closing your connection down.  I'm unsure why that happens, but it'd be ok if maxwell could manage to reconnect within 5 seconds.  

I'm happy to just make the timeout configurable, but would also like to go deeper on this issue and figure out just why maxscale is taking so long to setup the replication proxy connection.  Are there any logs from the maxscale server that might help us out?

**Comment by PsySkeletor** [comment]
Yup, but I need to generate them. Today I will enable the debug on maxscale and start generating logs.

saludos, regards..

######################
From my mobile phone

________________________________
