### ISSUE TITLE
 Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by cemo** [zendesk/maxwell#986]
We have an issue as this. We are investigating cause.

```
org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.2-f1790037-6c97-4e66-a283-5c8d6c32caf0-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.2-f1790037-6c97-4e66-a283-5c8d6c32caf0-libsnappyjava.so)
	at org.apache.kafka.common.record.CompressionType$3.wrapForOutput(CompressionType.java:75)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.<init>(MemoryRecordsBuilder.java:126)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.<init>(MemoryRecordsBuilder.java:162)
	at org.apache.kafka.common.record.MemoryRecords.builder(MemoryRecords.java:473)
	at org.apache.kafka.common.record.MemoryRecords.builder(MemoryRecords.java:457)
	at org.apache.kafka.common.record.MemoryRecords.builder(MemoryRecords.java:405)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.recordsBuilder(RecordAccumulator.java:241)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:217)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:791)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:745)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.sendAsync(MaxwellKafkaProducer.java:213)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.sendAsync(MaxwellKafkaProducer.java:209)
	at com.zendesk.maxwell.producer.AbstractAsyncProducer.push(AbstractAsyncProducer.java:73)
	at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.run(MaxwellKafkaProducer.java:174)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.2-f1790037-6c97-4e66-a283-5c8d6c32caf0-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.2-f1790037-6c97-4e66-a283-5c8d6c32caf0-libsnappyjava.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:174)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:152)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:97)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:89)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:79)
	at org.apache.kafka.common.record.CompressionType$3.wrapForOutput(CompressionType.java:73)
```

**Comment by osheroff** [comment]
is this in the docker image or the tarball build?

**Comment by cemo** [comment]
was in the docker image. I added `libc6-compat` to dockerfile seems fine so far.

**Comment by cemo** [comment]
Is snappy compression enabled by default?

**Comment by osheroff** [comment]
>  I added libc6-compat to dockerfile seems fine so far. 

So that's the fix?  Can you PR that?  There was some effort to reduce the docker image size that appears to have broken stuff of late.

**Comment by cemo** [comment]
I added it and rebuilt the image. But before opening a PR I wanted to check everything. I will do when I will be sure.

**Comment by cemo** [comment]
Added `-Dorg.xerial.snappy.use.systemlib=true` and seems fine so far.

**Comment by cemo** [comment]
By the way I had not enabled compression on my configuration. If this is enabled by default, the parameter may be added by default as well.

**Comment by cemo** [comment]
Sorry for confussion. We had also set  `kafka.compression.type=snappy` in our config files. Nothing has to be done.
