### ISSUE TITLE
Kinesis producer stopped working in docker in the v1.14.6.

### ISSUE THREAD

**Issue by SerhiiKushnir** [zendesk/maxwell#989]
After upgrade from 1.14.4 to 1.14.6 faced the issue with kinesis producer.

`2018-05-22 16:27:57.802 | INFO  | aemon-0000 | ducer$MessageHandler:167   | Restarting native producer process.
2018-05-22 16:27:57.948 | INFO  | aemon-0000 | esis.producer.Daemon:421   | Asking for trace
2018-05-22 16:27:58.113 | INFO  | main       | gConnectorReplicator:71    | Setting initial binlog pos to: qa-db1-bin-log.007797:39072468
2018-05-22 16:27:58.384 | INFO  | 3.228:3306 | nlog.BinaryLogClient:542   | Connected to ***.***.***.***:3306 at qa-db1-bin-log.007797/39072468 (sid:101, cid:7312639)
2018-05-22 16:27:58.384 | INFO  | 3.228:3306 | torLifecycleListener:12    | Binlog connected.
2018-05-22 16:27:59.020 | ERROR | aemon-0000 | ducer$MessageHandler:152   | Error in child process
com.amazonaws.services.kinesis.producer.IrrecoverableError: Error starting child process
        at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:525) [amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:456) [amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63) [amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133) [amazon-kinesis-producer-0.12.8.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.io.IOException: Cannot run program "/tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_0529847a6647765630c02beeaf6a22c24858f873": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_151]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:454) ~[amazon-kinesis-producer-0.12.8.jar:?]
        ... 5 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_151]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_151]
        at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_151]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_151]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:454) ~[amazon-kinesis-producer-0.12.8.jar:?]
        ... 5 more
2018-05-22 16:27:59.021 | INFO  | aemon-0000 | ducer$MessageHandler:167   | Restarting native producer process.
2018-05-22 16:27:59.150 | INFO  | aemon-0000 | esis.producer.Daemon:421   | Asking for trace
2018-05-22 16:27:59.302 | INFO  | 3.228:3306 | torLifecycleListener:27    | Binlog disconnected.
2018-05-22 16:27:59.350 | INFO  | downThread | ell.util.TaskManager:37    | Stopping 2 tasks
2018-05-22 16:27:59.350 | ERROR | downThread | ell.util.TaskManager:40    | cause:
com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.
        at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:176) ~[amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:536) ~[amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:349) ~[amazon-kinesis-producer-0.12.8.jar:?]
        at com.zendesk.maxwell.producer.MaxwellKinesisProducer.sendAsync(MaxwellKinesisProducer.java:125) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.producer.AbstractAsyncProducer.push(AbstractAsyncProducer.java:73) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.replication.AbstractReplicator.processRow(AbstractReplicator.java:180) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:161) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:202) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:152) ~[maxwell-1.14.6.jar:1.14.6]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:223) ~[maxwell-1.14.6.jar:1.14.6]
2018-05-22 16:27:59.351 | INFO  | downThread | ell.util.TaskManager:45    | Stopping: com.zendesk.maxwell.schema.PositionStoreThread@2a600536
2018-05-22 16:27:59.351 | INFO  | downThread | l.StoppableTaskState:23    | com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
2018-05-22 16:27:59.351 | INFO  | downThread | ell.util.TaskManager:45    | Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@24a7fe0a
2018-05-22 16:27:59.351 | INFO  | downThread | l.StoppableTaskState:23    | com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
2018-05-22 16:27:59.584 | INFO  | downThread | ell.util.TaskManager:57    | Stopped all tasks
2018-05-22 16:28:29.448 | WARN  | main       | oring.MaxwellMetrics:42    | Metrics will not be exposed: metricsReportingType not configured.
2018-05-22 16:28:35.767 | INFO  | main       | roducerConfiguration:156   | Attempting to load config from file kinesis-producer-library.properties
2018-05-22 16:28:36.023 | WARN  | main       | roducerConfiguration:212   | Property Port ignored as there is no corresponding set method in KinesisProducerConfiguration
2018-05-22 16:28:36.282 | INFO  | main       | ucer.KinesisProducer:867   | Extracting binaries to /tmp/amazon-kinesis-producer-native-binaries
2018-05-22 16:28:43.341 | INFO  | aemon-0000 | esis.producer.Daemon:421   | Asking for trace
2018-05-22 16:28:43.528 | INFO  | main       | desk.maxwell.Maxwell:144   | Maxwell v1.14.6 is booting (MaxwellKinesisProducer), starting at Position[BinlogPosition[qa-db1-bin-log.007797:39072468], lastHeartbeat=1526998568719]
2018-05-22 16:28:46.811 | INFO  | main       | ema.MysqlSavedSchema:424   | Restoring schema id 144 (last modified at Position[BinlogPosition[qa-db1-bin-log.007797:38148024], lastHeartbeat=1526998145473])
2018-05-22 16:28:47.335 | ERROR | aemon-0000 | ducer$MessageHandler:152   | Error in child process
com.amazonaws.services.kinesis.producer.IrrecoverableError: Error starting child process
        at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:525) [amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:456) [amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63) [amazon-kinesis-producer-0.12.8.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133) [amazon-kinesis-producer-0.12.8.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

Looks like it's unable to execute Kinesis binaries, strange because as I can see the file exists in the container

`bash-4.4# ls -l /tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_0529847a6647765630c02beeaf6a22c24858f873
-rwxr--r--    1 root     root      35666344 May 22 15:47 /tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_0529847a6647765630c02beeaf6a22c24858f873
bash-4.4#
`

Rolling back to v1.14.4 solved the issue.

**Comment by osheroff** [comment]
bah ok.  There's too many problems caused by going to alpine linux.  I'm gonna revert back to the ubuntu image.

**Comment by ndeslandes** [comment]
oups :(
sorry about that

**Comment by SerhiiKushnir** [comment]
Thanks, guys, I'm very much appreciated about what you are doing!

**Comment by osheroff** [comment]
fixed that in the latest.
